### ISSUE TITLE
2.0.0 Spellbinding Cloth and Etheric Sword dupe bug

### ISSUE THREAD

**Issue by Ligi89** [JasonMcRay/InfiTech-1.7#107]
If you try to wipe enchantments off with a Thaumic Tinkerer spellbinding cloth, you'll get one sword without enchants and you also get back the enchanted one, with one point of durability fewer. I relogged, and even restarted client to see if it's a visual bug only, but for all intents and purposes, the swords are real.

**Comment by JasonMcRay** [comment]
Either TT devs have no idea how to fix that, or they dont want to fix that because we have GregTech?... well I think I will just remove the spellBinding cloth completely from game...

**Comment by JasonMcRay** [comment]
This little guy is no longer going to annoy the heck out of me... Its gone in v2.1.9! Rejoice
