### ISSUE TITLE
Apples

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#117]
Apples when eaten are currently filling both the hunger bars to full after eating just 1. Tested in single player and it seems to be the same. Had a look before I go out but can't find the source of this or find the reason in the configs but only had a quick look. Running 2.0.7

**Comment by JasonMcRay** [comment]
That is interesting... Let me check it in my instance

**Comment by JasonMcRay** [comment]
Unable to replicate. If you will hover over the apple and hold shift, how much is it showing it will fill?

**Comment by groveham** [comment]
Only a little bit, half a hunger? Just tried it again, it fills all hunger and then the 2nd hunger bar half way up. All other food seems to be normal so far, I'll try test it on other 'Morsel' food.

**Comment by groveham** [comment]
OK tried and tested the same thing with potatoes too

**Comment by JasonMcRay** [comment]
have you tried to redownload the pack, because I am really trying to recreate this issue, but I am unable to do so :(

**Comment by groveham** [comment]
I'll try that. I did manually update because of the FTB servers had issues with downloading when updating.

**Comment by groveham** [comment]
I had 'God' mode turned on both in single player and online. Ignore this, I turned off god mode and it's working fine! Silly me!!!!
