### ISSUE TITLE
Osmotic Enchanter crashing the client AND server

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#120]
Just letting you know, this happens for the second time now. I asked Grove to send server crash report to you. This is mine:

http://hastebin.com/ocezetabub.coffee

Looks like it happens when you choose enchants that exceed the capacity of your wand. The crash happens as soon as you hit the "enchant" button.

Because I don't have the server crash log, could you report them both to mod devs? Will be easier I think. Thx

**Comment by JasonMcRay** [comment]
This should be already fixed in latest Thaumic Tinkerer: http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/439/

**Comment by groveham** [comment]
It's not, he crashed the server so I'm
Just going to restore the world from a backup from my phone. 

http://pastebin.com/in1FyQaN

Can't do anything else until tomorrow afternoon

**Comment by JasonMcRay** [comment]
Confirmed fixed in e6ef49a07857853b9d4e48d2d20f4b018dc4a36f
