### ISSUE TITLE
Gendustry Liquid DNA crash 2.0.10

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#122]
http://pastebin.com/xWkiUvDF

I tried to look at the gendustry liquid DNA in NEI and was confronted by this wall of text.
Playing on Miguiks server with V2.0.2 of pack.

**Comment by Tyriael-Soban** [comment]
http://pastebin.com/H7ceGfv8

Client crashes when attempting to look up liquid DNA from Gendustry.

**Comment by JasonMcRay** [comment]
Was able to replicate it with latest versions of Gendustry, NEI and other included mods. Although got a bit different crash.

Reported to BDew: https://github.com/bdew/gendustry/issues/77

Also it doesnt crash without Binnie mods. So just in case reported it also to Binnie: https://bitbucket.org/binnie567/binnie-mods/issue/142/crash-when-looking-up-liquid-dna
