### ISSUE TITLE
2.0.8 Achievement / Statistic window crash

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#123]
Opened the statistics window in the game menu:

http://pastebin.com/8tw75J1d

Acheesement (Achievement) menu was opened just beforehand, stuttered hardcore, closed and then opened statistics window, crashed.

**Comment by JasonMcRay** [comment]
Are you able to recreate the crash everytime? Does it crash on SP?

Anyway do the basic steps. Update your Java, graphics drivers, redownload the modpack.

**Comment by Tyriael-Soban** [comment]
updating the graphics card is a touchy subject, ive noticed with AMD when you get the "latest version" it does, by no means indicate that it will be stable in any way shape or form.
As for recreating it, ill intentionally try tomorrow ... right now i should be in bed because i have to be up for work in 5 hours :P

**Comment by Tyriael-Soban** [comment]
http://pastebin.com/nH54K1pD

Fresh install of modpack, no binnies enabled, no fastcraft installed.

Will edit with the result of a java update.

**Comment by JasonMcRay** [comment]
Either FML, or some mod... Unfortunately there is no easy way of pointing at the broken mod without removing mods and clicking on the Statistics.

**Comment by JasonMcRay** [comment]
Not sure how that happened by I am no longer crashing when pressing Stastistics buttom... Can you confirm this? @Tyriael-Soban @groveham

**Comment by groveham** [comment]
I didn't crash at all when I clicked on Statistics in game, running 2.1.3

**Comment by JasonMcRay** [comment]
ok So i guess I can say, we have it fixed. Not sure how or what mod was causing that, though.

**Comment by Tyriael-Soban** [comment]
7 days ago, i read this and forgot to comment about repeating it on the same version as grove with no error... sorry about that @JasonMcRay
