### ISSUE TITLE
2.0.8 - logs identify incorrectly on WALIA tooltips

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#124]
I just had a weird one with WALIA incorrectly identifying Spruce logs that had been laid on their sides.

when i have the log in my hand, it is identified as spruce logs - if i place it vertically, it is still spruce.
If i place it horizontally, WALIA mistakes the same log for Oak.

![2015-01-13_21 42 41](https://cloud.githubusercontent.com/assets/9297841/5734176/2c658a04-9b6d-11e4-8965-b0e4f4f43aac.png)

I cheated in an oak log for comparison, note how WALIA still shows the spruce log as an oak, this only seems to happen to spruce logs.

**Comment by JasonMcRay** [comment]
Just to clean things up, reported to ProfMobius
https://bitbucket.org/ProfMobius/waila/issue/150/spruce-logs-mistaken-for-oak

**Comment by JasonMcRay** [comment]
Closed as minor issue.
