### ISSUE TITLE
Fusion Wall recipe incorrect

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-1.7#126]

**Comment by pyure** [comment]
Prematurely hit enter.  Can't edit descriptions.

You reworked the Fusion Wall recipe to require "Thalium", but it looks like you wanted Lead (Pb).

var elementPb = <minechem:minechemElement:81>; // THIS SHOULD BE 82, NOT 81

There's no way to get thallium (without the fusion reactor this recipe creates)

**Comment by JasonMcRay** [comment]
Oh, thanks, i have no idea how that happened. I will be doing quite extensive Minechem rework, so it will get fixed.

**Comment by cgjeff** [comment]
same goes for the tungsten wall used in the fusion / fission chamber as well I would think. Tantalum is one of the elements you can only get using the fusion chamber, but is required in the recipe for the tungsten plating to make the fusion chamber.

**Comment by JasonMcRay** [comment]
Someone (Minechem Devs) moved the metadata entries for elements by one in one of the updates.
Fixed in 91e575f167d0e0d86ca4d8105af992d89bb11a71 and b15b80c72dbee31ff11b0538dbad14d3e5d1dd21
