### ISSUE TITLE
2.0.10 Iron nugget  -> Steel nugget glitch.

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#127]
Miguknamja and i discovered this one earlier, i thought it was a glitch in Steves Workshop - so i tested it in a vanilla furnace, but it appears that when you smelt iron nuggets in any kind of furnace (that ive tested so far, so production table, furnace etc) that you get a steel nugget instead of a Wrought Iron one - NEI still lists the correct recipe. 
Miguk said he was tinkering with Mine tweaker to see if he could make a workaround.

**Comment by JasonMcRay** [comment]
I am unable to replicate with 2.0.10. When smelting Iron nugget in any furnace I am getting Wrough iron. Probably bug in your instance/server. Try to redownload the server/client files. If the NEI is showing the correct recipe, but you are getting something else.... Issue is likely on the server...

**Comment by JasonMcRay** [comment]
I saw Miguks post on forum... Closing this issue
