### ISSUE TITLE
Chunk loaders

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#129]
It seems chunk loaders are keeping parts of the world loaded all the time. I first noticed a drop in tps (to 19.33) when no one was online. I've logged onto the server this morning and I can see that when no one was online mobspawners are active. 

Here is part of my immibis.cfg file:
__________________________________________
    # Maximum number of chunks loaded by each player. Use -2 for unlimited.
    I:chunkloader.maxChunksPerPlayer=18

    # If true, chunkloaders placed by a player will only load chunks while that player is online.
    B:chunkloader.requireOnline=true
    B:chunkloader.useFuel=true
__________________________________________

That clearly states each person may force load max 18 chunks but only when they are online. I think the 18 max chunks is being respected but they are staying loaded (using fuel) all the time.

Is there another place in the configs this needs to be set to be active or is this a bug with the mod?

**Comment by JasonMcRay** [comment]
If they are using otger means of chunkloading, the immibis config is useless. Railcraft anchors for example are not affected by that.

**Comment by groveham** [comment]
OK I see, what chunk loading methods are affected by the immibis config?

Date: Sat, 17 Jan 2015 05:30:56 -0800

**Comment by JasonMcRay** [comment]
Immibis = Dimensional Anchor mod
Railcraft = World/Personal Anchors
Rest of the chunkloading is controled by forge.

**Comment by groveham** [comment]
Hmm going to have to control chunk loading in some way otherwise tps will drop like mad. Thanks for sorting out that confusion :)
