### ISSUE TITLE
IHL ACE contains uncraftable component

### ISSUE THREAD

**Issue by prudno** [JasonMcRay/InfiTech-1.7#130]
the IHL ACE contains Lazurite plates and allows no substitute.  Lazurite plates aren't craftable in any fashion (possibly becaus there isn't a lazurite block?).  Lapis plates used in the recipe would be a viable alternative but isn't doable at this point in time.

**Comment by Tyriael-Soban** [comment]
Lazurite can be crafted by placing a lazurite dust in any kind of compressor (GT Steam includted in that)

**Comment by prudno** [comment]
I attempted using a compressor on lazurite dust in an advanced compressor (GT) as well with no success before I posted this issue.  Maybe I tried the wrong one, but I'll give it a whirl again tomorrow (going to sleep).

**Comment by JasonMcRay** [comment]
The recipe doesnt work, not sure why.

**Comment by JasonMcRay** [comment]
Lazurite is not used in any recipes. So changed the IHL ACE recipe to use Lapis ones instead.
