### ISSUE TITLE
crashlog 20/01/2015-1

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#132]
The two crash logs you asked for. 

http://pastebin.com/EWaRjiiA
http://pastebin.com/WbH0jF6S

Both seem to be the same issue but I can't spot anything obvious. Both caused by different players in different worlds.

**Comment by JasonMcRay** [comment]
Thanks.. both are tied to HEE. HEE has been updated to v1.7 and it will be included in the v2.1.0 of the modpack. So.... I am going to put this on hold, and if the crash will happen again after an update, let me know, and I will move it to Chylex (also if it will hapen again, it will be awesome to have full FML log - and more awesome would be to have the FML log with HEE debug enabled in the server configs: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/HardcoreEnderExpansion.cfg#L35)

**Comment by JasonMcRay** [comment]
@groveham is this crash still happening with 2.1.0 of the modpack? Or are we safe with closing this?

**Comment by groveham** [comment]
It's not happened yet so feel free to close it :)

**Comment by JasonMcRay** [comment]
Ok if it will happen again feel free to reopen the issue and provide also the FML log with HEE debug mode enabled.
