### ISSUE TITLE
Iron Nugget > Furnace > Steel

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#133]
Seems this good'ol bug is back! I've just tried to get some wrought iron but it's smelted into steel instead. I'm using v2.1.0 on the server now. Only thing I changed was using the infitech script fix you posted on the FTB forum.

**Comment by JasonMcRay** [comment]
This cant be true... Any removed mods? Which could cause the recipes to break? i am currently playing 2.1.0 with the same script... no issues... getting wrought iron by smelting... but as always... redownload the server files and try to replace all the scripts (except the fix one) with freshly grabbed ones.

**Comment by groveham** [comment]
No removed mods what so ever, feel free to pop on and see it if/when you get the chance. The I've changed a few config options, nothing that would cause this though, just minor stuff for the server. I'll redownload and reupload now then give the server a restart. Might have to wait until the morning, I'm quiet tired.

**Comment by JasonMcRay** [comment]
you know what you can at least do..... /mt reload (either on console or ingame) and send me the minetweaker.log

**Comment by groveham** [comment]
Hmm only Service issue, SP worked fine in a creative world in normal furnace. Pastebin of minetweaker.log: http://pastebin.com/NFtZwTsv

**Comment by JasonMcRay** [comment]
Seems like you forgot to implement the fix because its still showing: ERROR: infitech.zs:32: Could not resolve <Enchiridion : items>

**Comment by groveham** [comment]
What?! I did, and I overwrote the file.... hmmm. I'll try it again and restart the server and let you know.

**Comment by groveham** [comment]
Updated with the link you posted on the FTB forums and still the same issue and exact same error in the Minetweaker.log file.

**Comment by JasonMcRay** [comment]
It cant error on something that doesnt exist :D If you will open the infitech.zs script and look at the line number 32.... what you have on that line?

**Comment by groveham** [comment]
Line 32: var book = <minecraft:book>;

**Comment by JasonMcRay** [comment]
Then it should not error out

**Comment by groveham** [comment]
And just to be sure: http://pastebin.com/ZA9b4xBd

Thats the paste bin of the script

**Comment by JasonMcRay** [comment]
ok grove.... This is completely your derp... Looked on your scripts and found exactly what I expected to find: You server is running with 2 script sets. one is in the root (that one is correct) and second one you have in the world folder.... The script works as follows:
If the minetweaker will find a scripts folder inside the world folder... it has higher priority. I fixed it for you.

**Comment by groveham** [comment]
My Bad I didn't know there was two and your instructions on the ftb site where i got it from didn't say that :P

**Comment by JasonMcRay** [comment]
It doesnt say that because there is no reason for anyone to have the scripts inside world folder.
