### ISSUE TITLE
Grave items disappearing

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#134]
My grave only had 2 items and the rest of them are gone.
I got no error or crashlog :(

**Comment by JasonMcRay** [comment]
Are you able to recreate it all the time, or does that just happened only once? It will be also great on having bit more information as possible. Was the grave on the ground? In the air? What items you had in there, and which were recovered.

**Comment by DarknessShadow** [comment]
It only happend once.
Grave was on the ground in the end.
Everything exept for the baubles items disappeared

**Comment by JasonMcRay** [comment]
Unable to replicate. Possible server lag issue.
