### ISSUE TITLE
Malisis Door crashing

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#135]
http://pastebin.com/41DG0Xk0

Server has had two crashes in the past 30minutes with the exact same crash log. Seems like it's being caused by Malisis doors but I'm not sure. It is mentioned in the crash log. But then again it also mentions crops and potatoes!

**Comment by JasonMcRay** [comment]
There is new version of Malisis Doors where it says "Fixed crash on dedicated servers." so maybe its fixed. if you want you can grab the updated version and test it out. http://minecraft.curseforge.com/mc-mods/223891-malisis-doors/files/2225300

**Comment by JasonMcRay** [comment]
Talked to Ordinastie (mod dev of Malisis Doors) and yes... this crash is fixed in version 1.4.3 of Malisis Doors.
