### ISSUE TITLE
Bed doesnt work

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#136]
A bed anywhere on my new home doesnt work.
You can place it and rightclick it but you get 2hearts dmg and kicked out again.
Its placed on a flat surface without a roof.
Coords: 
x: -100 
z: -250
y:  200

**Comment by JasonMcRay** [comment]
This is not a modpack issue. This is server related issue. @groveham ^^

**Comment by groveham** [comment]
Not a server issue, replicated in vanilla Minecraft, seems to be if you have a bed above the old 128 block height limit if I remember correctly, I've looked into this before, nothing I can do about it
