### ISSUE TITLE
2.1.0:  Buildcraft Gates uncraftable

### ISSUE THREAD

**Issue by prudno** [JasonMcRay/InfiTech-1.7#137]
Pretty self explanatory: there isn't any recipes in NEI for all types of BC gates, and known recipes in the assembly table don't work either so its not just a recipe display bug.  It was there in a previous version because we have some in our world from another player, and I've also looked at the recipes in the past.  From what I remember, there should be a BC assembly table recipe plus a GT assembling machine recipe.

**Comment by JasonMcRay** [comment]
Tested with latest, works perfectly.
Possible corrupted download, try to redownload the pack again. Or update to latest.
