### ISSUE TITLE
Secret rooms bug

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#139]
Secret Rooms crashing the server, crashed three times in 2 hours.

http://pastebin.com/Qd9t64Xs

Reported to author: https://github.com/AbrarSyed/SecretRoomsMod-forge/issues/171

**Comment by JasonMcRay** [comment]
Thanks to bringing this up.. I wasnt able to update SRM for some time, because it was broken with Malisis doors. But seems like it should be fixed, so v2.1.2 will have the fix.
