### ISSUE TITLE
Refined relocation crashes

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#140]
http://pastebin.com/ngVynimw
http://pastebin.com/0Tar61eL
http://pastebin.com/2818nXZT
http://pastebin.com/gEBPB3LF

Four crash logs, as far as I can tell they are all from the same issue, the server crashed 4 times, hence 4 logs. From what I gather, a player tried to extract from a RR Chest using BC pipes.

**Comment by JasonMcRay** [comment]
I am able to recreate the crash 100% time. Just to shed more light on the issue so ppl can try to not do this until its fixed: Its not BC pipe trying to pull out from RR chest. Its when BC pipe is placed next to relocator pipe.

Anyway reported to mod devs: https://github.com/Dynious/RefinedRelocation/issues/270

**Comment by JasonMcRay** [comment]
@groveham I recommend you to manually update and force ppl to update to RR 1.0.7e which has just been released, and it should fix that issue: http://www.curse.com/mc-mods/minecraft/refined-relocation#t1:other-downloads

**Comment by JasonMcRay** [comment]
Because I failed at tagging the fix in commit.... fixed in ed52f55d588c1a3cfa7d70ad24cc1f3d479562a9
