### ISSUE TITLE
Thaumcraft Crashes

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#141]
Running 2.1.1 - Server crashed, 14 crash logs from yesterday. See below. Is it worth updating to 2.1.2 to fix these bugs?

http://pastebin.com/fVhYYUmC

**Comment by JasonMcRay** [comment]
Both involved mods (Thaumcraft and TT) were updated in 2.1.2. After looking through changelogs:
Either update manually TT (http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/466/)
or update the modpack....

AKA yes its fixed in 2.1.2
