### ISSUE TITLE
Add GT crushed ores to Forestry Miners packs.

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#143]
Stemming from the shoutbox convo on the forums i've collected a list of crushed ore items that drop from small veins that are not currently picked up by forestry backpacks;

they all begin with;
gregtech:gt.metaitem.01

5032, 5034, 3035, 5036, 5054, 5048, 5057, 5086, 5089, 5502, 5810, 5500, 5535, 5526, 5503, 5022, 5501, 5505 - ill update this list as i encounter additional ores.

**Comment by JasonMcRay** [comment]
Thanks, if you will encounter more, please dont edit your post, but make another comment (so I can keep a track on this; would be harder for me to notice if you will only edit your post)

**Comment by JasonMcRay** [comment]
For some reason it didnt got pushed to v2.1.4... will get it in v2.1.5 :(
