### ISSUE TITLE
Unable to craft Scented Panneling

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#144]
I'm unable to craft Scented Panneling 4544:6 item from Forestry. Running 2.1.3 (yes that's right!) on the server and also tested locally as well. The recipe exists in NEI but when put into the carpenter, nothing shows up and the machine doesn't process stating the recipe doesn't exist. 

Do you need any other info?

**Comment by JasonMcRay** [comment]
Works fine for me... Are you sure you are puting correct items?

**Comment by JasonMcRay** [comment]
Tested also on your server, works perfectly fine.

**Comment by groveham** [comment]
Hmmm, 

I'll try redownload the modpack and test on Tuesday when I'm home, may be a visual bug on my end :/

**Comment by AiwendilCiunio** [comment]
do you have honey inside? :D

**Comment by groveham** [comment]
Yes I have honey inside, it was working fine until we updated. I'm at home tomorrow and will re-download the pack incase it's a visual bug on my end. If it still happens I'll add a screenshot so you can see ;)

**Comment by JasonMcRay** [comment]
@groveham Still an issue?

**Comment by AiwendilCiunio** [comment]
Jason, this happened to me today. Earlier today I crafted some just fine, now the carpenter doesn't recognize the recipe (it says "no recipe" on the right")..

**Comment by JasonMcRay** [comment]
It seems like its not being recognized sometimes when the server restarts. Will report it to the forestry devs.

**Comment by AiwendilCiunio** [comment]
Jason I'm an idiot and perhaps Grove was too before, since he's using Soartex as well.
I was trying to make the recipe with gold dust instead of beeswax :dancer: 

It works now.

**Comment by JasonMcRay** [comment]
Hmm. Ok. Thanks for lettimg me know. If i can get a confirmation about possible "user" derp from @groveham I will be able to close this issue so its not haunting me in here.

**Comment by groveham** [comment]
Well as far as I can tell I'm doing it right. 
http://postimg.org/image/6z85n2tb7/a84cffe6/

I'll try 2.1.6 and see if it's still an issue there. For what ever reason though it won't let me do it in 2.1.3

**Comment by groveham** [comment]
http://postimg.org/image/uag6c1mgd/

This shows I'm doing it right AFAIK and I still can't craft, single player or server side. I'll try update to 2.1.6 and see if that helps....

**Comment by AiwendilCiunio** [comment]
and you're ABSOLUTELY sure it was beeswax not something else? Because I was sure too, I got angry, posted here, then I hovered over the "beeswax" and felt like an idiot.

**Comment by groveham** [comment]
Yeah look at the screenshot I put in the last update

**Comment by JasonMcRay** [comment]
Ok @groveham can you give me the FML log from the time/server session when this issue appeared?

**Comment by groveham** [comment]
Uhhh I don't have those logs, don't keep logs that go back that far, I do remember it started after the 2.1.3 update but I'll try update to 2.1.5 and see if it still exists.

**Comment by groveham** [comment]
Exactly the same after the update. @AiwendilCiunio are you able to craft them on the server also or not? I've got both the FML-1 log and the latest-log too. 

FML-1 Log  =  https://www.dropbox.com/s/0tq6k3sk3h10o0v/fml-server-1.log?dl=0
FML-Latest  = https://www.dropbox.com/s/zz6x4x3f1utnavy/fml-server-latest.log?dl=0

**Comment by JasonMcRay** [comment]
Is the craftability and notcraftability changing after server restarts or randomly?

**Comment by groveham** [comment]
It's not working as far as I know, I've tried restarts, nothing helps it's like it's not working?

**Comment by JasonMcRay** [comment]
Ok reported to Forestry devs:
https://github.com/ForestryMC/ForestryMC/issues/553

**Comment by JasonMcRay** [comment]
@groveham It should be fixed in latest unstable build, but since I am unable to reproduce it in the version we have, maybe you will have better luck testing it: http://jenkins.ic2.player.to/job/Forestry_Dev/

**Comment by mezz** [comment]
Forestry 3.4.0 has changed the ID of liquid honey from previous versions. To convert old honey into new honey, you can run it through a Still (or just throw it away and make some new liquid honey). The issue may be that the Carpenter has the old type of liquid honey.

**Comment by JasonMcRay** [comment]
@groveham Were you using Forestry honey, or BoP honey? Seems like BoP honey doesnt work (that includes GT Honey Cell)

**Comment by groveham** [comment]
Confirmed it seems to be the BoP honey. Tried and tested with spawned in honey from Forestry.
