### ISSUE TITLE
Lazurite plate uncraftable

### ISSUE THREAD

**Issue by gallowglass** [JasonMcRay/InfiTech-1.7#145]
In version 2.1.3 lazurite plate is uncraftable.  I could have sworn I used to be able to make it by compressing lazurite dust or something...

**Comment by JasonMcRay** [comment]
Its broken since 2.1.0 or something like that... Are there any recipes that explicitely requires lazurite plates?

**Comment by gallowglass** [comment]
Not that I know of.  Lapis plates do what I need, I just have more lazurite (even after crafting up a stack of lazurite plates back before 2.1.0 apparently) than lapis.  No big deal I guess.

**Comment by JasonMcRay** [comment]
It was 1 lazurite dust = 1 lazurite plate, right?

**Comment by gallowglass** [comment]
I believe so.

**Comment by JasonMcRay** [comment]
Ok.. lets have them back :)
