### ISSUE TITLE
Malisis doors crashing

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#146]
Seems that Malisis doors is crashing the server. A lot of console spam (for a good hour) then crash. 

http://pastebin.com/be5Ddv09

**Comment by JasonMcRay** [comment]
Malisis were updated in the v2.1.4 of the pack... so it should be fixed
Changelog: - Fixed crash on dedicated servers.

If it will happen after updating, reopen this ticket.

**Comment by JasonMcRay** [comment]
Hmm.. After looking at the commit for Malisis doors it doesnt really look like it was fix for that... well... reopening, reporting and will wait for response.

**Comment by JasonMcRay** [comment]
@groveham can you give me the full FML log from the time the crash happened?

**Comment by groveham** [comment]
@JasonMcRay FML Log http://pastebin.com/GzJrzkFS Is that what you need? The entire log file is over 14MB

**Comment by JasonMcRay** [comment]
nope... i really need the full one :) try: https://gist.github.com/ or if not just upload it somewhere

**Comment by groveham** [comment]
https://www.dropbox.com/s/to1taq97xtkneze/fml-server-3.log?dl=0

**Comment by JasonMcRay** [comment]
Thanks.

**Comment by groveham** [comment]
For reference... http://pastebin.com/AUZkuzAB

**Comment by JasonMcRay** [comment]
just in case... still at v2.1.6?

**Comment by groveham** [comment]
Yes, server is running on 2.1.6 and people on the server have re-created it in SP on 2.1.6 too.

**Comment by JasonMcRay** [comment]
Is this still an issue on latest modpack version? (v2.1.9 or v2.2.0)?

**Comment by groveham** [comment]
Nope not had any issues with this for a while. 2.1.9 seems to have fixed the issue.

**Comment by JasonMcRay** [comment]
Ok.. If it will reappear, please reopen.
