### ISSUE TITLE
Server crashing (Again)

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#147]
Not quite sure, but this log is identical to others I've got since updating: 

http://pastebin.com/JSiRdHq1

If you need any other info, give me a shout

**Comment by JasonMcRay** [comment]
This might be a problem: ChunkPurge{1.2} [Chunk Purge] (ChunkPurge-1.6.4-1.2.jar)
Or Tick Dynamic might be a cause as well... since its one of those "lets dig into the forge code" mods, which might cause some unwanted issues...

**Comment by groveham** [comment]
That's fine, wanted to make sure it's not a known issue with any of the modpack mods, feel free to close it :)
