### ISSUE TITLE
IC2/Railcraft Server Lockup

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#150]
pastebin.com/9iJFPXe2

Server locked up, no crash log but got these error messages from the logs.

**Comment by JasonMcRay** [comment]
I was affraid that it can happen... You can try to remove IC2 api from Railcraft jar, that might help (make a big backup though).

**Comment by groveham** [comment]
I would but I can't test it at the moment, installed Windows 10 Technical Preview and Java system variables aren't applying correctly. Can't start a Test server at all :/

**Comment by JasonMcRay** [comment]
@groveham Is this issue still happening or was it just one time derp?

**Comment by groveham** [comment]
It was a 5 time derp one after the other but not happened since
