### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#151]
Not sure if this is anything you can help with? I'm having real issues tracking this one down.
When any players are online getting the following spam:

02.03 12:03:21 [Server] INFO java.lang.NullPointerException
02.03 12:03:21 [Server] INFO [12:03:21] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@29f0577d:
02.03 12:03:21 [Server] INFO [12:03:21] [Server thread/ERROR] [FML]: 24: ASM: codechicken.multipart.minecraft.EventHandler@68fb2e9e playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V

**Comment by JasonMcRay** [comment]
Can you provide full FML log?

**Comment by groveham** [comment]
I'll try get this for you but I'm not at home for a few days now, if you close it I'll reply and reopen later
