### ISSUE TITLE
Grave didn't give any item back

### ISSUE THREAD

**Issue by clashthunder** [JasonMcRay/InfiTech-1.7#152]
I died in nether.
I was burning, so I moved into narrow hallway (safe spot)
so I can retrieve my items later.
When I went back to the spot, and broke the grave
I didn't get any of my items back.
I only got exp back...

looks like a bug with gravestone.
I play on official infitech server

**Comment by groveham** [comment]
No error messages in the server logs or console to state why either...

**Comment by JasonMcRay** [comment]
Yes that is happening a lot when you break a grave. I am aware of this. You can right click the tombstone to retreive the items, though.
