### ISSUE TITLE
IHL Evaporator Error

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#153]
http://pastebin.com/UNNVVPRR

See above for the crash log, coming in thick and fast today! ;-)

**Comment by JasonMcRay** [comment]
That is a problem... IHL appears to switched over to support GT6. So no fixes in that... Also I am forced to not use newer versions of IC2, because of IHL... might end up removing the mod completely :(

**Comment by JasonMcRay** [comment]
Anyway I reported it and will see what response we will get...

**Comment by JasonMcRay** [comment]
IHL dev is going to make a new version this weekend with GT5 API. He admitted that he made the switch bit too fast.

**Comment by JasonMcRay** [comment]
This seems to be fixed in v2.1.6.
Closing
