### ISSUE TITLE
Cyanite Reprocessor vanishing when broken with a pickaxe

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#157]
As in title, happened to me on the server and later I tested in SP. BR machines should (and most of them do) drop fine when broken with a pick, but this one just disappears.

**Comment by JasonMcRay** [comment]
Which pickaxe you used? GT or vanilla?

**Comment by AiwendilCiunio** [comment]
EiO dark pick. Multimine was enabled. But I tried the same pick on other BR stuff and worked fine.

**Comment by JasonMcRay** [comment]
Confirmed as MultiMine issue.
