### ISSUE TITLE
Gendustry machines disconnecting themselves from IC2 cables after chunk unload

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#158]
After I log out or server gets restarted, my Gendustry stuff doesn't accept power from IC2 cables (theyre also visually not connecting). Breaking and replacing fixes this.

Apparently Grove has no such problems, but he's using GT cables to power these machines.

**Comment by JasonMcRay** [comment]
Hmm.. Can you replicate it in SP world, when you go far away to let the chunks unload and then come back? (keep in mind the spawn area is always loaded, so you need to go far from spawn as well)
