### ISSUE TITLE
Railcraft Anchor configs

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#159]
The following option doesn't seem to be working

anchors {
    # change to craftable=false to disable World Anchor crafting, they will still be available via Creative
    B:craftable=false

I've set it in the config, and confirmed players can craft it.

**Comment by groveham** [comment]
https://github.com/CovertJaguar/Railcraft/issues/537

**Comment by JasonMcRay** [comment]
Are you sure they can craft it, or they just see the recipe in NEI?

**Comment by groveham** [comment]
I tested it, was able to craft it. Wasn't sure if it was my permissions so I had a player create it. They have got NO advanced permissions at all so no reason why they can craft it.

**Comment by JasonMcRay** [comment]
Ok.. it is not a bug. I am hardcoding a recipe for it in railcraft.zs script file. So you need to either delete or comment out these: 
https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/railcaft95fix.zs#L71-L74
https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/railcaft95fix.zs#L79-L82

**Comment by groveham** [comment]
OK I'll do that, but is it the railcraft95fix.zs or the railcraft.zs? You've mentioned one, then the other...

**Comment by JasonMcRay** [comment]
Its the 95fix.zs :)

**Comment by groveham** [comment]
Well I've updated the wrong file then haha OK I'll get this change done and let you know

**Comment by AiwendilCiunio** [comment]
I can't craft anchors at all now.

**Comment by groveham** [comment]
I've only updated what jason said, are both of those for world anchors jason? I want to keep the personal anchors enabled

**Comment by JasonMcRay** [comment]
The one with diamonds in recipe is world and rhe one with emeralds is
personal

**Comment by groveham** [comment]
God knows why I didn't notice this.... But it's fixed and will take affect after the next restart. Thanks for clearing that up Jason.
