### ISSUE TITLE
Recent closed issue misunderstanding

### ISSUE THREAD

**Issue by hlaaftana** [JasonMcRay/InfiTech-1.7#160]
I reported that the Division Sigils were spawning in Stronghold Libraries. You, Jason McRay, replied by showing me the MineTweaker lines which disabled the Division Sigil spawning in chests. I knew this was a tweak by you, and I reported a problem with that tweak. Your original intent was to remove Division Sigils being obtainable from chests, no? You forgot to disable the spawning of Division Sigils in stronghold library chests. I hate it when people misunderstand my posts and then think I'm an idiot, but I'll let this one slide.

**Comment by JasonMcRay** [comment]
I said that those lines arent doing anything. The spawning of Division Sigils is disabled in extrautilities config file itself. When checking the loot tables, no division sigils are generating in any chests at all. If you found some, they must have been generated before it was disabled, again in extrautilities config.
