### ISSUE TITLE
Tin rotor non crafteable bug (solved)

### ISSUE THREAD

**Issue by miguel1118** [JasonMcRay/InfiTech-1.7#163]
Tin rotor isnt crafteable, and there is double display in the NEI

**Comment by Tyriael-Soban** [comment]
im not getting this issue in 2.0.10 - what you should have is an X - shape
So
TP - H - TP
TS - TR - F
TP - SC - TP

Where:
TP = tin plate
H = Hammer (metal one)
TS = Tin Screw
F = File
SC = Screwdriver

Source: http://ftb.gamepedia.com/Small_Rotor

**Comment by Tyriael-Soban** [comment]
gonna test this now just to be sure, placeholder comment.

**Comment by miguel1118** [comment]
Thanks, the recipe works, I think I was using another material screw..
