### ISSUE TITLE
Chisel Present chests Crash the client when placed

### ISSUE THREAD

**Issue by miguel1118** [JasonMcRay/InfiTech-1.7#164]
I have tested it 2 times with a light grey present chest and the whole game crashed

P.D. Im new here and only want to help, should I post this kind of issues? Or is there a special kind of issues that should I post?
I mean, those issues didnt bother me, I can just avoid them..

**Comment by JasonMcRay** [comment]
Can you please provide a crashlog? Without that we cant do anything about that. Thanks

**Comment by miguel1118** [comment]
Damn, I cant reproduce it again, Idk what happen I did it 2 times yesterday just to be sure..
But this is the crash log http://pastebin.com/SaRb6JpX

Sorry, Henceforth I'm gonna wait and reproduce them more times before post issues
