### ISSUE TITLE
Waila shows wrong wire effective tool

### ISSUE THREAD

**Issue by miguel1118** [JasonMcRay/InfiTech-1.7#165]
Waila shows wrench as wire effective tool, but you actually need a wire cutter to remove placed wires. it took me a while to find the correct tool

**Comment by hlaaftana** [comment]
I love how you fixed the spelling of "shows" but not the spelling of "Waila".

**Comment by Timeslice42** [comment]
An excavation focus works too.

**Comment by JasonMcRay** [comment]
Closed as minor issue.
