### ISSUE TITLE
Right clicking on a Travel Anchor crashes clients

### ISSUE THREAD

**Issue by gallowglass** [JasonMcRay/InfiTech-1.7#166]

**Comment by gallowglass** [comment]
This is 2.1.4  I can get a log to you if you need it.

**Comment by miguel1118** [comment]
They will need it, post it once to speed up the process..

**Comment by gallowglass** [comment]
http://pastebin.com/B1yc3Tgi

**Comment by JasonMcRay** [comment]
Ehm are you sure its right clicking on Dimensional Anchor? Because from stacktrace i see only enderIO Travel Anchor...

**Comment by gallowglass** [comment]
Yep, my bad.  Travel anchor.  Sorry.

**Comment by JasonMcRay** [comment]
Can you please try to replicate this issue again on 2.1.6?

**Comment by gallowglass** [comment]
Can't use 2.1.6. Server won't start.

http://pastebin.com/BUJcxnYR

**Comment by JasonMcRay** [comment]
Looks like you have for some reason JourneyMap mod inside the server files.

**Comment by gallowglass** [comment]
I just unzipped the server from the FTB launcher.  I can try again maybe tomorrow.

**Comment by gallowglass** [comment]
Got 2.1.6 working (just had to remove JourneyMap from the server).  Right clicking on a travel anchor results in a client crash.

http://pastebin.com/k8hc5FU0

**Comment by gallowglass** [comment]
A new twist...  I crafted and placed these travel anchors way back in 2.0.something.  I just harvested them with a pickaxe and replaced them and now no crash when right clicking on them.  Something must have changed in the way some data was being stored since they were placed or something.  

So, in the end, maybe this is not a super big deal.  Just a strange mystery of computer science.
