### ISSUE TITLE
Iron veins Bug (gt.blockores.0.name)

### ISSUE THREAD

**Issue by miguel1118** [JasonMcRay/InfiTech-1.7#167]
There are some huge veins made of blocks called "gt.blockores.0.name" which give you vainilla iron ore when you break them, they look exactly as a stone block until you break them

**Comment by JasonMcRay** [comment]
I know about this, unfortunately there is nothing I can do about it. It is a bug within the GregTech which shouldn't happen. In most cases the fix is simple as restarting the world/ unloading and loading the chunks.

**Comment by AiwendilCiunio** [comment]
Really? That's interesting, never found any of these.

**Comment by JasonMcRay** [comment]
I personaly have found one little vein like this near AE2 meteor. This issue is rare, but happens. :(

**Comment by JasonMcRay** [comment]
Since GT5 is no longer being developed, this will not be fixed. Closing
