### ISSUE TITLE
Problematic Frame

### ISSUE THREAD

**Issue by miguel1118** [JasonMcRay/InfiTech-1.7#170]
I've got this error with different frame codes at random times:

[thread 4252 also had an error]# A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007032ebbe, pid=1196, tid=4248

 JRE version: Java(TM) SE Runtime Environment (8.0_40-b26) (build 1.8.0_40-b26)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 V  [jvm.dll+0x3aebbe]

Here is the log: http://pastebin.com/0iaGTzGJ

**Comment by miguel1118** [comment]
Now I got this one:

 Problematic frame:
 j  thaumcraft.common.lib.research.ScanManager.generateItemHash(Lnet/minecraft/item/Item;I)I+244

http://pastebin.com/x4eeD40x

**Comment by JasonMcRay** [comment]
Is it happening when you do something specific, like opening thaumonomicon"
or completely random?

**Comment by miguel1118** [comment]
completely random, when opening a chest, or converting wood to planks, even when I didnt do nothing..

**Comment by miguel1118** [comment]
Just walking:

Problematic frame:
 J 20709 C1 chylex.hee.mechanics.charms.handler.CharmPouchHandlerClient.onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V (172 bytes) @ 0x0000000004c3d54d [0x0000000004c3d5a0+0xffffffad]

http://pastebin.com/kcvrXvgM

**Comment by miguel1118** [comment]
Problematic frame:
 j  org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(Ljava/lang/ClassLoader;Ljava/net/URI;)Lorg/apache/logging/log4j/core/LoggerContext;+144

http://pastebin.com/aSHM7mn2

**Comment by JasonMcRay** [comment]
Try update your drivers, java, try using java 7 instead of 8. This is PC/core minecraft problem, not modpack i am afraid

**Comment by miguel1118** [comment]
Well my dryver was always updated, and now Im using java 7 71, they seems to happen less often now so thanks (:

**Comment by Tyriael-Soban** [comment]
(0xc0000005) indicates an issue between jwgl and your video card drivers, your openGL side drivers in the case of java, sadly there is no fix for this, not until either oracle or amd pull their fingers out of their arses

**Comment by pyure** [comment]
@Tyriael-Soban : no this looks different from mine.  Its JVM-specific, whereas mine references a amd driver file.
