### ISSUE TITLE
Massive amount of spam

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#171]
I'm getting a lot of spam in the console. 

25.03 10:02:34 [Server] INFO [09:02:34] [Server thread/ERROR] [FML]: 7: ASM: minetweaker.mc1710.ForgeEventHandler@55dd5b92 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
25.03 10:02:34 [Server] INFO [09:02:34] [Server thread/ERROR] [FML]: 6: ASM: chylex.hee.mechanics.misc.TempleEvents@11f0a10b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V

The log files are getting massive and need deleting daily. A server restart doesn't fix the issue.

**Comment by JasonMcRay** [comment]
I need to ask you for a FML log. Restart your server, let it load and after few seconds of the spam stop the server.

**Comment by groveham** [comment]
https://www.dropbox.com/s/0tq6k3sk3h10o0v/fml-server-1.log?dl=0
https://www.dropbox.com/s/0tq6k3sk3h10o0v/fml-server-1.log?dl=0
https://www.dropbox.com/s/zz6x4x3f1utnavy/fml-server-latest.log?dl=0

Not sure which one you needed, so here is all three

**Comment by JasonMcRay** [comment]
The 1st and 2nd is the same. But i think i will be fine with the two of them :)

**Comment by JasonMcRay** [comment]
Hmm.. can you give me also the log file from the same tame as the FML log? Of course containing the spam

**Comment by groveham** [comment]
They are the logs that should contain the spam, I made sure it was in the console before I uploaded the logs, is there nothing in there?

**Comment by JasonMcRay** [comment]
There is some spam in them but not that one you specified. I cant go to any
mod devs with these logs, since there is no reference to problematic mods

**Comment by groveham** [comment]
https://www.dropbox.com/s/zz6x4x3f1utnavy/fml-server-latest.log?dl=0
https://www.dropbox.com/s/to1taq97xtkneze/fml-server-3.log?dl=0
https://www.dropbox.com/s/pcvqksuog10agqu/fml-server-2.log?dl=0
https://www.dropbox.com/s/0tq6k3sk3h10o0v/fml-server-1.log?dl=0

Are those logs any good to you?

**Comment by JasonMcRay** [comment]
Spam is caused by servertools most likely. Go check with them.

**Comment by JasonMcRay** [comment]
Might also by problem with mytown:
Point of reference: fml-server-latest - http://pastebin.com/HXrsD9cg again its all over the place

**Comment by groveham** [comment]
Hmm I didn't see that. It wasn't that error, it was something else. I'll report this to the mod devs.

**Comment by JasonMcRay** [comment]
6: ASM: chylex.hee.mechanics.misc.TempleEvents@11f0a10 spam you are seeing is because of one of those mods (servertools or mytown) registering permissions for commands. Maybe its just a forgot debug feature turned on.

**Comment by groveham** [comment]
Hmm no problem, just wanted to make sure wasnt an issue with the pack :)
