### ISSUE TITLE
Server Crash - Secret TrapDoor

### ISSUE THREAD

**Issue by ALivingBeing** [JasonMcRay/InfiTech-1.7#172]
V. 2.1.6 Infitech2
The block when right clicked crash server.

**Comment by JasonMcRay** [comment]
No crash log = dont care

**Comment by groveham** [comment]
http://pastebin.com/AUZkuzAB - I have the same issue, crash log on the link :)

**Comment by JasonMcRay** [comment]
Duplicate #146
