### ISSUE TITLE
[Qusteion] GT Oregen

### ISSUE THREAD

**Issue by Dream-Master** [JasonMcRay/InfiTech-1.7#173]
@JasonMcRay
I see you running GT and Galactic Greg on your Server too.
I look inside your World Gen cfg from Gregtech and see the same Problem i have.
Ore be set to false and later in the cfg file (Dimension Section )there are set to true.

row 1823 and 1824

B:Nether_false=false
B:Nether_true=true

Olivine Mix true and false ?

Thanks for helping

**Comment by Timeslice42** [comment]
I swear I saw a response to this question somewhere. Did this to any forums too? I'd like to read the response again...

**Comment by Dream-Master** [comment]
I find a solution fot this error.

**Comment by Timeslice42** [comment]
What was the solution?

**Comment by Dream-Master** [comment]
The last line that added by GT is the line who is loaded in the Game.
B:Nether_false=false (not loaded)
B:Nether_true=true(loaded)

so have to set
B:Nether_true=false
and delete the first line than everything is fine and no other line will be generated anymore.

**Comment by Timeslice42** [comment]
That makes sense. Thank you :)

**Comment by Dream-Master** [comment]
Np. That cost me a lot of time to find it out.

**Comment by groveham** [comment]
I remember it, it was suggested to recreate the config to remove and old settings
