### ISSUE TITLE
IC2 Crops not plantable

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#174]
IC2 Crops cant be planted on farmland.

Solution: update MalisisCore: to 0.11.4+
http://minecraft.curseforge.com/mc-mods/223896-malisiscore/files

**Comment by Timeslice42** [comment]
Wow, really? I wonder how the heck that happened. And how did you figure it out?

**Comment by JasonMcRay** [comment]
It wasnt me. Someone on the forum thread found out about it. So all credit goes to him :)

**Comment by JasonMcRay** [comment]
Fixed in v2.2.0
