### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#175]
http://pastebin.com/BtrV2TLh
Please see the paste bin for the crash log

**Comment by groveham** [comment]
Not sure how it happened, people on the server stated it had crashed, it's happened twice so far, but we are on 2.1.6 so this may be been fixed by 2.1.9

**Comment by JasonMcRay** [comment]
Update to 2.1.9

**Comment by groveham** [comment]
Seems to have fixed the issue.
