### ISSUE TITLE
Tablet Fake Player Crash

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#176]
After updating to 2.1.9 this crash is still present. See thelink below.  

http://pastebin.com/ukvW3HwC

**Comment by JasonMcRay** [comment]
Can I get more info on this? When the crash is occuring? When interacted? Broken? Sit on? Looked at? :)

**Comment by groveham** [comment]
As far as I'm aware it happens on interaction and crashes the server :/

**Comment by JasonMcRay** [comment]
Reported to mod devs: https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/726

There is a chance its World Edit causing problems.

**Comment by JasonMcRay** [comment]
After some testing, it looks like its World Edit issue. Report to them
