### ISSUE TITLE
IC2exp infinite energy.

### ISSUE THREAD

**Issue by Verharn** [JasonMcRay/InfiTech-1.7#180]
Recently I observed that the parallel connection of the energy sources to a single wire greatly increases the total value of the energy transmitted on the wire. For example, if you connect in parallel 2 MFSU with 2048 EU/t output, you get about 8196 in the wire. And if you connect 4 MFSU, you get 32,768 EU/t. Most importantly, from 2 fully charged MFSU in this connection we will get 160 million EU/t instead of 80 million, which allows you to create an infinite source of energy, which charges itself! This method works with all the generators and energy storage from the IC2exp.

**Comment by JasonMcRay** [comment]
Thanks for report... This is quite serious issue.

Reported to mod devs: http://bt.industrial-craft.net/view.php?id=1593
