### ISSUE TITLE
Infinite liquids

### ISSUE THREAD

**Issue by Verharn** [JasonMcRay/InfiTech-1.7#181]
ME Chest with Fluid Storage Cell and any liquids in the Universal Fluid Cell can give us any amount of any liquid. Liquids that were originally designed for pouring in cells (water, coolant, honey, etc.) multiply following method: just put 3 or more cells with liquid in the ME Chest with Fluid Storage Cell. The amount of cells equals 64 and on the right, which should appear empty cells, will filled 64 cells. Now we can take any amount of cells, because they will appear again. If we have cell with molten solid (iron, redstone, gold, etc.) just put one cell into ME Chest with Fluid Storage Cell. Liquid from the cell will appear in the chest, but cell will be not empty and we can put it into the chest again.

**Comment by JasonMcRay** [comment]
Reported to mod devs:
https://github.com/ExtraCells/ExtraCells2/issues/222
