### ISSUE TITLE
Acid bucket recipe accepts fresh water

### ISSUE THREAD

**Issue by QuiOui** [JasonMcRay/InfiTech-1.7#184]
The recipe for etching acid accepts fresh water from harvestcraft as an ingredient.  This allows you to get a free bucket each time you make one.

**Comment by JasonMcRay** [comment]
This is bit harder to fix on my side. Even when I hardcode minetweak recipe to use only vanilla bucket, for some reason its pulling it as ore dictionary entry.

Reporting to mod dev: https://github.com/MineMaarten/PneumaticCraft/issues/460

**Comment by JasonMcRay** [comment]
For the time being disabled crafting of Fresh Water (v3.1.1)
