### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#185]
2.2.1.1 crashes on startup during the new animated Mojang screen.

The Mojang screen stalls on either

   Loading - Constructing Mods 1/7
   Construction  - Mod Minechem 106/143

or

   Loading - Constructing Mods 1/7
   Construction  - Mod Tweaker 107/143

then returns to the Launcher screen after several minutes.

Crash report here: http://pastebin.com/pY6rpyZ5

Note: 2.2.0 works fine.

**Comment by JasonMcRay** [comment]
Can you please provide full FML log as well? Thanks

**Comment by lafflam** [comment]
The FML log file is 4.4 MB, too big for pastebin. I can compress it as a tar.gz or a zip file, but I do not see a way to attach it here on GitHub. What is your preferred way to receive it?

**Comment by lafflam** [comment]
@JasonMcRay, I uploaded the zipped log file to my own server for you to download. This seemed the easiest way to get you the log you requested. Hope this helps you.

http://lafflam.com/sites/default/files/fml-client-2.log.zip

**Comment by JasonMcRay** [comment]
Try to disable Fastcraft

**Comment by lafflam** [comment]
I disabled Fastcraft and tried again. Same problem. The new animated Mojang screen stalls at the same point, the FTB Launcher panel continues scrolling along for a few minutes, then around the time the Mojang screen should change to the Minecraft screen it crashes and dumps me back to the FTB launcher.

Could it be the new animated Mojang screen? As you can see from the logfile, I'm running Linux. Could it be something as silly as a font issue or something similar? I have not yet tried updating LWJGL, nor have I tried changing Java versions. But 2.2.0 runs fine with my current setup.

I'm happy to continue troubleshooting this with you, lemme know what you need me to try next.

Here are the last log files:

http://pastebin.com/nPy4ifiT
http://lafflam.com/sites/default/files/fml-client-latest.log.zip

**Comment by JasonMcRay** [comment]
Seems to be unfortunately tied to this: https://github.com/MinecraftForge/FML/issues/644
Not much I can do about it :(

**Comment by downslope7** [comment]
You can disable the loading screen for now in `splash.properties`.

**Comment by lafflam** [comment]
Thank you ds7.

Funny, I had just finished reading the thread from Jason's last post and discovered the exact same suggestion there. Quickly tested it, and it worked fine. Came here to update the thread and you beat me to it :-D

So until the devs figure it out, set <code>enabled=false</code> in <code>splash.properties</code> file.

Thank you for your help too, Jason.
