### ISSUE TITLE
IHL Tools recipes

### ISSUE THREAD

**Issue by Act0r** [JasonMcRay/InfiTech-1.7#190]
The problem is IHL Tools recipes requires refined iron plates (acheson furnace for example) which can't be produced.
![acheson furnace](https://cloud.githubusercontent.com/assets/3992756/7901381/3792371a-078d-11e5-81d0-9d7f9dc84b31.jpg)

**Comment by JasonMcRay** [comment]
Due to removal of IHL in v3 its no longer relevant.
