### ISSUE TITLE
Builder's Wand Lag and Memory

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-1.7#192]
The Builder's Wand can be unusually laggy with normal use. Problem doesn't exist in Reloaded. I've never seen it before, but it can take several seconds for it to place blocks. Happens sometimes but not all the time.

Possibly connected: I successfully builder's wanded 3 rows (with lag), and on the last one my system hit a bad memory leak. RAM allocation went to 100% and I had to kill minecraft process.

**Comment by JasonMcRay** [comment]
Can confirm it on my end as well. Reported to mod devs:
https://github.com/rwtema/extrautilities/issues/632
