### ISSUE TITLE
Ore Generation

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#194]
I found vanilla Emerald Ore in v3 on the server.

**Comment by JasonMcRay** [comment]
I remember seeing that it is because some wierd coding in vanilla MC and there is nothing to do about it. @Blood-Asp confirmation?

**Comment by Blood-Asp** [comment]
yes, emerald ore does spawn different as other ores and can't be disabled that easy.

**Comment by JasonMcRay** [comment]
Marking as "vanilla issue" and closing, since there is nothing we can do and honestly its not creating any imbalances.
