### ISSUE TITLE
Cheap lvl 3 Pickaxe

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#195]
The blue power amethyst can be be crafted into a lvl 3 pickaxe

**Comment by groveham** [comment]
The GT Pickaxe that is, a bit overpowered but it doesn't have a very good durabillity, so makes it kind of ballanced.

**Comment by DarknessShadow** [comment]
Yes but like the thaumcraft shard pickaxes another tool rod would be good (steel) because it really easy to get lvl 3 mining with it

**Comment by JasonMcRay** [comment]
I dont know... Obtaining Cobalt and using that as lvl 3 pickaxe is not hard to get.

Also quesstion: Can be GT small ore amethyst used for Blue Power crafting?

**Comment by DarknessShadow** [comment]
Yes the gregtech small amethyst ore also drops the amethyst that can be used for crafting.
But so far i havent found any of those on the server.
I've tested it in sp and it drops lots of amethyst dust which cannot be used.

**Comment by groveham** [comment]
Maybe put two or even 4 dust into a compressor = one gem? 

Atleast that gives a use for them
