### ISSUE TITLE
Macerator double recipes

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#198]
Macerator:
Cobblestone -> Sand
Cobblestone -> Stone Dust (this should be disabled)
Stone -> Cobblestone (this should be disabled)
Stone -> Stone Dust

**Comment by JasonMcRay** [comment]
Unfortunately minetweaker is not able to remove IC2/GT recipes within the macerator. Within recipes.cfg I am not able to find a solution.
@Blood-Asp: Any suggestions, or possibilities?

**Comment by Blood-Asp** [comment]
All GT machines replacing IC2 machines use the IC2 recipe system. So making MT work there would be a IC2 issue.
I'm not sure where the recipes get added, so can't promise i can fix that.

**Comment by JasonMcRay** [comment]
@Blood-Asp Any update on this?

**Comment by Blood-Asp** [comment]
I will look into it tomorrow. Finally weekend...

**Comment by JasonMcRay** [comment]
Ok. Thanks

**Comment by Timeslice42** [comment]
I swear you had fixed this one already somewhere in v2.x

**Comment by DarknessShadow** [comment]
Yes you've already fixed that in the past in v2.0.7(8) https://github.com/JasonMcRay/InfiTech-1.7/issues/112

**Comment by JasonMcRay** [comment]
Looking at the changes in 2.0.7(8) I am unable to pinpoint the fix. Closest one was update of GT. :(

**Comment by DarknessShadow** [comment]
So it looks like you won't find a solution to the problem :(
Thats why I think we should look for other (temporary) solutions.
Crafting: Stone Dust -> Sand
Forge Hammer / Macerator: Stone Dust -> Sand
Forge Hammer / Macerator: Gravel -> Sand (Cobble to Gravel is already a Forge Hammer recipe)

**Comment by Timeslice42** [comment]
I agree that forge hammer gravel -> sand makes the most sense. Then again, I'm totally up for more uses for stone dust; stone dust doesn't recycle into scrap, scaffolding is too expensive to use construction foam everywhere, and there's only so much I can do with concrete.

**Comment by Timeslice42** [comment]
Also, has it been tomorrow yet, @Blood-Asp ?

**Comment by Blood-Asp** [comment]
Fixed in GT 5.08.20

**Comment by JasonMcRay** [comment]
YAY! Love you @Blood-Asp :)
