### ISSUE TITLE
Hunger Overhaul settings

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#199]
I don't know if you remember, but long ago you nerfed all growth speed by 50%. Maybe it's time to re-think that? The pack is much harder than it used to be, and using vanilla growth speed will let people use other forms of power generation (like methane), because you nerfed charcoal so much.

**Comment by DarknessShadow** [comment]
charcoal  is not really nerfed

**Comment by Timeslice42** [comment]
IC2 crop growth speed is still normal :P
