### ISSUE TITLE
Barrel Hammer

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#200]
The jabba barrel hammer uses 5 iron ingot.
I think you could change that to 5 iron plates :)

**Comment by Erixonich** [comment]
I think, that using ingots more more realistic and logic. Just imagine how u will assemble HAMMER from plates!

**Comment by Timeslice42** [comment]
I agree, the GT hammer is ingots, shouldn't the barrel hammer be too? Maybe just stick the GT hammer as a tool in the barrel hammer recipe?
