### ISSUE TITLE
Wire Cutter

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#202]
Both gregtech and ic2 wirecutter are enabled
The ic2 one "Cutter" should be disabled becasue its alot cheaper to make and cannot break wires.
And it crashes the client when you try to craft with it and it only has 1 durability left

**Comment by JasonMcRay** [comment]
@Blood-Asp isnt it supposed to be disabled by default when GT is installed? Checking configs and all i see is under Disabled recipes IC2 blockcutter true so it should be gone, but its not

**Comment by JasonMcRay** [comment]
reported: https://github.com/Blood-Asp/GT5-Unofficial/issues/47
