### ISSUE TITLE
BP and WR-CBE

### ISSUE THREAD

**Issue by Erixonich** [JasonMcRay/InfiTech-1.7#205]
While using wireless reciver conected with red alloy wire and i have wondered that this cables are waiting for some block refresh to change their state. When signal is turned off this cables will also wait for some block refresh and etc.
![1](https://cloud.githubusercontent.com/assets/12836717/8095637/866ab06c-0fd8-11e5-8eb7-2f5889ac6a9c.png)
![2](https://cloud.githubusercontent.com/assets/12836717/8095638/866b8bcc-0fd8-11e5-8f99-b16eb8b50789.png)
![3](https://cloud.githubusercontent.com/assets/12836717/8095636/8669ac76-0fd8-11e5-8459-f7917a0a0712.png)
![4](https://cloud.githubusercontent.com/assets/12836717/8095639/866de1c4-0fd8-11e5-8787-14928c4d1d84.png)

**Comment by JasonMcRay** [comment]
Just to make sure I will report it to correct mod author. If you put normal redstone instead of the BP Alloy Wire. Is it waiting again for block update or not?

**Comment by Erixonich** [comment]
Vanila redstone items are working correct

**Comment by JasonMcRay** [comment]
This is known issue. For time being use Blue Alloy or other redstone wires.
