### ISSUE TITLE
TC Infused Ore harvesting issue

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#206]
The thaumcraft shard ores can be harvested with a stone pick, but not with the GT flint pick. Now that GT5 is being supported again that might be fixable now.

**Comment by JasonMcRay** [comment]
@Blood-Asp (I know I am lazy to open the issue on your issue tracker) :D

**Comment by JasonMcRay** [comment]
Or you know what, because I am feeling nice: 
Reported: https://github.com/Blood-Asp/GT5-Unofficial/issues/48

**Comment by JasonMcRay** [comment]
According to @Blood-Asp it would need to be changed in Thaumcraft, and since Thaumcraft development seems to stop for 1.7 I am closing this issue as minor.
