### ISSUE TITLE
Automatic Stack Replacement does not recognize GT tool types correctly!

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#207]
Inventory Tweaks has long had this issue;
When mining with a GregTech pickaxe or working with any GregTech tool and that tool breaks, Inventory Tweaks will attempt to replace the tool automatically - however, it almost never replaces it with the correct type of tool and many times whilst mining, ive broken a pick and suddenly found myself beating upon solid stone with a shovel, or my sword and vise versa found myself hitting a zombie with my pickaxe when my sword breaks.

**Comment by JasonMcRay** [comment]
I already tried to sort it out, its not really possible, but not sure why. @Blood-Asp any insight on this? I tried to add "craftingToolPickaxe" into the sorting/refilling config (tree) and it did nothing. Would it be possible to include Inventory Tweaks API inside GT?

**Comment by Blood-Asp** [comment]
i'm not sure how that works. normally it should be fine when inventory tweaks also looks at metavalue(damage value) when choosing the new item. this would be for all GT items.

**Comment by JasonMcRay** [comment]
just tried to put there id="gregtech:gt.metatool.01" damage="6" to code an axe... After it broke, got switched for a shovel... Not sure if it will be able to fix...

**Comment by JasonMcRay** [comment]
managed to do it. It will not work together with vanilla tools, so GT pickaxe will not get replaced after breaking by vanilla iron pickaxe; and vanilla Iron Pickaxe will not get replaced after breaking by GT Pickaxe. Just call it a limitation, because I am unable to do anything more.
