### ISSUE TITLE
Thaumcraft automated (tree)farms

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#208]
Jason can you modify the thaumcraft recipes?
All automated tree farms require LV or MV gregtech machines to make EXCEPT the golem which can be made before you are in the bronze age and DO NOT need any fuel or maintenance which is overpowered.
It would be good if the axe of the stream or the golem animation core chop recipes would be changed to require steel / stainless steel OR reduce the requirements for the other automated tree farms (but I think making it harder is better than making it cheaper).

**Comment by JasonMcRay** [comment]
Modifying TC recipes is quite hard to do. Changes will not appear inside Thaumonomicon, I have already tried to do some changes. It would confuse a lot of ppl :(

**Comment by DarknessShadow** [comment]
:( but they are so much more overpowered compared to the over automated treefarms

**Comment by JasonMcRay** [comment]
If the recipe is normal mcrafting, then yes. But if it requires Arcane Worktable, Infusion crafting or Crucible crafting, it will not show anywhere. Also you might see that Thaumium pickaxes still have default recipe in the Thaumonomicon.

**Comment by DarknessShadow** [comment]
But you could disable the arcane worktable recipe and make a normal one instead

**Comment by JasonMcRay** [comment]
Decided to leave it like it is now.

**Comment by GamesGamble** [comment]
hmm i think its quite OP consuming nothing. With the Golems i can literally do anything and that without any power, can do it before Bronze Age and yeah Thaumcraft generally is OP when you look at the other mods. Can you please change Thaumcraft Recipes?

**Comment by JasonMcRay** [comment]
You and probably others like @DarknessShadow will be glad to hear, that I
have a plan for that. But it will not be sooner than 3.2.x will come.

2015-11-02 7:45 GMT+01:00 Joscha <notifications@github.com>:

**Comment by GamesGamble** [comment]
very nice :D

**Comment by DarknessShadow** [comment]
Nice its finally happening :) !!

**Comment by JasonMcRay** [comment]
Feel free to post here suggestions for new recipes for certain Thaumcraft items. Keep in mind that I can't change recipes for multiblocks (like Infernal Furnace). But I can change regular recipes (Infusion, Arcane Workbench, Crucible) and also I am now able to reflect the changes in Thaumonomicon.

**Comment by DarknessShadow** [comment]
Thaumostatic Harness
It can be made without ANY gregtech machines.
I think the infusion recipe should include a basic circuit (or the ic2 jetpack)

Wand Focus: Excavation
This can also be made without ANY gregtech machines and it ignores the different mining levels for ores.
You can easily mine iridum ore with it (level 4).
I think the recipe should have one of the lvl4 material in it (iridium, naquadah, osmium or tungestensteel).

Golem Core: Harvest
100% automating farms shouldn't be possible before you reached LV.
Golems also don't need any maintenance and don't require power so I think they should require MV.
Change the crucible recipe to a arcane workbench recipe and make it so Golem Animation Core Blank + aluminium plate + circuit = Golem Core: Harvest

Arcane Bore
It doesn't require any gregtech machines.
Automated mining should be a bit harder than that. ^^
Change the arcane infusion recipe to require a LV or MV component (for example replace vanilla piston with MV electric piston).

**Comment by Xavion3** [comment]
Closing this now as it's been done with the TC overhaul. Excavation focus, Arcane Bore, and Harvest core are all MV now, harness is LV.
