### ISSUE TITLE
Thaumcraft cheat book

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#209]
The creative only cheat book is disabled in the configs which makes testing things in very annoying.
B:allow_cheat_sheet=true

**Comment by JasonMcRay** [comment]
It is disabled to prevent ppl spawining in the "cheat sheet" and by mistake learning all the researches. To test stuff in creative use commands: /thaum help

**Comment by DarknessShadow** [comment]
Oh I did not know there are commands for thaumcraft.
