### ISSUE TITLE
BC Quarry

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#212]
A recent discussion on the Public server, we're not sure the BC quarry is needed as we have EnderIO quarry.  If anything, the BC quarry although it requires an Advanced Diamond drill should be disabled, enderIO is better in almost every way as well as being harder to obtain and requiring a QED and more Tech/Power. 
BC quarry seems a bit OP and there is no reason to craft a EnderIO quarry or attempt to because of the BC version. 

Let me know your thoughts but the vast majority of people on the server are saing it's not needed and should be disabled.

**Comment by JasonMcRay** [comment]
enderIO Quarry? Or did you meant Extra Utilities EnderQuarry?

**Comment by groveham** [comment]
Yeah that's the one I mean ;)
