### ISSUE TITLE
Ender quarry nerf, and BC quarry disable

### ISSUE THREAD

**Issue by Erixonich** [JasonMcRay/InfiTech-1.7#213]
Recipe uses diamond pickaxe instead off drill. But BC's one uses correct recipe. Mb u will fix one these quarries?(Hope it will be EU quarry) And BC quarry can keep loaded up to 25 chunks for free (EU only 2 in every moment). It should be disabled.

**Comment by groveham** [comment]
Duplicate of https://github.com/JasonMcRay/InfiTech-1.7/issues/212
