### ISSUE TITLE
Graphite

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#218]
Graphite Dust cannot be smelted to Graphite Bar
Graphite Dust with an Ingot Mold in the Alloy Smelter cannot be smelter to Graphite Bar
4x Small Pile of Graphite Dust with an Ingot Mold in the Alloy Smelter can be smelted to Graphite Bar
Graphite Dust can be crafted into 4x Small PIle of Graphite Dust

Plz make a normal furnace recipe for Graphite Dust to Graphite Bar

**Comment by JasonMcRay** [comment]
Reported: https://github.com/Blood-Asp/GT5-Unofficial/issues/50
