### ISSUE TITLE
Flint Pickaxe and Rubber Wood

### ISSUE THREAD

**Issue by Ugachaga** [JasonMcRay/InfiTech-1.7#222]
1. Flint Pickaxe is not described as pickaxe so it cannot dig hard blocks as Gold or Magnetite Ore (cannot even destroy these blocks).

2. Not sure if issue but there is no recipe to craft Wooden Planks from Rubber Wood. Also Rubber Tree durability seems too low.

**Comment by Timeslice42** [comment]
1. While there is an issue with flint pickaxes that Blood Asp has been made aware of, the Harvestability WAILA plugin also doesn't know how to recognize GT tools, and basically lies. The flint pickaxe is not meant to harvest most ores. It can handle chalco, pyrite, and copper, but not magnetite, gold, iron, or tetrahedrite. Basically, if you can harvest it with a stone axe, then you're supposed to be able to harvest it with a flint axe. Infused ore is the exception to this (which is what the reported bug is about).

2. Rubber wood isn't proper wood. You're supposed to smelt it into jungle wood.
