### ISSUE TITLE
Thaumic Tinkerer enchants not in enchanter

### ISSUE THREAD

**Issue by Xavion3** [JasonMcRay/InfiTech-1.7#223]
So I figured I'd mention this as you added the thaumcraft ones but thaumic tinkerer adds about a dozen different enchants that currently can only be gained through it's system. You could add them to the enchanter if wanted. I could provide thoughts on what to use and lists if you feel it's worth going into more.

**Comment by JasonMcRay** [comment]
I will be taking a look at the enchants in one of the next updates.

**Comment by JasonMcRay** [comment]
@Xavion3 I would welcome a little help on the enchants. I am trying to come up with something, but my mind is too tired from all the stuff :(

Thanks a lot
