### ISSUE TITLE
Blue and purple alloy ingots uncraftable

### ISSUE THREAD

**Issue by Xavion3** [JasonMcRay/InfiTech-1.7#225]
Both of the other alloy ingots are uncraftable due to lacking non-BP recipes, blue alloy because it uses teslatite + silver but GT has nikolite + silver where nikolite isn't in this pack and purple alloy ingots just lack a non-BP recipe altogether. It should have red alloy + blue alloy or gold + 8 infused teslatite for the ways of making a purple alloy.

**Comment by JasonMcRay** [comment]
Blue alloy recipe is already implemented: https://github.com/JasonMcRay/InfiTech-1.7/blob/dev/scripts/bluepower.zs#L87
Purple alloy not. Working on it right now.

**Comment by JasonMcRay** [comment]
Fixed in https://github.com/JasonMcRay/InfiTech-1.7/commit/99694615031d725fc5a7befd7a3274da97e7ca28
