### ISSUE TITLE
Making distilled water

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#231]
The IC2 Condenser does not accept steam.

**Comment by JasonMcRay** [comment]
How are you trying to put steam in? It works fine for me.

**Comment by DarknessShadow** [comment]
with a fluid conduits from the top/side/bottom

**Comment by JasonMcRay** [comment]
As I said, works completely fine for me. So probably fixed in v3.1.0. If the issue persists, let me know.
