### ISSUE TITLE
Changelog Inaccuracy

### ISSUE THREAD

**Issue by bcg17** [JasonMcRay/InfiTech-1.7#234]
The change log does not state the removal of minechem. In v3.0.0 minechem was updated but is never stated to be removed in the later versions yet the pack in its current state does not have minechem in it.

**Comment by JasonMcRay** [comment]
On github the changelog can be incacurate, since sometimes I do some changes right before it is pushed to FTB Launcher. For most accurate please check the changelog posted on the FTB Forum: bit.ly/infitech2
