### ISSUE TITLE
Big Reactor

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#235]
Why does the Big Reactor consume 1mb of water to produce 1mb of steam?
To generate 400eu/t (2railcraft turbines) I need 13 (!!!) reservoirs to get the necessary water into the Big Reactor :(
(In real life its 1:1673 not 1:1)
Can you fix this somehow because making a closed loop with the Big Reactor turbine isnt a viable option either because it requires that you run the reactor first.
(Sadly there are no Liquid Transfer Nodes to supply so much water
Why are they disabled?)

**Comment by Timeslice42** [comment]
rofl. Apparently you completely ignored me when I discussed this 6 months ago. RL is roughly 1:1600, and minecraft is 1:800. This issue has been reported to erogenous, and he's changing it in BR 0.5x, which is a long way out.

Now you know why I stopped using BR with steam in 1.6 and won't go back until it's fixed. That being said the liquid transfer nodes shouldn't be disabled. They should be a QED recipe with bluetonium in the recipe somewhere.

But making a closed loop with the BR turbine is most certainly a viable option. The BR setup in IT2 is made only for using steam to generate RF. That's all Jason wants it to be used for. If you want to get EU out of it you have to use the PC conversion stuff. Pyure can show you how that's done.

**Comment by JasonMcRay** [comment]
Just as Timeslice said. BR is RF gen, if you want to have suitable EU gen make EU Reactors.
