### ISSUE TITLE
Yellorium

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#236]
Uranium 238 Ingot can be used in the Big Reactor
We could disable Yellorium Ore generation and change the recipes to use Uranium 238 Ingot instead.
(or make a crafting recipe to turn Uranium 238 into Yellorium if you dont want to change all recipes xD)

**Comment by Timeslice42** [comment]
I'd much prefer we disabled using other mods' uranium in the big reactor, but honestly disabling yellorium oregen would leave us with pure GT oregen, except for thaumcraft, which would be cool.

**Comment by winsomniak** [comment]
Blue power dust too

**Comment by DarknessShadow** [comment]
Jason why do you want yellorium / big reactor to be seperated from the rest ? ( also no yellorium generation on moon/mars)
I think it would be the best to use gregtech oregen for everything if possible.

**Comment by JasonMcRay** [comment]
Because having GT oregen for some of stuff, will be bit too much overkill.
