### ISSUE TITLE
Radioisotope Thermoelectric Generator

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#238]
With 6x Pellets of RTG Fuel its producing 32eu/t INDEFINITELY
6x Pellets of RTG Fuel costs 18 Plutonium 244 and 324 Iron
It was balanced in vanilla ic2 because getting plutonium was alot harder but now with plutonium veins its easy to get more than a stack of plutonium.

I think the recipe should be change to
use 3x DENSE Plutonium 244 Plate not ingots (9x the cost)
OR 
use 3x Crate of Plutonium 244 Plate (x16 the cost)

Also the recipe for the Generator itself should include adv circuits (requires mv)

**Comment by AiwendilCiunio** [comment]
you realize how rare plutonium veins are? I mean never found a single one yet, and I played quite a lot - dev server, v2 and now v3. Also I think its 24 eu/t (need to confirm).

**Comment by DarknessShadow** [comment]
Does that mean once you find a plutonium vein its good that you now have indefinitly 128eu/t or more?

**Comment by Xavion3** [comment]
And when you kill the ender dragon you can indefinitely get 2000EU/t, when you reach MV you can indefinitely get several million EU/t from solar panels, with thaumcraft you can indefinitely produce charcoal for EU, there are plenty of ways of producing power that are capable of lasting forever that aren't too complex. Plutonium really isn't one worth complaining about.

**Comment by pyure** [comment]
DS, today everyone did an about-face and decided plutonium veins could get nerfed.  All you needed was patience :p
