### ISSUE TITLE
Missing crafting recipes

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#241]
Chemical Red Dye doesnt have a crating recipe (also all other colors)
-> Red Pipe Wire uncraftable (all colors)
-> all buildcraft Gates uncraftable

**Comment by JasonMcRay** [comment]
Chemical Dyes cannot be crafted. Only way to obtain Chemical Dyes is to find the sprays in dungeons.

To craft Pipe Wires use the second recipe (Water Mixed Dye). Check NEI and dont look only at the first recipe you see.
