### ISSUE TITLE
Tesselator crash 

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#243]
http://pastebin.com/kYwdR6VC

I installed a few basic fluid conduits in my base and now cant spend more than 2 mins in the world before it ditches me with a rendering error - a couple of websearches indicate that this may be caused by optifine, will disable and update.

**Comment by Tyriael-Soban** [comment]
Seems to be an issue with optifine, disabling it stops the crashes.

**Comment by JasonMcRay** [comment]
Closing as invalid/not modpack related issue.
If the issue will re-appear without Optifine, then please report it again.
