### ISSUE TITLE
Solar Boiler gains heat at night.

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#246]
The GT solar boiler seems to continue to heat up in the middle of the night, just tested it with a few of them and this is what i saw, the boilers continue to generate heat regardless of the time of day.
![2015-06-24_15 14 31](https://cloud.githubusercontent.com/assets/9297841/8341788/8dd4c336-1a84-11e5-8105-cde4273b786e.png)

**Comment by JasonMcRay** [comment]
Single player or Multiplayer?

**Comment by Tyriael-Soban** [comment]
Single player.

**Comment by Xavion3** [comment]
It's been mentioned in the thread I'm pretty sure but this happens on multiplayer as well, the official server is affected by it.

**Comment by DarknessShadow** [comment]
Yes it happens also on the public server.

**Comment by JasonMcRay** [comment]
Reported to @Blood-Asp
https://github.com/Blood-Asp/GT5-Unofficial/issues/74
