### ISSUE TITLE
Ender IO Item conduits fill ALL slots on BBF.

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#248]
Attempted to automate my BBF and this happened.
Took items out and threw them back in to check, but every time i put them back in, they just fill the entire machine up, stopping production.
It also seems to only input 4 iron bars into the top slot before attempting to send them elsewhere.

![2015-06-26_16 17 34](https://cloud.githubusercontent.com/assets/9297841/8388401/0933a6b4-1c1f-11e5-8c6b-19aaa193bf0f.png)

**Comment by JasonMcRay** [comment]
This is intended, you arent supposed to automate BBF.
