### ISSUE TITLE
Drum vanishing

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#249]
Using the Advanced Diamond Drill in 3x3 Mode on drums makes the drums vanish.

**Comment by JasonMcRay** [comment]
Note for myself: test with other tools that mine 3x3 to pinpoint which mod is resposible.

**Comment by JasonMcRay** [comment]
Gravisuite issue. Reported:
http://forum.industrial-craft.net/index.php?page=Thread&postID=189974#post189974

**Comment by JasonMcRay** [comment]
Mod not updated for over a half a year. Closing. Just be aware of this issue,
