### ISSUE TITLE
Galacticraft Oxygen

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#253]
I think the galacticraft Oxygen Bubble Distributor should be disabled because it does NOT need a closed area to function. The Oxygen Sealer needs a closed area to function and is disrupted when you open 1 block which creates the need for Airlocks.
Also it does not make sense to make a "Air Bubble" inside a vacuum.

**Comment by Xavion3** [comment]
Complain to galacticraft devs? They clearly felt the bubble distributor makes sense, so maybe it functions in some complex technobabble way.

**Comment by JasonMcRay** [comment]
I am not going to disable any blocks without game breaking reason. Not going to listen to the whining "it was craftable, but now its not, people who made it are in advantage" and blablabla
