### ISSUE TITLE
Missing recipe

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#254]
The Gas Liquefier has no recipe which is bad because its needed to convert gregtech oxygen into galacticraft oxygen.

**Comment by DarknessShadow** [comment]
The Gas Liquefier is uncraftable because the Fluid Manipulator in the recipe has no recipe

**Comment by JasonMcRay** [comment]
Crap. I have forgot about it. Sorry.
