### ISSUE TITLE
Automatic Stack Replacement shows no regard for the type of item when shuffling GT items.

### ISSUE THREAD

**Issue by Tyriael-Soban** [JasonMcRay/InfiTech-1.7#255]
I'm not entirely sure if this one can -actually- be fixed, but when inventory tweaks does its automatic stack replacement, say i'm moving steel into into a barrel with a double RMB; it will whip a totally unrelated item into my hand thats also from GregTech, like stone dust, or a totally different ingot like bronze, or even any other type of metal plate that is in my inventory.

**Comment by JasonMcRay** [comment]
unfortunately there is no easy way to "fix" this. It would require literaly typing every item into the InventoryTweaks config. The best solution if it bothers you is to disable the replacement
