### ISSUE TITLE
Galacticraft config

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#257]
I think rockets should be able to launch in the end and go to the end (with launch controller)

Also if you die on any galacticraft dimension you will spawn there -> you can get stuck there

Thats how the configs should be :)

   # IDs of dimensions where rockets should not launch - this should always include the Nether.
    I:"Dimensions where rockets cannot launch" <
        -1
     >

 # May rarely cause issues if enabled, depends on how the other mod's dimensions are.
    B:launchControllerAllDims=true

B:"Force Overworld Spawn"=true

**Comment by JasonMcRay** [comment]
Traveling to the End via rocket is nonsense. End is not a planet.

Overworld spawn forcing will be enabled in next version.

**Comment by JasonMcRay** [comment]
On the other hand, it will allow players to abuse it for easy return to overworld (with the use of ender chest). So no. The overworld spawn forcing will not be enabled. Either try not to die or built your moon/mars outposts near spawn.
