### ISSUE TITLE
FML Handle event/crafting console errors

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#261]
Don't think it's having an impact on gameplay as far as I can tell but I'm getting a lot of errors in the console to do with FML PlayerEvents. I have tested this on our test server without any extra mods added such as MyTown2. 

http://pastebin.com/nLWpS24D

If you need anything else give me a shout

**Comment by JasonMcRay** [comment]
Steves Workshop issue. 
Reported: https://github.com/Vswe/Production/issues/32
