### ISSUE TITLE
Dusts priority

### ISSUE THREAD

**Issue by CAHbl4** [JasonMcRay/InfiTech-1.7#267]
After 3.1.2 update all dust outputs comes in ic2 version if they presented in ic2. Not a big deal but little ridiculous.

**Comment by JasonMcRay** [comment]
I changed the unification targets in 3.1.2, because some machines were no matter what outputting non-GT dusts, which lead to "double-unification". On output slot or in chests they stayed as for example IC2 dust, but when you picked it up manually it turned into GT version.
