### ISSUE TITLE
Forestry Worktable not working nicely with recipes that need GT Tools

### ISSUE THREAD

**Issue by SolManX** [JasonMcRay/InfiTech-1.7#269]
Layout any recipe involving a GT tool. Eg Iron pick head.

Clicking the output *will* give you a pick head. Clicking a second time won't. You'll have to re-layout the recipe.

Other recipes work fine.

I *guess* it's possibly related to the damage/durability values changing on the tools.

**Comment by JasonMcRay** [comment]
Reported: https://github.com/ForestryMC/ForestryMC/issues/750

**Comment by JasonMcRay** [comment]
Fixed in unstable forestry builds.

**Comment by JasonMcRay** [comment]
Appears to not still be fixed. Putting on Hold

**Comment by JasonMcRay** [comment]
Ok now it should be fixed in: https://github.com/JasonMcRay/InfiTech-1.7/commit/13c2154c827dd85c8672a7cfad5a18cce8ae0352

**Comment by JasonMcRay** [comment]
I guess I will rename this issue thread to "Neverending Worktable Issues".

Another issue found and that is when I layout a recipe for example to make Iron Plate
x, H, x
x, I, x
x, I, x

H = Any GT Hammer
I = Iron Ingot
x = nothing

And I put the Hammer and Iron Ingots into the storage area, I start to hear massive ear-busting hammering sound looping again, again, and again until I close the worktable

I remember this issue to be present in the past, then it got somehow fixed, and now it is back.
