### ISSUE TITLE
Connected Textures

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#270]
The enderio Facades dont have connected textures anymore In the newest version 3.1.2 
<a href="http://imgur.com/lHYKei9"><img src="http://i.imgur.com/lHYKei9.jpg" title="source: imgur.com" /></a>

**Comment by AiwendilCiunio** [comment]
I can confirm that, before update it was fine.

**Comment by JasonMcRay** [comment]
Is it for all blocks that have connected textures? or only for example with chisel blocks?

**Comment by AiwendilCiunio** [comment]
hard to tell because I can't think of any non-chisel blocks that have connected textures. Other than glass, but that won't work with facades. Can you give me examples of such blocks so I can test them?

**Comment by JasonMcRay** [comment]
extra utilities types of stone for example

**Comment by AiwendilCiunio** [comment]
nope, ExU edged stone bricks don't connect either.

**Comment by DarknessShadow** [comment]
The enderio facades do have connected textures with each other
<a href="http://imgur.com/cffdHdP"><img src="http://i.imgur.com/cffdHdP.jpg" title="source: imgur.com" /></a>

**Comment by JasonMcRay** [comment]
Ok. Reported to eIO dev: https://github.com/SleepyTrousers/EnderIO/issues/2641

**Comment by JasonMcRay** [comment]
Still happens with ExU. It has been reported while ago. https://github.com/rwtema/extrautilities/issues/462

**Comment by JasonMcRay** [comment]
Looks like RWTema is not really looking at the reported issues that much :(. Gonna close this.
