### ISSUE TITLE
Vanilla Diamond Ore in the End

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#271]
A player has found vanilla diamond ore in the end. I have asked for a screenshot and they have uploaded it here (2nd image down). You can faintly see the diamond ore in the bottom left corner on the underside of an asteriod in the end. 

http://infitech.enjin.com/forum/page/1/m/26910956/viewthread/22823167-just-small-screenshot-about-ateroids-dimension#p101175106

**Comment by JasonMcRay** [comment]
@Blood-Asp I call you in here (before i will report it on your git :D)
It obviously is spawning on Hardcore Ender Expansion Island, but before I will bother Chylex, would like to see if there is something you could do :p

**Comment by Blood-Asp** [comment]
No, i don't think there is anything i could do. No idea how this could happen, but GT and GalacticGreg both have zero code that could spawn vanilla stuff, so i can be sure it is not on my side.

**Comment by DarknessShadow** [comment]
Ehm Jason this was reported months ago (by me) and thats a feature of HEE
https://github.com/JasonMcRay/InfiTech-1.7/issues/81

**Comment by JasonMcRay** [comment]
Oh well then.. there we go....

**Comment by chylex** [comment]
That's a feature of HEE :P
