### ISSUE TITLE
Not able to get Bronze dust achievement on last version

### ISSUE THREAD

**Issue by miguel1118** [JasonMcRay/InfiTech-1.7#272]
I cant get the bronze dust achivement on this version(3.1.2) it seems that it need gt bronze dust but 
everytime I craft it changes to ic2 bronze dust, 
I've tried with the normal craft (3 copper dust + 1 tin dust on inventory)
Giving me gt bronze dust with creative
Using a mixer
Crafted it with small bronze pile dusts
Converting bronze ingot into dust

Nothing seems to work

**Comment by miguel1118** [comment]
I've downgrade to 3.1.1, now I can craft gt bronze dust but it still didnt gave me the achievement S:

http://s28.postimg.org/pxkmhipcd/Sin_t_tulo.jpg

**Comment by DarknessShadow** [comment]
try to drop it on the ground and pick it back up that helps sometimes

**Comment by miguel1118** [comment]
Yeah, I´ve tried that lot of times, sadly it didnt work..

**Comment by Tyriael-Soban** [comment]
I have a similar issue with regards to creation of magnetic rods on 3.1.1 - i cannot get the achievement for making the rod and i have tried throwing them on the floor and making them on the vanilla minecraft table.

**Comment by miguel1118** [comment]
There are more bugs on the achievements?
Oh well, maybe I should stop trying to complete them

**Comment by JasonMcRay** [comment]
I would suggest if you encounter an achievement bug, report it directly to @Blood-Asp, because its completely something out of my hand.

https://github.com/Blood-Asp/GT5-Unofficial/issues

**Comment by miguel1118** [comment]
Thanks, I've already posted it there

**Comment by JasonMcRay** [comment]
According to GregTech Issue Tracker it is fixed.
