### ISSUE TITLE
Pneumaticcraft Helmet Durability Zero

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#274]
I crafted a Pneumaticcraft helmet with empty air canisters. The helmet appeared to have an *actual* durability of 0, even though it *reported* a durability of 120000. I charged the helmet to 4 bars of pressure, and after a couple of hits from a zombie it disappeared from my head.

I crafted another helmet with air canisters pre-charged to 4 bars, then I charged the completed helmet to 4 bars. After a couple of hits from a zombie the helmet displayed a normal durability bar.

I have found no information that this is normal behavior for a helmet crafted with zero-bar canisters. AFAIK crafting the helmet with empty canisters should be allowed. I have found a few pieces of information that indicates this use to be a possible bug, but it was closed on the developer's GitHub due to lack of info (iirc).

I already posted this to the Forum on the InfiTech2 Public Server, and I can re-open it on the dev's if you think this is on him.

**Comment by JasonMcRay** [comment]
Reported to devs: https://github.com/MineMaarten/PneumaticCraft/issues/519
