### ISSUE TITLE
Oxygen Sealer

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#276]
I tested a bit and the following blocks dont work to pressurize a room.

Thickend Glass 1445
Edged Glass 1445:1
Glass Bricks 1445:2
Carved Glass 1445:3
Golden Edges Glass 1445:4
Obsidian Glass 1445:5
Swirling Glass 1445:6
Glowstone Glass 1445:7
Heart Glass 1445:8
Square Glass 1445:9
Dark Glass 1445:10
Reinforced Dark Glass 1445:11
Ethereal Glass 1480
Ineffable Glass 1480:1
Dark Ethereal Glass 1480:2
Ethereal Glass (Inverted) 1480:3
Ineffeable Glass (Inverted) 1480:4
Sapphire Glass 1776
Reinforced Sapphire Glass 1777
White Stained Glass 580 (+ all colors 580 -> 580:15)
Carpenter's Garage Door 1134
Garage Door 1553
Wooden Vanishing Frame 1549
Iron vanishing Frame 1549:1
Gold Vanishing Frame 1549:2
Diamond Vanishing Frame 1549:3
Diamond Vanishing Frame 1550

**Comment by Timeslice42** [comment]
I'm not convinced that the garage doors should count as air-tight. Everything else looks right to me.

**Comment by DarknessShadow** [comment]
I think they should because they are basicly like the galacticraft airlock except you can make it look however you want.

**Comment by Timeslice42** [comment]
I haven't seen the malisis garage doors, but I was talking about both of them. Garage doors have seams in them, which is why things like airlocks were invented in the first place.

**Comment by JasonMcRay** [comment]
C'mon you are really thinking that I will allow DOORS as air locks?...

**Comment by DarknessShadow** [comment]
Then dont add the door to the sealable blocks but its still strange how you are against this but not against the "Oxygen Bubble Distributor" that can do the same as the oxygen sealer but WITHOUT any kind of room / sealable blocks around it.

**Comment by Timeslice42** [comment]
Lol, now you're just reaching, Darkness.

**Comment by JasonMcRay** [comment]
Added. Except vanishing frames and walkthrough glass. Vanishing frames acts as doors and walkthrough glass is glass that player can pass, so if entity can, then the oxygen can pass through it as well
