### ISSUE TITLE
IC2 Cables

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#278]
I think it would be good to reenable the ic2 cables because
1) people just transfer batteries for lossless energy
2) it quite annoying to use transformers as cables for rtg / semifluid generators

Maybe just reenable the glass fibre cable with a more expensive recipe so nobody will use them for long distance lossless energy transfer.

**Comment by JasonMcRay** [comment]
Yea people are using workaround for this... hmm.. lets see, lets get rid of all other mods, because they cause as an workaround to some aspects.

And why use transoformers as cables, just use one transformer and then cables....
