### ISSUE TITLE
Chiseled Arcane Stone Blocks trasparency

### ISSUE THREAD

**Issue by Ugachaga** [JasonMcRay/InfiTech-1.7#279]
Infitech2 3.13:
![infitech313chisel](https://cloud.githubusercontent.com/assets/12869346/8539266/3740e7e0-249b-11e5-8e22-03de3808e7b9.jpg)

Some Chiseled Arcane Stone Blocks are transparent like xray:
- Beveled Tile;
- Brick (not original Thaumcrafts Arcane Stone Brick);
- Temporal Conduit;
- Braaainz;
- Internally Arcane.

Issue appeared with upgrade to Chisel 2.4+ (2.3.10.37 works fine).

**Comment by JasonMcRay** [comment]
I had similiar issue, can you pls provide a fml client log? Its probably too big for pastebin so upload it somewhere and post a link for download. Thank you

**Comment by Ugachaga** [comment]
Going a bit deeper it is Optifine bug. 

[There](https://github.com/Chisel-2/Chisel-2/issues/173) is described a similar problem with older versions of Optifine+Chisel and given instructions for troubleshooting:

> This problem start when you use multi-core chank loading.

So it is not Infitech problem, I will just roll back to Chisel 2.3.10.37 until/if Optifine fix it.
