### ISSUE TITLE
[Suggestion] Thaumcraft NEI Plugin

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#280]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2237271-1-6-4-1-7-10-thaumcraft-nei-plugin-nei

So Aiwen doesn't forget that thaumium armor is crafted with plates... :P

**Comment by JasonMcRay** [comment]
I suppose it shows NEI recipes only if player has a research, right?

**Comment by Timeslice42** [comment]
Correct.

**Comment by DarknessShadow** [comment]
Does that mean you can/will now change Thaumcraft recipe with that plugin?

**Comment by JasonMcRay** [comment]
Yes and no. I will not change that.
