### ISSUE TITLE
Journeymap Mini-map often non-functional underground.

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#285]
The 5.1.0 version of JourneyMap unlimited is having issues on my world. Half the time it displays a blank (grey) map for the slice that I'm in while underground. However the full-screen map is working as expected. I've never tried the fairplay version of JM, but I wonder if it's getting confused about which edition it is.

I've reverted to 5.0.1 in the mean-time.

**Comment by JasonMcRay** [comment]
If you will zoom in/out does it still happens? Also can you try to delete the map data files (journeymap/data/sp(mp)/{world}/DIMx) and see if it will still happen?

**Comment by Timeslice42** [comment]
I tried creating a new world to see what would happen. Still having the same problem. The weird thing is I get different things displayed at different zoom levels while standing in one location:
http://imgur.com/aEUgxg0
http://imgur.com/P5ZWRTy
http://imgur.com/XymhykX

**Comment by JasonMcRay** [comment]
Hmm.. Could you provide fml-client-latest.log (minecraft/logs), and journeymap.log (minecraft/journeymap/journeymap.log)? Thanks

**Comment by Timeslice42** [comment]
Someday I'll actually remember to get you this information...

**Comment by Timeslice42** [comment]
https://www.dropbox.com/s/ue5crw9qy364jro/JourneymapIssue.zip?dl=0
This was a short run from my base down through my mining areas. Different slices at different zoom levels, with the most zoomed out level usually just showing grey on the minimap. The full map always showed what I expected.

Sadly there doesn't seem to be any red flags in either log file.

**Comment by JasonMcRay** [comment]
Thanks.

**Comment by JasonMcRay** [comment]
Closing as Minor, since mod dev doesnt responded to the ticket since it was reported to him.

**Comment by Timeslice42** [comment]
Which is why I just stuck with the older version of journeymap.
