### ISSUE TITLE
Forestry Backpack

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#286]
The 45 slots version of the backpacks cannot be made with an already used (but empty) 15 slot backpack
Tested it with digger and miners backpack

**Comment by JasonMcRay** [comment]
This is unfortunately not possible to fix, bue to Forestry Backpacks when used are assigned unique ID, which I can't wildcard.

I am asking modTweaker devs, if there is a solution for that. You can keep an eye in here: https://github.com/jaredlll08/ModTweaker2/issues/180

**Comment by DarknessShadow** [comment]
Is the crafting issue only with the carpenter or can you make a normal crafting recipe to turn it back into a "new" backpack?

**Comment by JasonMcRay** [comment]
In all crafting recipes, so I am unable to make a recipe to craft that "special UID backpack" back to "normal" :(

**Comment by JasonMcRay** [comment]
Not ModTweaker issue, Its core Minetweaker :( which is bad, because I dont see any updates to the code for over a year :(

Anyway Reported there as well. https://github.com/stanhebben/MineTweaker/issues/33

**Comment by DarknessShadow** [comment]
Is there a reason why you report it to ModTweaker and MineTweaker but not Forestry directly?

**Comment by Voidi** [comment]
Recipe for turning back to new backpack:
`recipes.addShapeless(<Forestry:minerBag>, [<Forestry:minerBag>]);`

**Comment by JasonMcRay** [comment]
>Recipe for turning back to new backpack:
recipes.addShapeless(<Forestry:minerBag>, [<Forestry:minerBag>]);

I have tried that and it did not work. Not sure why. Will mess with it tomorrow.
