### ISSUE TITLE
Magical Wood

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#291]
Magical Wood can be crafted with gregtech swords that have enchants on them but it only takes 100 durability of them instead of consuming it completly.
4x gt thaumium swords give 8 magical wood with each crafting and it can be repeated 256 times giving a total of 32 stacks magical wood.

**Comment by JasonMcRay** [comment]
Since this would need to be fixed in ExU side, and due to my past experience on "how fast it will be fixed" I am making HardCoded fix. Magical Wood will be only crafted by using crafted enchanted books (minecraft:enchanted_book). Nothing else.
