### ISSUE TITLE
Ender Quarry Speed Upgrade

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#293]
The Ender Quarry Speed Upgrades are not craftable. All other upgrades have a recipe.

**Comment by JasonMcRay** [comment]
Its interesting because i am unable to find any reference to Speed Upgrades and their being disabled. No Minetweaker script, no config set to disable them. They are just gone (do you remember when they were craftable, if they even were?)

**Comment by DarknessShadow** [comment]
I dont remember when they had a crafting recipe but i didnt look for one before i made the quarry some days ago.
