### ISSUE TITLE
malisiscore looking for DoorTileEntity

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#294]
http://pastebin.com/gvFq3Vb3

Seems to be a bug, not sure if it's with the modpack setup/config or the mod itself but people are timing out when a certain players joins. Lots of these in the console, I just copied what I could.

**Comment by JasonMcRay** [comment]
Hmm.... can you test with updated MalisisCore (http://minecraft.curseforge.com/mc-mods/223896-malisiscore/files) and MalisisDoors (http://minecraft.curseforge.com/mc-mods/223891-malisisdoors/files)?

**Comment by groveham** [comment]
I only have one server as of Yesterday so I will try to re-create it on my personal PC. Not sure if I can replicate the exact conditions but will give it a shot!

**Comment by JasonMcRay** [comment]
Maybe also ask for fml-client log from those who are getting timed out.

**Comment by groveham** [comment]
My FML Client Log, The Server time and Client log times are the same too to make it easier. 
https://www.dropbox.com/s/bmcdaihia7frceq/fml-client-latest.log?dl=0

Tested with the latest version seems to fix it as far as I can tell with one players testing visiting peoples bases too. 
malisiscore-1.7.10-0.12.5.jar
malisisdoors-1.7.10-1.9.3.jar
