### ISSUE TITLE
[Suggestion] Cosmetic config settings

### ISSUE THREAD

**Issue by Ugachaga** [JasonMcRay/InfiTech-1.7#296]
1)  Disable welcome message by MrCrayfishFurnitureMod (./config/cfm.cfg): 
```
# Enabled or disable the welcome message [default: true]
B:display=false
```
2) Enable Forge load sceen, compatible with latest Optifine (./config/splash.properties):
```
enabled=true
```
3) Move Gravisuite GUI to bottom for use with Thaumcraft GUI (./config/gravisuite.cfg):
```
I:hudPosition=3
```

**Comment by JasonMcRay** [comment]
1) Yep can do that.
2) Will not enable load screen. Reason is, some players (me included) are having problems with the screen getting stuck during the load. 
3) Every side is occupied so there is no place for it. TopL: Thaumcraft; TopR: Minimap; BottomL: Chat; BottomR: Galacticraft Oxygen Indicator.

**Comment by Ugachaga** [comment]
![gravichat](https://cloud.githubusercontent.com/assets/12869346/8669738/d5b7bb68-2a38-11e5-84ba-c083e1eae687.jpg)

Two rows fits just perfectly under the chat.

**Comment by JasonMcRay** [comment]
Oh. ok then. Thanks
