### ISSUE TITLE
Dimensional Anchor and World/Personal Anchor fuels costs wildly different

### ISSUE THREAD

**Issue by Xavion3** [JasonMcRay/InfiTech-1.7#297]
So both machines do effectively the same thing but have wildly different costs. Not sure what you want to use or if they scale differently off number of chunks but I've just written up each ones values in the other's format if you want to pick one.

Railcraft values for Immibis anchor
```
S:chunkloader.fuels=minecraft:ender_pearl=864000
```

Immibis values for Railcraft anchors
```
S:passive.fuel=minecraft:ender_pearl=0.25,minecraft:nether_brick=0.00278,minecraft:netherrack=0.00112,minecraft:dirt=0.00028,minecraft:glowstone_dust=0.03334,EnderIO:itemMaterial#5=0.75,EnderIO:itemMaterial#6=1.0,minecraft:ender_eye=0.5,minecraft:stone=0.00084,minecraft:coal#1=0.01667,minecraft:nether_star=2.0,minecraft:magma_cream=0.25,minecraft:cobblestone=0.00028,minecraft:coal#0=0.16667,minecraft:redstone=0.01667
S:personal.fuel=minecraft:ender_pearl=0.25,minecraft:nether_brick=0.00278,minecraft:netherrack=0.00112,minecraft:dirt=0.00028,minecraft:glowstone_dust=0.03334,EnderIO:itemMaterial#5=0.75,EnderIO:itemMaterial#6=1.0,minecraft:ender_eye=0.5,minecraft:stone=0.00084,minecraft:coal#1=0.01667,minecraft:nether_star=2.0,minecraft:magma_cream=0.25,minecraft:cobblestone=0.00028,minecraft:coal#0=0.16667,minecraft:redstone=0.01667
S:world.fuel=minecraft:ender_pearl=0.25,minecraft:nether_brick=0.00278,minecraft:netherrack=0.00112,minecraft:dirt=0.00028,minecraft:glowstone_dust=0.03334,EnderIO:itemMaterial#5=0.75,EnderIO:itemMaterial#6=1.0,minecraft:ender_eye=0.5,minecraft:stone=0.00084,minecraft:coal#1=0.01667,minecraft:nether_star=2.0,minecraft:magma_cream=0.25,minecraft:cobblestone=0.00028,minecraft:coal#0=0.16667,minecraft:redstone=0.01667
```

**Comment by JasonMcRay** [comment]
Thanks for suggestion but I ended up with doing it completely different.

RC anchor can be only powered by Ender Pearls for 4hrs - 3x3 chunks
Immibis Anchor can be powered by Nether Star (24hrs), Coal (10min), Charcoal (1min) and Vibrant Crystal (12hrs) - 1 chunk

So RC Anchors are efficient for covering large areas, wheres Immibis are scalable and can use variety of fuel but not that much efficient in large areas.

**Comment by DarknessShadow** [comment]
Why is charcoal only 10% as good as coal?
Why did you decrease the RC anchor costs by 100%?

**Comment by Ugachaga** [comment]
As for me, Immibis Anchor still looks completely useless compared to RC Anchor. Atleast if you can afford to spend ender pearls (ender lilies world loot allow it, regardless of the technological level and access to the End). But if you just started you can't/shouldn't use any of Immibis Anchor fuel: charcoal just garbage and coal much useful to convert into diamonds. Perhaps Thaumcrafts Alumentum would be a good possibility to use charcoal as base to fuel Anchor. 

Still it's a very narrow field of application for 1x1 chunk loader. The only real use of Immibis Anchor is for covering large area, but the price looks extremely high (I'm in the middle of HV era, don't know about endgame stage). It would be great if we can fuel Immibis Anchor by ender pearls/eyes of ender with RC Anchor rate or so.
