### ISSUE TITLE
SG Craft Bugs

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#300]
An incoming wormhole can be closed with the computers even though its disabled in the config.
When deactivating an outgoing wormhole the opencomputers computer suddenly sees it as an incoming wormhole.

I cant find the bugreport thing for sgcraft do you know where I should report this?

**Comment by JasonMcRay** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287806-gregs-sg-craft-1-9-3-for-minecraft-1-7-10 directly on the forum
