### ISSUE TITLE
QED ore processing recipes 

### ISSUE THREAD

**Issue by Ugachaga** [JasonMcRay/InfiTech-1.7#301]
QED ore processing recipes does not support GT ores. 

Also there is strange SAG mill recipe Yellorium Ingot to Uranium 238 dust.

**Comment by JasonMcRay** [comment]
I cant add GT ores to QED processing (these kinds of recipes are hardcoded), thats up to ExU itself, and as I know RWTema and his approach to suggestions i dont think he will add support to it. You could try to report it and ask him about that (https://github.com/rwtema/extrautilities/issues)

As for Yellorium to Uranium in sag mill, I will take a look onto it.
