### ISSUE TITLE
Pneumaticcraft Pneumatic Door "Camouflage" not working with Chisel2 Blocks

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#303]
The UI of the pneumatic door from Pneumaticcraft has a place to put a block so the operating mechanism can be disguised. It works perfectly with every block I have tested EXCEPT Chisel2 blocks which have no effect. Chisel2 blocks used to camouflage the mechanism properly, but stopped working a couple modpack revisions back.

I already posted this to the InfiTech2 Public Server Forums. I am not sure in which other GitHub it belongs, either Pneumaticcraft or Chisel2.

**Comment by JasonMcRay** [comment]
Most likely PneumaticCraft issue.
If you want to add some info or be kept posted about the issue convo: https://github.com/MineMaarten/PneumaticCraft/issues/562

**Comment by JasonMcRay** [comment]
@lafflam may I ask for full FML-client log? It will be probably too big for pastebin so upload whole file somewhere and post me a link.
