### ISSUE TITLE
Firewall Pipe

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#305]
The logisticspipe firewall pipe can cause a world corruptions.
I think we should remove the recipe for it until its fixed.

**Comment by lafflam** [comment]
Here is the first crash log on the InfiTech Public Server associated with this bug:

http://pastebin.com/CEhFxV0B

**Comment by theZorro266** [comment]
Should be fixed by https://github.com/RS485/LogisticsPipes/commit/e2111489f76e3f7384b9eb75c00a6ba87370e556

**Comment by JasonMcRay** [comment]
Well that was unexpected and fast :)
