### ISSUE TITLE
[3.1.4] Cropnalyzer no longer working

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#306]
While you can still use it to get info on pre-scanned crops in-world, the cropnalyzer can no longer be opened with a GUI to scan seed bags. Was this a modpack change or an IC2 change? Or a bug?

**Comment by JasonMcRay** [comment]
Known issue, fixed in latest IC2.
Dupe of #299

Will be making pack update this weekend. So either wait or update manually IC2
