### ISSUE TITLE
Cropnalyzer charging discrepancies

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#307]
Using the latest IC2 (756) the cropnalyzer, which now has 100k EU storage built in, can be charged using an LV battery (RE-battery), but cannot be charged in an LV battery buffer. I don't remember if minetweaker lets you set the charging tier of an item.

**Comment by JasonMcRay** [comment]
GT Issue (probably).
Reported: https://github.com/Blood-Asp/GT5-Unofficial/issues/96

**Comment by JasonMcRay** [comment]
Actually, can you charge the Cropnalyzer in IC2 energy storages (batbox, mfe, etc.)? If not, then its either intended to not work in LV Bat Buffer, or it should be chargable in IC2 storages and it is IC2 bug

**Comment by JasonMcRay** [comment]
Also please try out the MV buffer (as suggested by @Blood-Asp)

**Comment by Timeslice42** [comment]
Yeah, it works fine in both an MV battery buffer and a CESU.
