### ISSUE TITLE
Arc Furnace Charcoal issue

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#308]
The arc furnace has a recipe which takes wood and oxygen and creates charcoal. However charcoal must be made in the absence of oxygen, so this doesn't make any sense.

**Comment by DarknessShadow** [comment]
What about the Coke Oven?

**Comment by JasonMcRay** [comment]
Hmm.. looks like I cant code it without Oxygen. It looks like the Arc furnace NEEDs fluid to be present in it.

**Comment by JasonMcRay** [comment]
just got told that there will be natively different style of Making Charcoal. So this will be no longer relevant. Closing.
