### ISSUE TITLE
[Suggestion] Jabba tiers color

### ISSUE THREAD

**Issue by Ugachaga** [JasonMcRay/InfiTech-1.7#309]
![jabba_colors](https://cloud.githubusercontent.com/assets/12869346/8888038/490207d0-32be-11e5-9cd1-5b39a1911e5e.jpg)
Recently added tiers of barrels is not distinguished by color. It seems that this can be corrected as the config file has settings to override color through the tiers.

**Comment by DarknessShadow** [comment]
I think the color should be something like this
Tier 3 Wrought Iron AB9A9A
Tier 4 Cobalt 4444D6
Tier 5 Steel 6D6D6D
Tier 7 Diamond C1F6F6
Tier 8 Aluminium 649CBB
Tier 9 Titanium BC89CD
Tier 10 Tungstensteel 555589
Tier 11 Iridium BBBBBF
