### ISSUE TITLE
GT charged quartz relict

### ISSUE THREAD

**Issue by Ugachaga** [JasonMcRay/InfiTech-1.7#311]
Wiremill recipe for quartz fiber still using deleted gt.metaitem.01.23517

**Comment by JasonMcRay** [comment]
Oh whoops. I thought I got rid of all of them... Cant curently check but is there still another way of getting Quartz fiber with something else in wiremill?

Just want to know how serious is this problem.

**Comment by DarknessShadow** [comment]
You can get it with certus quartz/ charged certus / nether quart and quarzite
