### ISSUE TITLE
ME system dupe

### ISSUE THREAD

**Issue by Erixonich** [JasonMcRay/InfiTech-1.7#312]
After every restart quantity of items in my me system is doubled. Even if i take all storage cells from drives i can see and INTERACT with half of my items. I thought it is visual bug. But yesterday i ve done one experiment: I took 2 turbines from system (before this bug i had 1 turbine btw). and waited next restart. Now i have 2 turbines, which can be used. I think i can dupe all my items. And all my Railcraft machines (turbine, boiler, coke oven) stop working after restart. All this is happenned after patch 3.1.4.

**Comment by JasonMcRay** [comment]
Test with 3.1.5 please and report back. Thanks

**Comment by Erixonich** [comment]
I Can't repeat it in sp. Need to w8 update
