### ISSUE TITLE
Severe Server Lagspikes - Cause Unknown

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#316]
Over the past several weeks, the players on the InfiTech Public Server have helped identify some bugs that were causing lag problems, and our efforts helped get some bugs fixed. But as you may be aware, we are still battling extremely severe lagspikes, and have not been able to figure out an exact cause.

I created a long post in the Bugs Forum of the InfiTech Public Server website describing our problem. I included some relevant stats about our server, screenshots of Opis, plus three VisualVM snapshots during some of the worst lagspikes today. I also included snapshots of the server running great shortly after restart.

I hope the information could help pinpoint the cause of the severe lagspikes.

Here is a link to the thread:
http://infitech.enjin.com/forum/m/26910956/viewthread/23374161-severe-server-lagspikes-cause-unknown

If you would like me to duplicate all of that information here, I can try. Please let me know what additional information could help.

EDIT: Here is one of many stall reports generated by the sampler mod during the lagspikes documented in the Forum link above. I hope this helps:

http://pastebin.com/2sgNetEk

Here is another a few hours later:

http://pastebin.com/dXH0VY8y

**Comment by AiwendilCiunio** [comment]
We would also like if someone could direct us to people that could help us, or indicate where we should ask for help. We don't really have programmers among us, so looking for a solution is a bit like searching for a needle in a hay bale (yes, it's a polish saying, but you get what I mean : P)

**Comment by lafflam** [comment]
Based on suspicion from Grove and testing from Jason, we removed Forge Essentials from our server and replaced it with ServerTools. For part of the day the server ran better than it had in a while, so there certainly was merit to getting rid of Forge Essentials. But I could tell from Opis that there was still a small lagspike about every 45 to 50 seconds. Not much of a spike, but that shape could still be seen in the Opis graph at a very regular interval.

Later in the day, the spikes were becoming bigger with longer periods of blocklag. A few of the worst spikes generated stall reports. Here is one of them:

http://pastebin.com/vp52CGCK

Sorry I don't have better news.

**Comment by AiwendilCiunio** [comment]
As I said in a ticket about redstone conduits, I'm suspecting (based on the data we have and links I posted) that they may be a cause of lag/spikes. Apparently latest dev versions of EnderCore and EnderIO fix some problems.

I know you were testing a replica of our world some days ago. Would it be possible (if for some reason we can't do that - Grove is still busy it appears) if you loaded the world with latest dev versions and checked if they fix the issue?
