### ISSUE TITLE
Item names in Gravisuite recipes

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-1.7#317]
The Ultimate Lappack recipe has requires a "itemSuperConductor.name" which in turn requires 6 "itemSuperConductorCover.name"s.  

![image](https://cloud.githubusercontent.com/assets/8617528/9020352/c5eac046-37d4-11e5-9e77-e26ab2e7abeb.png)

**Comment by JasonMcRay** [comment]
I hate when mod author just doesnt care about localizing his stuff.... Although this is not forgotten localization, its more of derp in the code. Will hardcode it via Minetweaker, because I cant be bothered to fix it in the code itself :)
