### ISSUE TITLE
Applied Energistics Capacity Card recipe not registering in NEI

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-1.7#318]
Item is in NEI but no recipe.

Other AE card recipes look fine.

I wanted to debug this for you but you were too lazy to alias the items and I'm too lazy to figure them out in reverse.

recipes.addShapeless(<appliedenergistics2:item.ItemMultiMaterial:27>, 
[<appliedenergistics2:item.ItemMultiMaterial:25>, <appliedenergistics2:item.ItemMultiMaterial:35>, 
<appliedenergistics2:item.ItemMultiMaterial:35>, gemChargedCertusQuartz]);

**Comment by JasonMcRay** [comment]
@Pyure it works fine for me... it has been an issue in v3.1.4 and it should be fixed in v3.1.5 already. Please double check.

**Comment by pyure** [comment]
Confirmed, woops.

I didn't update to latest version until after I'd reported this, and didn't think to re-check it.
