### ISSUE TITLE
Infinite nether quartz loop

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-1.7#319]
1 Nether Dust
= 2 Nether Quartz Seeds
= 2 Pure Nether Quartz  (Chemical Reactor)
= 2 Nether Quartz Rods + 4 Small Dusts (Lathe) <=== Problem
= 2 Nether Quartz Rods + 1 Nether Dust (Shapeless)
GOTO Start

Recommended lathe recipe
=========================
Remove: 1 pure nether quartz => 1 nether quartz rod + 2 small nether quartz dust
Add: 1 pure nether quartz => 1 nether quartz rod + 2 tiny nether quartz dust

**Comment by pyure** [comment]
dunno why underlining with a bunch of equals created gigantic bold header text.

**Comment by JasonMcRay** [comment]
I am not sure if I can fix it, since I had problems with altering default GT recipes. Will try, otherwise it will need to be fixed by @Blood-Asp in GregTech itself.

**Comment by JasonMcRay** [comment]
Yup cant alter already existing recipes in GregTech... Gonna report to Blood directly so he has it :)
