### ISSUE TITLE
Clicking buttons in Export/Import Thaumic Energistics Buses causes crash

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-1.7#320]
Fixed in newest version: thaumicenergistics-0.8.10.9.jar  (CONFIRMED)

http://minecraft.curseforge.com/mc-mods/223666-thaumic-energistics/files/2249944

Bugfixes:
....
Clicking on a button in the export or import bus will no longer crash.
....

**Comment by JasonMcRay** [comment]
Already aware of this and fixed in dev
