### ISSUE TITLE
Vibrant Alloy

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#323]
Fluid Extractor:
Vibrant Alloy Ingot = 144mb Molten Phased Gold (needed for Octadic Capacitor)
Vibrant Alloy Nugget = 16mb Molten Vibrant Alloy (needed for Vibrant Crystal)

**Comment by JasonMcRay** [comment]
just to clarify, By this you mean that Ingot is giving Molten Phased Gold but Nugget gives Molten Vibrant alloy, yes?

**Comment by DarknessShadow** [comment]
yes

**Comment by JasonMcRay** [comment]
This I am unable to touch, reported to Blood and changed the recipe for Vibrant Crystal to request Phased Gold.

https://github.com/Blood-Asp/GT5-Unofficial/issues/116
