### ISSUE TITLE
Can't get Bronze achievement

### ISSUE THREAD

**Issue by j2ghz** [JasonMcRay/InfiTech-1.7#328]
Tried crafting bronze with IC2 copper and tin that drops from ores. Tried giving myself Gregtech bronze and copper, but it just crafted IC2 bronze and giving Gregtech bronze didn't work either.

Had to get it by using `/achievement give bronze player`.

**Comment by j2ghz** [comment]
I looked at GT source and it looks like it only detects the GT variant
https://github.com/Blood-Asp/GT5-Unofficial/blob/master/main/java/gregtech/loaders/misc/GT_Achievements.java#L299
```java
if(stack.getUnlocalizedName().startsWith("gt.metaitem.")){
			if(stack.getUnlocalizedName().equals("gt.metaitem.01.2300")){
				issueAchievement(player, "bronze");
			}else if(stack.getUnlocalizedName().equals("gt.metaitem.01.2300")){
				issueAchievement(player, "bronze");
```
Also there is the same condition twice. Shouldn't one of them be for the IC2 variant?
I did NEI dumps (of my inventory) while trying to get it and none of the bronze I had started with `gt.metaitem.`, insted it was `ic2.itemDustBronze`
```
Slot,Display Name,Amount,Damage,Max Damage,Item ID,Unlocalized Name,Item Class,NBT
0,Bronze Dust,3,0,0,IC2:itemDust,ic2.itemDustBronze,ic2.core.item.resources.ItemDust,
```

**Comment by j2ghz** [comment]
Shall I do more research, report it to Blood-Asp/GT5-Unofficial or wait for more people to encounter this bug?

**Comment by JasonMcRay** [comment]
I already talked privately about this to Blood Asp, but he might have forgot about it. Feel free to open an issue on GT5 tracker to poke him :D

**Comment by Blood-Asp** [comment]
There was just no update since i was told where the issue really comes from.
