### ISSUE TITLE
ME Cables

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#330]
<a href="http://imgur.com/24iOUZo"><img src="http://i.imgur.com/24iOUZo.png" title="source: imgur.com" /></a><a href="http://imgur.com/PQbAQ3x"><img src="http://i.imgur.com/PQbAQ3x.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/dukq3j0"><img src="http://i.imgur.com/dukq3j0.png" title="source: imgur.com" /></a><a href="http://imgur.com/ERDnlqv"><img src="http://i.imgur.com/ERDnlqv.png" title="source: imgur.com" /></a>

Thats just a mess.
3 recipes (with different costs) for 3 different cables that basically do the same.
The only difference between the me fluix cable and the covered cable is visual so why are the covered cables alot cheaper?
I think we should do me conduit and covered cable as an upgrade of the me fluix cable.
Also the me conduit is cheaper than the me fluix cable with the added function of allowing multiple conduits in 1 blocks which doesn't make sense (more function = cheaper?).

I think we should change it to this:
<a href="http://imgur.com/V8f1OCU"><img src="http://i.imgur.com/V8f1OCU.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/z9P3jT4"><img src="http://i.imgur.com/z9P3jT4.png" title="source: imgur.com" /></a><a href="http://imgur.com/pDYM3P9"><img src="http://i.imgur.com/pDYM3P9.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/F3cxlaZ"><img src="http://i.imgur.com/F3cxlaZ.png" title="source: imgur.com" /></a>

**Comment by DarknessShadow** [comment]
Btw why are you making the me fluix cables 50% cheaper?
Just to have all recipes with 3 cables as output? 
>+recipes.addShaped(FluixGlassCable * 3

**Comment by JasonMcRay** [comment]
Yep just to simplify calculations :)
