### ISSUE TITLE
UUMatter

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#331]
The IC2 Replicator has no crafting recipe and the GT Replicator does not have the IC2 uumatter recipes.

https://github.com/Blood-Asp/GT5-Unofficial/issues/138

**Comment by JasonMcRay** [comment]
It is intended to have IC2 Replicator disabled

**Comment by JasonMcRay** [comment]
IC2 UUM is actually more expensive than GT UUM. (10x EU per L UUM to be exact) So using the IC2 replicator allows to aquire some materials much cheaper than intended
