### ISSUE TITLE
Dimensional Transceiver

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#332]
The cost to run a Dimensional Transceiver is only 50 RF/t = 12,5 EU/t
Thats like nothing compared to the ME Quantum Bridge 148,5 EU/t = 594 RF/t especially because the Dimensional Transceiver is 1 block and the ME Quantum Bridge is a multiblock and multiblocks should always be better than the single block equivalent.

Thats why I think it should require a bit more energy to run than the ME Quantum Bridge.
Please change the running cost of the Dimensional Transceiver to 650 RF/t = 162,5 EU/t.

**Comment by JasonMcRay** [comment]
Oh... I thought I must have missed a zero in there, because I was going to set it 10x expensive. Thanks for pointing that out.

**Comment by AiwendilCiunio** [comment]
Actually, the cost is higher. 50 RF/t is only for powering the Transceiver, each action (transferring power, items, liquids) increases the power draw substantially. So please check it out because I'm afraid that you're about to make it so expensive that it will be useless.

**Comment by DarknessShadow** [comment]
But isn't that the same for the Quantum Bridge ?

**Comment by DarknessShadow** [comment]
# When set to true the RF cost of sending a cart within the same dimension will be capped to the cross dimension cost [default: true]
    B:enderRailCapSameDimensionPowerAtCrossDimensionCost=true

    # The amount of power required to transport a cart across dimensions
    I:enderRailPowerRequireCrossDimensions=12500

    # The amount of power required to teleport a cart per block in the same dimension
    I:enderRailPowerRequiredPerBlock=10

    # The cost in RF of transporting a bucket of fluid via a Dimensional Transceiver.
    I:transceiverBucketTransmissionCostRF=250

    # Amount of energy lost when transfered by Dimensional Transceiver; 0 is no loss, 1 is 100% loss
    D:transceiverEnergyLoss=0.30

    # Maximum RF/t sent and received by a Dimensional Transceiver per tick. Input and output limits are not cumulative
    I:transceiverMaxIoRF=20480

    # Number of RF/t required to keep a Dimensional Transceiver connection open
    I:transceiverUpkeepCostRF=50

Thats all I can find about the Dimensional Transceiver in the config and those are independant of the "UpkeepCost"

**Comment by AiwendilCiunio** [comment]
http://ae-mod.info/ME-Quantum-Network-Bridge/
No, upkeep is constant.

Also I have been using Transceivers for a while now (nether pump and quarry), and they're certainly drawing a lot more power when they're actually doing something (especially pumping lava from nether). I will test this today when I'm back home.

**Comment by DarknessShadow** [comment]
Please read what I wrote
I:transceiverBucketTransmissionCostRF=250
That wont be higher when we increase the upkeepcost.

**Comment by JasonMcRay** [comment]
When transfering items the cost is not raised. So it is still upkeep RF/t. For fluid its different, fluid transfer will drain 250 per bucket on top of the upkeep RF/t.

So for upkeep I guess we will keep it as suggested 650RF/t but will lower the Transmission cost per bucket.
