### ISSUE TITLE
QuantumSuit Bodyarmor

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#333]
I think we should replace the NanoSuit Bodyarmor in the recipe with the Advanced NanoChestPlate because thats an upgrade of the NanoSuit Bodyarmor and is expensive and not very cheap like the NanoSuit Bodyarmor.

The progression right now is:
NanoSuit Bodyarmor -> Advanced NanoChestPlate
or
NanoSuit Bodyarmor -> QuantumSuit Bodyarmor -> Gravisuite

It would be better like this:
NanoSuit Bodyarmor -> Advanced NanoChestPlate -> QuantumSuit Bodyarmor -> Gravisuite

**Comment by JasonMcRay** [comment]
Gonna leave it as it is, because if I will change the recipe it will break the function where Eu stored is tranfered to final product.
