### ISSUE TITLE
Dieing in the End

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#337]
~~If you run into a iris from a gate thats in the end your grave does NOT spawn.~~
Your grave does not spawn also the enchants that should allow you to keep your items after death (soulbound / reincarnating) don't work when you die in the end

~~But if you do the same from a gate thats not in the end everything works fine.~~

**Comment by DarknessShadow** [comment]
This has nothing do to with the Stargate (ops).

It affects dieing while in the end.

**Comment by JasonMcRay** [comment]
https://github.com/chylex/Hardcore-Ender-Expansion/issues/135

**Comment by JasonMcRay** [comment]
As per @chylex, void chest will be gone in HEE2, so it will resolve this issue. Closing as intentional behaviour and minor
