### ISSUE TITLE
Endium Block

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#338]
The Endium block can be crafted 3x3 from Endium Ingots and not inside the compressor.

**Comment by AiwendilCiunio** [comment]
I don't think this should be changed because the recipe appears in Ender Compendium. Unless after changing the recipe it would show up properly in the compendium.

**Comment by JasonMcRay** [comment]
Well its the same as with Thaumium... It also still appears in Thaumonomicon that you need Thaumium Ingots for chestplate, but when you look at it via NEI, it shows correctly.
