### ISSUE TITLE
[New Mod] Funky Locomotion

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#341]
I think it would be very nice to add Funky Locomotion to Infitech 2.
It adds the RedPower2 style frames to the game which would be AWESOME.

Author: RWTema
Download: http://www.curse.com/mc-mods/minecraft/224190-funky-locomotion
Mod Spotlight: https://www.youtube.com/watch?v=egR01_eILXw

**Comment by AiwendilCiunio** [comment]
This sounds promising. I always loved RP2 frames and their possibilities, though I never learned to use them properly :D.

This mod (after testing ofc) could be a nice addition.

**Comment by hlaaftana** [comment]
I'm pretty sure this has been considered before

**Comment by DarknessShadow** [comment]
># Configuration file

>client {
    B:redrawChunksInstantly=true
}


>general {
    B:addFrameCopyResetRecipes=true
    B:addRecipes=true
    I:energyPerBlock=250
    I:maximumBlocksPushed=1024
}

Thats the entire config file.
We can easily increase the energy cost for framequarries so they wont be overpowered..

The mod only adds 5 blocks and 2 wrenches so balancing the recipes shouldn't be that hard.

This is my first idea on how to change the recipes:

Frame: soft + normal Hammer
<a href="http://imgur.com/pggPz7L"><img src="http://i.imgur.com/pggPz7L.png" title="source: imgur.com" /></a><a href="http://imgur.com/jgQscQ6"><img src="http://i.imgur.com/jgQscQ6.png" title="source: imgur.com" /></a>
Frame Pusher:
<a href="http://imgur.com/OhkHIt2"><img src="http://i.imgur.com/OhkHIt2.png" title="source: imgur.com" /></a><a href="http://imgur.com/ULnIO04"><img src="http://i.imgur.com/ULnIO04.png" title="source: imgur.com" /></a>
Frame Puller:
<a href="http://imgur.com/Vp22yy7"><img src="http://i.imgur.com/Vp22yy7.png" title="source: imgur.com" /></a><a href="http://imgur.com/GzHghn5"><img src="http://i.imgur.com/GzHghn5.png" title="source: imgur.com" /></a>
Frame Slider:
<a href="http://imgur.com/dGOOMf5"><img src="http://i.imgur.com/dGOOMf5.png" title="source: imgur.com" /></a><a href="http://imgur.com/43A5Sl4"><img src="http://i.imgur.com/43A5Sl4.png" title="source: imgur.com" /></a>
Frame Booster: Frame Pusher, Puller or Slider in the recipe
<a href="http://imgur.com/qFYQhOv"><img src="http://i.imgur.com/qFYQhOv.png" title="source: imgur.com" /></a><a href="http://imgur.com/Bq8tZkJ"><img src="http://i.imgur.com/Bq8tZkJ.png" title="source: imgur.com" /></a>
Wrench: I think this doesn't need a change.
<a href="http://imgur.com/dOdOrAq"><img src="http://i.imgur.com/dOdOrAq.png" title="source: imgur.com" /></a>
iWrench:
<a href="http://imgur.com/QhNVWAa"><img src="http://i.imgur.com/QhNVWAa.png" title="source: imgur.com" /></a><a href="http://imgur.com/dNPcC1Q"><img src="http://i.imgur.com/dNPcC1Q.png" title="source: imgur.com" /></a>

**Comment by DarknessShadow** [comment]
Hm I posted my suggestion for the recipes more than a week ago and no reply.

Does that mean those recipes are already perfect or did everyone ignore this?

**Comment by JasonMcRay** [comment]
I am afraid after reading through the Issues Funky Locomotion will not be added... There is a bug which crashes server/client when frames move in chunkloaded dimension (https://github.com/rwtema/FunkyLocomotion/issues/75)

Will take a look into Forge Relocation how stable it is.
@DarknessShadow if you know about other mod with similiar capabilities, let me know.

**Comment by JasonMcRay** [comment]
I think I found one: Framez. From the description it looks great. Testing in progress...

Also if anyone else wants to test Framez mod, you are mostly welcome to help out.
http://minecraft.curseforge.com/projects/framez

**Comment by JasonMcRay** [comment]
Closing this issue/suggestion and opening second one for Framez (just to keep it clean)
https://github.com/JasonMcRay/InfiTech-1.7/issues/428
