### ISSUE TITLE
SAG mill cobble to sand byproduct

### ISSUE THREAD

**Issue by Ugachaga** [JasonMcRay/InfiTech-1.7#343]
![sagcobblebug](https://cloud.githubusercontent.com/assets/12869346/9569583/789bc072-4f91-11e5-8a5d-838160f4fd13.png)

**Comment by JasonMcRay** [comment]
Its only the naming or the gravel is never outputed as well?

**Comment by Ugachaga** [comment]
Something is outputted with gravel icon and strange name. It does not stack with normal gravel.

**Comment by JasonMcRay** [comment]
Reported to devs:

https://github.com/SleepyTrousers/EnderIO/issues/2776

**Comment by JasonMcRay** [comment]
Oh it seems it is known issue: https://github.com/SleepyTrousers/EnderIO/issues/2751
