### ISSUE TITLE
Chisel-2 Packed Ice Item ID Conflicts?

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#344]
Chisel-2 mod is supposed to have 15 different options for packed ice blocks (Item ID 1204:1 through Item ID 1204:15). When I place packed ice (Item ID 174) in the chisel in order to carve it, it only allows me to make the normal packed ice with different meta data (Item ID 174:1 through Item ID 174:15). It won't let me carve the packed ice into the Item ID 1204 variants.

For some reason, NEI shows two pages of Chiseled packed ice... one page with the fancy 1204 variants, and one page with the plain 174 variants.
 
I made a set of packed ice stairs (Item ID 1206), but could not carve it inside the chisel at all. So I placed the stairs on the ground and tried to carve it in-world. That did not work, so I silk-touched the stairs and it converted to Large Rough Ice Bricks (Item ID 1140:3), which is NOT the same as the packed ice bricks that I want (Item ID 1204:3).

I suspect there is a problem with modpack Item IDs, which may affect additional less-popular Chisel blocks, but I am not sure. This is posted in the Infitech2 Public Server forums as well as here. I have not contacted the Chisel-2 mod authors yet.

**Comment by JasonMcRay** [comment]
Should be fixed in next chisel update (not 2.5.0, the one after hopefully)
