### ISSUE TITLE
EnderIO not accepting higher voltage than HV

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#345]
I tried with different machines and capacitor banks. It will only draw GT EU up to HV. When I connect it to EV (haven't tried IV, but I suppose it won't work either), it just doesn't draw energy.

**Comment by JasonMcRay** [comment]
This is known and there is not much to do about it.
@Blood-Asp can provide more info about why it happens, because if I would try to explain, I would confuse myself

**Comment by Blood-Asp** [comment]
The RF block must accept a full EU package to once. So 512EU/t*3,6 = 1840RF/t.
The GT Energy system can't transfer a incomplete package so the rest would be lost. So that no energy is lost, the whole transfer is blocked. Only below 32EU/t = 115RF/t it stores incomplete packages so nothing is lost.
