### ISSUE TITLE
bug: blaze powder too many aspects in alchem furnace

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#346]
According to the tooltip i see, 1 piece of blaze powder should give
4 ignis, 2 instrumentum, 2 praecen, 1 perditio
but putting it in an alchem. furnace gives
!!24 ignis, 2 instrumentum, !!12 praecen
so a LOT more than it should. (was 1.0.6, didnt update to .7 yet so please test if you can)

**Comment by JasonMcRay** [comment]
It actually should be just 2 Ignis and 1 Praecantatio since Blaze Rod is 4 and 2.
This is most likely because of some recipe added by other mods, and its copying the aspects from there. Hardcoded in next pack update.
