### ISSUE TITLE
Infitech starts in minecraft 1.8.8 post update september 8th

### ISSUE THREAD

**Issue by septIO** [JasonMcRay/InfiTech-1.7#347]
So, since yesterday (september 8th), when i try to launch Infitech 2 through the curse voice launcher, it uses an instance of Minecraft that runs on patch 1.8,8 instead of 1.7.10.

I've tried to re-install the pack several times, and to different locations, but still gets the same result.
I've tried on a different computer, and still get this issue (Althought the computer is on the same IP, but i don't think that should matter).

I've backed up my Curse-instance of my saved world, and are currently trying different solutions, i'll get back if i fix it.

**Comment by JasonMcRay** [comment]
Which pack version are you trying to play?

**Comment by septIO** [comment]
I'm trying to launch version 3.1.7

**Comment by septIO** [comment]
I tried to launch some other packs on the curse client, and they all come down to the same bug, so it's not because of your pack, it's curse who's fucking with me. Sorry, You can close this issue
