### ISSUE TITLE
Can't Receive GT Steel Achievement

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#349]
After months of playing, I finally made a Bronze Blast Furnace (BBF) and cooked my first steel ingots. However, the game did not reward me with the GT Steel Achievement even though I have the bronze dust prerequisite.

Up until now, I have been finding steel ingots in chests and have been using them for tools, but "finding" steel does not reward a player with the achievement either because the player has to make it in a BBF for the achievement to register (AFAIK).

Help?

**Comment by DarknessShadow** [comment]
Have you tried dropping the steel on the ground and picking it up again?

**Comment by JasonMcRay** [comment]
there is not much I can do about it. Achievements are completely out of my hand. Reporting directly to @Blood-Asp is best in this case. You can also "cheat" in the achievement by using minecraft command (/achievement give steel [player]), of course OP permission is required :)

**Comment by Blood-Asp** [comment]
When the BBF does not work, pick up a full stack of ingots at once. That also fulfilly the steel achievement.
Still, the BBF not working is something that should not happen.

**Comment by Blood-Asp** [comment]
Looking at the code, the only way i can imagine the steel achievement in the BBF to fail is when it lost it's owner name. That sometimes happens when unloading / reloading the controller block. Try to replace it and produce a steel ingot without unloading the controller meanwhile.

**Comment by lafflam** [comment]
1. I have tried dropping the steel on the ground and picking it up again, both with steel I have found and steel I just pulled out of the BBF... still no achievement.

2. I have replaced the BBF controller and produced a steel ingot while remaining next to the BBF... still no achievement.

3. I am just a few seconds away from cooking up a full stack of steel in the BBF. Wait for it ... ... ... waaait for it ... ... ... Done ... and no achievement. I even dropped them on the ground. I will ask around to see if others are having trouble getting that achievement. If so, then as an OP I might just have to ghost the achievement to anyone who asks.

Please let me know if there is any additional information I can provide to solve this problem legitimately.

**Comment by Blood-Asp** [comment]
Dropping a full stack on the ground and picking it up should be a sure way to work. Sounds to me as if there is something other wrong. The bronze dust achievement did really unlock, right?

**Comment by lafflam** [comment]
OK, the backpack I was wearing prevented the stack from entering my inventory after picking it up from the ground. So that explains why picking it up from the ground failed to grant the achievement.

But I still did not get the achievement when removing the steel from my BBF and placing it carefully into my inventory. Reason unknown.

I will keep the backpack in mind next time I think there is a problem with an achievement. For now, I'm good. Thanks.

**Comment by Blood-Asp** [comment]
Placing an item in the player inventory from another inventory creates no event i can catch, so it is not possible to issue an achievement then. Only picking it up from the ground or crafting can be noticed. The machines need special code that sometimes can break... and the backpack is also something i did not know about.

**Comment by JasonMcRay** [comment]
I guess this then can be closed. If any more issues, reopen.
