### ISSUE TITLE
gt.blockores.2000.name instead of Naquadah Side-Ore (3.1.6)

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#350]
Hi! I have the complete world started in 3.1.6, never ran a different version,
got lucky and found a naquadah asteroid in the end, naquadah ore itself is present correctly,
but a sideore named "gt.blockores.2000.name" (id=975:2000) shows up.
I found no other side ores, so i'm assuming that it is supposed to be enriched naquadah (id=975:2326).
It looks exactly like endstone and only sometimes has different lighting, i mainly recognize it by the tooltip.
I didnt get to take it home to the pulverizer yet, but nei does not recognize it when pressing U on mouseover.
I suspect a bug in the ore-gen.

**Comment by JasonMcRay** [comment]
It seems like a remnant of the removal of Enriched Naquadah. Anyway since you are running quite old version I am closing this. Also I think this has been fixed in later versions of GT (5.08.28 if I am not mistaken)
