### ISSUE TITLE
Magic Bees hives extremely rare

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#351]
I always remember them being quite common, a lot more common that Forestry hives. 
Now I was flying for about 20 minutes and found 1 Unusual Hive. Is this intended? If so, it's pretty frustrating, because getting pristine princesses is really infuriating now.
Was this changed by you, by mod author or is it a bug?
Bees are already weak with all your recipe and (especially) power usage changes. I did bees on v2 just to see how it was, but this time I didn't even bother because they are so crap now they're not worth the effort.

**Comment by JasonMcRay** [comment]
I havent touched anything related to Magic Bees. Looking through Magic Bees config there is nothing related to their spawn rate, so it must have been changed by devs. I suggest you to ask directly to Magic Bees devs (https://github.com/MagicBees/MagicBees/issues).

**Comment by mezz** [comment]
Magic bees now uses Forestry's hive API and should have similar rates to Forestry. 
You can adjust the rate of hives in the Forestry Common config file. Should be something like `world.generate.beehives.amount`

**Comment by JasonMcRay** [comment]
If it will get boosted in FT, wont it affect FT hives in the way there will
be too much of them?

**Comment by mezz** [comment]
There will be more Forestry hives and Magic Bees hives. I think he just wants more hives in general (from any mod), and expected Magic Bees to have high rates like before.
