### ISSUE TITLE
X.A.C.T Crafter has inventory disappear randomly after 3.1.9 update

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#357]
After the 3.1.9 update several users, myself included, have had their items and recipes disappear from the inventory of the XACT Crafter.  

Mine personally ocurred as such:
http://forum.feed-the-beast.com/threads/1-7-10-infitech-2-modpack-v3-1-9-gregtech-balanced-hard-mode-modpack-updated-09-13-2015.50185/page-335#post-1437667

**Comment by JasonMcRay** [comment]
reported.
https://github.com/UniversalLP/XACT/issues/10

**Comment by JasonMcRay** [comment]
Might be fixed in: https://github.com/UniversalLP/XACT/releases/tag/v0.5.4

Can't do any test until weekend probably (busy)

**Comment by JasonMcRay** [comment]
Not fixed. Still happening.

http://pastebin.com/cKmj9NYS
