### ISSUE TITLE
Modpack Idea: Killing Jason should drop a tin ingot

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#358]
Subject speaks for itself :-)

**Comment by JasonMcRay** [comment]
If it will be possible, I am up for it :D

**Comment by JasonMcRay** [comment]
Currently not possible, not going to add extra mod just for this. Minetwekaer 3.1 has this listed in the planned features, so lets wait for that.

Putting on hold until then :)

**Comment by lafflam** [comment]
Well, if killing Jason someday drops tin, then you might need to configure it so Jason only has a "random chance" to drop tin (sort of like zombies have a random chance to drop iron). Otherwise, players might just set up Jason farms in order to farm tin.

BTW, there is already a LOT of chat spam like "Jason was killed by Minecraft." I assume this is cause by Jason dying in players' mob farms. Is there a way to turn off the chat spam about killing Jason?

**Comment by JasonMcRay** [comment]
Thats vanilla thing announcing death of named mob. I will take a look if it
is possible to disable it, but it will also disable anouncing all the
deaths.

**Comment by JasonMcRay** [comment]
You can try to set this to false: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/cofh/core/common.cfg#L14 let me know if that works
