### ISSUE TITLE
Add support for Hardcore Ender Expansion

### ISSUE THREAD

**Issue by adamsonich** [JasonMcRay/InfiTech-1.7#359]
Please add support for HEE
in ingame wiki wrote that 1 ore is 1-3 powders, so i make macerator reciept for 4 powder

// ---     Created by adamsonich     ---
// ---  for HardcoreEnderExpansion   ---
// --- for infitech2 by Jason McRay  ---

import mods.ic2.Macerator;

// --- Variables ---

var EndPowderOre = < HardcoreEnderExpansion:end_powder_ore >; -- End Powder Ore
var EndPowder = < HardcoreEnderExpansion:end_powder >; -- End Powder

Macerator.addRecipe(EndPowder * 4, EndPowderOre);

will check other stuff and try update list

**Comment by JasonMcRay** [comment]
It is planned addition to GT in core. I did not had time to test the test version.
https://github.com/Blood-Asp/GT5-Unofficial/issues/154

**Comment by DarknessShadow** [comment]
Gregtech adds endium ore but @adamsonich is talking about end powder

**Comment by JasonMcRay** [comment]
Oh right... Sorry. I misread
