### ISSUE TITLE
Framed Chest (Bibliocraft)

### ISSUE THREAD

**Issue by Verharn** [JasonMcRay/InfiTech-1.7#360]
A crash occurs if you put combs or propolis (I just tested with those 2 items from Forestry)  into the Framed Chest (Bibliocraft). When you look in the direction of that chest the client shuts off at once. This is the problem of the rendering. 

http://pastebin.com/VWp96QX4

**Comment by JasonMcRay** [comment]
Update Bibliocraft: http://minecraft.curseforge.com/mc-mods/228027-bibliocraft/files/2258792

Will be pushed into the next pack update (no ETA on that tho)

**Comment by lafflam** [comment]
Due to the severity of the client crash (and no way to get close enough to the chest to remove it) we have updated to version BiblioCraft[v1.11.2][MC1.7.10].jar on the InfiTech2 Public Server, and the client crash is fixed.
