### ISSUE TITLE
EnderIO bug in Infitech 2

### ISSUE THREAD

**Issue by Scarofin** [JasonMcRay/InfiTech-1.7#362]
Hello,

I had a bug occur in the official infitech 2 server. It had to do with EnderIO Plate and Glider attached to it.

I made EnderIO Plate (chestplate) and Glider attachment in the game, and my friend put them together in the anvil. 

When I used it for gliding around, everyone else in server was kicked with message "Fatal error". They could join in, but would be kicked again. I was the only one who didn't get kicked. 

I managed to find out what caused the problem. When I was in my base with friends, nothing happened while gliding around. The problem happened when I flied about 10-20 chunks away and pressed G button (toggle glide). Everyone in the server was kicked with "Fatal error" message.

Here are console logs from that time. Just look for 19:08:00 onward.
paasi is the one who had his minecraft crash at 19:08:14, and Scarofin was me who didn't notice anything at the same time.

https://github.com/Scarofin/Github_files/tree/master

**Comment by JasonMcRay** [comment]
I will need server log from the time of the occured Fatal Error (@groveham)

**Comment by groveham** [comment]
Struggling to find the logs for the referenced time, at 19.08 server time it was rebooting, how many hours ahead/behind are you from GMT+0 @Scarofin ?

**Comment by Scarofin** [comment]
Emm, we are at GMT+3:00 here in Finland. It should be 16:00 in the server time.

**Comment by groveham** [comment]
OK so had a look around the relevant logs, seems like it was 17:00 server time (server is in france GMT+1). 
http://pastebin.com/D9am7bkQ
You can see the players disconnecting and reconnecting constanty but no errors that I can tell.

**Comment by Scarofin** [comment]
I think other people were not kicked. My console only said "paasi left the game" etc, nothing relating to kick, only that players left the server. Server log didn't indicate this either. 

Maybe it has something to do with the client, so the client side mod crashes when some type of action (pressing button G, changing glider settings in this case) happens.

If that's it, it should be easy to replicate.

**Comment by JasonMcRay** [comment]
After searching around, i have found out this: https://github.com/SleepyTrousers/EnderIO/issues/2743
it looks like its exactly that issue you guzys are experiencing.

**Comment by JasonMcRay** [comment]
@groveham is that log from console or the fml-server.log?

**Comment by groveham** [comment]
Directly from the FML log

**Comment by JasonMcRay** [comment]
Should be fixed in latest pack version (3.1.15) if not, let me know :)
