### ISSUE TITLE
Gendustry EU problem

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#365]
This is somewhat similar to a bug I had in v2 of the pack, although not completely similar.

I placed 4 Industrial Apiaries, each powered by its own MFE. They were working for a few days and then one by one, over a few days, they stopped receiving power. Even though MFE was full and was outputting towards the apiary. First only 1 apiary didn't accept power, but eventually (yesterday) all of them stopped working.

What I tried:
-breaking and replacing the apiary
-breaking and replacing the MFE
-breaking the apiary, putting some other block in its place, and the placing the apiary again.

None of above worked. When I placed the faulty apiaries somewhere else they accepted power fine.

Now comes the really weird part: I tried placing another chargeable block in apiaries' place, an MFE. And to my amazement it didn't charge up, even though it was next to a full MFE.

I broke all apiaries and waited till server restart, then replaced them. They are working (for now).

I'm not sure what's going on, but the bug has to do with coords, not specific blocks.

Also, before I used MFE to power my apiaries I tried using GT cables. They would fry randomly when I tried to connect them :/

**Comment by JasonMcRay** [comment]
I see you already reported this to bdew as well. Will monitor that.
https://github.com/bdew/gendustry/issues/137

**Comment by Timeslice42** [comment]
Try using a GT battery box and GT cables that transmit twice the amperage you think you should be needing. I'll bet it has to do with using the IC2 API incorrectly.

**Comment by Timeslice42** [comment]
Can you reproduce this in current versions, @AiwendilCiunio ?
