### ISSUE TITLE
MachineStats.cfg change results in blown up Magic Energy Absorber?

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#367]
There is a config change in 3.1.12 (compared to 3.1.9) that may have caused on of our player's Magic Energy Absorbers to blow up. The config in question is in config/GregTech/MachineStats.cfg.

B:MagicEnergyAbsorber.AllowMultipleEggs_false=true

was changed to

B:MagicEnergyAbsorber.AllowMultipleEggs_false=false

Is this an intended change? And is a blown up Magic Energy Absorber the desired result?

EDIT: For now I changed the config back to TRUE and reloaded the player's region file. If the config change was intended, then I will give players fair warning before changing it back to FALSE.

**Comment by JasonMcRay** [comment]
i am looking through the changes, and it has never been set to true in the default pack. Are you sure it was set to that in 3.1.9? Wasnt the change been done only on server side by you or @groveham ?

**Comment by groveham** [comment]
I can confirm I haven't changed that setting, Malfal has a guide on our server of the settings I change.

**Comment by JasonMcRay** [comment]
I redownloaded modpack and server from the launcher at v3.1.9... that config is set to false. So it must have been changed by someone.

**Comment by lafflam** [comment]
Aiwen just posted to our forums that he had asked Grove to change the config because he was aware that they could blow up. I know Grove said he did not change it, and I know I have not changed it, but who changed it is not really important.

What seems important is this: 

According to http://wiki.industrial-craft.net/?title=IndustrialCraft-Addons:GregTech-Addon ...
----
the Dragon Egg Siphon has a Cheat-Protection in this Device, which prevents multiple Dragon Egg Siphons from being used at once (if you have multiple Dragon Eggs). If you want to use multiple Dragon Eggs (for example, when aquired some via Mystcraft), then use the Config to disable the Cheat-Protection.
----

So if the setting is left in the default FALSE on a server that contains multiple Magic Energy Absorbers and multiple Dragon Eggs, then the default config is supposed to blow them up. I can understand that behavior in a normal single-player world maybe, but is that the intended behavior in a modpack where players have the ability to make Dragon Eggs (especially on a on a mulit-player server where many players have the ability to make Dragon Eggs)? Should the official modpack setting be TRUE?

For now I will add this to the list of our server-sdie config changes that we make on the InfiTech2 public server until we get this sorted out. But other servers (and even single players) appear to be affected by this, so I think it might need to be addressed before closing as "invalid".

**Comment by lafflam** [comment]
P.S. not sure why that got bolded in my previous comment. Sorry... I was not shouting :-)

**Comment by JasonMcRay** [comment]
Good point actually.
