### ISSUE TITLE
[New Mod] Coolers

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#368]
This is a nice mod it adds coolers. The coolers are small chests only for food which you can carry around and they automatically refill your hunger bar using the food inside.
I tested it and it works prefectly with Infitech2 in ssp.

Author: gudenau
Forum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293031-coolers

**Comment by JasonMcRay** [comment]
After some thinking I am not going to add this mod. I am not fond on automatic refilling of hunger.

**Comment by DarknessShadow** [comment]
Btw the ic2 quantum helm already has "auto eating" but its annoying because there are other useful helms (goggles of revealing, lp hud glasses).

Why not add it with an expensive recipe?
quantum helm + something -> cooler ?
