### ISSUE TITLE
duplication bug in xact crafter mod

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#369]
You can craft EVERY recipe without using the ingredients.
The ingredients have to be in a ic2 safe next to the crafter but they arent used up when you craft items.
I tested it in ssp survival.

Its now known for almost 2 years -> https://github.com/Xhamolk/XACT/issues/91#issuecomment-144348305

**Comment by JasonMcRay** [comment]
XACT is no longer maintained by Xhamolk. UniversalLP has taken over:
Reported: https://github.com/UniversalLP/XACT/issues/11

**Comment by JasonMcRay** [comment]
@DarknessShadow can you just for testing purposes go to xact.cfg and set this line to false: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/xact.cfg#L29 and test it?

**Comment by DarknessShadow** [comment]
>@DarknessShadow can you just for testing purposes go to xact.cfg and set this line to false: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/xact.cfg#L29 and test it?

That didn't help.

But this might help
>
customization {
    # Make the crafter ignore blocks [default: []]
    S:ignoredBlocks <

**Comment by DarknessShadow** [comment]
yes this helps
>customization {
    # Make the crafter ignore blocks [default: []]
    S:ignoredBlocks <
        IC2:blockPersonal:-1
     >
}

**Comment by JasonMcRay** [comment]
Closed by #370
