### ISSUE TITLE
A Malis Door made with Pnematicraft Compressed Iron Blocks crashes the client

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#373]
My son used a Malis Door Factory to create a Compressed Iron Block door with Spruce wood frame (very fancy).  He accidentally dropped the door on the ground and his client immediately crashed.  Closed FTB completely when it crashed.  He logged in again and immediately crashed.  

I went towards the chunk where the door was on the ground.  As I got within render range my client closed.

Crash log here: http://pastebin.com/zZN6Hj5G

**Comment by lafflam** [comment]
Here is the portion of server log that should be applicable.

http://pastebin.com/h8MePzXN

**Comment by JasonMcRay** [comment]
Reported to devs: https://github.com/Ordinastie/MalisisDoors/issues/55

**Comment by JasonMcRay** [comment]
Is this still happening in latest pack version @lafflam @Dlur100 ?

**Comment by lafflam** [comment]
This had occurred in 3.1.12. I edited the region file to remove the offending door when I updated the server to 3.1.14. As far as I know it has not been tested again since. I will ask Bloxs to test the same door design in the current 3.1.14 version in Single Player.

**Comment by JasonMcRay** [comment]
in theory this should be already fixed. If not, please reopen.

**Comment by MJRLegends** [comment]
I know this is a very old issue, but i just tested it and i still crash when using CompressedIronBlock in a door

Crash log: https://paste.ee/p/WJQ3n

MC Version: 1.7.10
Forge: 10.13.4.1614
PneumaticCraft: 1.12.7-150
Malisis Doors: 1.7.10-1.13.2
Malisis Core: 1.7.10-0.14.3
