### ISSUE TITLE
[New Mod] Greg's Lighting

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#374]
This mod adds floodlights which can light up a large area (64blocks long with default config) and there is also a version which runs on energy (1eu/t).
I think it would be nice to have an technical method of lighting up big areas in contrast to the magical way with the arcane lamp.
I tested it and it works prefectly with Infitech2 in singplayer.

Author: greg (not the greg from gregtech but the greg from gregs sg craft)
Forum: http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/GregsLighting/

**Comment by Blood-Asp** [comment]
Adding light covers is on my to do list for GT5.09. But it will take another 1-2 months until i'm there.

**Comment by JasonMcRay** [comment]
Honestly EnderIO Powered light covers also quite a big area, and it requires some energy to run.
