### ISSUE TITLE
PneumaticCraft Lubricant does not appear obtainable

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#375]
A bucket of PneumaticCraft Lubricant (itemID 6010) is required to craft PneumaticCraft Speed Upgrades (6012:5), but the PnC lubricant does not appear to be obtainable, so the Speed Upgrade is not craftable.

Additionally, it has been reported to me that the PnC Thermopneumatic Processing Plant produces GT lubricant instead of PnC lubricant. I don't think MineMarten ever intended for his lubricant to be compatible with any other lubricant from any other mod. AFAIK, the sole purpose of PnC Lubricant is to make Speed Upgrades for PnC.

I suggest PnC lubricant to be reinstated to the game as the author intended. I would further argue that it remain incompatible with any other lubricant in the game.

Just think of it like IRL... some oils are compatible for use in pneumatic systems, and some oils are not.

EDIT: It appears that SOME PnC fluid buckets are craftable in a Fluid Canner, but some are not. If you prefer to unify Lubricant in the game, another idea would be to add a Fluid Canner recipe to put GT lubricant in a bucket and output the necessary PnC Lubricant bucket. The same could be done for a bucket of oil and gasoline.

**Comment by JasonMcRay** [comment]
I guess I will go with the simplest solution in here. Will just add Bucket filling recipe for PC Lubricant and maybe others, as long as it will not conflict (which it should not).

PC lubricant and GT Lubricant are in the end totally the same (when it comes to crafting).
