### ISSUE TITLE
Unable to make Biomass using Fir Saplings and Honey in Fermenter

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#376]
NEI says that FIR saplings can turned into biomass using "fluid.honey" in a fermenter. However, when I put honey into the fermenter, it is called "Honey" and it will not make any biomass from fir saplings.

I tested the same setup for different saplings, such as oak, and it works as expected. However, those saplings required "Honey" in the recipe, not "fluid.honey"

I assume this is simply a config change to fix the recipe so that fir saplings use "Honey" instead of "fluid.honey" ?

EDIT: I have examined NEI and found all of the saplings from ExtrabiomesXL suffer from the problem described above. Looking into a fix...

EDIT #2: Not sure if this will help, but I found this in my local single-player logs:

./minecraft/logs/fml-client-latest.log:54251:[16:06:06] [Netty Client IO #1/DEBUG] [FML/]: Fixed item id mismatch Forestry:fluid.honey: 585 (init) -> 536 (map).
 
In single-player, Honey is SUPPOSED to be itemID 585 (according to NEI). itemID 536 turns out to be Reinforced Construction Foam in single-player.

However, I checked the itemID on the server, and Honey is 536.
Reinforced construction foam is 487 on the server.
Galacticraft crude oil is 585 on the server.

I am... confused.

**Comment by JasonMcRay** [comment]
Reported: https://github.com/ForestryMC/ForestryMC/issues/883
