### ISSUE TITLE
Galacticraft oil not processable in Pneumaticcraft refinery

### ISSUE THREAD

**Issue by DenTommes** [JasonMcRay/InfiTech-1.7#379]
Oil collected underground called "oilgc" is not accepted by Pneumaticcraft refineries. Processing it in a Gregtech distiller works.

**Comment by JasonMcRay** [comment]
Reported to devs:
https://github.com/MineMaarten/PneumaticCraft/issues/734

**Comment by JasonMcRay** [comment]
@DenTommes just in case. Is it happening with Latest (3.1.14) modpack version, right?

**Comment by JasonMcRay** [comment]
Ok issue has been found and solution will come with next pack update.

Note: Already existing Galacticvraft OilFields will be removed. Since anyway there are/will be already 3 diferent types (PneumaticCraft, GregTech, BuildCraft).

**Comment by DenTommes** [comment]
I'm sorry, I only now noticed you made another comment on the issue.

but yes, it was 3.1.14.

what happens to drums filled with this type of oil when it gets disabled?

**Comment by JasonMcRay** [comment]
Either will become just empty, or gone from game (most likely to happen)
