### ISSUE TITLE
Charcoal production tiering

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#381]
Charcoal Pit -> Coke Ovens -> Pyrolyse Oven

Remove Arc Furnace Charcoal recipe
Slight change with Coke Ovens

**Comment by DarknessShadow** [comment]
Coke Ovens are tier2 ? Does that also include a recipe change?

**Comment by JasonMcRay** [comment]
Yup it will

**Comment by JasonMcRay** [comment]
Slight change: Arc Furnace will stay as an option for fast production in between Coke Ovens and Pyrolyse Oven. Will get boosted slightly in speed and will consume slightly less Oxygen. Power usage will remain the same or be raised by a bit.

@Blood-asp: Does PA supports Arc Furnaces?

**Comment by Blood-Asp** [comment]
Yes, arc furnace is supported.

**Comment by JasonMcRay** [comment]
Implemented in 04d33539744b8ed0687f3275834cdbd86f3fa8d9
