### ISSUE TITLE
GT Guide Books

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#384]
GT Multiblock guidebooks with pictures on how to build,since some of them are realy complex and ingame help is not great.

Crafting of those books will be tied to the actuall block Controller, wheres the controller will be returned
Something like: Book+Ink+Oil Drilling Rig controller => Drilling Manual + Oil Drilling Rig returned

Required to check for possible ownership issues, and possible disassembling issues.
If there will be an issue, possible request for GTTweaker and Printing Machine script: (Paper+Ink+Block)

To-do-list:
- [x] Charcoal Pit
- [x] Bronze Blast Furnace
- [x] Electric Blast Furnace
- [x] Implosion Compressor
- [x] Vacuum Freezer
- [x] Distillation Tower
- [x] Processing Array
- [x] Oil Drilling Rig
- [x] Advanced Miner II
- [x] Large Heat Exchanger
- [x] Pyrolyse Oven
- [x] Oil Cracking Unit
- [x] Multi Smelter
- [x] Fusion Reactor
- [x] Steam Turbine
- [x] Plasma Turbine
- [x] Gas Turbine
- [x] Large Boilers

(Did I missed any other GT Multiblock machine? )

**Comment by JasonMcRay** [comment]
Completed: 
- [ ] Charcoal Pit
- [ ] Bronze Blast Furnace
- [ ] Electric Blast Furnace
- [ ] Implosion Compressor
- [ ] Vacuum Freezer
- [ ] Distillation Tower
- [ ] Processing Array
- [ ] Oil Drilling Rig
- [ ] Advanced Miner II
- [ ] Large Heat Exchanger
- [ ] Pyrolyse Oven
- [ ] Oil Cracking Unit
- [ ] Multi Smelter

(Did I missed any other GT Multiblock machine? )

**Comment by DarknessShadow** [comment]
obviously you forgot about fusion

**Comment by DarknessShadow** [comment]
and the steam / plasma turbines

**Comment by JasonMcRay** [comment]
thanks, added

**Comment by JasonMcRay** [comment]
Also forgotten:
- [ ] Large Boilers

**Comment by Timeslice42** [comment]
Speaking of the large boiler, does it ever have material output (such as ash)?

**Comment by JasonMcRay** [comment]
@Timeslice42 No
