### ISSUE TITLE
FTB Infitech Crash

### ISSUE THREAD

**Issue by DenTommes** [JasonMcRay/InfiTech-1.7#386]
I encountered this crash when leaving the Client running for a few hours.

This is the log shown in the FTB console, I hope it's the needed one?

http://paste.feed-the-beast.com/view/121438c4

If you need anything else, just let me know!

Edit: I shouldn't be opening new Issues at 4 am... there's always something that slips my mind when I'm tired

**Comment by groveham** [comment]
Just so it's clear, is this FTB Infinity or the FTB Infitech 3rd party pack? 

This is the Github for FTB Infitech2 not Infinity.

**Comment by DenTommes** [comment]
It's Infitech

**Comment by JasonMcRay** [comment]
Reported to devs:
https://github.com/BuildCraft/BuildCraft/issues/3084

**Comment by JasonMcRay** [comment]
Fixed in v3.1.16
