### ISSUE TITLE
Can't centrifuge combs in 3.1.15

### ISSUE THREAD

**Issue by Yabdat** [JasonMcRay/InfiTech-1.7#390]
Updated to 3.1.15, and noticed that combs doesnt centrifuge in the GT centrifuge anymore. According to NEI it only works with the Forestry centrifuge, and since that is disabled...

**Comment by JasonMcRay** [comment]
It is known issue. 
Most of the Forestry processing recipes arent working in 3.1.15 (This includes, Carpenter, Squeezer, Centrifuge related processing recipes)
@Blood-Asp is aware of it and will release hotfix soon. When he does, I will make a pack hotfix ASAP.
