### ISSUE TITLE
[Mod Suggestion] TubeStuff (only for Online Player Detector)

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#391]
Because various things in this modpack will keep working even if player is offline and (theoretically) his chunks shouldn't be loaded, there are problems that can affect server's performance or wreck havoc in player's base.

Only mod that offers a device which will output a signal when its owner is online is TubeStuff - Online Player Detector. I don't care about rest of the mod, you can disable it, but I think this detector is something that could help quite a bit on server (I for one can think of several places in my base where I would really like using it).

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1281065-immibiss-mods-now-with-85-7-less-version-numbers

**Comment by Dlur100** [comment]
I've been wanting the online player detector for a while now :)

**Comment by DarknessShadow** [comment]
Yes that online player detector would be cool but its kinda strange that no other mod has it.

**Comment by DarknessShadow** [comment]
Actually now that we have Tubestuff in this modpack I think we could also enable the Block Breaker and the Deployer.

The Block Breaker uses the durability of tools to break the block infront of it (no problem with gregtech tools).

The Deployer makes a rightclick with the item inside which would be useful for automatically placing pneumaticraft drones (doesn't work with dispenser).

**Comment by JasonMcRay** [comment]
I am not fond of any block breakers
Deployer - there is buildcraft pipe that does this.

**Comment by DarknessShadow** [comment]
I didn't know about the "Stripes Transport Pipe" from buildcraft but now I've tested it and it cannot place pneumaticraft drones.
