### ISSUE TITLE
Suggestion: Nerf Amadron Tablet 

### ISSUE THREAD

**Issue by DenTommes** [JasonMcRay/InfiTech-1.7#392]
Pneumaticcraft's Amadron Tablet allows it to trade resources like LPG for Emeralds.

Considering the low production price of LPG it seems to be a little overpowered.

I'd suggest to change the currency from Emeralds to GT credits.

**Comment by lafflam** [comment]
Just putting this out there for some perspective...

Pam's Harvestcraft vegetables basically have a zero production price (except for time), and it is easy to trade Pam's vegetables for emeralds with villagers... like, forever.

So, is easy access to emeralds really overpowered? Or should villager trading be nerfed too?

**Comment by DenTommes** [comment]
There's still a big difference between the Amadron tablet and villager trading. while it's possible to trade for virtually unlimited Emeralds with Villagers, it will take a lot of time and manual work.

One will often need close to a stack of material to get an emerald and they will "timeout" after a couple of trades, only giving a few Emeralds per trade, so one will have to initiate a trade with them very often, which increases manual work needed to get Emeralds.

This limitation isn't present with the Amadron Tablet

with the Amadron Tablet it's possible to trade for emeralds in bulk. One can buy hundreds at a time, without having to wait to make the trade available again.

I'm not suggesting to completely getting rid of the possibility to buy Emeralds via Amadron Tablet.
but to simply increase the prices to get an Emerald. It would make it harder to farm them, getting the Tablet closer to the difficulty set by Gregtech.

So why do I suggest changing the currency to GT credits?
Well, GT credits aren't used anywhere in the modpack (at least to my knowledge) and adding them to a trading system like the Amadron Tablet, while not necessary, just seems to be the right thing to do.

**Comment by JasonMcRay** [comment]
There is not much i can do about the Tablet. Using GT Credits is a nono, because they will have a use in 3.2. I am currently thinking about removing all the trades from the tablet and let it only serve as player trade option.

As about the items that are only obtainable via the tablet (PCB Blueprint and Assembly Programs), they will be obtained diferently.

**Comment by JasonMcRay** [comment]
or actually there are rare coins that I could use (Ancient Gold Coins). They cant be crafted and can be only found in "Ancient Ruins".

**Comment by JasonMcRay** [comment]
But that can cause issue on the other hand... how are ppl actually going to buy the PCB Blueprint for example without any coins? Trades are randomized so it might end up with not being to get certain Amadron only items.

**Comment by DenTommes** [comment]
The Tablet has two configs, one for randomized trades and one for trades which are always available

**Comment by JasonMcRay** [comment]
Actually i think it might work...
