### ISSUE TITLE
Server Crash on Playerjoin

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#394]
Basically what the subject says. There crash report is below, seems to be something from GT afaik crossed with LP?

http://pastebin.com/DRj13kPJ
Running 3.1.14

Let me know if you need any more info

**Comment by JasonMcRay** [comment]
Update :)

**Comment by JasonMcRay** [comment]
Or remove the affected type filter block at the place where the crash is
originating

**Comment by groveham** [comment]
There's a new update out 0_0

OK will take a look :)

**Comment by lafflam** [comment]
I do not think this is related to the crash from above... but now the server is crashing at Furian's new base. Here is the crash file: http://pastebin.com/QHRgwcjn

That file was generated AFTER I had already deleted the ticking entity at 14354,82,15554 using NBTEdit.

**Comment by JasonMcRay** [comment]
Its not related, but TT has been updated in 3.1.16, so I would try to update to see if it will still crash. If it will... report will be needed to make to TT devs (aka either open the issue in there: https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues and post here the link for the issue, or let me know it still crashes and I will report it there).

**Comment by JasonMcRay** [comment]
As for the old RF API from Railcraft... I noticed that RC has been updated, so It might solve that line. But so far I havent noticed any problems related to old API. So for now I would ignore that message

**Comment by lafflam** [comment]
For the short time that 3.1.16 ran on the official public server, the TT crash still crashed. I was finally able to removing the errored tile entity using forge.cfg.

I'll forward the server crash log to the TT devs.

**Comment by JasonMcRay** [comment]
Ok. Thanks. When you do that, please post here link to the raised issue, so I can keep an eye on it. Thanks

**Comment by JasonMcRay** [comment]
@lafflam Have you done the report to TT devs? If so please post here a link to raised issue on their tracker, so I can keep an exe on it, when its fixed.

**Comment by lafflam** [comment]
Reported the Tablet of Necromancy server crash to TT devs here:
https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/795
