### ISSUE TITLE
3.1.16: Alvearies empty after update

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#395]
After we upgraded to 3.1.16 on the official server all of our Forestry alvearies were empty of bees and product.  Tried breaking the multiblock structure and rebuilding it, but the bees did not return.

Apiaries were fine, and industrial apiary also fine.

We are restoring back to 3.1.14

**Comment by lafflam** [comment]
Bee houses were also fine. Just the Forestry alvearies were empty afaik.

**Comment by JasonMcRay** [comment]
Reported: https://github.com/ForestryMC/ForestryMC/issues/907

It was already an reported issue but supposedly fixed, unfortunately it is either back, or wasnt fixed... (https://github.com/ForestryMC/ForestryMC/issues/378)

**Comment by JasonMcRay** [comment]
>  Mezz
Thanks for the report!
This is an expected part of upgrading to Forestry 4, and only happens during the upgrade.
You can see the change log and important information for upgrading to Forestry 4 here: https://www.reddit.com/r/feedthebeast/comments/3mmlwd/forestry_40_beta/

So unfortunately nothing to do about that. Take out the bees from alvearies, and then update.
