### ISSUE TITLE
Digger's Forestry Backpacks not picking up items

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#397]
Digger's Forestry Backpacks not picking up items. It looks to me like the backpack.cfg file is messed up for the digger's backpack section. Testing in progress.

**Comment by JasonMcRay** [comment]
I see where the problem is... Just move entries in the backpacks.cfg from itemStacks into item.stacks and oreDict to ore.dict

i seem to forgot this one, when i was fixing that

**Comment by lafflam** [comment]
That is exactly what I am testing. If I change this on the server, I assume players will have to do the same in their client?

**Comment by JasonMcRay** [comment]
Not sure. But they should be fine, because this has nothing to do with client settings. So no matter what they have in their configs, the clients will grab the server settings.
