### ISSUE TITLE
EnderIO Item Conduits Randomly Disconnecting from Alvearies

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#399]
We upgraded to 3.1.16 on the official server today.  I have always used EnderIO item conduits to automate my bee production and it's always worked great.  Today I've had about half of my alvearies disconnect themselves from the enderio conduit, which halts production of product and doesn't automatically reinsert the queen anymore, like this:
![image](https://cloud.githubusercontent.com/assets/14374121/10720922/3f22a7c0-7b6a-11e5-943f-9fb94172f33c.png)

Here it is broken: 
![image](https://cloud.githubusercontent.com/assets/14374121/10720870/863119cc-7b69-11e5-996e-d34719f2b38a.png)
![image](https://cloud.githubusercontent.com/assets/14374121/10720876/993cfd1a-7b69-11e5-9cf3-7180ebdd5a2b.png)

In order to fix it I can either break that stub of pipe and redo it completely, or I found out if I place a piece of conduit adjacent to it the connection will recreate itself including any settings.  

Example:
![image](https://cloud.githubusercontent.com/assets/14374121/10720899/e8765a52-7b69-11e5-9906-3a3e71c0d6cf.png)

If I break that extra piece of conduit the connection to the alveary will stay for an undetermined bit of time.

One thing I've noticed is that the only alvearies I have this happening on is when there's a single piece of enderIO conduit connected to the alveary.  I have other alvearies set up with more conduit and connected differently to my centrifuging system that do not seem to disconnect:

![image](https://cloud.githubusercontent.com/assets/14374121/10720930/5b3b9d04-7b6a-11e5-9180-778a2582d4df.png)

Also, I have four more alvearies that are set up the same way as the ones that randomly disconnect (all alvearies disconnect at the same time btw, not like 1 at a time.  When I check on them they are all broken).

I have a LOT of alvearies, and this never happened prior to implementing forestry 4.0.

**Comment by Dlur100** [comment]
I did some more testing and it seems like if I set up my conduits like shown in the 2 pictures below it won't break (yet):
![image](https://cloud.githubusercontent.com/assets/14374121/10722307/b9993192-7b7c-11e5-8de1-6b912bb6596d.png)

![image](https://cloud.githubusercontent.com/assets/14374121/10722308/bd7b3666-7b7c-11e5-9aa1-dc71b6850046.png)

**Comment by JasonMcRay** [comment]
If you rebuild/refresh the multiblick (by breaking one block and placing it back to recreate the alveary) is it still happening?

**Comment by Dlur100** [comment]
Yeah, I've broken and recreated all of these several times.

The thing with putting 2 conduits didn't fix it either:
![image](https://cloud.githubusercontent.com/assets/14374121/10728777/d811c3c4-7bb2-11e5-97e0-539173b3d9d8.png)

The really odd thing is that it seems like all I need to do to re-establish the connection is to place or remove a block near the affected conduit.  It's like a BUD detector somehow:

![image](https://cloud.githubusercontent.com/assets/14374121/10728793/fa0e1cde-7bb2-11e5-8736-01ebe464b2a7.png)

![image](https://cloud.githubusercontent.com/assets/14374121/10728798/ff4402b8-7bb2-11e5-8997-eda94b761174.png)

**Comment by JasonMcRay** [comment]
Reported: https://github.com/SleepyTrousers/EnderIO/issues/2931

**Comment by JasonMcRay** [comment]
Can you just for testing purposes try to put for example BC pipe? It might be actually something with Forestry itself (if BC pipe will also disconnects)

**Comment by HenryLoenwind** [comment]
It even is extremely likely a problem on Forestry's side. 

If I had to guess, I'd say the multiblock has to re-form after the chunk is loaded, but for a moment it is just a bunch of blocks---that don't have an inventory to connect to. So far it's fine, but then the multiblock forms and doesn't tell the blocks around it that it now does accept connections.

**Comment by JasonMcRay** [comment]
I just noticed exact issue posted on forestry tracker: https://github.com/ForestryMC/ForestryMC/issues/923

**Comment by Dlur100** [comment]
Jason, I haven't tried BC Apiarist pipes yet, but Malfal uses those on the official server and when I asked him last night he hadn't experienced the issue of his pipes disconnecting.  I didn't go look how his are set up though.

Other information:  None of the effected alvearies are built over chunk borders.  I have this occurring across multiple chunks.  All of the chunks my alvearies are in are force loaded with Admin Anchors.  I would also agree that this seems to happen at server start, and probably not just randomly throughout the boot.

I will try apiarist pipe tonight when I get home to see if it happens with that in my case.  If I wasn't so short on aluminum I'd just switch everything to industrial apiaries at this point :)

**Comment by JasonMcRay** [comment]
Ok it has been fixed in Latest Unstable Forestry build. Will be pushed to the modpack when it hits stable release.

**Comment by JasonMcRay** [comment]
Fixed in 4f547d0643f83ac1bdd2e8d61cf9a9bb8398aa5e

**Comment by JasonMcRay** [comment]
Fixed in https://github.com/JasonMcRay/InfiTech-1.7/commit/c61dad84d429e52d44a01f80c90970a950901961

**Comment by Dlur100** [comment]
This is still happening in 3.1.20 btw

**Comment by JasonMcRay** [comment]
Yep I know. Its because we needed to roll back forestry to the version where its broken because of GT not playing nicely with FT where it was fixed

**Comment by JasonMcRay** [comment]
fixed in 38ea05d7a1ba663faec8ece1a4c3bd12db9c4d34
