### ISSUE TITLE
[NEW MOD] Wawla

### ISSUE THREAD

**Issue by GamesGamble** [JasonMcRay/InfiTech-1.7#401]
Wawla is expanding the functions of Waila, it requires NEI and Waila. It shows the Tier of the Tools that is needed for harvesting, Light Levels, Block Break Progress, Armor of Players and Mobs, Armor Points etc. It actually adding addtionally features to: Vanilla, Pixelmon, Thaumcraft, Tinkers Construct.
All can be configured Client and Server wide like NEI and Waila.

Website: http://www.darkhax.net/wawla.html

**Comment by DarknessShadow** [comment]
This would be nice if the harvesting tooltip works better **with gregtechs metatileentities** than WailaHarvestability.
Light Levels is nice so you dont have to count constantly if you try to make redwheat.

The other features are all those "nice to have" so I think it would be a good addition.

**Comment by GamesGamble** [comment]
Some Features working only when the server mod is installed, too. You can disable features serverwide. Iam using it actually, not discovered any Problems.
