### ISSUE TITLE
NEIServer.cfg

### ISSUE THREAD

**Issue by GamesGamble** [JasonMcRay/InfiTech-1.7#402]
Normally NEI generates the NEIServer.cfg when is installed on the server. But with this Modpack it doesn´t and there is also some INPureProjects things that changes something in NEI. Where can i setup that cheatmode with OP is disabled (Thats normally possible with the NEIServer.cfg) serverwide and not clientwide?

**Comment by JasonMcRay** [comment]
the server config for the NEI is located under world/NEI/server.cfg it has been moved there to allow per world changes for multiworld servers and stuff

**Comment by GamesGamble** [comment]
Thanks for the info :D
