### ISSUE TITLE
Jabba B-space

### ISSUE THREAD

**Issue by Ligi89** [JasonMcRay/InfiTech-1.7#403]
Jabba barrels B-space upgrade

Couldn't find any indication why it's disabled.
If disabled because it's sort of overpowered (single item type interdimensional transport) then I suggest making the recipe of this upgrade use thaumcraft magic mirrors.

If you can make magic mirrors, then you already have interdimensional item transport, this B-space upgrade just allows for a little bit more flexibility at that point.

**Comment by DarknessShadow** [comment]
I'm against free easily automatable item teleport.

I didn't know that the magic mirrors were free interdimensional item teleportation which can be made in bronze age.

Maybe we should disable them (or made a EV recipe for them but sadly I know you don't want to change any thaumcraft recipes even when they are op).

**Comment by JasonMcRay** [comment]
bSpace upgrade is not exactly teleportation method. It acts as unpowered "shared" inventory

**Comment by DarknessShadow** [comment]
Bspace is an enderchest with 1 slot.
That is enough to use it as item teleportation (logisticspipe inventory system connector).

**Comment by Ligi89** [comment]
Ok, if I may add to this:

While mirrors indeed do not require power, without an energized node with ordo in it, they can't do constant large scale teleportation. Without it they slow down gradually while items are transfered and recover speed gradually when there's no transfer. This makes them unsuitable for, say, transfering the goods from a quarry unless you have a good ordo node.

I also don't think thaumcraft recipes should be modified to such an extent.

So, I still support my original idea, but how about this:
You can't use the B-space upgraded barrels without the B-space tuning fork anyways, so, let's change the recipe of the fork too. For example make it require enderium plates and make it an assembler recipe. That way, you can't use it till you have at least a HV blast furnace and a vacuum freezer already.

**Comment by DarknessShadow** [comment]
Lets compare the other teleportation methods:

ME Quantum Bridge:
Requires MV to build and 148,5 EU/t = 594 RF/t to run

Dimensional Transceiver:
Requires HV to build and 162,5 EU/t.= 650 RF/t to run

Stargate:
Requires EV to build and 500k EU up to 4million eu for maximum 5min connection
(also it needs lots of rare naquadah)

Magic Mirror:
Requires Flint Age to build and nothing to run only a enegized node to speed up teleportation

BSpace Uprade:
Requires MV to build and nothing run
(vanilla recipe would already require enderium)

IC2 Teleporter:
Requires MV to build and does not work across dimensions but I don't know about energy cost

GT Teleporter:
Requires HV to build and does not work across dimensions but I don't know about energy cost

Telepad:
Requires HV to build and up to 1000 RF/t to run (without upgrades)

The BSpace Upgrade and the Magic Mirror are way too cheap compared to the rest.
Especially because the BSpace Upgrade does not require any energy to run and the magic mirror only need an enegized node which only has to be placed once and you can forget about it.

**Comment by Ligi89** [comment]
While that comparison does hold some merit, it's flawed. Here's why:
Some of those teleporters can teleport entities/players as well as items, some of them can even teleport liquids, and the amount doesn't matter. Compared to these, the B-space is a sluggish, item only, and single type only shared inventory.
You're comparing sportscars to a bicycle.

If we followed this kinda thinking that 'free to run = bad', then we need to disable thaumcraft itself, as nothing in that mod requires any EU to run. Golems are energy and maintenance free farmers.
Infernal furnace runs free as well. 

Should we disable those as well? Maybe Thaumcraft as a whole, too, as it adds non-gregtechy tools and armor?

Mirror/B-space cheaper than thee others? Yes, it is. Can it do the same as those? No it can't.
It's weaker in item teleportation and unable to teleport entities/liqiuds.

In the end, the question is, should we have a minor convenience in B-space (somehow tweaked ofc.), or should we disable every other convenient and OP stuff as well?

**Comment by groveham** [comment]
Ok from seeing everyone's views on this I thought I'd wade in and say my views. 

Ok so technically it is 'free item teleportation' BUT can we not add it into a tiered system? 
Dark just gave some good examples there, possibly create the recipe so they need LV or MV then if they are as sluggish as suggested it'd be better to then upgrade when possible to another teleportation method where you would out grow this system. 
I think this would suite both arguments while allowing it to still be used where you only need simple teleportation of items and nothing complex...

**Comment by DarknessShadow** [comment]
Yes on its own it cannot teleport items / liquids but logisticspipe is transporting liquids over the pipes in itemform so with the help of the inventory system connector you can transport liquids over magic mirrors / barrels.

With the AE2 Spatial IO stuff you can temporarily "convert" entities / players into items and also teleport them over magic mirrors / barrels

I do think that golem farms are op and should be changed (but thats a bit off topic here) -> https://github.com/JasonMcRay/InfiTech-1.7/issues/208 and the infermal furnace is really only a furnace which are really cheap anyway (=not a big problem).

I think the two free teleportation methods should get at least IV recipes if we allow them.

**Comment by Ligi89** [comment]
Question is, when you have a Spatial IO setup ready, would you really bother to use single-type item teleport the way you described anymore? By the time you can make that, using more advanced forms of teleportation is probably what you're gonna do, because they are simpler to effectively use.

**Comment by DarknessShadow** [comment]
>Question is, when you have a Spatial IO setup ready, would you really bother to use single-type item teleport the way you described anymore? By the time you can make that, using more advanced forms of teleportation is probably what you're gonna do, because they are simpler to effectively use.

Definitely a NO here because you can get stuck inside the cells so you have to make it as safe as possible and bspace barrels wont suddenly disconnect when you run out of power.

>I think this would suite both arguments while allowing it to still be used where you only need simple teleportation of items and nothing complex...

Considering that you can have massive autocrafting with lp on the moon and all your items in the overworld in a me system and are then able to request anything from that from mars with the help of a few barrels / magic mirror I have to say you can do compelx things with it.

**Comment by Dlur100** [comment]
Is there a way to configure b-space barrels to have a finite range?  For example, transvector interfaces can only be 5-6 blocks away from their target to function.  I have zero experience with b-space barrels, but perhaps if they had a finite operating range of 16 blocks (a chunk basically) they would be useful without being unbalanced.

I'm a heavy magic mirror user.  I've even used one to receive the fruits of my ender quarry (after heavy filtering/voiding at the quarry site so I'm not transferring stone/gravel/chisel blocks/etc).  This particular use was a bit of a stretch in the realm of balance to me, but it's available so I use it.  My quarry finished a few days ago and I finally located a suitable spot (I think Malfal's base is safe :P ) and set up a new and improved quarry site.  This time I'm just going to dump all the ore into ME drives and filter anything that I don't specifically want (anything that isn't ore).  A 64k ME storage drive and a telepad sneakernet has much higher bandwidth than a magic mirror or anything else really :)  

I'd be fine with magic mirrors having a range limit also (like 1k blocks) and not working across dimensions if it was possible to do so also.  It would sort of make the hand mirror and hungry hand mirror worthless, but it wouldn't ruin my game play experience.

**Comment by DarknessShadow** [comment]
Finite range would be good but I'm not seeing it in the configs :(

**Comment by Ligi89** [comment]
Well, I can't test it on this pack myself, but I remember the tuning fork having some durability bar thingy when you start a pairing process, and it depletes in a steady pace. I never used it in long ranges, I always just used it inside the base, so that bar never ran out for me.

If it works as I think it does, then that means that unless you get the help of another player and use a teleport command, or use another kind of teleportation method to go to a faraway spot, then it's range in theory is actually limited. What I don't know, however, is how the fork reacts to being shoved into a backpack/enderchest/etc.

**Comment by DarknessShadow** [comment]
I think you forgot about the Dolly.

**Comment by Ligi89** [comment]
Huh, now that you mention it, I never tried to dolly a linked barrel. You're saying it retains the link when moved? That circumvents the limitation of the fork if so.

**Comment by Dlur100** [comment]
Can't the dolly have blocks be blacklisted from being moved though?

**Comment by DarknessShadow** [comment]
>Huh, now that you mention it, I never tried to dolly a linked barrel. You're saying it retains the link when moved? That circumvents the limitation of the fork if so.

Yes

>Can't the dolly have blocks be blacklisted from being moved though?

No

**Comment by JasonMcRay** [comment]
B-Space barrel upgrade will stay disabled. Magic mirrors are going to be nerfed to require something along the late EV early IV age.

**Comment by Ligi89** [comment]
Okay, cool...

And what changes do you plan to make to golems, infernal furnace, etc... so basically all the useful things thaumcraft provides?
If you start to modify thaumcraft recipes, why not balance them all?
As it is right now, mirrors are in line on the scale of OP-ness with golem farms.

If you nerf mirrors, golems should be next, as those are waaay more powerful than mirrors.

Just my 2 cents

**Comment by JasonMcRay** [comment]
I have only |--| this time :) Few others are comming... It might not be out next update, but few stuff will happen with certain TC recipes

**Comment by JasonMcRay** [comment]
Well... I cant do jack shit with Infernal Furnace, since I have no ability to change multiblock creations...
