### ISSUE TITLE
[New Mod] Steve's Factory Manager

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#407]
This is an awesome mod which allows us to move items / liquids around with all types of condition.

This mod is not in this pack because its considered OP due to the fact that it doesn't require any energy to run.
I think we can still put it in this modpack.
To "fix" the no energy requirement we could simply change the recipe of the "Machine Inventory Manager" (nothing in this mod works without this block) to include a fully charged battery so we have an initial investment of for example 100 million EU instead of a constant power drain.

I think we have those options:
fully charged Lapotron Crystal (10 million EU) HV Autoclave is required
fully charged Charging Lapotron Crystal (40 million EU) HV Autoclave is required
fully charged Lapotronic Energy Orb (100 million EU) EV Assembler is required
fully charged Lapotronic Energy Orb Cluster (1 billion EU) IV Assembler + Fusion is required

I could do all the necessary recipe changes to greggify this mod if you want it. https://github.com/JasonMcRay/InfiTech-1.7/compare/master...DarknessShadow:patch-2

Download: http://minecraft.curseforge.com/projects/steves-factory-manager.

**Comment by Ligi89** [comment]
We already have Logistics Pipes and Applied Energistics 2, why would we need another powerful logistics mod that doesn't use power?

I think this is redundant...

**Comment by JasonMcRay** [comment]
@Ligi89 is right. We have LP and AE2 for logistics. Adding one more is pointless. You can set diferent conditions with other mods (BC gates for example), maybe not all SFM is capable of...

**Comment by DarknessShadow** [comment]
You are comparing it to AE2 and LP but that is just wrong.
AE2 and LP are about autocrafting and centralized access to **all** of your items.

Steve's Factory Manager (SFM) is about moving items / liquids from and sending redstone signals A to B with all types of conditions.
You should compare it more to something like enderio conduits which is also why we should add it in this pack. Right now its inevitable **literally everyone** is using the enderio conduits because there is no alternative that is as powerful. I think we should add SFM to get more options into the game and not *force* everyone to use the same boring old stuff because there is nothing else that is as good.
