### ISSUE TITLE
[New Mod] Alternate Terrain Generation

### ISSUE THREAD

**Issue by GamesGamble** [JasonMcRay/InfiTech-1.7#411]
Forum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291067-atg-alternate-terrain-generation
Download: http://www.curse.com/mc-mods/minecraft/228356-alternate-terrain-generation#t1:other-downloads

I used it before and the Environment looks so awesome. Even FTB uses this Mod at some Modpacks. The best way is to generate a world and look around then you see what i mean :D Btw. why are you using ExtraBiomes instead of Biomes ´O Plenty? I´d prefered Biomes O´ Plenty more because it looks nicer, has more Biomes and earch Biome has there own difficulty, stuff and bonuses (So each player can setup there own difficulty what they want to play with)

Here is some information about ATG:
ATG adds a new world type which entirely replaces the base method of creating the world.

Vanilla generation creates "blobs" of land within the world and assigns random biomes to each, shuffling them around a bit to add rivers and such. The height and shape of terrain within these areas is determined by the biome, not the rest of the world.

ATG completely changes this, instead creating height, temperature and moisture maps for the world and deriving the final biome based upon those. Higher areas are colder, areas away from the sea and where the temperature is high tend to be dryer.

Using the generator config, any biome from any mod can now be added to ATG. Mods which used to use the API to insert their biomes still can, as it means they will appear in the default configuration, and can add their own terrain altering GenMods to be used by their biomes.

ATG is supported by directly by EBXL and Highlands, and includes small compatibility modules for Buildcraft's oil biomes and TC4's magical forest. This means their biomes will appear by default in the generator config, but you can add your own or make any changes that you wish.

A preconfigured generator.cfg for Biomes'O'Plenty can be found here.

All mods which add non-biome terrain generation features such as Thaumcraft, Buildcraft, IC2 and so forth work as expected, only mods that add whole new biomes require config modification. Buildcraft's oil biomes will spawn in the world, but they're rare, so keep your eyes peeled!

**Comment by JasonMcRay** [comment]
Problem with adding new World Gen to already running modpack can cause issues in the way of ugly transitions and similiar.

As for why I choose EXBL... just personal preference.

IF there will be pack update that will need new world (because of some mod will update with huge change to world gen) or if there will be InfiTech 3, then I can consider adding ATG.

**Comment by GamesGamble** [comment]
yeah that was the idea.

**Comment by JasonMcRay** [comment]
Will keep this in mind IF there will be some big update.
