### ISSUE TITLE
Little Macerator Recipe Bug

### ISSUE THREAD

**Issue by GamesGamble** [JasonMcRay/InfiTech-1.7#412]
There is a 406 Nether Quartz recipe with 67:7 Stone Stairs in the Macerator xD the 67:7 Stone stairs doesn´t exist (Nei shows only 67 Stone Stairs[Vanilla MC]) and i dont thing that you can make Nether Quartz out of Stone Stairs xD

**Comment by JasonMcRay** [comment]
Looks either it was just issue on your own side, or it has been fixed in some mod updates. AKA not able to replicate in dev.
