### ISSUE TITLE
EnderIO Conduits flickering in main world

### ISSUE THREAD

**Issue by Vliro** [JasonMcRay/InfiTech-1.7#413]
The conduits from Ender IO are flickering so much to the point where they don't really exist anymore. However, it only occurs in my main world with a lot of stuff, in a flat, creative world it doesn't happen. 
I am running the dev version of Infitech, the latest one from github.

https://gyazo.com/281c39fb795be9f52c1124ee7c1051d7

I've attempted to update both java and nvidia geforce. I've added SFM to the pack but it flickers regardless if it is installed or not.

**Comment by JasonMcRay** [comment]
It is known issue and mod devs are already aware of it...
https://github.com/SleepyTrousers/EnderIO/issues/2812

**Comment by JasonMcRay** [comment]
Looks like its fixed in latest.
Fixed in 683ea5a95edc575c542842e0f41c5021250b1da3
