### ISSUE TITLE
ExtraUtilities drums dupe

### ISSUE THREAD

**Issue by desertir** [JasonMcRay/InfiTech-1.7#415]
InfiTech v.3.1.17
If make R-Click on the water tank from Railcraft with staked drums (two or more) they will be duplicated. See screenshots:
Before R-Click
![image](https://cloud.githubusercontent.com/assets/10061582/11015036/4f1af5dc-8570-11e5-9f1e-8a48a50d72da.png)
Right after (one is gone and pay attention to water value)
![image](https://cloud.githubusercontent.com/assets/10061582/11015038/58897620-8570-11e5-8164-aea10b6a4013.png)
Where is it? Make inventory sorting...
![image](https://cloud.githubusercontent.com/assets/10061582/11015048/972ff570-8570-11e5-88dc-60d216ebfe49.png)
ExtraUtilities took a one drum and gave the same number of drums which was.
Also they are filled with water at 5 buckets (liquid dupe). I think it dupe maybe work with different liquids, or maybe not :)
I don't know which mod guilty of this. I think is ExtraUtilities.

**Comment by desertir** [comment]
Agggr... I'm not the first :D
https://github.com/rwtema/extrautilities/issues/703

**Comment by desertir** [comment]
Also drums are nice working with an EnderIO fluid tank.

**Comment by JasonMcRay** [comment]
ExU Drums will be made unstackable to prevent this issue in next update.

**Comment by desertir** [comment]
@JasonMcRay how about a bedrockium drum? I fogot about it and not tested it :)

**Comment by JasonMcRay** [comment]
This covers also bedreockium drums, since they use same item ID (in our case the mod is affecting all items named ExtraUtilities:drum and doesnt care about meta (which is :1 for bedrockium)
