### ISSUE TITLE
Advanced Jetpack -> "Engine Boosters" are uncraftable

### ISSUE THREAD

**Issue by xxlux** [JasonMcRay/InfiTech-1.7#417]
In 3.1.6 the Engine Boosters are not craftable

**Comment by DarknessShadow** [comment]
That should have fixed it https://github.com/JasonMcRay/InfiTech-1.7/commit/0dda8b42a5df2ea1a833c8044ca3fd9288f631e7 but I think Jason hasnt published it to FTB launcher yet.

**Comment by JasonMcRay** [comment]
Yup correct. This fixed in https://github.com/JasonMcRay/InfiTech-1.7/commit/0dda8b42a5df2ea1a833c8044ca3fd9288f631e7 for next pack update (let's hope this weekend)
