### ISSUE TITLE
Enderman heads (eIO vs. HEE)

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#418]
eIO and HEE Enderman heads are not exactly the same. I know it sounds wierd how two heads from same monster are diferent, but HEE heads are meant to drop in much much lower amounts. They should NOT be interchangeable

**Comment by chylex** [comment]
Reversed, EIO heads are supposed to be more rare :P HEE just hands them out to everyone

**Comment by JasonMcRay** [comment]
Hmm... My enderman spawner made 2 stacks of eIO heads and half a stack of
HEE heads...

**Comment by chylex** [comment]
HEE doesn't respond to cleavers or any item that increases the head drops, might be why.

**Comment by JasonMcRay** [comment]
Hmm... that might be the case actually.... I used The Ender sword (increases head drops from enderman).

Anyway still they should not be interchangeable :)

**Comment by JasonMcRay** [comment]
And actually that makes HEE heads more rare, since they have "fixed" drop rate and dont respond to increases via special items :)

**Comment by chylex** [comment]
They respond to looting, but not modded items or enchantments.

**Comment by Timeslice42** [comment]
Remind me again why we care? Neither mod provides any advantage for having more than one head.
