### ISSUE TITLE
superconducting wire crafting issues

### ISSUE THREAD

**Issue by Bweslake** [JasonMcRay/InfiTech-1.7#420]
superconducting wire crafting is a little bugged. it loses items if shift+left clicking. empty cells are not returned if there is a stack in the crafting panel. also it consumes all the material for multiple crafts but only outputs 1 craft's worth. if there are cells in the inventory of a production table it consumes all cells at once even without shift clicking. all testing was done in a production table

**Comment by JasonMcRay** [comment]
Reported to mod devs (https://github.com/Vswe/Production/issues/36)
But dont keep your hopes for the fix too high... Steves Workshop havent been touched for over a year by mod developer.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/37 long long time ago...

**Comment by JasonMcRay** [comment]
its also not only issue with Superconductors. It happens with ANY recipe that uses cells that:
1) can stack
and
2) are returned after crafting

**Comment by Blood-Asp** [comment]
well, it is certainly a SFM bug. there is no way for me to fix it. The only workaround for me is to move all recipes using cells into machines or similliar.

**Comment by JasonMcRay** [comment]
Maybe someone will be able to make a patch for that.

**Comment by Dlur100** [comment]
If you auto-craft with AE2 this is a non-issue correct?

**Comment by JasonMcRay** [comment]
Yes AE2 is fine... Its only Workshop issue, which I said if noone will be able to make patch for it, will not get fixed. If i knew modding stuff, I would make a patch for it. But I unfortunately have no idea what and how.

**Comment by JasonMcRay** [comment]
Since Steves Workshop is no longer maintained and I am not going to fix someones mess. Closing as Mod Dev doesnt care.
