### ISSUE TITLE
Chisel Enderchest Issue

### ISSUE THREAD

**Issue by MineMine** [JasonMcRay/InfiTech-1.7#423]
First, sorry for my bad english 

There is possible way to make an enderchest without using the current recipe 
It's simple just use Chisel2's chisel and convert Vanilla chest to Ender chest :( 

Is there possible way to fix or temporary ban for this glitch?

**Comment by JasonMcRay** [comment]
Add this <<ore:chest>>.remove(<<minecraft:ender_chest>>);
to any script file (in scripts folder).

Will be fixed in next pack hotfix

**Comment by MineMine** [comment]
Thanks for replying :D
