### ISSUE TITLE
clientside fps spikes/drops since 3.1.18

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#424]
Getting clientside fps spikes/drops since 3.1.18, about once every 1-2 minutes, even when just moving the cam in a small circle without moving a step.
Nothing suspicious on f3 page as far as i could see.
Upgraded from 3.1.6 to 3.1.18, so not sure if .18 is the first version causing this.

**Comment by JasonMcRay** [comment]
1) Update Java?
2) Update Graphic drivers?
3) Do you use any JVM arguments?
4) What are you PC specs?

**Comment by ghoulsblade** [comment]
1) updated java from 7.something to 8.44, didnt help
2) graphics card is driver update not possible atm, updater says error connecting to nvidia, try again later.
3) no jvm params, FTB launcher default, 8GB RAM assigned
4) specs:  NVidia GEFORCE GTX 560, driver version 353.06
i7-2600 CPU @ 3.4GHz, 12 GB RAM, Win7 Professional 64Bit sp1

seems to occurr every 30 seconds, on the moon as well (no machines yet besides stargate+batbuff+ gc oxygen bubble + collector powered by dieselgen + small wheat field and a few chests)

**Comment by JasonMcRay** [comment]
1) Latest java is 8.66. Make also sure you have 64bit java and not 32bit (for what is worth i have both of them just in case)
2) Updaters sucks, do manual update
3) 8 gigs is a waste. I run with 4 gigs allocated with no problems. Also try out the recommended JVM args i have posted on the first page on forum.

Lastly I have pushed out .19 update with updated forge, so it might now run even better.

**Comment by JasonMcRay** [comment]
@ghoulsblade If you are still experiencing fps spikes can you try to disable JourneyMap?

**Comment by ghoulsblade** [comment]
Got Java 8.66, that was just a typo.
Gfx-Driver : did manual update in device manager, took a while but finally displayed already up to date.
Update modpack to 3.1.20, but still had the fps spikes even in overworld wilderness 1km away from vase and on moon.

Disabling Journeymap helped !!! had no spikes since several minutes now.
I'll try resetting my mapdata later, first need to make a backup of the waypoints.

**Comment by JasonMcRay** [comment]
@ghoulsblade thanks. Will you with Journeymap enabled be able to get me a screeshot of F3 taken at the point of the spike?

**Comment by JasonMcRay** [comment]
Me with techbrew have found that the spikes are indeed every 30s when JM is writing map data to the disk. If you disable mapping the lag will be gone, but map data will not be saved. We will be performing more testing probably today and hopefully will get this fixed.

btw @ghoulsblade do you have FTB installed on SSD?

**Comment by ghoulsblade** [comment]
screenshots : i actually did that before making the ticket, but didnt see anything suspicous, here are they anyway: 
![2015-11-16_23 12 34-a](https://cloud.githubusercontent.com/assets/378125/11430909/106f5814-948e-11e5-8860-4004901b860d.png)
![2015-11-16_23 13 06-b](https://cloud.githubusercontent.com/assets/378125/11430910/10719836-948e-11e5-9d6f-97291c790c25.png)

SSD: nope, only good old harddisk here, SSDs were still expensive when i assembled the PC originally so i didnt bother, and didnt get around to upgrade it yet. Speeds vary greatly btw, we have a new generation one at work that can go 2000MB/s read, 1000 write, most normal ones only have 300-500 each. Needs a M.2 adapter card plugged into PCIe x4+ slot tho. Looks like a RAM module, and that M.2 plug is often used in flat notebooks etc it seems.

**Comment by JasonMcRay** [comment]
Ok.... techbrew provided to me an experimental JM version where this is fixed. So if anyone stumbling in here and having this issue, where minecraft freezes every ~30s: https://www.dropbox.com/s/4v546rur6nicni6/journeymap-1.7.10-5.1.2experimental-unlimited.jar?dl=0

This is expermimental version, use at your own risk. All what it has is fixed the mapping. Will not be putting it into modpack itself, until there is stable release.

**Comment by JasonMcRay** [comment]
Ok seems like techbrew released the fixed version. So go and download the JM 5.1.2 from curse page

**Comment by ghoulsblade** [comment]
got a link ? latest i see on curse is 
journeymap-1.7.10-5.1.1rc1-unlimited.jar 	7 November 2015

**Comment by JasonMcRay** [comment]
It has been taken out, because of another issue found. I have experimental version of JM where it seems fixed. I will post here a link for it when I get the chance (not near my comp at moment)

**Comment by JasonMcRay** [comment]
@ghoulsblade here is the experimental version: https://www.dropbox.com/s/aceu4i6v6kp8oma/journeymap-1.7.10-5.1.3experimental-unlimited.jar?dl=0

Just a disclaimer: do not report bugs with this version to journeymap devs. It is experimental version, use at your own risk :p

**Comment by JasonMcRay** [comment]
Fixed by 86ef426ec25982c2aeb6b5109c1b612b3de25e3b
