### ISSUE TITLE
GT<>Forestry compat broken (3.1.18)

### ISSUE THREAD

**Issue by random51** [JasonMcRay/InfiTech-1.7#426]
Various bee things not processing in centrifuge/extractor as they should.

**Comment by ghoulsblade** [comment]
confirmed, cant get honey from combs with greg centrifuge in 3.1.18. any other way available?

**Comment by JasonMcRay** [comment]
I will try to make a .19 with reverted Forestry to 4.0. No promisses when, I am lying in bed with man-flu. :(
