### ISSUE TITLE
Foresty <> GT interaction broken (3.1.19)

### ISSUE THREAD

**Issue by random51** [JasonMcRay/InfiTech-1.7#427]
You can put the items in the machines now, unlike in 3.1.18, but they still don't process.

Hope you're feeling better, Jason. :)

**Comment by JasonMcRay** [comment]
Can you give me example what is not processing? I tried combs in centrifuge and they worked perfectly

**Comment by random51** [comment]
Nothing is processing. I've got combs in a turbo centrifuge, honey drops in an hv extractor, seeds in an mv extractor. They just sit there. I thought maybe was some sort of power issue/bug so I put some impure dusts into the turbo centrifuge and it processed those fine.

**Comment by JasonMcRay** [comment]
Kill me now... I tested and it work, but I pushed to the FTB launcher wrong files.... Argh....

**Comment by JasonMcRay** [comment]
Can you give me example what is not processing? I tried combs and they
worked perfectly.
