### ISSUE TITLE
[NEW MOD] Framez 2

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#428]
From the description it looks great. Testing in progress...

Also if anyone else wants to test Framez mod, you are mostly welcome to help out.
http://minecraft.curseforge.com/projects/framez

**Comment by JasonMcRay** [comment]
And before anyone will start yelling: "You said you will not be adding any Alpha mods and Framez 2 is"

I know it is. But v3.2 of the pack is still in making and will take few days/weeks/months/years before finished :D

**Comment by JasonMcRay** [comment]
Took "only" 5hrs :D

**Comment by AiwendilCiunio** [comment]
/centuries/millienias/eons? Hopefully not :)

**Comment by JasonMcRay** [comment]
Well you can kinda check the stuff to do here: https://github.com/JasonMcRay/InfiTech-1.7/milestones/v3.2.0

Some of them are pretty much simple, just click, one line in scripts or similiar. But some of them are quite extense (like the Guide books and the Bee overhaul)
