### ISSUE TITLE
There is no way to get Ender IO's Enderman Head for Soul Binder, etc.

### ISSUE THREAD

**Issue by dontcorrelateme** [JasonMcRay/InfiTech-1.7#431]
Endermen drop only Hardcore Ender Expansion heads (4216) which can't be converted to Ender IO's (1386).

**Comment by JasonMcRay** [comment]
HEE heads are more common than eIO. To increase eIO heads drop you should use empowered The Ender sword.

Both heads are dropping. Conversion between them has been removed
