### ISSUE TITLE
Ludicrite Block (Big Reactors) glitch

### ISSUE THREAD

**Issue by MineMine** [JasonMcRay/InfiTech-1.7#433]
my user found some glitch to avoid Ludicrite Block recipe (actually Multiplying its ingot)

just place Ludicite block and brake them with Auto-Smelt and Fortune enchanted Pickaxe

this way can multiply 1 Ludicrite block to 9~36 Ludicrite ingots

I hope this glitch fixed :D or explain to me How to fix it

**Comment by JasonMcRay** [comment]
thanks for report. To fix you can set this line: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/endercore/endercore.cfg#L10 to false. (If this is on server, you can just change it in server configs, it will be synced to all players)

Will be fixed in next pack update.

**Comment by MineMine** [comment]
Thanks for fast replying :D
