### ISSUE TITLE
IC2 machines won´t connect with GT cables

### ISSUE THREAD

**Issue by danirpg** [JasonMcRay/InfiTech-1.7#434]
I try to connect a CESU battery with a GT cable but they cant connect.
![ss 2015-11-28 at 01 30 40](https://cloud.githubusercontent.com/assets/15187376/11451855/656b4728-95d4-11e5-8ac7-d403654060d7.jpg)

**Comment by lafflam** [comment]
I am pretty sure you must connect IC2 power sources to GT transformers first, and THEN to GT cables. I have not tried it with a CESU yet, but that basic process has worked every time for other IC2 power sources.

**Comment by danirpg** [comment]
Yep, i solve this with transformer thanks.
