### ISSUE TITLE
[Recipe Issue] Can craft PHC cotton out of candleberries

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#435]
I don't know how this happened, but there is a recipe to craft two candleberries into two cotton. This isn't exactly a game breaking issue, but it is dumb.

**Comment by Timeslice42** [comment]
It looks like one of PHC's weird "craft two X into two X" that all of her stuff has, but messed up.

**Comment by JasonMcRay** [comment]
I will force remove that recipe. Also reported to Pam.
https://github.com/MatrexsVigil/harvestcraft/issues/36
