### ISSUE TITLE
ServerCrash: bluepowermod TubeLogic IllegalArgumentException

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#436]
Just found a server crash, the players that discovered it said: "Placed a opaque tube at a side of a Manager while the whole thing was connected to a Retriever. Or maybe I broke some tube connected to that thing."
[crash-2015-11-29_15.13.10-server.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/46634/crash-2015-11-29_15.13.10-server.txt)
Not urgent, easy to avoid once known, just thought i'd let you know :)

**Comment by JasonMcRay** [comment]
Could you please give me a screeshot of the setup? it will be easier for me to recreate. Thanks

**Comment by ghoulsblade** [comment]
the player already took it apart, sorry

**Comment by JasonMcRay** [comment]
Can you please ask him to recreate that setup?

**Comment by JasonMcRay** [comment]
https://github.com/Qmunity/BluePower/issues/432

**Comment by ghoulsblade** [comment]
screenshots from elvanos:
![2015-12-01_23 44 03](https://cloud.githubusercontent.com/assets/378125/11516773/d117904a-9885-11e5-9f19-54213dc2943c.jpg)
![2015-12-01_23 44 09](https://cloud.githubusercontent.com/assets/378125/11516774/d11beec4-9885-11e5-84f1-aa2478822ba6.jpg)
![2015-12-01_23 44 17](https://cloud.githubusercontent.com/assets/378125/11516775/d11cdba4-9885-11e5-9618-38cb9b2105a0.jpg)
![motorframe02](https://cloud.githubusercontent.com/assets/378125/11516776/d11fcac6-9885-11e5-9fd4-1172ab82d03f.jpg)

**Comment by JasonMcRay** [comment]
Closing as one time crash, I tried exactly replicate the setup, and is not happening for me at all (both SP and MP)
