### ISSUE TITLE
"t" key no longer interacts appropriately with AE2 terminals

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#437]
After the 3.1.20 update the "t" key stopped working when in auto-search mode.  This makes it pretty difficult to search for anything with the letter "t" in it.

**Comment by JasonMcRay** [comment]
If I undersdtand correctly the T key is not working at all in terminals...

Did some testing
You have two options.
1) Do not hover with your cursor over any item in NEI while typing in the searchbox
2) Change keybind for Search For Item In Nearby Inventories to something you will not use that much.
(its located in NEI Options (open inventory > bottom left) > KeyBindings > Inventory)

I will see if I can change it to something not too much used like / * or something like that

**Comment by Dlur100** [comment]
That was it, thanks!   What is the purpose of "search in nearby inventories" btw?

**Comment by JasonMcRay** [comment]
When you hover over an item in NEI and press the corresponding key, it will show you where the item is in your chests/containers with little particles.

![2015-11-29_16 48 27](https://cloud.githubusercontent.com/assets/4236895/11458076/144a0ed4-96b9-11e5-884c-ec35f5f1bdce.png)

**Comment by Dlur100** [comment]
Ahh ok, so cool for early game.  Not useful at all with ae2 :)
