### ISSUE TITLE
Quantum Chest looses items when used with enderio itemduct

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#438]
![2015-11-29_20 48 49-quantumchest](https://cloud.githubusercontent.com/assets/378125/11459617/d47249b2-96da-11e5-8fec-b974eec1644c.png)

QuantumChestII - EnderIoItemConduit - VanillaChest
put a few stacks into the QChest manually, it showed 1500+
pumped them out to the VanillaChest with EnderIoItemConduit using 12 speed upgrades.
piped them back from VanillaChest to QChest with EnderIoItemConduit using 12 speed upgrades.

Very reliable to reproduce, i noticed it when moving stone from quarry, to another quantumchest a few blocks away, somehow went from over a million stone or so down to about 10k.

**Comment by ghoulsblade** [comment]
tried without speed upgrades and 2 stacks manually inserted into empty QuantumChestII, 
pumped out to VanillaChest with EnderIoItemConduit without speed upgrades, 2 stacks in vanilla chest.
Pumped them back into QuantumChest with EnderIoItemConduit without speed upgrades, only 64+4 left. Was using CobbleStone. So extraction works fine, insertion is bugged.
Insertion using ME export bus seems to work tho.

**Comment by JasonMcRay** [comment]
@Blood-Asp you or EnderIO?

**Comment by JasonMcRay** [comment]
Reposted to GT tracker.
https://github.com/Blood-Asp/GT5-Unofficial/issues/342

**Comment by JasonMcRay** [comment]
fixed in 38ea05d7a1ba663faec8ece1a4c3bd12db9c4d34
