### ISSUE TITLE
infitech2 upgrade problem 

### ISSUE THREAD

**Issue by adamsonich** [JasonMcRay/InfiTech-1.7#443]
Me and my friends played some version of infitech 2 modpack with gregtech v26 and without galacticraft. I make update upto v3.1.21 of infitech2 with gregtech v32 and with GC. Input hatch as part of EBF stoped drain oxygen. if I delete GC then input hatch starts drain oxygen.
as i can see, problem is oxygen oredict beetwin GC and GT.

How resolve problem?

I can upload 2,3MB world-save with same problem.
I posted same issue in Blood-Asp/gregtech5exp issues theard

**Comment by JasonMcRay** [comment]
Closing as Blood replied to you in there
