### ISSUE TITLE
intentional? cant automate battery buffer output

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#444]
I cant seem to find any way to extract empty batteries from a battery buffer (EV), 
tried hopper, enderio, ME import bus, storage bus, item translocator,  LV conveyor module, EV robotic arm on lots of different settings.
Is that intentional?

**Comment by DarknessShadow** [comment]
yes thats intentional

You can only insert / extract SINGLE USE batteries.

**Comment by ghoulsblade** [comment]
Should allow it for IV battery buffer and IV conveyor/roboarm at least.
Found one way that works anyway: dynamism tablet with wrench to break->lapos fall out, can place the battery buffer again with another dynamism tablet y-level higher.

**Comment by Timeslice42** [comment]
The battery buffer isn't really intended for charging so much as a power buffer. Version 5.09 of GTU has a machine specifically designed for charging/discharging batteries, and does so at an accellerated rate.

**Comment by JasonMcRay** [comment]
This is intended. As mentioned by DarknessShadow you can only automate Singel use batteries in Battery Buffers.
