### ISSUE TITLE
[Mod Issue] Thirsty Tank not respecting finite water

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#445]
Reported: https://github.com/Tuhljin/Automagy/issues/41

**Comment by ghoulsblade** [comment]
Probably intentional as the tank does consume the water when glyphs are used to upgrade the speed.

**Comment by JasonMcRay** [comment]
Honestly this doesnt that much bothers us. For Infitech purpose gonna tend to it as intended. Of course config option will be nice for some players.
