### ISSUE TITLE
AE2 Ore dictionary trouble

### ISSUE THREAD

**Issue by desertir** [JasonMcRay/InfiTech-1.7#449]
So, ore dictionary names of a pure nether quartz and a pure certus quartz are interchanged:
Pure Nether Quartz Crystal - itemCertusQuartz
Pure Certus Quartz Crystal - itemNetherQuartz
Because of this the blank pattern recipe has the pure nether quartz instead of the pure certus quartz.

**Comment by JasonMcRay** [comment]
Will not swap the oredict entries, but will at least change the affected items to use the latter.

**Comment by JasonMcRay** [comment]
fixed in 38ea05d7a1ba663faec8ece1a4c3bd12db9c4d34
