### ISSUE TITLE
Crash with OC's adapter.

### ISSUE THREAD

**Issue by desertir** [JasonMcRay/InfiTech-1.7#451]
RClick on an adapter from OpenComputers evokes a crash. After that I can't go in the world.
Crash log http://pastebin.com/CbabJZ2D
Full log http://www.filedropper.com/fml-client-3 (can you tell me a better file hosting?)
Pack version is 3.1.21

**Comment by JasonMcRay** [comment]
Hmm.. For some reason I forgot to update OpenComputers... just update it manually and everything should be fine.
http://minecraft.curseforge.com/projects/opencomputers/files/2267428

**Comment by desertir** [comment]
"I forgot to update OpenComputers..."
Happens :)
