### ISSUE TITLE
Missing Extractor Recipes

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#452]
The following EBXL flowers are missing (blue) dye extraction recipes:
```
<ExtrabiomesXL:flower3:12>
<ExtrabiomesXL:flower3:1>
<ExtrabiomesXL:flower2:4>
```

**Comment by JasonMcRay** [comment]
@Timeslice42 can you please provide item names? I dont trust item IDs at all, since they are no longer used and can be different in different instances.

**Comment by Timeslice42** [comment]
Pretty much all of the EBXL flowers that give [blue] dye. I'll update with the names.

**Comment by Timeslice42** [comment]
I have no idea if any others are missing.

**Comment by JasonMcRay** [comment]
EXBL flower extraction is GT thing. Part has been done earlier, but seems like few has been missed.
https://github.com/Blood-Asp/GT5-Unofficial/issues/170
