### ISSUE TITLE
XACT not correctly interfacing with AE2

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#453]
The AE2 module for XACT doesn't appear to be working. You're meant to be able to place an ME interface next to an XACT table and the table will be able to access any item from that network. I checked the config and it is set to load, but it's not working.

Since I can't figure out where you're getting this new version of XACT from I'm forced to report it here.

**Comment by JasonMcRay** [comment]
XACT AE2 integration is highly WIP so its not yet finished... Unfortunately @UniversalLp is not currently working on the XACT actively. But from what he told me, he would love to fix few bugs and somewhat complete it.

**Comment by UniversalLP** [comment]
I'm sorry but unfortunately I got sick so I can't make any promises as to when I'll be able to work on it again

**Comment by Timeslice42** [comment]
Did you ever re-add the Logistics Pipe functionality?

**Comment by UniversalLP** [comment]
I did not do it in particular but if you mean automatic inserting of items, that should work

**Comment by Timeslice42** [comment]
No. In 1.6.2 you could put an ME interface or an LP supplier pipe next to an XACT table and it would be able to access items from either network. Since you didn't immediately realize that's what I mean, I'm going to assume the answer is no :)

**Comment by Timeslice42** [comment]
Come to think of it it might have been a requester pipe, not a supplier.
