### ISSUE TITLE
autoclave enderio vibrant crystal bug

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#455]
FYI found a big with autoclave recipe for enderio vibrant crystal.
put liquid vibrant alloy and emerald dust in autoclave.
making a single one works.
making 2 at once gives you 1
making 9 at once gives you 8
seems the first one is lost if there is more dust in queue, maybe stacking bug.
Workaround : make single ones manually (take out result before putting in more dust)
or set auto-export to a chest, that works as well.

**Comment by JasonMcRay** [comment]
Not a bug.... Autoclave has a 85% success chance for Vibrant Crystal and Pulsating Crystal
