### ISSUE TITLE
Master Magic Energy Converter (HV) needs Europium=Fusion1

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#459]
just a suggestion, Master Magic Energy Converter (HV) needs Europium to craft.
Europium needs Fusion Mark1, which can produce IV, 2 tiers above HV.
So by the time you can craft the HV converter, you dont need it any more.
Maybe sth else thats high tier but before Fusion, e.g.  lutetium (from depleted thorium rods), tungstensteel, that eldritch eye or boss drop primorial pearl, ultimet (ebf2 + vacfreezer), enderium/naquadria/enr.naq/naq.alloy/fluxed electrum/ (ebf3+vfreezer), plutonium 241 isotope (hv centri, small chance), superconductor wire, 1 fusion coil (rather than whole reactor), or lapo orb which needs EV assembler.

**Comment by JasonMcRay** [comment]
I suggest to go with the GT related tweaks to GT machines directly to https://github.com/Blood-Asp/GT5-Unofficial/issues. Some time ago I said that I will not change recipes for GT machines on my own.
