### ISSUE TITLE
Bibliocraft Potion Shelf recipe issue

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#461]
Somehow the only vanilla wood that is working in the potion shelf is oak. I see all the forestry and EBXL woods, but only oak. It's possible other recipes may be affected as well.

**Comment by JasonMcRay** [comment]
Its pretty much all Bibliowoods Forestry items. We need to wait for Nuchaz to update Bibliowoods to support latest Forestry. I am not going to add recipes via minetweaker because.... There is a lot of them

**Comment by Timeslice42** [comment]
Issues with forestry is causing vanilla wood recipes to be missing?

**Comment by JasonMcRay** [comment]
I am not getting that problem in my instance... Everything except forestry
related bibliowood szuff is craftable

**Comment by Timeslice42** [comment]
That's weird. I'm seeing everything except for vanilla woods, where I only see oak. Confusing... either way it's worth waiting until biblio updates forestry support.

**Comment by JasonMcRay** [comment]
Bibliowoods will not be updated anymore. So it might be good time to remove it from the pack on the big 3.2 update. BiblioWoods addons have been superseded by the Furniture Paneler block from Bibliocraft. You can accomplish the same looks (and much much more) with the furniture paneler.

**Comment by Timeslice42** [comment]
Agreed.
