### ISSUE TITLE
Magic Bees Vis Apiary Booster not working

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#464]
I built the vis apiary booster and set it up according to MysteriousAge's video (https://youtu.be/dk_0uDVedNI) but it doesn't do anything. It doesn't even pull centi-vis from my energized node. I'm pretty sure Myst has moved on, do you know who is maintaining the mod now?

If we can't get it to work we should just remove the research page.

**Comment by JasonMcRay** [comment]
Myst, @Arkandos and @Mezz are maintaining it (I think).... but not sure how actively...
On the github last "something" happend on 27th October (https://github.com/MagicBees/MagicBees)

**Comment by Arkandos** [comment]
I'm not maintaining it anymore, but I think both @MysteriousAges and @Mezz are maintaining it.

**Comment by JasonMcRay** [comment]
@Timeslice42 Please when you get the chance please give me screenshot of the setup.
