### ISSUE TITLE
Nuclear Control not showing Thorium

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#465]
If you use a remote sensor kit on an IC2 reactor that contains IC2 fuel cells (uranium or MOX) then it can provide the time remaining until the reactor runs out of fuel (assuming constant runtime). However this piece of information doesn't work for thorium.
Does the thorium fuel cell need to implement an interface, or does nuclear control just need to be told to look for thorium?

**Comment by JasonMcRay** [comment]
My guess would be just Nuclear Control must be updated for Thorium...

**Comment by Blood-Asp** [comment]
Purely code on NC side. Me replacing also Uranium&Mox fuel rods in the latest GT version will also break that support currently working partly.
