### ISSUE TITLE
Server Crash - IC2 Nuclear Reactor

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#466]
In creative, removing someone's base who's left, they had an IC2 Nuclear Reactor surrounded by heat casing, generating 'Hot Coolant'. Destroyed this in creative dropped all the items into coolant that was inside the reactor and seems to be crashing the server when ever I log back in.

 Crash report: http://pastebin.com/RBFuw1VK

Logged with IC2: http://bt.industrial-craft.net/view.php?id=1792

**Comment by JasonMcRay** [comment]
Its not probably IC2, according to the crash report it seems like Nuclear Control mod.
Reported: https://github.com/xbony2/Nuclear-Control/issues/136

**Comment by JasonMcRay** [comment]
You could either remove the base with MCEdit, or maybe forge item removal could help (as always: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/forge.cfg#L13-L17)
