### ISSUE TITLE
Thermal cloth recipe

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#469]
Change enchanted fabric for polyethylene "foil". Add recipe for the foil (likely cutting machine and ingot of polyethylene) if @Blood-Asp is not going to add it in the core in different way.

**Comment by JasonMcRay** [comment]
Reminder for @JasonMcRay :) Dont forget about it AGAIN!

**Comment by Timeslice42** [comment]
lol
