### ISSUE TITLE
Add VoxelMap as an optional mod

### ISSUE THREAD

**Issue by piotrb** [JasonMcRay/InfiTech-1.7#472]
Hey,

Loving the pack, would just like a choice of a better map mod (I get I can add it manually, but its a lot easier to have it officially supported).

VoxelMap requires Liteloader thats about the only weird thing about it .. I personally find it a much simpler map experience than journeymap.

**Comment by piotrb** [comment]
http://minecraft.curseforge.com/projects/voxelmap
http://www.liteloader.com/download

Liteloader is very weird .. it has a useless jar installer .. but you can just open the jar and grab the actual proper mod from inside of it ..

**Comment by JasonMcRay** [comment]
I chose Journeymap for personal preference. Adding Voxelmap and Liteloader will not help to ease the installation... You will still need to enable the VoxelMap and Liteloader manually and disable Journeymap manually. Having it enabled all the time will just mess things up. So there is no real reason to add it on my end...

**Comment by piotrb** [comment]
Well technically you can leave liteloader enabled all the time .. it doesn't do anything on its own :)

**Comment by piotrb** [comment]
really the main reason I did end up switching was compatibility with this little thing ..

http://minecraft.curseforge.com/projects/minimapsync

On a small co-op server its nice to be able to do that .. and its journeymap support seems broken ..
