### ISSUE TITLE
Add MouseTweaks

### ISSUE THREAD

**Issue by piotrb** [JasonMcRay/InfiTech-1.7#473]
http://minecraft.curseforge.com/projects/mouse-tweaks

Especially on a greg pack, its a nice to be able to do a lot of manual things easier .. this just gives you a bunch of convenience tools .. can be optional since its a client side only mod anyways, but would be nice to not have to keep adding it every update :)

**Comment by JasonMcRay** [comment]
I was actually looking for this mod, but had no idea how it is called :) Thanks :)
