### ISSUE TITLE
Server crash with XACT portable crafter and "saving recipes to nbt"

### ISSUE THREAD

**Issue by piotrb** [JasonMcRay/InfiTech-1.7#474]
Sorry don't have a log for ya, we just stopped using them on my server, but its an issue .. seems to trigger a fair bit in normal use .. is XACT really worth its weight in the pack anyways?

**Comment by JasonMcRay** [comment]
Without log and recreation steps I can't help.

**Comment by piotrb** [comment]
I'll try to repro it again on .23 and see

**Comment by piotrb** [comment]
Ok this is from my server's crash logs

**Comment by piotrb** [comment]
https://gist.github.com/piotrb/c3d27fd85fc8286af3ed

**Comment by piotrb** [comment]
This is still from .21 but then not much changed between .21 and .23

**Comment by JasonMcRay** [comment]
Reported: https://github.com/UniversalLP/XACT/issues/14

**Comment by UniversalLP** [comment]
Do you now by any chance what you or the player did with the craft pad before it crashed? Like any special items/recipe in the craft pad. Does it crash when opening the GUI or randomly when using it?

**Comment by piotrb** [comment]
I never really got the repro down clearly .. it triggered on closing the UI (I imagine thats where it saves the nbt of the last recipe)

it seems a bit random, I'd make a few things no problem, open close, etc .. but other times when I closed the pad it'd crash the server

Oh yea if it makes any difference always used it without a chip

**Comment by JasonMcRay** [comment]
@UniversalLP I experienced it few days ago... dont remember what exactly I had in Craft Pad. I think I had in there just GT tiny dusts (9 to make 1 normal dust), thats what I am using the craftpad mostly for.

**Comment by UniversalLP** [comment]
I could reproduce the same crashlog when I died while having the craftpad gui open. So I guess it happens when it's trying to write the NBT onto the item but the item is null.
I got that fixed and I'll make a release of it tomorrow

**Comment by JasonMcRay** [comment]
Thanks a lot

**Comment by Timeslice42** [comment]
Why was this closed? It's still an issue.

**Comment by JasonMcRay** [comment]
https://github.com/UniversalLP/XACT/releases/tag/v0.5.5b

**Comment by JasonMcRay** [comment]
Closing it again, because this issue is fixed. I know that AE integration is broken, but as long as players will not try it, they will not crash.
