### ISSUE TITLE
Crash client with Shift+Ctrl+click invtweak + redpower bags

### ISSUE THREAD

**Issue by InferExcav** [JasonMcRay/InfiTech-1.7#475]
When u want remove many one type items from bags (Red power) with Shift+Ctrl+click, minecraft is crashing :c

**Comment by DarknessShadow** [comment]
1)
Redpower2 hasnt been updated after 1.4.6.
The redpower2 clone projectred is also not in the pack since v3.1.
We have bluepower in the modpack.

2)
A crashlog is ALWAYS necessary when reporting a crash.

**Comment by InferExcav** [comment]
[crash-2016-02-07_09.48.03-client.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/120624/crash-2016-02-07_09.48.03-client.txt)

**Comment by JasonMcRay** [comment]
Should be fixed in v3.2

**Comment by JasonMcRay** [comment]
Ok. Doesnt look like its fixed.
Anyway Dupe: #493

**Comment by InferExcav** [comment]
I found the cause of this problem. I have OP roots on my server, so when I try to use combination of Ctrl+Shift+Click (invtweak) )to move a lot of items of one type, it sometimes didn't work (if u want to move ur items fast to bags/big coal boilers/railcraft coal furnace/some types of workbench e t. c. but when u try put them back it works correctly) and NEI in the same moment sometimes without any reason try to give me a stack of this items to me. Client crashes when my inventory full and NEI doesnt have place to put a stack of items.
So, I think invtweaks bad working with inventories in different mods and when it happend somehow this combination to move items go to NEI. And maybe NEI thinks that bag that u opened also is ur inventory and tries to give u items.
The interesting fact is that Shift-Click always works correctly, but Ctrl-Shift-Click have problems.

**Comment by JasonMcRay** [comment]
It is pretty much cross issue with Inventory tweaks and NEI. Ususally happens when you have full inventory.

There is not much we can do about that since both mods are no longer developed for 1.7 as far as i am aware

**Comment by InferExcav** [comment]
Anyway, thanks a lot for helping to solve this problem.
