### ISSUE TITLE
NBT related Duplication with Sorting Machine (Blue Power)

### ISSUE THREAD

**Issue by Verharn** [JasonMcRay/InfiTech-1.7#476]
https://youtu.be/kDzETlw897k

**Comment by JasonMcRay** [comment]
Seems like Sorting Machine is ignoring NBT data on blocks... Thanks for nice report and recreation.

**Comment by JasonMcRay** [comment]
Reported to mod devs: https://github.com/Qmunity/BluePower/issues/439
