### ISSUE TITLE
Exception ticking world: extrabiomes.items.ItemNewSapling?

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#477]
Two crashes on the official server, one right after another. Still running 3.1.21. 

First crash.
Crash report: http://pastebin.com/zdnVVgb9
Partial FML Server log: http://pastebin.com/7ytbsw2j

This was followed by a second crash that appears to have occurred during restart.
Crash report: http://pastebin.com/YRn6rbzn

**Comment by JasonMcRay** [comment]
Is it just like that? Or does it happen with certain player logging in?

**Comment by JasonMcRay** [comment]
Try updating EXBL to latest (http://minecraft.curseforge.com/projects/extrabiomesxl/files/2273301) and let me know please

**Comment by JasonMcRay** [comment]
Ok confirmed that it will not help... but new EXBL version is in progress of making.

**Comment by lafflam** [comment]
I just discovered we are having a problem with a certain player and/or a region file, so I am not sure if these crashes are related to a "certain player logging in" yet. Suggest closing until I have more precise information.
