### ISSUE TITLE
Applied energistics plugin for XACT

### ISSUE THREAD

**Issue by DuckyC** [JasonMcRay/InfiTech-1.7#478]
Im unsure if this is the ported version this modpack uses
https://github.com/UniversalLP/XACT/blob/master/changelog
but it seem like it. It has an update that adds back AE intregration to the XACT crafter.

**Comment by JasonMcRay** [comment]
Yes it is and here: https://github.com/UniversalLP/XACT/issues/15 you can see it doesnt work. Also there is no reason to remind me of mod updates. There will be no pack update anymore for 3.1... We are working on 3.2

**Comment by Timeslice42** [comment]
Don't get too excited about this either, as the AE2 integration is broken.
