### ISSUE TITLE
AE2 deletes GT tool at zero power not zero durability 

### ISSUE THREAD

**Issue by Bweslake** [JasonMcRay/InfiTech-1.7#479]
tested with HV tungstensteel wrench and shift clicking crafting in AE2. if power on wrench runs out it simply goes missing.

**Comment by JasonMcRay** [comment]
Should be fixed in rv3 of AE2. Havent tested yet.

**Comment by JasonMcRay** [comment]
testing happend. Not fixed

**Comment by JasonMcRay** [comment]
Reported to mod devs: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2188

**Comment by JasonMcRay** [comment]
Closing since AE2 dev for 1.7 has stopped.
