### ISSUE TITLE
How to enable recipe for charger from Applied Energistics 2?

### ISSUE THREAD

**Issue by InferExcav** [JasonMcRay/InfiTech-1.7#481]
I cant use NEI option to find Charger (id:186) AE2 recipe in single and multiplayer modes. Have you make some changes or is there exist another way to create this block to chrarging different tools and crystals from AE2?

**Comment by DarknessShadow** [comment]
I think its disabled.
You can charge tools in the enderio capacitor bank and you can make charged certus quartz in the gregtech electrolyser.

You have to remove this line to enable it again: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/AE2.zs#L266

**Comment by InferExcav** [comment]
Thanks ;)
