### ISSUE TITLE
Iron Block

### ISSUE THREAD

**Issue by InferExcav** [JasonMcRay/InfiTech-1.7#482]
How to create Iron Block on Steam Alloy Smelter if recipe of iron block require 320 EU and 64EU/t. I put 9 Iron ingots with Mold (block) correctly (including correct input and output for steam) in Steam Alloy Smelter but it doesn't work. I think that I should wait for "electric era" but i need anvil in recipe of Steam Forge Hammer. So I dont know how to get Iron Blocks for my next recipes. Can you help please?

**Comment by JasonMcRay** [comment]
You need compressor to make blocks. Check NEI, its all in there

**Comment by InferExcav** [comment]
Oh god... My epic fault. Sorry :c
