### ISSUE TITLE
Check Harvestcraft foods for incorrect aspects

### ISSUE THREAD

**Issue by Xavion3** [JasonMcRay/InfiTech-1.7#483]
It was mentioned on the forums that some harvestcraft foods had metallum, that probably shouldn't be happening so they will have to been gone through and scanned to track down oddities and work them out.

**Comment by catt0** [comment]
If you refer to [this ](https://github.com/password_reset/0034fd05ff75a6da54405ea800620b17149f550f656a23bd92ce56bcd13682a5656d61696cb467726579746f6d63617440796d61696c2e636f6da5666f726365c2)post by me, I was talking about Delighted Meals. I tested around a bit and seems to come from the pot used in making the cheese, it gives cheese 6 Metallum. Jason already posted about this and there is a workaround [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294413-pams-mods-jan-23rd-2016-1-7-10-mod-pams-need-moar?comment=2043).

**Comment by Xavion3** [comment]
That first link is a password reset link, but yeah that might be what I was referring to, kinda forgot to actually go scan the things but I'll definitely look into this thanks.

**Comment by Xavion3** [comment]
So got annoyed as a huge portion of the items in the mod are suspect as anything which uses milk, water, pot, skillet, or saucepan could've been hit so it has been countered by just removing metallum from those. Seems to have worked so it'll be closed for now, included in the thaumcraft overhaul.
