### ISSUE TITLE
GT Credits

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#484]
Disable crafting of the credits for 3.2 release.

**Comment by OvermindDL1** [comment]
Is there another method of 'money' for a server?  Being able to anvil the thing that credits are pressed from to make a centrally unique 'bank' of credits is great for economy on servers.

**Comment by JasonMcRay** [comment]
IC2 coins are still in.

**Comment by OvermindDL1** [comment]
But cannot be used to make a centrally controlled bank like GTs coins and coin presses can do, thus no control over the economy.

**Comment by JasonMcRay** [comment]
Why not? GT Credits are completely crafted the same as IC2 credits, there is just less of them.

**Comment by Blood-Asp** [comment]
GT Credits get a personal tag, so if you control the mold, it can't be copied.

**Comment by JasonMcRay** [comment]
Well, you know you aren't making it easy for me... Time to do some rewrites :(
