### ISSUE TITLE
Modify DOB bee to be obtainable

### ISSUE THREAD

**Issue by Xavion3** [JasonMcRay/InfiTech-1.7#485]
Still needs the solar panel from a mod we don't have.

**Comment by Xavion3** [comment]
Mentioning as a reminder that it only works with the Forestry centrifuge and not the GT one due to having >6 outputs for the comb.

**Comment by JasonMcRay** [comment]
Closing on behalf of: https://github.com/JasonMcRay/InfiTech-1.7/issues/586
