### ISSUE TITLE
BC Gates uncraftable?

### ISSUE THREAD

**Issue by piotrb** [JasonMcRay/InfiTech-1.7#486]
This might be a dumb question .. but I can't seem to find any way to craft the BC gates (not the chips, I see the recipes for those), but gates, the ones you'd put on BC pipes

**Comment by piotrb** [comment]
I did just reinstall for good measure .. nope .. NEI is unhelpful .. just shows that the gates can be converted in the integration table .. but how do you get the original basic gate to begin with?

**Comment by Xavion3** [comment]
They should be craftable in the assembly table, although I'm pretty sure you only view the recipes in NEI if you look at the recipes for the gates without expansions. Try redstone chipset + red pipe wire in an assembly table to see if the recipes work.

**Comment by JasonMcRay** [comment]
Go to buldcraft/compat.cfg and set the hidefacaderecipes to false. There is bug in buildcraft compat that hiding of facades is disablibg nei integration for assembly table fully

**Comment by piotrb** [comment]
Oh that was a bit obscure .. that solved it :)
