### ISSUE TITLE
To do list for v3.2

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#487]
What needs to be done:

- [x] Englishification and journal entries for HQM (REQUIRED) - @Pyure
- [x] Thaumcraft overhaul - @Xavion3 @Timeslice42 - ea11519eb771418ff0d45df28097343f5145de13
- [x] PneumaticCraft overhaul - @JasonMcRay (just few last bits in there) - 7b3d1f6dda8494e434223c36a1daa7ce64d6a40f
- [x] Rewrite current PcCraft quests because of the overhaul - @JasonMcRay - LOCAL
- [x] Buildcraft overhaul - @JasonMcRay - afa74098d882d65da3850407093b41843a833389
- [x] Steves Carts addition + de-nerf few recipes - @JasonMcRay or @Xavion3 - 4b2c1cde4b02ebb34181979cbe863835f5d33580
- [x] Put the quests (englishification) into HQM (REQUIRED) - @JasonMcRay
- [x] Test the quests - everyone if possible (REQUIED) (XACT is really helpful in creative with crafting quests); also make sure that there are no quests missing

**Comment by Xavion3** [comment]
Magical steel quest should be modified, the thaumcraft overhaul makes it use wrought iron instead of normal iron but the quest just mentions the use of iron.

**Comment by JasonMcRay** [comment]
Successfully tested HQM:
- Bronze Age
- LV Age
