### ISSUE TITLE
How to harvest wire & cables?

### ISSUE THREAD

**Issue by InferExcav** [JasonMcRay/InfiTech-1.7#492]
Wire cutter doesn't work correct with wires.
Waila tells that I should harvest them with wrench, but it also doesn't help.
Thanks :)

**Comment by Blood-Asp** [comment]
Wirecutter is the correct tool. Maybe the mining level is wrong?

**Comment by InferExcav** [comment]
Oh, thanks. Don't see that cables require mining level ._.
