### ISSUE TITLE
Crash client with Shift+Ctrl+click invtweak + railcraft furnace

### ISSUE THREAD

**Issue by InferExcav** [JasonMcRay/InfiTech-1.7#493]
#475 I think it is the same problem like with bags.
[crash-2016-02-07_09.35.37-client.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/120621/crash-2016-02-07_09.35.37-client.txt)

**Comment by OvermindDL1** [comment]
Last I checked, the invtweak in this pack is old and buggy, with many crashing bug fixes in the latest.  At the very least auto-refill will crash the client if their inventory is full as of the latest official version of Infitech, and there are a few other cases, such as the one in this Issue that can also happen.

**Comment by InferExcav** [comment]
No problems, i just report a bug)

**Comment by JasonMcRay** [comment]
@OvermindDL1 Last I checked we have latest InvTweaks. The other "latest" versions are for 1.8 if I am looking correctly

**Comment by JasonMcRay** [comment]
just went ahead and reported
