### ISSUE TITLE
Anchor crash

### ISSUE THREAD

**Issue by Tratolak** [JasonMcRay/InfiTech-1.7#496]
When i place any type of anchor from railcraft in the world, save & quit and try to load the save again, the game will crash. When i tried it on 3.1.17 it didn't occur. Anchors/Chunkloaders from other mods work fine.

http://pastebin.com/KqWypdam

**Comment by Xavion3** [comment]
Does restarting minecraft allow you to load the world again? I've encountered something similar before where it would work once per game start, thought that got fixed though.

**Comment by Tratolak** [comment]
Yes it does. Thanks

**Comment by Xavion3** [comment]
Ok so if memory serves this was an issue with RC 9.8 that I fixed by downgrading, as mentioned no idea what the state of the bug is now though.

**Comment by Timeslice42** [comment]
Is this still an issue in 3.2?

**Comment by Xavion3** [comment]
It should be, found the issue reported on the railcraft issue tracker and it has been fixed, just got to wait for Railcraft to release an update before we actually get the fix it seems.
