### ISSUE TITLE
Food overhaul

### ISSUE THREAD

**Issue by Xavion3** [JasonMcRay/InfiTech-1.7#497]
Overhaul PHC and GT foods fit with the GT crafting themes better and actually work with hunger overhaul. Plan more later.

**Comment by Timeslice42** [comment]
To quote myself:
Remove or require the GT food stuff, get rid of the GT food items (they cheat somehow that doesn't respect Hunger Overhaul settings), ensure that all the food basics like flour, etc. have a by hand+durability recipe and a machine recipe
And we could cover the aspects in that too.
We should be enforcing or removing the GT food machines.

**Comment by Timeslice42** [comment]
This should also include increasing the output of certain reipces, such as fish sticks, so that there is a net increase in food value, rather than a loss.

**Comment by Xavion3** [comment]
Is it even possible to do that with Mine/Modtweaker?

**Comment by JasonMcRay** [comment]
Changing food values? Not easily. One way of doing that is more crafting
steps

**Comment by Timeslice42** [comment]
No, I was talking about increasing the output, so, like 6 fish sticks instead of one, to pull a number out of a hat.

**Comment by JasonMcRay** [comment]
So is there something we are going to do about this?

**Comment by Timeslice42** [comment]
We're still on 3.2.x, so we have plenty of time :p 
How's that RFTools integration coming along, anyways? :p
