### ISSUE TITLE
Fix TC scripts crashing on script reload

### ISSUE THREAD

**Issue by Xavion3** [JasonMcRay/InfiTech-1.7#498]
The scripts work perfectly but currently you have to restart infitech every time you want to open a world or join a server. Putting this here so I don't forget again.

**Comment by JasonMcRay** [comment]
just in case I or anybody else will be looking for the mentioned issue: https://github.com/jaredlll08/ModTweaker2/issues/307

**Comment by Xavion3** [comment]
Right, forgot to get a minimum reproduction going. Guess that'll go on my list of things to do then.

**Comment by Xavion3** [comment]
Fixed now, at least a work around was implemented.
