### ISSUE TITLE
Aroma1997 Dimensional World

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#500]
Possible modpack addition: [Aroma1997 Dimensional World](http://minecraft.curseforge.com/projects/aroma1997s-dimensional-world)

A Dimensional World is similar to an Overworld plains biome, except it is perfectly flat. The config can be changed so that the land height is about y=128 in order to ensure that all GregTech ores may generate. This dimension could be perfect for servers. For example, server operators could restrict EnderQuarries to this dimension in order to protect player bases from accidental destruction. And both single-player and server worlds could benefit by keeping the Overworld looking nicer (i.e., no more deserts changed to long swathes of brown grass dotted with flowers... yuck!).

The easy part is that the modpack already has Aroma1997 Core in it, so adding the Dimensional World would be easy.

I do think the default recipe to craft the Dimensional World portal may be too easy. I think it might be best to force early players to explore and mine manually in the Overworld, Nether and End until they are ready to build their first EnderQuarry. This could easy be changed in the scripts to require a item that can only be crafted around the same time as an EnderQuarry.

Of course, there are other potential problems. For example, would a mining world shift the balance of the game too much by making it a little easier to acquire tin? And would a mining dimension prevent players from exploring Galacticraft for mining resources? Those are things for Jason to decide.

In the end, I have tested Dimensional World on my personal InfiTech2 home server, and it seems to work as expected. I hope there is still time to consider this for addition to 3.2.

EDIT: Outstanding video tutorial about this mod: https://www.youtube.com/watch?v=Qljya-1qJQ4
I think the recipe for the Dimensional Changer is also too easy, so that could also be Gregified/Jasonfied in the scripts. Oh, and mobs can spawn underground in caves, I believe. They just don't wander up to the surface very often due to the eternal daylight. As for the portal spawning underground in the mining dimension... I have had that happen too, but I considered it a feature :-)

**Comment by JasonMcRay** [comment]
As because we will be adding RFTools specifialy for Mining Worlds/Dimensions in future update, this mod would become redundant, and removing it from the pack afterwards would case brain damage to players/server owners (mainly with moving stuff out of there)

Also I hate flat world for mining, simply because it will impact balance. You will be able to find all the ores that would spawn in overworld in high y-level flat world without any issues.

If server owner/player decides to add it on their end, its their decision. But that decision is not supported by us (read if something will break in Mining World it will be player/server admin thing to fix).

**Comment by lafflam** [comment]
I had the same concerns about the flat world and balance. I did not know that you were already considering RFTools as a possible mining solution. Looking forward to it :-)

**Comment by JasonMcRay** [comment]
It will take some time... RFtools are currently at ine of the lowest
priority enhancements

**Comment by lafflam** [comment]
Understood. Thanks for the feedback.
