### ISSUE TITLE
[Dev] /help 4 command crashes the game

### ISSUE THREAD

**Issue by Amberlight1** [JasonMcRay/InfiTech-1.7#501]
No server crash, only local

**Comment by JasonMcRay** [comment]
Crash log please?

**Comment by Amberlight1** [comment]
sure, here we are..
http://pastebin.com/A4ra2i9j

**Comment by JasonMcRay** [comment]
Reported: https://github.com/INpureProjects/INpureCore/issues/22

**Comment by JasonMcRay** [comment]
Fixed with helpfixer mod.
