### ISSUE TITLE
[Dev] wand rod not craftable (pulp plate gives arrowheads)

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#502]
saw + woodpulp plate + file  gives arrowheads rather than a wand core

**Comment by JasonMcRay** [comment]
Fixed: https://github.com/JasonMcRay/InfiTech-1.7/commit/1e3780a7d546b0dd10149718c0959f850cfeaaa6

**Comment by Timeslice42** [comment]
lol, nice one, Jason :)
