### ISSUE TITLE
[Recipe] Better Fluxed Electrum and Flux Crystals

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#503]
Right now the recipes for fluxed electrum and the flux crystals are pretty lame. If I remember correctly you need the fluid transposer to make them, so I think that means they should be a chemical bath recipe?

You could just copy the recipes for enderium dust and the pulsating crystal.

**Comment by Xavion3** [comment]
Ender io alloy smelter cheats with fluxed electrum but yeah, normal recipe is two liquid redstone dust + electrum dust/diamond for fluxed electrum dust or flux gem. Fluxed electrum also needs pyrotheum to smelt normally, that requires magic to get in InfiTech though.

**Comment by Timeslice42** [comment]
Pyrotheum is required for anything over 2000 C (2273.15K), which an EBF can (and in fact does) handle, although GT says it's a 3000K recipe.
