### ISSUE TITLE
[3.2 DEV] Conflict in TC infusion enchantment

### ISSUE THREAD

**Issue by DerEchteLanger** [JasonMcRay/InfiTech-1.7#504]
The enchantment books "Stealth V" and "Translucency II" have the same required materials in their infusion, it will allways try to create the translucency one, even if you have the right essentia for stealth.

**Comment by Xavion3** [comment]
Hopefully fixed by https://github.com/JasonMcRay/InfiTech-1.7/commit/140ce5a6a8390b6ed08b56c194409914763b08dc
