### ISSUE TITLE
[Dev 3.2] Suggestion: Reduce the generation of Chisel-Blocks

### ISSUE THREAD

**Issue by DerEchteLanger** [JasonMcRay/InfiTech-1.7#506]
I think the generation of Chisel-Blocks (granite and others) is way to high. If you find an GT  ore-vein large areas of it are overwritten with chisel-blocks, replacing usefull ores with almost useless blocks. The config has values of 8 (marble has 7), maybe reduce that to something between 1-3. Except for some chisel recpies they are only usefull as a decorative block, and if you want to buildsomething from them there should still be enough in the world, you just have to look a few seconds more.

**Comment by Timeslice42** [comment]
This is why intelligent people just disable the chisel world gen :P
