### ISSUE TITLE
[DEV] Tool continualy breaks and unbreaks on Brittle Charcoal

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#508]
While harvesting Brittle Charcoal from the charcoal pit, each piece takes away a lot of durability, and then most of that durability is given back.

As the tool gets lower in durability, this causes the tool to go through its "broken tool animation" (complete with sound), and then the tool pops back into my inventory for each piece of charcoal harvested until the tool eventually breaks completely.

I cannot imagine this durability calculation and animation is by design, so I assume it is a bug?

**Comment by JasonMcRay** [comment]
Already noted:
https://github.com/Blood-Asp/GT5-Unofficial/issues/439
