### ISSUE TITLE
[Dev] still fatal error after disconnect+reconnect with new thaumcraftclusters.zs

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#510]
https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/thaumcraftclusters.zs
still getting fatal error when trying to reconnect after disconnecting. i put the thaumcraftclusters.zs into minecraft/scripts/ and it replaced an existing file with the same name there.

/mt research ALCHEMY
log in my singleplayer world where i did /tc research all...
[minetweaker.log.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/178415/minetweaker.log.txt)

i also get the error on groves infitech 2 dev server where i dont have all research, log for that in a few minutes...

**Comment by Xavion3** [comment]
As in you try to leave and enter a single player world and the error still occurs? Ignore the server for the moment, others have reported issues with the server specifically. So try reloading the world and the minetweaker.log from after the bug has occurred too preferably, should hopefully point out if it's the same bug and when it happens.

**Comment by ghoulsblade** [comment]
I leave singleplayer and connect to grove's dev server, that worked.
/mt research ALCHEMY : command not allowed for me on groves dev server.
I disconnect from server and try to connect again : "A fatal error has occured, this connetion is terminated"
No files within the whole minecraft directory have a changetime in the last few minutes after the error.
i try again: failed to connect to server: nullpointer exception.
i try again: "A fatal error has occured, this connetion is terminated"
i try again: "A fatal error has occured, this connetion is terminated"
i still dont see changed files in minecraft folder, so i rclick FTB launcher tray icon, show console, copy all, attached below, contains nullpointer exception stacktrace (2) 
The first fatal error was after leaving singleplayer and connecting to devserver the 2nd time at 18:58:08:
NullPointerException 
at modtweaker2.mods.thaumcraft.research.MoveResearch.undo(MoveResearch.java:72)
at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:88)
and another nullpointer twice right after in at modtweaker2.mods.thaumcraft.research.AddPrereq.undo(AddPrereq.java:56) ~[AddPrereq.class:?]
all 3 
[ghoul-infitech-dev-relog-error.zip](https://github.com/JasonMcRay/InfiTech-1.7/files/178433/ghoul-infitech-dev-relog-error.zip)
at [18:58:10]

**Comment by ghoulsblade** [comment]
i'll close the client and try again with just singleplayer and a new world

**Comment by ghoulsblade** [comment]
singleplayer seems to work.
started client, created singleplayer survival world with cheats=on, left (after getting some flint, making some tools, chopping some trees, starting looking for rubber, finding sugarcane...),
rejoined singleplayer world, left, rejoined singleplayer world.
no errors.

**Comment by ct-klein** [comment]
The public dev server had not been restarted after the patch was applied.  Server has been restarted now and the problem no longer happens.

**Comment by ghoulsblade** [comment]
solved since grove's server was restart :)
