### ISSUE TITLE
guide books

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#511]
The table with all possible maintenance problems is looking weird.
<a href="http://imgur.com/W2bN5eb"><img src="http://i.imgur.com/W2bN5eb.png" title="source: imgur.com" /></a>

The possible recipes for the BBF could be made a bit larger.
I think 6 recipes for an entire page would be better.
(Also you didn't include the charcoal recipes.)
<a href="http://imgur.com/ws3N5K8"><img src="http://i.imgur.com/ws3N5K8.png" title="source: imgur.com" /></a>

**Comment by Timeslice42** [comment]
Define "weird". The table looks like it has the right tools/problems to me.

**Comment by DarknessShadow** [comment]
The content of the table is correct but it should be readable no matter which gui scale you have.
Large:
<a href="http://imgur.com/vnv3RYV"><img src="http://i.imgur.com/vnv3RYV.png" title="source: imgur.com" /></a>
Normal:
<a href="http://imgur.com/4AXoV9X"><img src="http://i.imgur.com/4AXoV9X.png" title="source: imgur.com" /></a>
Small:
<a href="http://imgur.com/TJICYIW"><img src="http://i.imgur.com/TJICYIW.png" title="source: imgur.com" /></a>
You can read the rest of the text normally even on small gui.
<a href="http://imgur.com/Pv55bQG"><img src="http://i.imgur.com/Pv55bQG.png" title="source: imgur.com" /></a>
And is there any reason why half of it is left-aligned and the other half centered?

**Comment by Timeslice42** [comment]
I'm pretty sure that's an image, and not a table proper. It looks like enchiridion's image scaling doesn't handle text very well. @JasonMcRay would know more.

**Comment by JasonMcRay** [comment]
Yes that is an image, because Enchiridion doesnt have propper tables. I can try to just make the picture bigger, or as last resort can just write it as a text.

**Comment by DarknessShadow** [comment]
It would also be good to inlcude a tooltip so people know that the machine is not used up when crafting the books.

**Comment by JasonMcRay** [comment]
The tooltip is shown when looking at the recipe in NEI: Does not get consumed in the process

**Comment by DarknessShadow** [comment]
I'm not seeing it.
http://imgur.com/aALpeYb
http://imgur.com/lINfgjf

**Comment by JasonMcRay** [comment]
Oh the normal crafting recipes. Yes.i will add something to them: "Does not get consumed when used to craft a guide" or something like that
