### ISSUE TITLE
[3.2] Uncraftable IC2 drills brake recipes

### ISSUE THREAD

**Issue by AiwendilCiunio** [JasonMcRay/InfiTech-1.7#514]
It is required for BC Mining Well and Steve's Hardened Drill.
Likewise, Diamond Drill is required to make Galgadorian Drill.

**Comment by DarknessShadow** [comment]
And the ic2 miner and ic2 adv miner need a drill in the gui to work.

**Comment by JasonMcRay** [comment]
Already fixed: https://github.com/JasonMcRay/InfiTech-1.7/commit/2572876e112e3e88d40c0cd7db0dcf2f75624a86

**Comment by JasonMcRay** [comment]
And the miners: https://github.com/JasonMcRay/InfiTech-1.7/commit/c88afd29bc346d6bee959b9c4323cf035ca877a9
