### ISSUE TITLE
GRegtech Boilers won't accept charcoal from Logistics Pipes or BC Pipes

### ISSUE THREAD

**Issue by songtsanGambo** [JasonMcRay/InfiTech-1.7#515]
As I changed to 3.2 from 3.1.23 I find that my Logistics Pipes system that fed my 
Gregtech Small Coal Boilers and Gregtech High Pressure Boilers no longer worked.  Each Boiler had a chassis with an Active Supplier Module set to keep the boilers filled with 2 charcoal.  The LP-packages would route to the boilers but not enter and eventually got routed to the default destination.

Each Boiler's chassis also had an Extractor Module to pull the ash out.  This also does not work anymore. 

Manually adding the charcoal to the Boilers thru the GUI works fine.  

I Replaced a Boiler with a chest, the chest received charcoal from the Logistics Pipes system as it should.  

I also have a Railcraft low-pressure Boiler fed by the Logistics Pipes system - It continues to work correctly.  

I replaced the Logistics Pipes system with a standard buildcraft pipe loop pulled from a chest containing charcoal (and eventually returning there).   The Boilers would not accept the charcoal.

**Comment by Xavion3** [comment]
Not a bug, in GT 5.09 bronze age solar and coal boilers now require manual interaction, for coal it's that you can't automate item intput/output anymore.
