### ISSUE TITLE
recipe conflict

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#521]
The minecart and the stevescart standard hull have the same recipe.

**Comment by Timeslice42** [comment]
They shouldn't. The vanilla minecart should have a GT recipe. The vanilla recipe should be gone.

**Comment by Xavion3** [comment]
The vanilla minecart does have a GT recipe, it's just that when I changed the Steve's Carts hull recipes over to GT style I missed it makes them the same as the normal cart recipe.
