### ISSUE TITLE
Malisis trapdoor recipe collision

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#525]
You cannot make vanilla trap doors with any vanilla plank other than oak, as it makes a wood specific trapdoor from malisis instead. I don't see a config option so the recipes will have to be fixed manually. Maybe add the bibliocraft saw to the crafting recipe for the malisis trapdoors?

**Comment by Timeslice42** [comment]
Update: doors have the same issue.

**Comment by DarknessShadow** [comment]
I'm not seeing a problem with the doors. The vanilla one isnt used in any recipe and I think its good that you get a door that is matching with the type of wood.

**Comment by JasonMcRay** [comment]
It is minor issue, but still... nothing too tedious to fix. Malisis recipes will get a saw included in them, so you will be able to use any wood for Vanilla Doors and specific wood + saw for malisis versions

**Comment by JasonMcRay** [comment]
Fixed via PR #530
