### ISSUE TITLE
Bronze Age quest needs LV machine to complete

### ISSUE THREAD

**Issue by UbersawMed** [JasonMcRay/InfiTech-1.7#526]
So basically the Bronze Age quest "Better Steam Storage" requires making (among other stuff) 8 Iron Tank Valves, which require Iron Bars, which now require an Assembler to make (which is a LV machine), making the quest not completable (by standard means) on the Age it's placed on.

While a possible solution is that you're suposed to find 2 different villages with Blacksmiths and take the bars off the two buildings, that's not a viable solution on some servers as exploring consumes a lot of resources and is to be avoided as much as possible.

**Comment by Timeslice42** [comment]
You can't craft the iron bars with a wrench? That sounds like a bug to me.

**Comment by JasonMcRay** [comment]
Fixed in: 3e642d9ce3fa86db59d870040e809a865bc936ab (Workaround fix)
