### ISSUE TITLE
Cannot craft sticks with jungle wood planks.

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#527]
The planks still work in a lathe to get sticks, but the vanilla recipe is gone.

**Comment by Timeslice42** [comment]
Looks like this may just be the IC2 crafting bug.

**Comment by JasonMcRay** [comment]
Yes its the aparently unsolvable IC2 crafting bug with wooden planks, which is in IC2 since... quite a long time ago

**Comment by JasonMcRay** [comment]
The bottom of this is that each recipe that involves plankWood gets removed with the IC2 NEI Handler crash (which happens when looking for certain recipes).
Solution would be on our side to force add the recipes via MT, but there is just so much of them :(
