### ISSUE TITLE
Update to Gregtech 5.09.20

### ISSUE THREAD

**Issue by Native91** [JasonMcRay/InfiTech-1.7#531]
Are you gonna update to version 5.09.20? It looks like some big improvements are added to have less NEI clutter and also a ton of bugs are fixed.

Changelog here:
http://ftb.gamepedia.com/GregTech_5_Unofficial/Experimental_Changelog#5.09.20

**Comment by JasonMcRay** [comment]
Update will happen when I feel like its worth it and nothing will break. .20 is fairly big update, which needs to be tested more. I am following the mod updates, so there is no reason to remind me about them.

**Comment by Timeslice42** [comment]
On the other hand I'm going to update right now. Will alert if I find any issues, but I'm so early game I probably wouldn't see them in the first place.
