### ISSUE TITLE
Possible solution for 1.7.10 boat desync on servers

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/InfiTech-1.7#536]
In Minecraft 1.7.x, boats have always had a really bad sync problem for servers (see https://bugs.mojang.com/browse/MC-2931). The bug was apparently resolved in 1.8, but InfiTech2 players are left to suffer without this very important mode of transportation. Dramatic, I know... but I like boats :-) 

Anyway, I found a Forge mod called [Better Boat](http://minecraft.curseforge.com/projects/better-boat) that claimed to maintain better Client-Server sync. I tested this mod on my personal server running InfiTech 3.2.2, and I was able to navigate a very long river with many hairpin turns with only occasional minor rubberbanding, no desyncing, and without crashing my boat. Granted, the server was running on the same machine as the client, so I didn't have to deal with network latency and poor ping. That said... I have never been able to operate a boat like that on a 1.7.10 server...at full speed too!

Everything about the boat as an Item remains Vanilla. However, when the boat is placed in the water, the mod replaces the Vanilla boat Entity with a custom Better Boat Entity. Entering, navigating and exiting the boat all remain Vanilla, except that the boat maintains really good sync to the server in my limited testing.

The mod does change two more minor things, but I don't think these unbalance the game at all (but that is for you to decide). First, boats do not break into plank and sticks when hitting land or squid. Instead, squid receive damage from the impact and your boat bounces off course. If you hit land, the boat breaks and you get your boat back (I like this part very much).

For better Better Boat to work, another mod called [Bookshelf](http://minecraft.curseforge.com/projects/bookshelf) must also be installed. The versions I tested are:

BetterBoat-1.7.10-1.1.0.jar
Bookshelf-1.7.10-1.0.4.187.jar

If you would like to see how it performs under significant server load and poor ping before considering it for official addition, I'm sure I can arrange a test on the Official InfiTech2 Public Server. But I did not want to test there if you didn't like the idea from the start.

EDIT: Both mods need to be on the server and the client for it to work.

**Comment by Timeslice42** [comment]
Well, you're half right - boats have been bad for SSP and SMP since 1.3.2. That said, better entity tracking on boats would be fantastic. Bouncing off of squid is fine, but, if possible, we might have to disable the boat not being destroyed when it hits land, as that would devalue the IC2 rubber and carbon fiber boats. Or not.

**Comment by lafflam** [comment]
You raise a good point about the IC2 rubber and carbon fiber boats. However, this modpack may have already made the rubber boats obsolete by making rubber harder to get by adding sulfer to the recipe :-)

I checked the config folder on my test server. I was hoping to find a way to re-enable boat breaking while keeping the better client-server sync. Unfortunately there are no configs for Better Boat. And I should probably test to see how well the rubber and carbon fiber boats maintain sync with and without the Better Boat mod. I will post my results.

**Comment by JasonMcRay** [comment]
If there would be a config option to disable the boat not breaking, I am up for it to be added. Yes Rubber and Carbon Fiber boats are bit harder to get, but still if ppl wants to travel by boat, they will want to go for one of these to make sure they boat will just pop and not break.

**Comment by Timeslice42** [comment]
Also the electric boat, but even if boats didn't break, (while it has energy) it is faster than travelling by regular boat.

**Comment by JasonMcRay** [comment]
Seeing that the option for turning on/off the boat breaking is not comming in any time soon... Closing this suggestion.
