### ISSUE TITLE
Forestry Worktable / Water Bucket crash

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-1.7#537]
Shift-clicking the water-bucket-to-pams-fresh-water recipe crashes the game.  

Crash log: http://pastebin.com/h8qixKsq

Was able to reproduce successfully (2/2 times)  Only happens when shift-clicking; clicking for a single execution of the recipe does not seem to create problems.

**Comment by JasonMcRay** [comment]
Reported: https://github.com/ForestryMC/ForestryMC/issues/1121

**Comment by JasonMcRay** [comment]
@pyure Can you please test this again in latest pack version? Thank you

**Comment by zogarr** [comment]
I just ran into this today.  It is still a problem.
