### ISSUE TITLE
Can initiate locked quest "Balance of Power" but not complete it

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-1.7#539]
I can open the quest "Balance of Power" even though I have not completed what appears to be a prerequisite: "Alchemical Processing".

I have completed two task requirements for Balance of Power: A vinteum crystal and balanced shards.  I do not get buttons to complete the quest.  Presumably because Alchemical Processing is incomplete?

**Comment by pyure** [comment]
Can confirm that the problem was the incomplete prerequisite, but is it normal that I should be able to open a quest with an incomplete prereq?

**Comment by Xavion3** [comment]
Yeah for some reason you can often go into visible quests that are locked I find, I'll make sure to figure out why it's showing up as visible, think I might've set the visibility wrong.

**Comment by JasonMcRay** [comment]
Known issue: https://github.com/lorddusk/HQM/issues/145

**Comment by Xavion3** [comment]
I've been swapping things to reverse trigger as a replacement, makes them invisible until they're unlocked.

**Comment by JasonMcRay** [comment]
Unfortunately HQM is currently stopped from developing (LordDusk stopped the work on HQM). If anyone will pick on HQM that is uncertain.
