### ISSUE TITLE
3.2 fire resist potion 8minutes recipe missing

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#541]
its possible to make the normal 3minute fire resist in LV brewery, but there is no recipe for the 8minute variant, usually 3minute + redstone = 8 minute

**Comment by Timeslice42** [comment]
This is true for all potions. The brewery was never fully implemented for all potion brewing possibilities.

IMO you're better off just putting seed oil (or creosote) and redstone in there to get lubricant quickly.
I'm pretty sure that @Blood-Asp doesn't plan to finish this, but I'll let him speak for himself.

**Comment by JasonMcRay** [comment]
I am re-enabling vanilla brewing stand (which I wanted to do quite long time ago before 3.2 was released, but forgot).

In future I might add the recipes to brewery via MT, but no promisses.

**Comment by JasonMcRay** [comment]
As its not worth the time spent on MT the recipes for brewery... closing this as minor. If I will have time at some point I might make a PR directly to GT to implement all the brewings.
