### ISSUE TITLE
Hand utility items overhaul

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#547]
As a future task I'd like to overhaul all of the hand utility items from the various mods to use item casings rather than ingots (as opposed to changing them to plates). We should list the items that we think qualify, preferrably in this first post. I'll add a few now.
### Open Blocks
- [x] Slimalyzer
### Steve's Carts 2
- [x] Entity Analyzer
### Ender I/O
- [x] Conduit Probe
- [x] Coordinate Selector - would need electric steel item casings
### Forestry
- [x] Beealyzer
- [x] Treealyzer
- [x] Flutterlyzer
### Industrial Craft 2
- [x] Weeding Trowel

**Comment by JasonMcRay** [comment]
Adding to the list:
Weeding Trowel
