### ISSUE TITLE
Adding Centrifuge methane recipes for PHC meats

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#549]
I tried doing this myself, but the recipe doesn't show up, and the minetweaker log shows the success message. These are basically the same as the vanilla meats. Since the cooked versions of these meats aren't actually obtainable I didn't bother to add them.

```
var rabbit	 = <harvestcraft:rabbitrawItem>;
var venison = <harvestcraft:venisonrawItem>;

mods.gregtech.Centrifuge.addRecipe([null], <liquid:methane> * 96, venison, null, null, [0], 380, 1920);
mods.gregtech.Centrifuge.addRecipe([null], <liquid:methane> * 96, rabbit, null, null, [0], 380, 1920);
```

**Comment by JasonMcRay** [comment]
Well... you made it wrong, thats why it doesnt show up:
```
OutputArray, InputFluid, InputStack, InputCell, OutputFluid, OutputArrayChances, Time in Ticks, EnergyUsage
```
You put output fluid into input fluid. I am fixing it and also adding cooking recipes, because why not.

**Comment by Timeslice42** [comment]
I tried it like the wiki showed and I kept getting mismatched function signature errors. So I opened up the code and put it in the order that the addRecipe java method had it in, and I no longer got errors.
