### ISSUE TITLE
warded glass

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#553]
The recipe is just insane.
It needs 1 adv circuit for 1 warded glass.

**Comment by Xavion3** [comment]
Yeah sorry, that's my bad, it's not meant to be just the 1 warded glass.

**Comment by Timeslice42** [comment]
Why does this take circuits at all?

**Comment by Xavion3** [comment]
Easiest and most thematic way to make wither proof blocks not early steam, good circuits replaced zombie brains as they work out who should be able to break blocks? I dunno what logic was used to make warded glass or pressure plates require brains in the first place but it can apply to circuits as well.
