### ISSUE TITLE
project-red replacement for deployer ?

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#563]
is there a project-red replacement for deployer ?
it right-clicks stuff and i've used a bunch for thaumcraft all over the place.

**Comment by JasonMcRay** [comment]
Stripes pipes, golems, OC Robots, PC drones, PR version is disabled.

**Comment by DarknessShadow** [comment]
The bluepower version was enabled but the projectred version gets disabled?
That doesnt make sense.

**Comment by Timeslice42** [comment]
Unless the striped pipes recipe has been changed, I don't see how they're any less OP than the deployer.

**Comment by JasonMcRay** [comment]
Stripes pipes I have changed to require GT stripes block and a gear (if I remember correctly).

BP Version was enabled, but shouldn't be. Same as with OpenBlocks block placer and breaker were disabled.

I guess for Thaumcraft it would be to infusion "autocrafting"? But you can do that simply with just regular pipes as the Pedestal counts as inventory container

**Comment by DarknessShadow** [comment]
He used it to right click the alembics and fill phials with essentia.

**Comment by ghoulsblade** [comment]
Yeah, essentia transfer using phial, filling and emptying. Golems tend to fall off into the void on multiplayer servers when chunks are loaded late, and they cause lag if used in great numbers, so something that rightclicks is needed to make alchemy scalable to mass production.
Buildcraft pipes tend to spill in a number of situations and timing is also a problem, plus the required setup is a lot bigger and uglier. So unless the dynamism stuck-on-unload bug is fixed i'll prolly go use opencomputers robots. I doubt the server will like having several dozens of them around.
If theres a project red alternative maybe make it craftable with titanium, i wouldnt mind a tech gate, but outright disabling it makes things ugly, and i dont see the point if there's other things doing the same thing just less elegantly.

**Comment by DarknessShadow** [comment]
I don't know about projectred but tubestuff has a deployer https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/immibis.cfg#L43

**Comment by Timeslice42** [comment]
Or better yet just use thaumic energistics. It has "large-scale thaumcrafting" right on the label.

**Comment by Dlur100** [comment]
Thaumic energistics is the best solution for this problem, but I'm kind of a believer in that there shouldn't just be 1 way to do something.  Some folks like magic, others don't.  Some folks like AE2, others don't.  It's one thing to force everyone down a GT path since this is a GT centric modpack, but beyond GT there really ought to be options.

(ghoulsblade is one of the people that doesn't really care for AE2 :P  )

**Comment by JasonMcRay** [comment]
I already said that there are number of different options to make rightclicking outomated. Gonna say it again, Stripes Pipes, OC Drones, PC Drones, Golems

**Comment by Timeslice42** [comment]
It's *Stripe* Pipe, not Striped, and certainly not Stripes.
