### ISSUE TITLE
[QUEST] Water from Skyes

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#564]
Apparently its not set as consume task for the water collection.

**Comment by Timeslice42** [comment]
I swear I changed it to a consume task like three times... also,  did I really call it "Water from Skyes"? Could you rename it to "Water from Skies" or even better, "Water from the Sky"?

**Comment by Timeslice42** [comment]
Thanks for cleaning up my mess :)

**Comment by JasonMcRay** [comment]
Reopened because for some reason its looking for actual Water ITEM, instead of FLUID.

**Comment by JasonMcRay** [comment]
Fixed. lets hope finally.

**Comment by Timeslice42** [comment]
I swear I clicked on the fluid and not the item... what did you do differently? Did you use oredict for the item?

**Comment by JasonMcRay** [comment]
To ensure I am adding really fluid and not an item is to spawn in a cell or bucket of said liquid into my inventory. Then if, and ONLY IF, the quest is set to consume it will show not only the item on the left side but alsso the fluidstack.

You can easily check if you are doing it properly because for fluidstack you will not get offered with oredict/fuzzy/nbt

**Comment by Timeslice42** [comment]
Thanks, that's a great tip.
