### ISSUE TITLE
ic2 teleporter not usable with mfe+mfsu disabled

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#565]
ic2 teleporter needs a nearby energy buffer for instant large amount access, MFE + MFSU are disabled, so is the ic2 teleporter useless ?

**Comment by Timeslice42** [comment]
Probably. Last time I checked (which was probably in MC 1.4.7) the teleporter was hardcoded to look for and MFE or MFSU.

In the meantime travel anchors can be used as a poor man's substitue.

**Comment by Timeslice42** [comment]
Theoretically a superconductor cable should work... or the equivalent of a supercondensator.

**Comment by JasonMcRay** [comment]
You can't put GT Battery Buffer right next to it?

**Comment by Timeslice42** [comment]
You can put it there, but a battery buffer can't transfer a million EU at once.

**Comment by DarknessShadow** [comment]
I put a EV battery buffer with 9 charged lapotron crystals next to it and it did not work for a distance of 3 blocks.

**Comment by Xavion3** [comment]
There's a magical solution too.

**Comment by DarknessShadow** [comment]
He wanted to prevent lossless energy transport with batteries.

**Comment by yznpku** [comment]
The only OP eu storage is CESU (which you can craft pre-LV). The others are just as expensive as GT counterparts.

**Comment by ghoulsblade** [comment]
So its not about storage, but about transport of energy in energy crystals and lapos. MFE and MFSU allow the items to be piped in and out, which is not allowed in greg battery buffers except with single-use batteries.
Hrrrrmmmm. Isnt there a way to block pipes connecting to them or prevent items entering the input slot somehow ?

**Comment by DarknessShadow** [comment]
CESU cannot be crafted so early it need adv re batteries which need annealed copper

**Comment by ghoulsblade** [comment]
Ic2 chargepads work i hear -> closed

**Comment by Timeslice42** [comment]
@DarknessShadow An EV battery buffer can't transfer 1M EU at once. *If* a GT buffer can work (and I don't think it can), it would be either a UV or MAX tier battery buffer.

**Comment by DarknessShadow** [comment]
@Timeslice42 I does not work I tested it (still with the ev battery buffer) and it could not teleport 1 item.
I did the same thing with a batbox and it worked and only used 30 EU (1 item over 3 blocks).

**Comment by Timeslice42** [comment]
That settles it then. It's a good thing we have chargepads. I thought that was a seperate mod, did they get annexed into IC2?

**Comment by DarknessShadow** [comment]
It was a seperate mod but not anymore.
