### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#567]
I opened a component bag and my game crashed.
http://pastebin.com/TdEquG48
http://pastebin.com/dwSESGyD

**Comment by JasonMcRay** [comment]
Component bag of what tier?

**Comment by DarknessShadow** [comment]
I don't know it crashes now every time I load the world.
I also got mv electric pistons out of the same bag if that helps.

**Comment by JasonMcRay** [comment]
What quest was it. That might help.

2016-03-31 10:21 GMT+02:00 DarknessShadow <notifications@github.com>:

**Comment by DarknessShadow** [comment]
I can't tell you I was going through tons of quests.

**Comment by DarknessShadow** [comment]
It should have been the LV quests

**Comment by DarknessShadow** [comment]
Btw I found a serious bug with the bluepower deployer they can open the bag but they arent used up.

**Comment by Timeslice42** [comment]
The BP deployer is disabled... test it with the PR deployer.

**Comment by DarknessShadow** [comment]
Definitely component bag tier 2 that causes the crash
