### ISSUE TITLE
WAILA

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#570]
Its kinda strange that waila is sometimes showing the fluid amount 3 times in the tooltip.
<a href="http://imgur.com/QmqxMFE"><img src="http://i.imgur.com/QmqxMFE.png" title="source: imgur.com" /></a>
It shows it even 4 times.
<a href="http://imgur.com/IiLfhpg"><img src="http://i.imgur.com/IiLfhpg.png" title="source: imgur.com" /></a>

**Comment by Timeslice42** [comment]
Yeah, this is on my list of things to investigate, but I don't image I'll make much progreess very quickly. If you want to tinker around, any help would be appreciated.

**Comment by JasonMcRay** [comment]
Are anyone able to pinpoint when this started to happen? Or is it here for quite some time?

**Comment by Timeslice42** [comment]
I've seen doubles for as long as I can remember in 3.x. I've never seen triple or quad.

**Comment by Timeslice42** [comment]
What did you do for this issue?

**Comment by JasonMcRay** [comment]
Disabled IFluidHandler in Waila plugins config
