### ISSUE TITLE
Mod Suggestion: Zombie Awareness and OpenModularTurrets/GunCustomization

### ISSUE THREAD

**Issue by nekoexmachina** [JasonMcRay/InfiTech-1.7#575]
The idea behind this is to make a game more harsh from a PvE view. Zombie Awareness makes zombies aware of players, especially if a player in question is bleeding; makes them roam in hoards; makes them want to kill you. Fun!
OpenModularTurrets is a way to protect one's base when one has some technologies for that.

ZA: http://minecraft.curseforge.com/projects/zombie-awareness/
Needs lib  http://minecraft.curseforge.com/projects/coroutil
OMT: http://minecraft.curseforge.com/projects/openmodularturrets

**Comment by JasonMcRay** [comment]
InfiTech is not about survival or defending base. I dont see reason to add these mods in.

**Comment by nekoexmachina** [comment]
OMT only has its reason if ZA is in the pack, yeps. 

Infitech is about overcoming different set of difficulties, which might've included the pve situations. If not, that's not, no big deal. :-)

**Comment by JasonMcRay** [comment]
I am keeping the survival elements mostly out (except HO of course), because I intend to make a adventure/survival modpack in the future. So if I would do this in InfiTech, than in the other modpack it will feel like its exactly the same, but without the tech mods.

**Comment by yznpku** [comment]
I don't think mobs fit in this factory building pack.... I'm a peaceful mode player lol.
