### ISSUE TITLE
p2p fluid void bug

### ISSUE THREAD

**Issue by Nex4rius** [JasonMcRay/InfiTech-1.7#576]
I'm not sure if this is a ae2, enderio or ~~gregtech~~ bug ... 
~~https://www.youtube.com/watch?v=rXwPFKkrJ_8&feature=youtu.be~~

Happens when I do this:
any fluid conduit -> p2p -> gas turbine
any fluid conduit -> p2p -> fluid regulator (ic2)

Does not happen:
any fluid conduit -> p2p -> bc tank
gt fluid pipe -> p2p -> fluid regulator
gt fluid pipe -> p22 -> gas turbine

https://www.youtube.com/watch?v=5sf6j-GUdwA&feature=youtu.be

workaround:
use one gt pipe between fluid conduit and p2p

**Comment by JasonMcRay** [comment]
it might be any of the mods really.
I reposted it to both parties:
eIO: https://github.com/SleepyTrousers/EnderIO/issues/3255
AE2: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2228

**Comment by JasonMcRay** [comment]
Did little bit of analyzation (can be seen in the eIO issue). The workaround actually does not work as well. Looks like P2P tunnels accepts anything, but void what they can't use.

**Comment by DarknessShadow** [comment]
I tested it again with gregtech pipes and no liquid was lost.

https://www.youtube.com/watch?v=KjoS5H2bQ_o

**Comment by JasonMcRay** [comment]
Hmm.. Probably because GT is sending liquids in diferent way... But long story short, eIO has nothing to do with this issue, since if you use Buildcraft pipes it also voids liquid.
