### ISSUE TITLE
Several GT gasses have a temperature of 0 Kelvin

### ISSUE THREAD

**Issue by UbersawMed** [JasonMcRay/InfiTech-1.7#577]
So apparently several Gregtech gasses like Oxigen and Nitrogen are listed as being 0 Kelvin, which apart from not making any phisical sense make transporting them using wooden pipes instantly kill you when close enough, and hurt you for 4 hearts when touching a bronze pipe conducting them.

Considering Liquid Nitrogen is listed at 70K, this is probably an oversight.

(Also, bye bye 0 death counter :P)

**Comment by JasonMcRay** [comment]
It is an issue with GC loading these Gases and overwriting the GT values. I raised an issue on GC tracker: https://github.com/micdoodle8/Galacticraft/issues/2167

**Comment by JasonMcRay** [comment]
Fixed in latest GC
