### ISSUE TITLE
[Quest] Ore Annoyance

### ISSUE THREAD

**Issue by Polyblock** [JasonMcRay/InfiTech-1.7#578]
In the Ore Annoyance's second task the required ore for coal, tin and Iron cycle between all the different version (stone, both granit, netherrack...) but the Chalcopyrite seem to only accept the stone variant. Is it a feature or a bug?

Running last version on official server

**Comment by Xavion3** [comment]
Coal does it too? That's odd, otherwise I'd have suspected it's a side effect of adding the oredict entries for clusters which put all the different kinds of iron/copper/tin/etc into a single special oredict entry so you can use any for clusters, but coal doesn't have a cluster.

**Comment by Timeslice42** [comment]
That's because chalcopyrite isn't a universal ore. It would have to be copper to get the same effect. Personally I'd rather it stayed chalco, but I don't think it's a huge deal either way.

**Comment by Xavion3** [comment]
I mean, we should at least be capable of creating an oredict so if you stumble across a vein in granite you can just grab a granite version of the ore.

**Comment by Timeslice42** [comment]
That doesn't sound right... maybe he did miss the oredict tag on that item.

**Comment by Xavion3** [comment]
All GT ore variants are oredicted separately, so you'd have something like oreChalcopyrite and oreBlackGraniteChalcopyrite and oreRedGraniteChalcopyrite, for clusters I made stuff like listAllOreIron to get around the issue but if that wasn't done and you went by poedict you'd just get normal variants as different stones have different entries.

**Comment by JasonMcRay** [comment]
I think the same ores within different types should at least be oredicted in the list dictionary. Maybe @Blood-Asp could do it natively, if it will not break anything
