### ISSUE TITLE
etching acid

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#580]
I think you made that way too expensive and it doesn't really fit anymore.
It used to be that 1 bucket of etching acid was needed and thats it.
Now the recipe was moved to the mixer and its only giving 50mb etching acid.
You have to do that recipe twice and then you only have a 70% chance to get an unassembled pcb.

You made that pneumaticraft PCB in lots of recipe especially in opencomputers and its strange that you now need a good spider, zombie and creeper farm to make a computer or other technical blocks.

**A 70% for a unassembled PCB needs 2 spider eyes, 2 rotten flesh, 2 gunpowder and 2 green plastic.**

**Comment by JasonMcRay** [comment]
You have 3 options on how to make the PCB
1) Slowest, but can be done forever: 1.000mB of Etching Acid in a pool, through the PCB in
 - You need 20 of each for infinite PCBs
2) Faster, but consumes the Acid: 100mB of Etching Acid in the Chemical Bath, but since the bath is more intense, it has a chance of destroying the PCB
- You need 2 of each per PCB
3) Fastest, no Acid consumption: Assembly Line.

**Comment by Timeslice42** [comment]
Honestly, we should ditch the hackneyed vanilla recipe for the etching acid, and just use proper nitric acid diluted to 25-50% as the recipe for etching acid. This is a real etching solution for copper. There are several other etching solutions available, but none that GT already has a recipe for.

**Comment by Timeslice42** [comment]
So 4000mb of fluid nitric acid plus a water cell in a mixer would get you 5000mb of etching acid (and an empty cell).

**Comment by Timeslice42** [comment]
In theory we could also a tanzanite (purple) lens in a laser engraver to make the developed pcb. Does the laser support percentage chance output? Even if not, tanzanite isn't super-easy to find.

**Comment by JasonMcRay** [comment]
Problem with developing the PCB in the laser engraver is that it "doesn't know" the blueprint. So it would either made no sense with the lens, or it would have the blueprint instead of the lens, which also willnot make any sense, because it is not "UV-like".

**Comment by Timeslice42** [comment]
That's what the purple lens is for - bombarding it with intense amounts of UV light. It's just a thought anyways.

**Comment by JasonMcRay** [comment]
True, but it does not know in what pattern to bombard it in. It will miss the blueprint.

**Comment by Timeslice42** [comment]
It's not making a blueprint. The pattern is "bombard all parts equally.

**Comment by JasonMcRay** [comment]
But it needs the blueprint to know in what pattern to bombard the empty PCB. Same as the UV Light box, has a blueprint in it, to bombard the empty pcb

**Comment by Timeslice42** [comment]
Ah, see I didn't know that.

**Comment by DarknessShadow** [comment]
We could make it like the ae2 processors with the pattern in froming press.

**Comment by JasonMcRay** [comment]
Nah... I am keeping the current UV Box developing, But will change the etching acid recipe
