### ISSUE TITLE
osmium bee

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#582]
Osmium bees were not nerfed like the other.
They give osmium nuggets instead of the combs that need uumatter or chemical reactor + ore.

**Comment by JasonMcRay** [comment]
Cant modify bees. Osmium is not our custom bee, it comes from Magic Bees. Since the bee is fairly easy to get... i submitted request for adding a option to disable specific bees. Then we could make our own osmium bee, which will not be so powerfull.

**Comment by JasonMcRay** [comment]
Part 1 - Removal: https://github.com/JasonMcRay/InfiTech-1.7/commit/74a2bec37b15966bfe90335ffd71f680a620d5e8

Part 2 - Adding back: Comming Soon(tm)

**Comment by DerEchteLanger** [comment]
The bees are still obtainable and working, somthing went wrong with them i guess...

**Comment by JasonMcRay** [comment]
Dang.... Got reverted from the fix

**Comment by JasonMcRay** [comment]
Blacklisted: 1aba730e775e5a1909a0fdb094d3b348b2524421
