### ISSUE TITLE
containment box: quad uranium fuel rod doesnt fit in

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#583]

**Comment by JasonMcRay** [comment]
Only depleted fuels can be currently put in the box. Also you can't put GT rods in it. Raised an issue on IC2 tracker: http://bt.industrial-craft.net/view.php?id=1846

Also @Blood-Asp is there a way to let GT fuel rods (Thorium) to be able to be put in the containment box?

**Comment by JasonMcRay** [comment]
Closing as minor
