### ISSUE TITLE
Smelting Stone in furnace makes Blue Power Stone Tile instead of Project Red Circuit Plate

### ISSUE THREAD

**Issue by Daur99** [JasonMcRay/InfiTech-1.7#584]
Smelting Stone in furnace makes Blue Power's Stone Tile instead of Project Red's Circuit Plate x2. Has this been reported already? Can't make hardly anything in Project Red without this working.

**Comment by JasonMcRay** [comment]
In the end of bluepower.zs file please add following lines for a workaround:

`furnace.remove(<bluepower:stone_tile>);
recipes.addShapeless(<ProjRed|Core:projectred.core.part>, [<bluepower:stone_tile>]);`

It will disable making of the BP tiles and also will allow you to convert BP Tiles to PRTiles.
