### ISSUE TITLE
Assorted Thaumcraft Changes

### ISSUE THREAD

**Issue by Xavion3** [JasonMcRay/InfiTech-1.7#585]
- [x] Decrease warp on researches.
- [x] Add calcite + iron cluster recipe
- [x] Add charcoal recipe back in
- [x] Fix primordial naquadah creation
- [x] Review amethyst lens for telekinesis foci
- [x] Remove U-235 purification
- [x] Remove IBF cluster tripling recipes form NEI
- [x] Disable fiery steel dust as fuel

Just making this to try and keep track.

**Comment by Dlur100** [comment]
All of these changes look good to me.  Especially glad charcoal creation is coming back.

An update on amethyst lens.  After about 3 weeks of mining across 5+ people we've found 1 small amethyst ore.  I think amethyst was no big deal before (3.1.x ) when blue power amethyst ore generated, but now it's sort of off.  How about a sapphire lens instead?  Not the perfect color, but reasonably close and keeps with the lens theme.

**Comment by Xavion3** [comment]
Thinking I might go red garnet, once you've hit late MV it becomes incredibly easy to get as it's a byproduct of several different ores from a few different veins and even before that it spawns as a small ore. The question is how common is the small ore? A quick test in creative indicates at least you very reliably get red garnet, and even flawless or exquisite is relatively common.

**Comment by Dlur100** [comment]
In our experience red garnet is not an issue as well.

**Comment by JasonMcRay** [comment]
@Xavion3 Fiery Steel dust as fuel. I suppose you mean the Magical Thingie Fuel to get EU. Only Dust or also the Cell?

**Comment by Timeslice42** [comment]
If by cell, you mean the fiery blood cell, that one is much trickier to get and we decided that it was fine as a fuel source.

**Comment by Xavion3** [comment]
Yeah the fiery blood cell is fine, considering at least just running the two shards needed per cell into balanced shards gives you 70% of the power for a fraction of the cost anyway it's really not unusually good.

**Comment by JasonMcRay** [comment]
Well in the config i see dustFierySteel and cellFierySteel. there is nothing about fieryBlood anywhere
