### ISSUE TITLE
What? Bees?

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#586]
- [x] Modify bee requirements to require block of resource they are producing (to be inline with IC2 crops)
- [x] Add special catalyst items in preparation of DOB bee
- [x] Add custom block required for DOB bee to work
- [x] Bring back FT Centrifuge to make DOB Combs actually possible to use
- [x] Change the FT Centrifuge recipe and if possible make it into machine that ONLY works on DOB Combs (texture and rename would be nice)

**Comment by Xavion3** [comment]
The original suggested catalysts, taken from all the resources that the DOB bee produces.

Suggested catalysts
Magic: All 6 primal shards, balanced shard, thaumium ingot
Fuel: Lignite Dust, Coal Dust, Coal, Oil Drop, Uranium-235 ingot, Naquadah ingot, Carbon Dust
Natural: Plant Ball, Sticky Resin, Stone
Alloy: Red Alloy ingot, energetic alloy ingot, vibrant alloy ingot, steel
Crystal: Certus Quartz, Fluix Crystal, Ruby, Blue Sapphire, Green Sapphire, Diamond, Olivine, Emerald, Lapis Lazuli
Lesser Metal: Copper, Tin, Lead, Iron, nickel, zinc
Precious Metal: Silver, Gold, Chrome, Platinum, Iridium
Greater Metal: Aluminium, Manganese, Titanium, Tungsten, Osmium
Redstone is unplaced, unsure which category to put it in.

**Comment by Timeslice42** [comment]
I say put it in fuel. Both EE2 (which we don't have) and IC2 (which we do have) consider it a fuel. In vanilla IC2 you can even power IC2 machines by putting redstone in the battery slot.

**Comment by Xavion3** [comment]
There's only 7 items in fuel, you can fit another in even with normal crafting. Both coal and coal dust are drops though, maybe swap it to lignite, coal, and coal coke or a coal block instead of the normal coal?

**Comment by Xavion3** [comment]
If we're making bees require resource blocks to breed, enable them in gendustry so they require those even if using the mutatron?

**Comment by Timeslice42** [comment]
Only if the mutatron has some sort of UI element that tells you when you're missing the base block.

**Comment by Xavion3** [comment]
Tested with the help of Pyure, NEI seems to display any breeding requirements on the mutatron page as special requirements only if the mutatron is set to require them. So no UI element while looking at the machine but it'd show up in NEI.

**Comment by JasonMcRay** [comment]
Well.. will at least make the bees require blocks as a flower. Also the final step will be Dragon Essence Infusion... at least it will make players to look at HEE

**Comment by JasonMcRay** [comment]
Ok little thinking about the recipe styles:
Magic - Infusion into Thaumium
Fuel - Infusion into Redstone Block
Natural - ???
Alloy - Alloy smelter (Red Alloy + Energetic Alloy => Energized Red Alloy; Vibrant Alloy + Steel => Vibrant Steel Alloy; Energized Red Alloy + Vibrant Steel Alloy => Catalyst)
Crystal - If possible crystal growing aka AE2 throw into pool of water; if not... ???
Lesser Metal - Dusts -> Mixer
Precious Metal - Would like ChR. 3 inputs total, so Silver+Gold = Electrum (1 input), are there any alloys with Chrome, Platinum?(2nd input) Iridium (3rd input)
Greater Metal: ???
