### ISSUE TITLE
mass fabricator needs a little more than 4 amps..

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#590]
4 amps hv -> mv transformer -> mass fabricator with battery in it, battery drains slowly.
No cable in between, massfab directly at transformer, no other machines connected, so loss minimized as much as possible.
Maybe due to transformer not being lossless and 32eu/t x 4 amps uu recipe ?
Please set the recipe to 30eu/t if possible, the difficulty should be in producing the required amount of power, not in running an extra tiny cables because it doesnt add up even if you optimize loss as much as possible.

**Comment by JasonMcRay** [comment]
I am not touching that
Cross-Reported: https://github.com/Blood-Asp/GT5-Unofficial/issues/484

**Comment by Timeslice42** [comment]
Even with a battery buffer attached directly to the machine there is going to be loss. There's no way to completely avoid loss.
