### ISSUE TITLE
Duplicating bugs

### ISSUE THREAD

**Issue by SkyraSK** [JasonMcRay/InfiTech-1.7#599]
I found 2 bugs .
First is iron round gives 6 metalum and can be easily used for infinite iron source.
Second one is about production table placed next to x.a.c.t crafting table, if you have materials in production table and you craft something in x.a.c.t one resources are not used and you can still get items crafted.

Edit: sorry it isn't production table, it is Worktable from Forestery

**Comment by Timeslice42** [comment]
With @UniversaLP MIA it's feeling more and more like XACT isn't worth all the issues. I had a crash the other day while crafting with my XACT table where it tried to pull the furnaces out of the upgrade slots from the adjacent SW table for crafting.

**Comment by Timeslice42** [comment]
Can you fix this for forestry worktables too?
