### ISSUE TITLE
Singe-Use Batteries

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#605]
There are currently three issues with the IC2 single-use batteries; two which we can fix, but one which @Blood-Asp would have to fix.

1. They are an early game power source, yet take a copper cable to make (due to historical reasons). This should be changed to a tin cable.
2. They provide 1200 EU, and yet take 4800 EU worth of materials to make. In an IC2 machine one redstone will provide 800 EU, and in a generator a (non-hydrated) pile of coal dust will provide 4000 EU. The recipe should output at least 4 items, preferrably 6 (to compensate for the material lost via the tin cable), rather than just one.
3. Currently the IC2 single-use batteries don't work in the GT machines. This would obviously have to be a change to GT code.

**Comment by JasonMcRay** [comment]
1) Done
2) Done
3) Up to @Blood-Asp make sure to let him know
