### ISSUE TITLE
blue alloy (gt) should use electrotine (PR) instead of nikolite

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#606]
blue alloy (gt) recipe in alloysmelter currently uses nikolite, which is an unobtainable ore.
I think it should use electrotine (Project Red) instead.
It is useful for HV cables and one of the gregtech thaumcraft aspects.

**Comment by JasonMcRay** [comment]
Added f829abe80ddb4507009fe64390dbe6b5140fa631
