### ISSUE TITLE
compressed iron

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#615]
Compressed iron cannot be made with:

1. ITNT
2. Tiny TNT
3. overloading of a gregtech machine

<sub>but it works with (aka workaround):
1. Alumentum
2. Unstable Ingot crafting fail
3. using a bed in the nether
4. creeper
5. tnt
6. crashing a rocket
</sub>

**Comment by JasonMcRay** [comment]
Since mod devs can't use forge events for explosions it will not work with few modded explosives. I reported it a while ago, and it doesnt seem that they care... Closing this since there is still number of different ways.

**Comment by JasonMcRay** [comment]
http://bt.industrial-craft.net/view.php?id=1820
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/932
