### ISSUE TITLE
Mana beans do not show any aspects when scanned by Thaumometer

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#619]
None of the mana beans show any aspects when scanned, yet we all know they contain aspects :)

**Comment by Xavion3** [comment]
I could try fixing this but I'd give it solid odds I'd instead overwrite all mana beans to having the same aspects.

So actually this sounds great, will try. I don't mind if mana beans are nerfed into oblivion.

**Comment by DarknessShadow** [comment]
I don't think we can fix it because when we do this:
>Aspects.set(<<Thaumcraft:ItemManaBean>>, "aer 1");

This happens:
<a href="http://imgur.com/mCUgkha.png"><img src="http://i.imgur.com/mCUgkha.png" title="source: imgur.com" /></a>

Btw the crystallized essence has the same problem.

**Comment by Xavion3** [comment]
So if it adds when setting obviously we just have to cheat. Set it to 0 and it'll add 0 of that aspect, shows up when scanning but no number and no increased yield from an alchemical furnace.

**Comment by JasonMcRay** [comment]
There is not much we can do. If we try to fix it with MT then it will cause unwanted results (https://github.com/JasonMcRay/InfiTech-1.7/pull/625)

Closing, if anyone has idea how to fix that, feel free to make PR. Otherwise mana beans will stay unscannable.
