### ISSUE TITLE
Reminder: Charcoal alchemical transmutation did not get re-enabled in 3.2.4

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#620]
Change log says it was re-enabled, but it's not.  Mentioned to Xavion on discord, but thought I'd put this here as a reminder :)

**Comment by JasonMcRay** [comment]
Already fixed and staged for this weekends patch: https://github.com/JasonMcRay/InfiTech-1.7/commit/a422065a6a0ab5f5b8403d3d37075d94a85905ad
