### ISSUE TITLE
Stargate and Telepad

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#621]
A stargate needs 875.000 EU for a connection to another dimension with same coords. That is only for opening the connection which doesn't include energy cost to maintain the connection so you can actually go through it.
A telepad needs 28.672 EU for the same teleport.

A stargate needs lots of naquadah which can only be found in the asteroid dimension. (naquadah needs MV cupronickel ebf + vacuum freezer)
A telepad's most expensive material are the dark steel ingots which are only steel + silicon + obsidian in a MV kanthal coil ebf.

Those are HUGE differences for two ultra long range, interdimensional teleportation devices.

**Comment by JasonMcRay** [comment]
Are you aware that if I will bring the Telepad power cost closer to the SG the charge up of the pad will go from 5s to 2 minutes 30 seconds?

**Comment by DarknessShadow** [comment]
Its better to wait 2min than interdimensional teleport for free. (28k eu is free)

**Comment by Dlur100** [comment]
Just change the telepad crafting recipe to require some Open Computers CPUs or something.  That'd discourage me from ever making them :P

**Comment by Xavion3** [comment]
Could modify it to be more similar to the stargate crafting recipe, swap some of the dark steel for naquadah alloy and throw in an EV emitter or field generator.

**Comment by JasonMcRay** [comment]
Will be slightly cheaper than Stargates. But will change the recipe for them slightly. Also the power cost has been raised for both x-dim and same-dim teleporting. Do not that range doesnt matter with Telepads in x-dimensional transfer.

Telepads will be the one to use for teleport in same dimension. Using SGates for same dimension is stupid and not really efficient idea.
