### ISSUE TITLE
stacking issue with empty canisters (galacticraft)

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#627]
I heard of a possible stacking issue with empty canisters from galacticraft,
either inside ME system or a greg machine with dual input used build sth from them.

**Comment by JasonMcRay** [comment]
And what exactly is the problem? They stack, but shouldn't, or the dont stack but they should? They dupe when stacked? I am not a mind reader so please.... more info

**Comment by ghoulsblade** [comment]
i think they were extracted from ME as stack but shouldnt stack, and the machine consumed the whole stack instead of only 1. But only what i heard in chat, so 2nd hand report. Would be best if someone could try it and check if there are obvious problems.

**Comment by JasonMcRay** [comment]
Well i am unable to recreate this in AE System. 2nd hand reports without steps to reporoduce are useless.
