### ISSUE TITLE
galacticraft asteroids dimension landing stuck

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#628]
One courageous astronaut already went to the asteroids dimension on Grove's server,
on arriving there he had encountered some problems:
he was not in a lander, and the world seemed frozen, mobs didnt move and he couldnt place blocks, oxygen wasnt consumed from his tanks either.
He relogged, and had the same problem again.
He relogged again a few minutes later and the problem was solved, he got lander and everything worked normally.

**Comment by JasonMcRay** [comment]
Can you reproduce the problem? If not it will be considered as lag issue, with which I cant do anything

**Comment by ghoulsblade** [comment]
It stayed stuck for about 10 minutes every time, and the rest of the server worked fine in the meantime, so i doubt it was lag. We dont want to risk dying from falling into the void and it didnt appear in singleplayer tests, so reproduction test will have to wait until we have established a small base there.

**Comment by Timeslice42** [comment]
Can you confirm this still happens? It sounds like it was lag from generating the asteroid dimension. Also, it would be good to have Grove around to look at the logs/server stats as it's happening.

**Comment by ghoulsblade** [comment]
seems solved now, cause was likely world generation taking very very long (>15minutes) initially

**Comment by JasonMcRay** [comment]
Indeed most likely lag + new dimension generating...
