### ISSUE TITLE
[Mods Suggestion]

### ISSUE THREAD

**Issue by Polyblock** [JasonMcRay/InfiTech-1.7#631]
[Ztones](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2221070-ztones-v-2-2-1-decorative-blocks-16x) - It is a mod that mainly bring decorative blocks with a strong "tech" look. It may integrate well in the pack without touching to the progression. The mod come with a few utilities and tools which can be disable in the config to keep only the decorative aspect.

[ExtraCells2](http://minecraft.curseforge.com/projects/extracells2) - I know it used to be in the pack and  it was removed because of the presence of duping bugs. From what I've read and tested myself most of those bug (maybe all) have been fix since. Do you think you will reconsider adding back the mod if there is no more dupe bug?

**Comment by DarknessShadow** [comment]
Ztones looks nice an we can always use more decorative blocks.

Definitely a no on ExtraCells that mod is buggy as hell.

**Comment by UbersawMed** [comment]
+1 on Ztones, used it on my previous world and it makes for some snazzy bases :D

**Comment by JasonMcRay** [comment]
ZTones: Yes, it looks really nice.

ExtraCells: No.. As @DarknessShadow said, its too much buggy and I lost hope in that mod.

**Comment by Timeslice42** [comment]
Yeah, it's pretty common for people to just add ExtraCells2 to SSP, but putting it on a server is just asking for trouble.
