### ISSUE TITLE
Hunger node

### ISSUE THREAD

**Issue by Erixonich** [JasonMcRay/InfiTech-1.7#639]
Is there any way to prevent grave destroyed by hungry node?
Yesterday i died near/in case of hungry node, and my grave and all stored items was destroyed by node, when i reached my deathpoint.

**Comment by Xavion3** [comment]
You can use /ob_inventory restore to cheat the items back onto you if you've got commands enabled. Information [here](https://openmods.info/faq.html).

**Comment by JasonMcRay** [comment]
No there is no way to prevent hungry nodes destroying graves. You should be more careful. The command is the only way if you feel like cheating :)
