### ISSUE TITLE
Swamps, jungles and deserts not generating?

### ISSUE THREAD

**Issue by estebes** [JasonMcRay/InfiTech-1.7#641]
After walking thousands upon thousands of blocks to try to find cactus and a swamp biome without any luck i begin to think they are not being generated.

**Comment by UbersawMed** [comment]
Mmm, I personally found one of each, maybe you're just being unlucky?

**Comment by JasonMcRay** [comment]
They do spawn, but given that there is quite a lot of other biomes... it has lower chance. But definitely it spawns.
