### ISSUE TITLE
2 buildcraft gates missing

### ISSUE THREAD

**Issue by ct-klein** [JasonMcRay/InfiTech-1.7#648]
Trying to make either the basic gate redstone fader gate.  It requires the redstone comp chipset.

All of the other chipsets can be used in the assembler or the integration table.  Trying to right-click the redstone comp chipset in NEI crashes the client.  I also dont see a recipe for the autarchic pulsar gate which uses the pulsating chipset.

I looked thru the buildcraft.zs file and see recipes for 6 of the 8.

**Comment by Xavion3** [comment]
Can't reproduce, I just tested and was able to craft and apply a redstone comp chipset and a pulsating chipset with an integration table. The recipe are comparator + redstone chipset in a forming press and ender pearl + redstone chipset in a forming press, both MV recipes, both show up in NEI for me.

**Comment by ct-klein** [comment]
sorry, I should of been more specific.  All the other gates are craftable in an assembler.

**Comment by Xavion3** [comment]
That's because that's how it works, you make the redstone chipsets in the laser engraver, the rest in the forming press with a redstone chipset, the gates themselves in the assembler, and apply upgrades in an integration table. The fader and pulsar are upgrades, thus need an integration table.
