### ISSUE TITLE
Ore clusters can't be inserted into steam macerators by automation.

### ISSUE THREAD

**Issue by yznpku** [JasonMcRay/InfiTech-1.7#654]
They can be inserted into electrical macerators (LV or higher) as expected, and putting these clusters manually into steam macerators will work normally.

**Comment by JasonMcRay** [comment]
Will need to wait for @Blood-Asp.

Cluster processing recipes are added to Pulverizer via MineTweaker. It seems that it is being "converted" to macerator as well. Adding both (macerator and pulverizer) recipes don't seem to work at all, it only registers the macerator one).
Tried to add pulverizer recipe also to InfinityCore directly. No change.

**Comment by JasonMcRay** [comment]
Totally forgot to report it to bloods git.
 https://github.com/Blood-Asp/GT5-Unofficial/issues/891

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10.
You can update GT to latest version to see if it is fixed (keep in mind that some things might not work 100% since GT did couple circuit progression changes)
