### ISSUE TITLE
Request: Server Download

### ISSUE THREAD

**Issue by dnulho** [JasonMcRay/InfiTech-1.7#659]
I was wondering if we could get a server package on curse, rather than just the client download. I'm not sure which version of forge is the best to use, and a simple .bat/.sh file that starts and runs the server would be awesome. I have some experience with doing this and can do a pull request if you can give me the necessary info. (Forge version, what commit is the stable/released version on curse, etc)

**Comment by JasonMcRay** [comment]
Currently the server files are available on FTB Launcher. Adding the server download to the Curse means manually uploading it. I am primarily uploading to the FTB Launcher and just syncing it to Curse automaticaly (it syncs clients, but not server). We might add a in-game button (in menu) to bring you to the server download page.

**Comment by dnulho** [comment]
That would be great. FTB Launcher has not been working correctly for me for some time, and i do not have it installed anymore. Can you post the url for me?

**Comment by JasonMcRay** [comment]
Here it is: http://ftb.cursecdn.com/FTB2/privatepacks/InfiTech2/3_2_5_1/InfiTech2Server.zip (for the latest version)
