### ISSUE TITLE
Fishing Golem Core is not able to be infused

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#665]
As discussed on Discord a few weeks ago the fishing golem core isn't able to be crafted.  

With all of the items placed exactly as the recipe states the infusion process won't start.

Jason was able to replicate the issue a a while ago and said it looked like the fish was the problem in the recipe.  Maybe got forgotten in the 3.2.5.1 fixes as I just tried it tonight and still no go.

**Comment by JasonMcRay** [comment]
Sorry forgot about it for 3.2.5.1 and I already have v3.2.6 releasing in few minutes. Will take care of it as soon as possible...

**Comment by Dlur100** [comment]
No problem.  I should have made a github issue to track this back when I first found the issue and we discussed it on Discord :)
