### ISSUE TITLE
(Greg's SG Craft) stargate problem

### ISSUE THREAD

**Issue by ddragon04** [JasonMcRay/InfiTech-1.7#671]
I tried the Greg's SG Craft in the modpack. I set up the ring and the DHD (Dial Home Device) and dial the for the gate it opens and I can go through it one way but trying to go back for a second trip i am unable to do so

**Comment by DarknessShadow** [comment]
Stargates are one way you have to turn it off and active it on the other side again to go back.

**Comment by JasonMcRay** [comment]
As Dark said. SG is meant to be 1 way (same as in the Stargate series)

**Comment by ddragon04** [comment]
but you can't turn it off from the other side

**Comment by DarknessShadow** [comment]
@ddragon04 Yes it works exactly the same as in the Stargate series.

You could make a computer at both sides and use them to transfer a message to the other dialing side (signals work both directions) to turn the stargate off.

**Comment by ddragon04** [comment]
i didn't know how to use computer craft mod. i seen it before but i never learn it

**Comment by JasonMcRay** [comment]
The connection will terminate i think after 5 minutes if you have no way of
shutting the connection manually

**Comment by DarknessShadow** [comment]
You could make a **very** simple programm to just turn the gate off after 30seconds.

Example
>component = require("component")
sg = component.getPrimary("stargate")
state, chevrons, direction = sg.stargateState()
run = true
while run == true do
if state == "Connected" then
os.sleep(30)
sg.disconnect()
end
end
