### ISSUE TITLE
AE2 Wireless Crafting Terminal recipe - possible script mismatch

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#672]
#### Issue Description:
Unable to craft the new AE2 wireless crafting terminal.  The recipe shows as working but you can't remove the item from the crafting table.  Also unable to create a pattern for the recipe in the ME Pattern Terminal

#### Is the issue happening on server? Client? Both?
Server

#### What happens:
Can't actually craft the new recipe.

#### What you expected to happen:
Being able to craft the new recipe :)

Xavion mentioned on Discord that it might be a script mismatch.

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):

3.2.6

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by Dlur100** [comment]
The recipe in the client script works.

The recipe on the public infitech server looks like this: 
![image](https://cloud.githubusercontent.com/assets/14374121/15133528/3464cfe8-1629-11e6-84a9-0f6b5cc9582e.png)

**Comment by lafflam** [comment]
I have confirmed the following on the Infitech2 Public Server:

AE2.zs line 213 looks like this:
var WirelessCraftingTerminal = <ae2wct:wirelessCraftingTerminal>;

AE2.zs lines 348 - 349 look like this:
// --- Wireless Crafting Terminal
recipes.remove(WirelessCraftingTerminal);

AE2.zs lines 804 - 808 look like this:
// --- Wireless Crafting Terminal
recipes.addShaped(WirelessCraftingTerminal, [
[WirelessReceiver, CraftingTerminal, WirelessReceiver],
[NQuartzPlate, Singularity, NQuartzPlate],
[NQuartzPlate, DEnergyCell, NQuartzPlate]]);

I also confirmed that my client AE2.zs matches the server's. However, NEI shows the recipe as indicated in Dlur's image (with Fluix Pearls, ME Wireless Access Point, Pure Fluix Crystals, ME Crafting Terminal, 64K ME Storage Components, and a Singularity).

**Comment by Dlur100** [comment]
Also, the magnetic card is not craftable.  Unsure if that's intended or not, but the recipe shows up in NEI

**Comment by JasonMcRay** [comment]
If I understand correctly the script on both client and server are the same. Looks like WCT is loading the recipe wierdly...

**Comment by JasonMcRay** [comment]
@lafflam Can you try to set this line on the server to true: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/WirelessCraftingTerminal.cfg#L14 ?

**Comment by JasonMcRay** [comment]
After bit testing... it doesnt work as well...

Reported: https://github.com/p455w0rd/WirelessCraftingTerminal/issues/36
