### ISSUE TITLE
Fluid duplication issue.

### ISSUE THREAD

**Issue by Slychocobo** [JasonMcRay/InfiTech-1.7#677]
#### Issue Description:
Added "Creeper Collateral" to the pack.

#### Is the issue happening on server? Client? Both?
Only tested in Client (LAN server enabled)

#### What happens:
Using a OpenBlocks tank from a users hand filled with a fluid on a EnderIO tank will fill the enderIO tank without emptying the OpenBlock tank.

If the EnderIO tank already has a fluid in the tank (that does not match the OpenBlocks Tank) the EIO tank will recieve an additional 8000mb of the fluid it already contains.

#### What you expected to happen:
Fluid should transfer, and remove the contents of the tank in the players hand.

#### Steps to reproduce (if aplicable):

1. Place EnderIO tank
2. Fill Opeblocks Tank with fluid (Only tested if tank is full)
3. "Use" OB tank from hand onto EnderIO tank.
...

____
#### Modpack Version (Do *not* use "latest"):

3.2.6

#### Your most recent log file where the issue was present: 

N/A

**Comment by JasonMcRay** [comment]
Has been already reported 6 hrs ago on eIO tracker...

https://github.com/SleepyTrousers/EnderIO/issues/3302
