### ISSUE TITLE
Can't breed Aluminium Bees

### ISSUE THREAD

**Issue by UbersawMed** [JasonMcRay/InfiTech-1.7#679]
#### Issue Description:
Tried breeding Aluminium Bees repeatidly without any success, makins sure all the stated conditions are met (Nickel and Zinc bees, Aluminum block right next to the beehive, using multiple metabolic frames...)
Also please state if you modified the modpack in any way.
Enabled Hardcore Wither, though it's unlikely to be the problem.

#### Is the issue happening on server? Client? Both?
Both on a SSP world and SMP server.

#### What happens:
After breeding Zinc and Nickel bees with an Aluminum block nerby it's expected to obtain Aluminum bees, but after around 30 tries with both GT and GalaxyCraft Aluminum blocks I didn't manage to get a single Aluminium trait.

#### What you expected to happen:
Get at least a single Aluminium trait.

#### Steps to reproduce (if aplicable):

1. Place a Zinc and Nickel queens on an apiary, preferibly with some oblivion and metabolic frames and with an aluminium block nerby
2. Wait for a tick
3. Confirm that there wasn't a single Aluminium trait in there
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.7

#### Your most recent log file where the issue was present: 

http://paste.feed-the-beast.com/view/d9e93317

**Comment by UbersawMed** [comment]
errrr, aparently the first attempt I made right after filing this log made some Aluminium bees, soooo...

:P

**Comment by Timeslice42** [comment]
Was this an issue between aluminum and aluminium?
