### ISSUE TITLE
BetterFonts

### ISSUE THREAD

**Issue by InferExcav** [JasonMcRay/InfiTech-1.7#681]
I always install BetterFonts mod cause I have problems with tiny standart russian font in thaumcraft and others mods. On version 3.1.17 BetterFonts1.1.4 was warking good, but on the newest pack 3.2.7 minecraft  crashes. Why?

[crash-2016-05-16_19.19.09-client.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/266500/crash-2016-05-16_19.19.09-client.txt)

**Comment by JasonMcRay** [comment]
Sorry can't say, because I dont know that mod. If you are having issue with that mod, report it to appropriate mod developer.
