### ISSUE TITLE
Problem?

### ISSUE THREAD

**Issue by InferExcav** [JasonMcRay/InfiTech-1.7#683]
> [22:51:17] [Server thread/WARN] [Thaumic Energistics]: Unable to load AE2 Inscriber recipes, aspect registration will be incomplete
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Inscriber Calculation Press" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Inscriber Engineering Press" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Inscriber Logic Press" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Printed Calculation Circuit" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Printed Engineering Circuit" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Printed Logic Circuit" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Inscriber Silicon Press" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Printed Silicon" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Inscriber Name Press" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Creative ME Storage Cell" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Matrix Frame" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "Creative Energy Cell" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "tile.appliedenergistics2.BlockPaint.name" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "P2P Tunnel - OpenComputers" for TC scanning.
> [22:51:17] [Server thread/INFO] [Thaumic Energistics]: Could not register "P2P Tunnel - Pressure" for TC scanning.

This is a part of server log after update it's okay?

**Comment by JasonMcRay** [comment]
Nothing to be worried about. Its just info that certain blocks autogeneration of aspects failed (or something along those lines). So they are just non scannable by Thaumometer
