### ISSUE TITLE
Soul bound items disappear on death in the end. 

### ISSUE THREAD

**Issue by randomguybob4** [JasonMcRay/InfiTech-1.7#686]
#### Issue Description:
Also please state if you modified the modpack in any way.
No I have not modded the mod pack in anyway.

#### Is the issue happening on server? Client? Both?
On servers

#### What happens:
When having soul bound armor on death in the end either by endermen, Hardcore ender expansion bosses/items, ender dragon, or falling into the void the items inside the inventory are deleted and are not found in the Open blocks grave, HEE Void chest, on the ground or back in the players inventory.

#### What you expected to happen:
What should happen is the soul bound items should stay in the inventory of the play through death or if this enchantment is broken the items should have gone into the void chest ( I died over the void, I have tested whether or not you have to fall into it or have items to fall into it and items can be tossed or have fallen out of the inventory from death). The items did not have time to despawn I ran back to my point of death in the end with enchanted boots with haste III I was back there in under 1min 30 sec so the items could have not despawned.

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):

3.2.6

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

http://paste.feed-the-beast.com/view/00bd649b

**Comment by JasonMcRay** [comment]
Re-posted: https://github.com/chylex/Hardcore-Ender-Expansion/issues/183

**Comment by JasonMcRay** [comment]
As a side note, i don't think it will be solved in current HEE iteration. This happens because of the Void Chest, which will be gone in HEE 2 (no ETA no that version). So dont have your hopes for fix high.
