### ISSUE TITLE
Add GT Granite blocks to Microblocks

### ISSUE THREAD

**Issue by AtroCty** [JasonMcRay/InfiTech-1.7#687]
See title. The smooth Granite Blocks looks awesome, but you can't make microblocks with them. It is possible to add it relatively simple.

**Comment by JasonMcRay** [comment]
If you by relatively simple mean adding ForgeMultipart Integration mod, last time I checked it, it was not behaving too well with our current modlist.

If you mean something else... please let me know because I can't think of anything else

**Comment by Xavion3** [comment]
We can use [microblocks.cfg](https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/microblocks.cfg) to add them can't we?

**Comment by AtroCty** [comment]
Yes, I think the line in microblocks.cfg would be:

"gregtech:gt.blockgranites":0-15

You could also add all the casings for decorative porposes as well.

**Comment by JasonMcRay** [comment]
blockgranites - OK
blockcasings - OK
blockconcretes - OK
blockmachines - NO, not working. Getting back "blank" machine block
blockores - NO, same reason as machines
