### ISSUE TITLE
Server Crash when using Crystal Capsules on Railcraft Water Tanks

### ISSUE THREAD

**Issue by CuteTuret** [JasonMcRay/InfiTech-1.7#688]
#### Issue Description:

Also please state if you modified the modpack in any way.

We added Morpheus and Toomuchrain on the server.
#### Is the issue happening on server? Client? Both?

Server
#### What happens:

When right-clicking on a water tank (watertanksiding) from railcraft using a crystal capsule from witching gadgets, the server crashes, when trying to use the crystal capsule on the GUI of the tank, the server crashes and crashes again if the chunk where the tank is loads.

Its worth mentioning that this happened on a Kcauldron server, but we wanted to report it regardless even though it doesn't happen in singleplayer. 
#### What you expected to happen:

What should happen is the crystal capsule should work as a bucket, being filled with water without causing any issues.
#### Steps to reproduce (if aplicable):

1.Right-Click with crystal capsule on Water Tank
2.Try filling the crystal capsule with water from the Water Tank GUI
3.
...

---
#### Modpack Version (Do _not_ use "latest"):

3.2.7
#### Your most recent log file where the issue was present:

[pastebin/gist/pastee etc link here]

http://vpaste.net/7xH65

**Comment by JasonMcRay** [comment]
Reported: https://github.com/CovertJaguar/Railcraft/issues/830
