### ISSUE TITLE
Server Crashing do to Crystal Capsule

### ISSUE THREAD

**Issue by Bl4ck5tar836** [JasonMcRay/InfiTech-1.7#690]
#### Issue Description:
Instant server crash if: 
Using the (witching gadget: Crystal Capsule ID: 6301) via Right click on ((iron tank) / (wooden watertank) : multiblock structures:railcraft)

Have modified the modpack?
-No

#### Is the issue happening on server? Client? Both?
Server

#### What happens:
instantly crashes server. Client side not affected. 

#### What you expected to happen:
Crystal Capsule should function like any other bucket minus the status effects such as burning or radiation.

#### Steps to reproduce (if aplicable):

1. With Crystal capsule in hand
2. Right-Click on any fluid tank ((specifically railcraft multi-block fluid tanks) I know these are affected)
3. Server should crash at this point.
...

____
#### Modpack Version (Do *not* use "latest"):

([InfiTec2]Version3.2.7) minecraft version:1.7.10

#### Your most recent log file where the issue was present: 
log file is on a public server.

[pastebin/gist/pastee etc link here]
![screenshot 2016-05-24 21 31 26](https://cloud.githubusercontent.com/assets/674147/15526585/8cd3479c-21f8-11e6-8cc7-2cbef5d42743.png)
![screenshot 2016-05-24 21 31 31](https://cloud.githubusercontent.com/assets/674147/15526584/8cd1d114-21f8-11e6-8ee9-6d3431d9d951.png)

**Comment by JasonMcRay** [comment]
Duplicate: https://github.com/JasonMcRay/InfiTech-1.7/issues/688
