### ISSUE TITLE
[Mod Suggestion] Electro-Magic Tools

### ISSUE THREAD

**Issue by AtroCty** [JasonMcRay/InfiTech-1.7#691]
Hey there,

I loved this Mod in TPPI:
http://mods.curse.com/mc-mods/minecraft/236669-electro-magic-tools

It would fit for immersive porposes perfectly, since it combines IC2 with TC.
Ofcourse the recipes needs to get tweaked (and the Solar Panels banned), but Quantum Boots of the Traveller are just awesome. ;)

**Comment by Xavion3** [comment]
There's a 1.7.10 version that made out of of early alpha? Nice. This one could get looked at, it was nice in TPPI1.

**Comment by JasonMcRay** [comment]
Looks good. @Xavion3 I will assign it to you, since it is Thaumcraft related :)

**Comment by Nex4rius** [comment]
Did you guys make any progress here?

**Comment by Xavion3** [comment]
Oh right, this one.

I actually did load this up and look through it it, it was discussed. I can't remember if we ever reached a final choice, but I remember one significant issue being that most of the mod would actually end up disabled. Things like super easy flight, all the solar panels, the derivatives of the ic2 tools, there wasn't going to end up all that much left so it was questionable if it was worth adding it.

Looks like it got some updates recently though, I'll make sure to look at it again.

**Comment by JasonMcRay** [comment]
Honestly if it will be too much disabled things and too much of a hustle I will vote for not adding any new mods to the pack.
