### ISSUE TITLE
Void Metal Transmutation?

### ISSUE THREAD

**Issue by TehScrub** [JasonMcRay/InfiTech-1.7#694]
Just another issue / thing that occurred to me. I get that when you first discover void metal, the void seed > 3 nuggets is supposed to be horribly inefficient, but for late game where void metal is required in bulk (mainly for Witching Gadgets), would it be possible to get an alternative recipe, probably a transmutation or infusion recipe that would give us an entire ingot instead of the nuggets? 

I could see this being locked behind the Primal Pearl research so it wouldn't be possible until you've scanned one, at the very minimum. Making void metal for the Primordial Armor is pretty painful, even with automation.

**Comment by TehScrub** [comment]
Obviously said transmutation would use the Primal Pearl in some way to make said ingots of void metal.

**Comment by Xavion3** [comment]
Transmutations are based off alchemy and alchemy only has one input and output, so can't really use pearls as they'd consume the pearl for each ingot and that's not something that's actually usable. I can add a recipe, but it needs to be something actually usable. Maybe turning thaumium to void metal? That might work.

**Comment by TehScrub** [comment]
Some way to make void metal slightly easier late game would be fantastic, and while it doesn't have to *use* the pearl, involving the pearl in some way, like locking the research for the transmutation seems pretty logical, as you already need plenty of void seeds just to make the eyes to go to the Outerlands. Transmuting Thaumium seems pretty logical honestly, since void metal is a madman's thaumium basically.

**Comment by FURi4N** [comment]
I dont think that should touch in any way. Why should late game be easier? This pack is build for to be long and hard. Btw almost all metal is possible to make with alchemy so actully i dont have to go outside base soon. And void seed is easy to get in a big amount just need to think about it a bit. So this is good as it is.

**Comment by TehScrub** [comment]
I wouldn't mind something much heavier / complex on aspects than the void seeds are, but having a "less resource efficient, more ease-of-use" way to do something would be nice is all.

**Comment by JasonMcRay** [comment]
@Xavion3 Are you going to do somehting for this, or can be closed?
