### ISSUE TITLE
[Suggestion] Extra Tree's

### ISSUE THREAD

**Issue by AtroCty** [JasonMcRay/InfiTech-1.7#695]
Hey there,

I kinda become a nuicance here ':)
Since I love decorative stuff and love all kinds of wood I wondered why we don't have Extra Tree's implemented:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284348-1-7-10-1-6-4-forestry-binnies-mods-1-8-0-2-0-dev

And again a BIG thanks for this modpack.

Best regards

**Comment by JasonMcRay** [comment]
In short, binnies mods were causing in past a really LONG loading times in combination with GT. And also since it comes in bundle with Extra Bees.... we have Gendustry and I dont want to have both mods present as they can clash together (especially with our custom bees)
