### ISSUE TITLE
connected textures with covers

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#697]
#### Issue Description:
Covers dont have connected textures when you make them from chisel blocks
<a href="http://imgur.com/PL405Dd.png"><img src="http://i.imgur.com/PL405Dd.png"/></a>

#### Is the issue happening on server? Client? Both?
only tested server

#### What happens:
no connected textures

#### What you expected to happen:
connected textures

#### Steps to reproduce (if aplicable):

1. make cover from chisel blocks
2. place them next to it each other

____
#### Modpack Version (Do *not* use "latest"):
3.2.7

#### Your most recent log file where the issue was present: 
none

**Comment by Xavion3** [comment]
That's not a bug is it? The only mod I've ever even heard of including support with connected textures and microblocks is XU.

So, why do you expect them to connect? Seriously wondering as I never heard of that being possible.

**Comment by DarknessShadow** [comment]
I thought that always worked with chisel .... hm 

Enderio + chisel work with connected textures together

**Comment by JasonMcRay** [comment]
FMP never had Connected Textures support, and will never have (since no longer maintained and I guess it would be too much for rewrite).
