### ISSUE TITLE
Crafting Planks with Chainsaw destroyed Chainsaw

### ISSUE THREAD

**Issue by TheMilso** [JasonMcRay/InfiTech-1.7#699]
#### Issue Description:
Also please state if you modified the modpack in any way.
While playing on Official server

#### Is the issue happening on server? Client? Both?
Only tested server side.

#### What happens:
when crafting Spruce planks with a LV blue steel chainsaw the saw ran out of power and was then destroyed (crafted in player inventory)

#### What you expected to happen:
the saw to run out of power and now work again till recharged

#### Steps to reproduce (if aplicable):

1.cut spruce logs with lv chainsaw low on power(crafted in player inventory)
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.7

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]
http://paste.feed-the-beast.com/view/78fbe9c8

**Comment by JasonMcRay** [comment]
Looks like fix to the quests broke something else... Fortunately I know how to fix it, quite easily...
Thanks for report
