### ISSUE TITLE
Some quest has outdated information.

### ISSUE THREAD

**Issue by yznpku** [JasonMcRay/InfiTech-1.7#703]
#### Issue Description:

The quest in fusion age which requires you to build a tungstensteel boiler states that tungstensteel boilers produce 40000L steam per charcoal and the bronze ones produce 16000L steam per charcoal.

#### What you expected to happen:

48000L for tungstensteel large boilers and 32000L for bronze large boilers.

#### Modpack Version (Do *not* use "latest"):

3.2.8

**Comment by JasonMcRay** [comment]
It should actually be steam per second and not per charcoal :)
