### ISSUE TITLE
It appears the 3.2.8 update has broken ender io farming stations

### ISSUE THREAD

**Issue by RabidDave** [JasonMcRay/InfiTech-1.7#708]
#### Issue Description:
It appears the 3.2.8 update has broken ender io farming stations, they work for a few seconds, then stop...breaking and replacing them does the same tested in SMP and SSP 

Also please state if you modified the modpack in any way.

#### Is the issue happening on server? Client? Both?
client is SSP and SMP

#### What happens:
they work for a few seconds, then stop

#### What you expected to happen:
they keep working

#### Steps to reproduce (if applicable):

1. 
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.8

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Known: https://github.com/SleepyTrousers/EnderIO/issues/3333

**Comment by RabidDave** [comment]
closed as dupe

**Comment by Timeslice42** [comment]
This is fixed in the latest build of eIO. Do we have that fix?

**Comment by JasonMcRay** [comment]
In 3.2.9 i have downgraded eio beacause the fix has not yet been done
