### ISSUE TITLE
Bronze Quest unable to claim rewards and move forward

### ISSUE THREAD

**Issue by PolloFresco** [JasonMcRay/InfiTech-1.7#713]
#### Issue Description:

On Bronze age quest, Analyzing Crops section as a Detection Task. It has been completed and says that it's 100% completed. Then it allows me to pic my reward, so I choose one and the claim button is ready like all the other quests. When i click the Claim Reward button nothing happens. It stays unclaimed. I tried picking the other reward and proceeded with the normal steps and nothing. The reward claim button doesn't activate.

Also please state if you modified the modpack in any way.
I have not modified this game in any way shape or form.

#### Is the issue happening on server? Client? Both?
I am hosting a 5 people server its just my and my closes real life friends. None of us can claim the reward.

#### What happens:
the reward cant be claimed by no one in the server, we are all in party and cant do it. So we are stuck in that quest and cant proceed to the next section after bronze age.

#### What you expected to happen:
For the quest reward to be claimed as usual and proceed to the next step.

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Your most recent log file where the issue was present: 
i dont know how to get the log file :/
[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Have you finished the quest before that? The Growing Crops quest?

**Comment by JasonMcRay** [comment]
Also dont forget to have free space in your inventory. I saw in past couple
ppl saying claim quest not work but they had full inventory :)

**Comment by PolloFresco** [comment]
yeah we had already completed the quest as a group and its happening with a couple of other ones i found out today. One of us already claimed it and got the rewards, Earlier today i was able to claim it again so now we have two rewards. Then quests that I already completed and claimed, its showing to them as finished but unclaimed. Same thing as this quest but its happening to them now with other quests. We are doing the quest as a party so im not sure if there is a tiny bug or something. Seems like its like that randomly with the quest as a party and seems that we are able to claim the same reward more than once when that happens.

**Comment by JasonMcRay** [comment]
Have you tried using the edit book to reset the not working quests? It
seems like bug in HQM but it is no longer maintained on 1.7 so the fix will
not happen.

Not sure if only party leader can use the edit book or each player will
need to do it.

**Comment by JasonMcRay** [comment]
Is it still an issue after v3.2.9?

**Comment by phit** [comment]
I had some people on my server have the same issue after we upgraded to 3.2.9 with the quest "avengers assemble!".
https://forums.stonebound.net/topic/346/infitech-2-bugged-quest-hqm

**Comment by JasonMcRay** [comment]
If you completed the quest before you need to reset the quest, because there has been some internal changes. There is nothing we can do about that. Just reset the quest with Edit book and all should be good.
