### ISSUE TITLE
/iskamiunlocked reporting false information

### ISSUE THREAD

**Issue by TehScrub** [JasonMcRay/InfiTech-1.7#714]
#I'm not sure if this is an issue on my end or not, but when I go to do /iskamiunlocked it tells me that I still need CAP_copper and CAP_gold research, and unless I've missed something, those do not actually exist. 

I'm at the point where I have no more research I can discover by any means, including knowledge fragments, and it appears that KAMI is at the moment unavailable unless I've messed something up.

This is on version 3.2.8 as well.

**Comment by Xavion3** [comment]
You've missed something, we've had a few people think they had everything only to find out they didn't. Possibly one of the scanning required researches from automagy. /iskamiunlocked is currently broken though, got a probable fix done however so it should work in the next version if nothing breaks.

Consult [here](http://imgur.com/a/uhaXc), it contains screenshots of every single research and some tips for the trickier ones. You should need everything in there to unlock Kami.

**Comment by TehScrub** [comment]
Hm. I went through all of those pictures and I do indeed have everything there except for the elemental fires, as we've disabled them serverside. Would having them enabled client side but not server side cause an issue with it? Those are the only thing I'm "missing" from everything in that album

**Comment by Xavion3** [comment]
Yeah sorry, you'll have to wait till the next update where they're no longer a requirement. See #706

**Comment by TehScrub** [comment]
I imagine having everyone disable them clientside *should* work until 3.2.9 correct?

**Comment by Xavion3** [comment]
Maybe. Never tested. It's not impossible based off other stuff that came up with testing, but I'm really not sure.

**Comment by TehScrub** [comment]
It seems to work on my end, guess it's a nice workaround until 3.2.9.
