### ISSUE TITLE
Remove requirement to craft LV versions of bronze machines as core progression from HQM

### ISSUE THREAD

**Issue by Xavion3** [JasonMcRay/InfiTech-1.7#715]
Just a suggestion but I've seen it crop up a few times now that people will put off doing the quest falling well behind in the book because the steam versions they had to craft still work perfectly. Keeping it as an optional quest sure but currently all higher tech including the assembler, ore processing and EBF are behind it.

**Comment by Timeslice42** [comment]
Or better still, only require the crafting of the machines that are necessary to get to the next tech level, and just mention the other ones.
