### ISSUE TITLE
duplicate anything bug

### ISSUE THREAD

**Issue by Nex4rius** [JasonMcRay/InfiTech-1.7#721]
#### Issue Description:

item duplication
#### Is the issue happening on server? Client? Both?

only tested it on server
#### What happens:

item duplication
#### What you expected to happen:

no item duplication
#### Steps to reproduce (if aplicable):
1. telepad with coords to another dimension
2. place chest cart ontop of it with items inside
3. teleport -> items get dropped but also teleported

---
#### Modpack Version (Do _not_ use "latest"):

3.2.9
#### Your most recent log file where the issue was present:

none

(btw I'm DarknessShadow but I've decided to change my name now)

**Comment by JasonMcRay** [comment]
I already reported this 2 months ago: https://github.com/SleepyTrousers/EnderIO/issues/3276

Not sure if it will get fixed, since I read that eIO development on 1.7 has been halted and fully moved to 1.9
