### ISSUE TITLE
Alchemical boilers are VERY laggy.

### ISSUE THREAD

**Issue by yznpku** [JasonMcRay/InfiTech-1.7#722]
Step 1: Place some reservoirs, fill them with water, and set to auto-output.
![2016-06-19_13 48 29](https://cloud.githubusercontent.com/assets/3965638/16175576/64f3b252-3625-11e6-8f4a-1b8faf58cbb3.png)

Step 2: Place some alchemical boilers. Fuels are not needed. They cause lag even if they are idle.
![2016-06-19_13 54 26](https://cloud.githubusercontent.com/assets/3965638/16175589/a9a9b540-3625-11e6-8ca4-1bef3c3cab03.png)

Step 3: BOOM.
![default](https://cloud.githubusercontent.com/assets/3965638/16175591/b278cf62-3625-11e6-8daf-52869c54f104.png)

**Comment by groveham** [comment]
Now we don't see that on the public server (running v3.2.9) but they are a very laggy in general, see link below for screenshot.

http://i.imgur.com/ru8j6vT.png

I have seen in opis (when more people are online, only 5 currently incluing myself who has none) that this number can be much much higher with a few more people online who use Thaumcraft which would suggest this may need looking at.

**Comment by Pyromancer56** [comment]
It's been an issue for awhile and you'd have to bring it up with the Automagy author I believe. Best work around is to not leave any fluid inside the boiler when you aren't using it. I use a Quantum tank that is controlled by two switches. One to feed the boiler and another to return the fluid to the tank when I'm done.

**Comment by yznpku** [comment]
I didn't know that the fluid inside can be extracted. What a weird machine.

Alright, thanks for the workaround.

**Comment by JasonMcRay** [comment]
I made a cross post about it to Automagy dev: https://github.com/Tuhljin/Automagy/issues/49
