### ISSUE TITLE
EnderIO + Gregtech molten metal dupe

### ISSUE THREAD

**Issue by MistaOmega** [JasonMcRay/InfiTech-1.7#723]
#### Issue Description:
Using a non-modified pack a user managed to get infinite molten titanium out of using a single ingot, an oxygen cell from GregTech and an EnderIO tank. It is shown here: https://www.youtube.com/watch?v=GkmUz4LFITc&feature=youtu.be

#### Is the issue happening on server? Client? Both?
Server and client

#### What happens:
Molten metals duplicate when right clicking on an ender io tank with an oxygen cell

#### What you expected to happen:
Nothing. The oxygen shouldn't go in

#### Steps to reproduce (if aplicable):

1.Add molten metal to ender IO tank
2.Right click with oxygen cell from GregTech
3.Profit
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.9

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Duplicate: https://github.com/JasonMcRay/InfiTech-1.7/issues/677
