### ISSUE TITLE
[HQM] Text typos

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#727]
In the "Steel Age" set in the "Insulation" quest one of the tasks is "Bath a cable", this should be _bathe_.
In the "Shop" set in the "Small Acid Battery" quest you mention "Acid Omes". Were you referring to the (imaginary) brand name "Acid Ohms", or did you mean to say "acid ones"?

On a related note, @JasonMcRay is your primary language german? Because you seem to want to capitalize every noun...

**Comment by JasonMcRay** [comment]
I am just used to capitalizing actual item/block names. The Acid Omes is just a typo, it should be acid ones
