### ISSUE TITLE
QDS wont connect for Biogas quest

### ISSUE THREAD

**Issue by MrJoshua68** [JasonMcRay/InfiTech-1.7#731]
#### Issue Description:
I have connected the Safegas quest to the QDS.  
I have bio gas that I have tried to pump into the QDS both directly from the fermenter, and from a BS Factory tank.  
From both the tank and the fermenter I have tried putting hte QDS directly next to them (both alongside and below) and with  gregtech pipes (both bronze and wooden).
I have tried all of these combinations both with and without an electric pump.  I have set the pump configuration to every setting.

The pipes do not visually connect to the QDS, but I dont know if thats just a visual glitch and something else is preventing the biogas from moving or if its part of the problem.

#### Is the issue happening on server? Client? Both?
Im not using a server, its all on my PC.

#### What happens:
Nothing

#### What you expected to happen:
biogas to flow into the QDS

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):

3.2.10 now, but saw this in 3.2.9 as well

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Yes. It is stated in the quest about QDS that GregTech pipes will not connect to it, because QDS is not coded as a tank and GT pipes only connect to blocks that has or are tanks. You need to use other pipes (Buildcraft or EnderIO for example... or you can fill EnderIO Fluid Tank and then use that)

**Comment by MrJoshua68** [comment]
Oh for petes sake...
Im terribly sorry. I read that at one point, but it just never registered
when I was trying to get it to work.

On Mon, Jul 4, 2016 at 1:40 PM, Jason McRay <notifications@github.com>
wrote:

> Yes. It is stated in the quest about QDS that GregTech pipes will not
> connect to it, because QDS is not coded as a tank and GT pipes only connect
> to blocks that has or are tanks. You need to use other pipes (Buildcraft or
> EnderIO for example... or you can fill EnderIO Fluid Tank and then use that)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JasonMcRay/InfiTech-1.7/issues/731#issuecomment-230340124>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATWOhH_oIVHfrWdlUsHVuP6nn_fM0DM6ks5qSVOQgaJpZM4JElP8>
> .
>



-- 
Why use 2 words when 20 will do? What does Hemingway know?
