### ISSUE TITLE
Quest "HV Tools" doesn't track correctly

### ISSUE THREAD

**Issue by UbersawMed** [JasonMcRay/InfiTech-1.7#733]
#### Issue Description: The first step of the quest "HV Tools" on the Nuclear Age doesn't track correctly the crafting of the Jackhammer.

Also please state if you modified the modpack in any way.
Nope.

#### Is the issue happening on server? Client? Both?
Tried it on the public InfiTech 2.0 Server.

#### What happens:
When I try crafting a Jackhammer the quest doesn't track me crafting the jackhammer and thus is impassable, blocking all the following quests.
Tried to craft a Jackhammer with full battery, one with empty battery and one with a Tungstensteel tip and an empty battery and none worked.

#### What you expected to happen:
The quest updating properly.

#### Steps to reproduce (if aplicable):

1. Craft Jackhammer.
2. ...
3. Profit! The quest still hasn't updated tho
____
#### Modpack Version (Do *not* use "latest"):
3.2.10.1

#### Your most recent log file where the issue was present: 

http://paste.feed-the-beast.com/view/e7ca6282

**Comment by JasonMcRay** [comment]
Should be fixed via: https://github.com/JasonMcRay/InfiTech-1.7/commit/23bfbbfacfdf2d7fb5edfc498c92567bda9ab960
Pushed the fix to the Official Server, let me know if it works or not :P

**Comment by JasonMcRay** [comment]
And it indeed is fixed via that

**Comment by codewarrior0** [comment]
Cool!

FYI, I had a jackhammer before this quest even unlocked, since it only uses Titanium parts (not Tungstensteel) and can be crafted well before any of the other HV power tools.
