### ISSUE TITLE
[v3.2.10] QDS crafting dupes the Quest Book

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#734]
QDS crafting dupes the Quest Book.

**Comment by Timeslice42** [comment]
Are you sure you weren't in creative mode? We just recently changed that recipe because it was consuming the quest book.

**Comment by JasonMcRay** [comment]
The book is set in the HQM code to not get consumed, so looks like we don't need the reuse().

**Comment by Timeslice42** [comment]
Cool.
