### ISSUE TITLE
Forge Fluid Registry Error with latest update (Gtech adding Radon)

### ISSUE THREAD

**Issue by AuricPolaris** [JasonMcRay/InfiTech-1.7#735]
#### Issue Description:
Also please state if you modified the modpack in any way.
The latest update of Infitech 2 updated Gregtech to include a new fluid: Radon. This appears to have broken the fluid registry of forge.

#### Is the issue happening on server? Client? Both?
The server is able to load and stay online but the client cannot join without being disconnected.

#### What happens:
Server and client load but the player is not able to stay connected.

#### What you expected to happen:
The player to stay connected to the server.

#### Steps to reproduce (if aplicable):

1. Load a server
2. Attempt to connect with a client
3.
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.10.1

#### Your most recent log file where the issue was present: 
Full client log: http://pastebin.com/LfSiE8XW
Forge Fluid Registry Error: http://pastebin.com/s1qUwD41
OpenMods critical exception error: http://pastebin.com/xSmxXgkt (This was after the forge fluid registry error, I thought to single it out as it seemed somewhat important)
[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Seems like the client is not running 3.2.10.1 version with the new Gregtech.
If it is running the 3.2.10.1 then please provide complete full log from the console (click on the upload log button in the console window and post the link in here.

**Comment by Nex4rius** [comment]
Thats strange the official InfiTech2 server runs with the newest version and we don't have this problem.
