### ISSUE TITLE
Can't create (or join) a server.

### ISSUE THREAD

**Issue by Soschian** [JasonMcRay/InfiTech-1.7#737]
#### Issue Description:
I was setting up a server today because my friend wanted to try out the modpack with me. After i couldn't join a few times getting an exception because of some missing mods, i checked the version of the server download and it wasn't updated to .10, it was still running on the .9 mods (.10 & .9 of your modpack). So i tried to install all of the missing mods, which didn't work.

#### Is the issue happening on server? Client? Both?
Both I'd say

#### What happens:
I get an Exception when trying to join the server (and yes i've forwarded the port and such, since the server for my own modpack still works) which is about some Forestry Mods (I think)

#### What you expected to happen:
To join the downloadble Server without any problems

#### Steps to reproduce (if aplicable):

1. Download via the "Server Download" tab in the Main Menu
2. Run the .bat file
3. Try to join the Server
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.10

#### Your most recent log file where the issue was present: 

I don't know what is needed here (from the logs) and i don't want to spam like 3000 lines of log somewhere

**Comment by phit** [comment]
the server download link in the main menu is outdated
here are the proper download links:

3.2.10 (Stable) http://ftb.cursecdn.com/FTB2/modpacks/InfiTech2/3_2_10/InfiTech2Server.zip
3.2.10.1 http://ftb.cursecdn.com/FTB2/modpacks/InfiTech2/3_2_10_1/InfiTech2Server.zip
