### ISSUE TITLE
Scanners consume 100mb of honey each cycle.

### ISSUE THREAD

**Issue by yznpku** [JasonMcRay/InfiTech-1.7#741]
According to NEI, it should be only 50mb.

**Comment by Timeslice42** [comment]
Scanners consume one drop's worth of honey, which is 100mb. Unless @JasonMcRay has done something weird with the forestry settings.

**Comment by JasonMcRay** [comment]
Nope. I done nothing. Its GT related issue (tested in fresh instance with GT and Forestry only)
https://github.com/Blood-Asp/GT5-Unofficial/issues/578
