### ISSUE TITLE
Naquadah Alloy ingot crafting

### ISSUE THREAD

**Issue by Anarack** [JasonMcRay/InfiTech-1.7#745]
#### Issue Description:
Recipe for naquadah alloy has a significantly cheaper version using different components

#### Is the issue happening on server? Client? Both?
Both

#### What happens:
Naquadah alloy dust has a significantly cheaper and different recipe of 
(iron dust + naquadah dust gives naquadah alloy dust in chemical reactor at 30 eu/t for 600 seconds) still must be run through a blast furnace at 120 eu/t for 300 seconds
 vs what appears to be the intended recipe of
 (Argon gas + Naquadah ingot + osmiridium ingot in a blast furnace at 30k eu/t for 25 seconds) 

#### What you expected to happen:
That naquadah alloy has the same components cost scale no matter how its made.

#### Steps to reproduce (if applicable):
Found in nei for naquadah alloy dust in the chemical reactor

____
#### Modpack Version (Do *not* use "latest"):
3.2.10.1

**Comment by Nex4rius** [comment]
Gregtech added the expensive recipe in the newest version and the cheap recipes was added by this modpack and forgotten to remove in the latest version but its already fixed so just wait for a new version.
https://github.com/JasonMcRay/InfiTech-1.7/commit/c72ae3de73578bba7f61afecdaa8b8f2c5469033
