### ISSUE TITLE
Small Cupronickel Gears?

### ISSUE THREAD

**Issue by Erithal** [JasonMcRay/InfiTech-1.7#746]
#### Issue Description:

Vanilla 3.2.10; when trying to construct clay golems, the 'small cupronickel gear' which is called for is not in NEI & cannot be crafted by any means I have found.
#### Is the issue happening on server? Client? Both?

The issue is happening on a private 3.2.10 multiplayer server and client-side in single player.
#### What happens:

Small Cupronickel Gear, which is called for in the Clay Golem Recipe is uncraftable. 
#### What you expected to happen:

Craft gears, infuse golems. Profit.
#### Steps to reproduce (if aplicable):
1. Look up 'small cupronickel gear' in NEI; it's not there.
2. Attempt to use small gear mold to make it anyway.
3. Fail & scratch head.
   ...

---
#### Modpack Version (Do _not_ use "latest"):

3.2.10
#### Your most recent log file where the issue was present:

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
It works perfectly fine. Both recipes: Crafting table with Hammer and Plate and also Molding.
It is true that it is not showing in NEI, but you can click on the gear when looking at the clay golem recipe.

**Comment by Erithal** [comment]
Confirmed craftable. 

I did manage to craft them with a hammer-- oddly the recipe didn't allow me to center the plate and use the hammer in the lower right corner, but you can craft it! The plate needs to be in the upper left corner and the hammer in the center. Strange behavior, but the recipe functions. Furthermore, the gear must be crafted in a fluid solidifier-- an alloy smelter doesn't cut it. NEI confirms this behavior.

Thanks for your time! Sorry for the derp on my part.

**Comment by Timeslice42** [comment]
Assuming that there is a small gear mold then it *should* be craftable in the alloy smelter. If not then that's a bug/issue.

**Comment by JasonMcRay** [comment]
Why are you reopening half a year old issue? Everything works as expected. And if there is a mold it does not mean it MUST be craftable in alloy smelter.
