### ISSUE TITLE
Random crash while moving around in house

### ISSUE THREAD

**Issue by austin1346** [JasonMcRay/InfiTech-1.7#747]
#### Issue Description:
Also please state if you modified the modpack in any way.
I added MoCreatures and CustomMobSpawner.
Faithful 32x32 texture pack.
Shaders mod with SEUS ultimate.
Optifine

I have removed ShadersMod, SEUS, and faithful but it still crashes withing 30s-1m of playing.

#### Is the issue happening on server? Client? Both?
Just the client

#### What happens:
Game freezes, I get the windows blue spinning wheel for about 2 seconds, then crash back to launcher.

#### Steps to reproduce (if aplicable):

1. Simply walking around in my house.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):
1.7.10 (v3.2.10)

#### Your most recent log file where the issue was present: 

http://hastebin.com/enehiqames.tex - (latest.log - Thrown exception at the bottom) 
https://drive.google.com/file/d/0B5Ufk04dlLGtbXNuRmw1OVAwX1U/view - (fml-client-latest.log - detailed report says it crashed while trying to render an item frame)

**Comment by JasonMcRay** [comment]
1) Turn off Multi-Core Chunkloading if you have Optifine
2) Have you tried to remove the ticking Item Frame on the specified coords?
3) Update Java
4) Update drivers
5) Update everything

**Comment by austin1346** [comment]
I have removed optifine, chunk loading was set to smooth by the way. It appears that removing it has fixed it as of now. I'll let you know if i come across the problem again. It usually crashed in about 2 mins, I've been playing for about 10 mins and it's fine.

**Comment by JasonMcRay** [comment]
Cool.. Yea Optifine can cause troubles. I spent some time tweaking optifine for myself.

[optionsof.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/384906/optionsof.txt)

Here is my config file for OF if you (or anyone else) are interested.
