### ISSUE TITLE
Nichrome Coil Block Quest

### ISSUE THREAD

**Issue by DuckyC** [JasonMcRay/InfiTech-1.7#749]
#### Issue Description:
The issue is that the Nichrome Coil Block quest called Coil'o'Mighty in the Nuclear Age requires you to have 256 Nichrome ingots but really you only need 128 to make the coil blocks
No changes to the modpack

____
#### Modpack Version (Do *not* use "latest"):
3.2.10

**Comment by codewarrior0** [comment]
Thanks!
