### ISSUE TITLE
Duplication with Arcane Terminal (AE)

### ISSUE THREAD

**Issue by Verharn** [JasonMcRay/InfiTech-1.7#750]
#### Issue Description:

Item duplication
#### Is the issue happening on server? Client? Both?

Both
#### What happens:

Item duplication
#### Steps to reproduce (if aplicable):
1. You need more than 1 item which you need to multiply into AE net (any storage)
2. Open Arcane Terminal and click the right mouse button then click the left one very fast on the items you need
3. ?????
4. PROFIT

---
#### Modpack Version:

3.2.10.1

**Comment by JasonMcRay** [comment]
I am trying to recreate it but with no luck. Would it be possible to make a video of it so I can see it in action?

**Comment by Verharn** [comment]
https://youtu.be/KH_ekeUDJJw

**Comment by JasonMcRay** [comment]
Thanks.. Managed to replicate

**Comment by JasonMcRay** [comment]
And I see it has been already reported quite a while ago: https://github.com/Nividica/ThaumicEnergistics/issues/313
