### ISSUE TITLE
Quest rewards stuck?

### ISSUE THREAD

**Issue by tsbardella** [JasonMcRay/InfiTech-1.7#753]
#### Issue Description:
I get the same reward every time.  I get six conveyor belts with componant bag.  Material bag I get 24 steel and 6 gold.  No changes made to the server.  On my client I had optifine but I removed it .

#### Is the issue happening on server? Client? Both?
I have a private server.

#### What happens:
I get the same reward each time

#### What you expected to happen:
I expected that the rewards would differ.  I think that they did the first few times. 

#### Steps to reproduce (if aplicable):
complete a quest.
1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.10.1

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

https://gist.github.com/tsbardella/d5391ec78f94c7e8f301c0175b86bd23

**Comment by JasonMcRay** [comment]
Reported to mod devs:
https://github.com/DoubleDoorDevelopment/JsonLootBags/issues/5

**Comment by JasonMcRay** [comment]
According to devs, fix is not possible. It would require whole rewrite of the mod, which will not happen for 1.7

**Comment by Claycorp** [comment]
You could add more options to the bag and get more possible outcomes. Smaller pools tend to repeat their self. That would be the only way I can think of getting around the vanilla loot gen problems. It's not an issue with the mod itself.
