### ISSUE TITLE
GT chainsaw with an EnderIO treefarm

### ISSUE THREAD

**Issue by yeti1026** [JasonMcRay/InfiTech-1.7#755]
#### Issue Description:

Gregtech Chainsaw placed as an 'Axe' in the EnderIO Treefarm causes the farm to operate, even when the chainsaw's charge has been depleted. Also the chainsaw's durability is not decreasing.
I have only tested it with an LV Iridium Chainsaw, with a lithium battery.
#### What you expected to happen:

I expected the farm to stop operating once the chainsaw's charge has been depleted.

---
#### Modpack Version (Do _not_ use "latest"):

3.2.10.1

**Comment by JasonMcRay** [comment]
Reported to mod devs: https://github.com/SleepyTrousers/EnderIO/issues/3648
