### ISSUE TITLE
GT 

### ISSUE THREAD

**Issue by groveham** [JasonMcRay/InfiTech-1.7#756]
#### Issue Description: 
GT Large Boilers tip in NEI states that the Output hatch must be one of the 'Fireboxes'. This is wrong, it should state "x1 Output Hatch (Any Casing)"

Also please state if you modified the modpack in any way.

No modifications

#### Is the issue happening on server? Client? Both?

Both client and server, with all large boilers

#### What happens:

Incorrect NEI tip

#### What you expected to happen:

I'd expect it to show "x1 Output Hatch (Any Casing)"

____
#### Modpack Version (Do *not* use "latest"):

3.2.10.1

**Comment by JasonMcRay** [comment]
Can you please make me a screeshot? Because I am checking the GT Code, and it is correct in there, and there was no edit for that.
