### ISSUE TITLE
[Issue] Crash Client while loading SGCraft

### ISSUE THREAD

**Issue by Moustik2002** [JasonMcRay/InfiTech-1.7#757]
#### Issue Description:
Modpack not modified, download and install release

#### Is the issue happening on server? Client? Both?
not even test on server yet

#### What happens:
Client crashed

#### What you expected to happen:
Client starts correctly

#### Steps to reproduce (if aplicable):

Install mod pack via Curse
Launch It

____
#### Modpack Version (Do *not* use "latest"):
InfiTech2-3.2.10-1.7.10 (Release)

#### Your most recent log file where the issue was present: 
http://pastebin.com/fqe77WQg

By the way, does it be possible to have server side files for last release (i mean not the beta)

**Comment by JasonMcRay** [comment]
You have a broken Forge installation (missing at least the typesafe-config lib). Reinstall or copy your libs from a working installation. This is known issue when launching via Curse Launcher. Nothing we or OC mod dev can do about it.

**Comment by Moustik2002** [comment]
ok thx for your fast answer, what about Server side files for the last release ?

**Comment by JasonMcRay** [comment]
Server files are not affected by this, however in the 3.2.10 the server files download from the main menu is broken.
use this link to download 3.2.10 server files: http://ftb.cursecdn.com/FTB2/modpacks/InfiTech2/3_2_10/InfiTech2Server.zip
