### ISSUE TITLE
Galacticraft Canister not beeing consumed

### ISSUE THREAD

**Issue by DenTommes** [JasonMcRay/InfiTech-1.7#758]
#### Issue Description:
Crafting the Oxygen Compressor from Galacticraft returns the empty canister 

#### Is the issue happening on server? Client? Both?
only tested in on server

#### What happens:

see above

#### What you expected to happen:
The canister to be used up

#### Steps to reproduce (if aplicable):

____
#### Modpack Version (Do *not* use "latest"):
3.2.10.1

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Works fine for me.

Might have got fixed by some mod update
