### ISSUE TITLE
ruby dust + electrolyzer

### ISSUE THREAD

**Issue by wtfmynamesarepopular** [JasonMcRay/InfiTech-1.7#759]
#### Issue Description:
Also please state if you modified the modpack in any way.

no changes whatsoever. curse launcher.

#### Is the issue happening on server? Client? Both?

both

#### What happens:

there are 2 types of gregtech ruby. the dusts have the ids 5717:2512 and 5717:2502.
xx02 can be electrolyzed (for stainless steel), while xx12 cannot.

#### What you expected to happen:

only one type of ruby dust should exist, they both have the exact same picture and name.

#### Steps to reproduce (if aplicable):

1. check ruby dust in NEI. 
2. try both types in an advanced (or higher) electrolyzer.

____
#### Modpack Version (Do *not* use "latest"):

3.2.10 from curse launcher.

#### Your most recent log file where the issue was present: 

-

**Comment by JasonMcRay** [comment]
The second type of ruby is so called Fools Ruby, which is intended to exist and intended to not have any use. It is a joke from Greg.
