### ISSUE TITLE
long tin rod and tin spring is uncraftable

### ISSUE THREAD

**Issue by skynsun** [JasonMcRay/InfiTech-1.7#760]
#### Issue Description:
Also please state if you modified the modpack in any way.

#### Is the issue happening on server? Client? Both?
I tryied in single player and on my own dedicate server.

#### What happens:
We can't craft those material (tin spring and long tin rod) which the recipe of spring tin does'nt show up  and the long rod itself doesn't show up in nei.

#### What you expected to happen:
craft my golem :D

#### Modpack Version (Do *not* use "latest"):

V3.2.11

edit: Quartzite Screw recipe seems to be broke too. And there is no bolt showing up in nei

**Comment by JasonMcRay** [comment]
We have found why is that.... The main change in GT was that it disables the items that are not used. Screw for example is used, so it enables it, BUT it doesnt look the recipe line and does not enable the Bolt.
