### ISSUE TITLE
Tricorder seems to not lose eu in multiplayer

### ISSUE THREAD

**Issue by skynsun** [JasonMcRay/InfiTech-1.7#761]
#### Issue Description:
Also please state if you modified the modpack in any way.
I just add endermanage which make unable to endermen to pick a block

#### Is the issue happening on server? Client? Both?
Tricorder works fine in single player. But doesnt in my own server.

#### What happens:
the battery of the tricorder does not go down when you use it.
i tryed used it throw away and pick up, use and disconnect reconnect. It doesn't seems to be a sync problem...

#### What you expected to happen:
tricorder use eu when you use it.

#### Steps to reproduce (if aplicable):

1. charge tricorder
2. use it
3. he doesn't loose eu

____
#### Modpack Version (Do *not* use "latest"):

V 3.2.11

**Comment by JasonMcRay** [comment]
Reported: https://github.com/Blood-Asp/GT5-Unofficial/issues/675

**Comment by JasonMcRay** [comment]
Portable scanner will not consume energy if used on normal block. It consumes energy only when used on Tile Entities (like GT machines). I also just now tried it on my local server. It consumes energy just fine when used on Machine.

Also remember if you have anything on you that can charge EU items (like Adv. Nano Chestplate) it will drain the energy from it.
