### ISSUE TITLE
TIN NUGGET EZ DUPE

### ISSUE THREAD

**Issue by syrun97** [JasonMcRay/InfiTech-1.7#762]
#### Issue Description:
Also please state if you modified the modpack in any way.
no modify

#### Is the issue happening on server? Client? Both?

maybe client

#### What happens:

GIVE 8 TIN NUGGET WHEN U SMELT A TIN NUGGET

#### What you expected to happen:

nothing (maybe smelt 9 tin nugget to ingot)

#### Steps to reproduce (if aplicable):

1.SMELT TIN NUGGET
2.GET 9 TIN NUGGET
3.DUPE!!
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.11 latest

#### Your most recent log file where the issue was present: 
![2016-10-06_22 23 22](https://cloud.githubusercontent.com/assets/19798397/19153974/8c49e65c-8c13-11e6-9407-f6df3c67175d.png)

[pastebin/gist/pastee etc link here]

**Comment by syrun97** [comment]
that works on other nuggets except for iron nugget.

**Comment by syrun97** [comment]
#

- [ ]

**Comment by syrun97** [comment]
oops my cat closed and reopened this.

**Comment by Nex4rius** [comment]
1) Why caps?
2) What exactly should we see on the screenshot?

**Comment by Nex4rius** [comment]
I just tested it with version 3.2.10.1
<img src="http://i.imgur.com/kXqZJFu.jpg">
and 3.2.11
<img src="http://i.imgur.com/63aq9rZ.jpg">
