### ISSUE TITLE
Compressed Aluminum(GC) not craftable.

### ISSUE THREAD

**Issue by Explodia** [JasonMcRay/InfiTech-1.7#763]
#### Issue Description:
Tried to start the Galacticraft questline and found only two NEI recipes for GC's compressed aluminum, both for disabled GC compressors.

#### Is the issue happening on server? Client? Both?
Client.

#### What happens:
Implosion Compressor has no recipe for it.

#### What you expected to happen:
Similar recipe to the other GC plates (two GT plates in the Implosion Compressor)

#### Steps to reproduce (if applicable):
N/A

#### Modpack Version (Do *not* use "latest"):
3.2.11 I think (Just updated).

#### Your most recent log file where the issue was present: 
Not sure where this would be. =/

**Comment by JasonMcRay** [comment]
Just in case. Only happens with Aluminium? All other Compressed Plates are fine?

**Comment by Explodia** [comment]
Iron, tin and bronze definitely are. Steel has a recipe, but I have not tried to make it yet. Have not  yet checked any other than those five

**Comment by JasonMcRay** [comment]
Ok thanks. We are currently working on the fix, but problem is we don't know what is causing that. It is definitely something with GregTech, because loading in .23 GT version works fine. Also in other modpacks (like Kirara) it works also just fine. So its Wierd!
