### ISSUE TITLE
creating wrought iron kills fps

### ISSUE THREAD

**Issue by wtfmynamesarepopular** [JasonMcRay/InfiTech-1.7#765]
#### Issue Description:

fps drop when making wrought iron.
re-enabled opis trying to figure out why i'm having 5fps top.
added the texture pack (purebdcraft+infitech addon)
added optifine because of these lags. even worse without.
#### Is the issue happening on server? Client? Both?

singleplayer, but server related issue
#### What happens:

5 fps when any kind of furnace melts iron nuggets.
edit: kind of inconsistent. i got considerable frame drops and a huge cpu load from my evy's workshops even without the transfer upgrade (though it got better without). i switched to using normal furnaces; and they still top the server timing -> tile entities list; a single one is comparable to the maxed out transfer node emptying my big reactor. bad influence on fps is a known problem of highly upgraded transfer nodes. and kinda expected if you watch the gui.
#### What you expected to happen:

please deactivate this bugged upgrade... i razed nearly my whole base on a backup copy to find the source before i knew about opis, and i didn't find it. with all the piping options, this upgrade doesn't add much anyway. except unnecessary cpu load for unsuspecting noobs like me.
edit: not sure, better fps :)
#### Steps to reproduce (if aplicable):
1. build ewy's workshops, insert worktables, furnaces and fuel.
2. setup auto transfer to and from the workshops to smelt and craft crushed iron into wrought iron ingots. i used chests in between as buffers.
3. watch framerate drop.
---
#### Modpack Version (Do _not_ use "latest"):

3.2.11 (Curse)
#### Your most recent log file where the issue was present:

wouldn't help.

**Comment by JasonMcRay** [comment]
Can you provide a screenshop of the Opis timings? So I can present it to "propper authorities" :)

**Comment by wtfmynamesarepopular** [comment]
oops wow, there's actually only one real lag generator. i was kinda
inefficient when i started the report, using 4/4 instead of 1/9 furnaces ;)
still, it's considerable.
​

**Comment by JasonMcRay** [comment]
I still need the opis timings. Because I am unable to replicate any considerable amount of lag when smelting Iron -> Worught Iron nuggets

**Comment by wtfmynamesarepopular** [comment]
well nvm, it's not as bad as i thought... i replied to the email with screenshots, but i guess that was automated; nvm
anyway, the lag occurs not when smelting iron nuggets to wrought iron, but when smelting crushed iron to iron nuggets. but it's still acceptable i guess, about 3 times as much as a normal furnace. just my huge array of furnaces kinda killed my weak cpu...
