### ISSUE TITLE
Quartzite screw missing recipy 

### ISSUE THREAD

**Issue by FrostySVK** [JasonMcRay/InfiTech-1.7#766]
#### Issue Description:
Also please state if you modified the modpack in any way.
Quartzite screw has no recipy, Quartzite bolt missing completely.
Not modified.

#### Is the issue happening on server? Client? Both?
Both.

#### What happens:
Quartzite screw has no recipy - most likely because the quartzite bolt is missing completely, cant be crafted and isn't in NEI either.

#### What you expected to happen:
N/A

#### Steps to reproduce (if aplicable):
N/A

____
#### Modpack Version (Do *not* use "latest"):
3.2.11

#### Your most recent log file where the issue was present: 
N/A
[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Duplicate #760
