### ISSUE TITLE
"HV Tools" quest doesn't like my JackHammer

### ISSUE THREAD

**Issue by wtfmynamesarepopular** [JasonMcRay/InfiTech-1.7#768]
thanks for the awesome pack! really hard to find any bugs at all!
#### Issue Description:
Also please state if you modified the modpack in any way.

activated opis.
didnt update to the latest version yet as it seems to have some problems like nugget duping.

#### Is the issue happening on server? Client? Both?

both

#### What happens:

after crafting the JackHammer(HV), the HQM doesn't realize it.
the quest book says empty, so i tried crafting it again without my jetpack. i also tried hss-s and tungstensteel as the quest text talks about tungstensteel. i also tried all 3 kinds of battery. 
(btw, there's also a typo, right side -> "Jackhamer"

#### What you expected to happen:

quest finished :p

#### Steps to reproduce (if aplicable):

1. get HQM to nuclear age
2. finish tungstensteel quest
3. try finishing "HV tools"

#### Modpack Version (Do *not* use "latest"):

3.2.10 (not latest, nvm if it's fixed in 3.2.11)

#### Your most recent log file where the issue was present: 

no crash

**Comment by JasonMcRay** [comment]
I think I have indeed fixed it in 3.2.11. As for the nugget dupe, I am right now preparing 3.2.12 update with couple hotfixes (nuggets included). So just keep an eye out, and if after the update the issue persist, please let me know.
