### ISSUE TITLE
galacticraft recipes

### ISSUE THREAD

**Issue by Nex4rius** [JasonMcRay/InfiTech-1.7#769]
#### Issue Description:

missing recipes

#### Is the issue happening on server? Client? Both?

client (havent tested server)

#### What happens:

lots of galacticraft machines don't have recipes

#### What you expected to happen:

they should have recipes

#### Steps to reproduce (if aplicable):

1. make new world
2. search galacticraft
3. try to look up recipes of the machines

____
#### Modpack Version (Do *not* use "latest"):

3.2.11

#### Your most recent log file where the issue was present: 

none

**Comment by Xavion3** [comment]
Specify more, a lot of machines don't have recipes because you're meant to craft everything in other methods.

Can you give examples? And double check the items it makes don't have a GT method of obtaining them first?

**Comment by Nex4rius** [comment]
- Oxygen Collector
- Oxygen Compressor
- Oxygen Decompressor
- Oxygen Bubble Distributor
- Oxygen Sealer
- Oxygen Detector
- Fuel Loader
- Cargo Loader
- Cargo Unloader

**Comment by JasonMcRay** [comment]
Wierd. Are you sure you have downloaded the pack properly? Can you try to redownload? Because in my instance all the recipes are present

**Comment by Nex4rius** [comment]
I've redownloaded everything and the recipes are still missing.

**Comment by JasonMcRay** [comment]
Hmm... I am currently making 3.2.12 hotfix, so when its up please try it in there and let us know

**Comment by JasonMcRay** [comment]
Also just out of curiosity, can you please upload minetweaker.log file?

**Comment by Nex4rius** [comment]
Its too big for pastebin.com :(

http://www.filedropper.com/minetweaker

**Comment by JasonMcRay** [comment]
It is possible that the new GregTech material system derped out. Hopefully it will get fixed in 3.2.13.

If you have time you can do quick test with redownloading latest GT.24 (https://www.dropbox.com/s/691teeuv0j7xdqc/gregtech-5.09.24.jar?dl=1)
Warning, just test it out. Do not use it (if you will not grab also the latest configs from git)

**Comment by Nex4rius** [comment]
It works in 3.2.13
