### ISSUE TITLE
Light Oxygen Tank not craftable

### ISSUE THREAD

**Issue by nephariouz** [JasonMcRay/InfiTech-1.7#771]
#### Issue Description:
The recipe for the Empty Light Oxygen Tank in NEI goes to the same recipe as the Full version of the tank. That recipe requires and Empty Light Oxygen Tank to craft so there is no way to craft an empty tank.

#### Is the issue happening on server? Client? Both?
Client

#### What happens:
The recipe for the Empty Light Oxygen Tank in NEI goes to the same recipe as the Full version of the tank. That recipe requires and Empty Light Oxygen Tank to craft so there is no way to craft an empty tank.

#### What you expected to happen:
Be able to craft the light oxygen tank.

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.11

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Can you please post a screenshot of what you see when searching for the recipe and also minetweaker.log file? Thanks

**Comment by nephariouz** [comment]
Screenshot of recipe for empty oxygen tank
(https://cloud.githubusercontent.com/assets/3893259/19224625/8419b66a-8e3e-11e6-8daa-c03a691f508c.png)

Log
(https://github.com/JasonMcRay/InfiTech-1.7/files/518640/minetweaker.txt)

**Comment by JasonMcRay** [comment]
Hmm... And there is no Shaped recipe when you click the arrows on top of NEI? Because according to the log file, the recipes are generated and loaded successfully.

**Comment by nephariouz** [comment]
No those arrows don't do anything for that item. They do work on every other item I've tried though.

My curse client seems to think that 3.2.11 is still the latest version.

**Comment by JasonMcRay** [comment]
Hmm.. That is interesting.

Have you tried to reinstall the modpack?

As for 3.2.12, it looks like something went wrong on the repository and it was not updated neither on Curse nor FTB Launcher.

If reinstalling will not help, wait for 3.2.12 to appear on the launcher.

**Comment by Nex4rius** [comment]
I also don't have the light oxygen tank recipe. I think its connected to https://github.com/JasonMcRay/InfiTech-1.7/issues/769

**Comment by nephariouz** [comment]
Looks like the recipe is fixed in 3.2.13. Thanks
