### ISSUE TITLE
Issue with 3.1.12 download.

### ISSUE THREAD

**Issue by olicool11** [JasonMcRay/InfiTech-1.7#772]
#### Issue Description:
Also please state if you modified the modpack in any way.
Modpack not modified. When attempting to download the 3.1.12 update via the FTB launcher the pack will fully download before failing to install with the error "Error while extracting zip: java.util.zip.ZipException: invalid code lengths set"

Apologies if this is the fault of the launcher, thought you would want to be informed anyway! This issue also happens for other users not just myself.

#### Is the issue happening on server? Client? Both?
Client- server manual zip download is fine.

#### What happens:
The launcher downloads the pack and then gives a failure to unzip.

#### What you expected to happen:
The pack to download then unzip and launch.

#### Steps to reproduce (if aplicable):

1. Update pack to newest version
2. Pack errors when attempting to unzip update.
...

____
#### Modpack Version (Do *not* use "latest"):
3.1.12

#### Your most recent log file where the issue was present: 
InfiTech2
Modpack is out of date.
Downloading Mod Pack
Issue with new md5 method, attempting to use backup method.
Local: 2538783B13A33F542BFF12D9FBACB6D6
Remote: 2538783B13A33F542BFF12D9FBACB6D6
Mods Folder: E:\Users\Oli\FTB\InfiTech2\minecraft\mods
Dynamic Folder: C:\Users\olive\AppData\Local\ftblauncher\ModPacks\InfiTech2\minecraft\mods
Error while extracting zip: java.util.zip.ZipException: invalid code lengths set
Extracting (Backup way)
Error while extracting zip: java.util.zip.ZipException: invalid code lengths set
Error unzipping modpack!!!

**Comment by Nex4rius** [comment]
Jason wrote that in the forum.
>v3.2.12 download is broken, please don't use. Wait for 3.2.13 to come up...

**Comment by olicool11** [comment]
Ahh I see, sorry hadn't occurred to me to check there- thanks.
