### ISSUE TITLE
Iconographic plates

### ISSUE THREAD

**Issue by Caotical** [JasonMcRay/InfiTech-1.7#776]
#### Issue Description:
Also please state if you modified the modpack in any way.

no

#### Is the issue happening on server? Client? Both?

both

#### What happens:

iconographic plate has no crafting recipe available in nei

#### What you expected to happen:

be able to craft icongraphic plates for mirrors and icongraph

#### Steps to reproduce (if aplicable):
N/A
1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):

3.2.12

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here] Uneccisarry

**Comment by JasonMcRay** [comment]
You cannot craft Iconographic Plate. You get it when you use Iconograph on your known block whilst having Mirrored Glass in your inventory.
