### ISSUE TITLE
update problems with curse

### ISSUE THREAD

**Issue by wtfmynamesarepopular** [JasonMcRay/InfiTech-1.7#778]
#### Issue Description:
Also please state if you modified the modpack in any way.

activated opis.

#### Is the issue happening on server? Client? Both?

happens before starting minecraft, N/A.

#### What happens:

1. 3.2.13 follows after 3.2.11, and 3.2.12 is missing. according to the changelog, 3.2.12 should be the newest version.
2. when trying to install 3.2.13, a window pops up:
profile error
curse encountered a problem during this operation
Error:
Exception of type 'Curse.Radium.InstallManagement.InstallTaskFailedException' was thrown.

#### What you expected to happen:

1. changelog version name should be the same as in curse.
2. 3.2.12 should install.
this might be related, i don't really know how curse works... and the exception is so general it hurts :(

#### Modpack Version (Do *not* use "latest"):

3.2.10 -> 3.2.13

#### Your most recent log file where the issue was present: 

no idea where to find curse's logs. (just the way curse/steam/origin developers want it to be?)

**Comment by JasonMcRay** [comment]
3.2.12 doesnt exist, It is corrupted version, so it doesn't appear on launcher.

As for 3.2.13 error you should report it to Curse, because they are managing the launcher and this error is not tied to modpack
