### ISSUE TITLE
No 3.2.12 version on FTB.

### ISSUE THREAD

**Issue by syrun97** [JasonMcRay/InfiTech-1.7#779]
#### Issue Description:
Also please state if you modified the modpack in any way.

#### Is the issue happening on server? Both?
client

#### What happens:

no 3.2.12 version on ftb but 3.2.13 version is shown

#### Steps to reproduce (if aplicable):

1.open FTB launcher
2.???
3.No 3.2.12
...

____
#### Modpack Version (Do *not* use "latest"):

FTB 1.4.12

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
3.2.12 doesnt exist... Or well.. It does internally, but it is corrupted zip file, so it has been removed from the launcher
