### ISSUE TITLE
Missing GregTech items

### ISSUE THREAD

**Issue by hubertnnn** [JasonMcRay/InfiTech-1.7#780]
After last update I found 2 missing items in my chests:

gt.metaitem.01.1064.name
This was one of the dusts that come from centrifuging rare earth

gt.metaitem.02.28512.name
Not sure what it was before but its in my gems chest so it probably was a gemstone of some kind.

Modpack Version: 3.2.13

**Comment by Timelife** [comment]
It seems like many thaumcraft related items have disappeared, astral silver, endium, vintium... This renders many Thaumcraft items including the runic matrix uncraftable.
