### ISSUE TITLE
Problem with alchemy including vitreus: gt.metaitem.01.8529.name

### ISSUE THREAD

**Issue by hubertnnn** [JasonMcRay/InfiTech-1.7#781]
When trying to do alchemy, every time I put vitreus to cauldron I get 
gt.metaitem.01.8529.name 
and vitreus is gone.
This happens even when using phials.

Steps to reproduse:
1. Empty cauldron
2. Drop phial of essentia - vitreus
3. There is 8 vitreus in cauldron
4. Drop second phial of essentia - vitreus
5. There is 4 vitreus in cauldron and you get gt.metaitem.01.8529.name 

Tested with vanilla glass, thickened glass and phials

Modpack Version: 3.2.13

**Comment by JasonMcRay** [comment]
Duplicate #780
