### ISSUE TITLE
RE-Battery ->Small Battery Hull?

### ISSUE THREAD

**Issue by Bryfer** [JasonMcRay/InfiTech-1.7#782]
You can only create RE-Batteries by filling Small Battery Hulls with molten redstone.
Why cant you put the RE-battery in an extractor to make it into Small Battery Hulls again?
it works with all other batteries using the Extractor

This is only an issue early game, before you find salt (or something else you can make batteries of)

____
#### Is the issue happening on server? Client? Both?

Both

#### What you expected to happen:

RE-Battery to turn into Small Battery Hull 

#### Steps to reproduce (if aplicable):

1. Craft Small Battery Hull
2. Put Small Battery Hull inside a Fluid Canning Machine, then add Molten Redstone in Fluid Canning Machine
3. Put RE-Battery inside Extractor
4. Become sad

____
#### Modpack Version (Do *not* use "latest"):

Infitech 2 version 3.2.13

**Comment by Nex4rius** [comment]
The reason why you cannot turn that back is because the RE-Battery is from ic2 and nobody made a recipe for that.

**Comment by Bryfer** [comment]
Yes. I figured that out too, That is why I wrote here so that "somebody" could add a recipe for that.
