### ISSUE TITLE
typos in changelog

### ISSUE THREAD

**Issue by syrun97** [JasonMcRay/InfiTech-1.7#787]
#### Issue Description:
Also please state if you modified the modpack in any way.

not modified

#### Is the issue happening on server? Client? Both?

changelog

#### What happens:

Typo

#### What you expected to happen:

in 14th line Dixed =>Fixed
in 15th line cu to=> cut to(maybe)

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):

3.2.14 changelog

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Oh c'mon grammar nazi :D 
The "Dixed the Fupe" is intended :P
