### ISSUE TITLE
[Recipe Issue] Missing quicksilver recipe

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#791]
We lost the mercury + circle mold in a fluid solidifier -> quicksilver recipe.

**Comment by wtfmynamesarepopular** [comment]
yea, first thing i did after updating was replacing my redstone->ruby dust fluid solidifier with a liquid trash bin :( 
to contribute: it's called mold (ball), not circle :)

**Comment by Timeslice42** [comment]
Yeah, that's the one :)

I find it shocking that you're not using your mercury for platinum production...

**Comment by codewarrior0** [comment]
Thanks! It was a lot simpler to stash all of that mercury in a drawer than in any kind of fluid tank.
