### ISSUE TITLE
astro miner + GT ores

### ISSUE THREAD

**Issue by wtfmynamesarepopular** [JasonMcRay/InfiTech-1.7#793]
Patchlog 3.2.11:
- Added compatibility for Astrominer with GregTech ores

Quest book 3.2.15:
"... currently, the Astro Miner is not able to mine GregTech ores and will get stuck ..."

which one is true?

**Comment by JasonMcRay** [comment]
When I was writing the quests it was bugged out. I wrote the quests while ago...

Anyway, the astrominer can mine GT ores as stated in the changelog.
