### ISSUE TITLE
Grinding balls(rounds) not craftable except dark steel

### ISSUE THREAD

**Issue by Amadeus99** [JasonMcRay/InfiTech-1.7#794]
#### Issue Description:

Titanium rounds, Naquadah Alloy rounds and Neutronium rounds are not craftable.  These rounds are used as grinding balls according to the ender io configs.  So, at the moment, only dark steel rounds can be used as grinding balls.

Modpack changes:
Disabled Mouse Tweaks and Open Eye.
Client: Installed OptiFine_1.7.10_HD_U_D6
  Updated Storage Drawers to 1.10.4
Server: Installed Morpheus-1.7.10-1.6.21
#### Is the issue happening on server? Client? Both?

SMP.  Haven't checked SSP.

---
#### Modpack Version (Do _not_ use "latest"):

3.2.15

**Comment by codewarrior0** [comment]
GT 5.09.25 disables unused materials and parts, enabling them again if they are found in a MT script. But the EnderIO configs are not MT scripts, so GT can't see that the rounds are being used.

It's not clear how to edit the GT configs to specifically enable those rounds, but it sounds like you can just add a MT script like Titanium Round->Titanium Round, and then GT will notice it's being used for something and enable it.

**Comment by JasonMcRay** [comment]
Dayum.. I thought I fixed it manually... Guerss i forgot to push the changes out.... thanks for a report, will get fixed in .16
