### ISSUE TITLE
Crafting quests with Ewys Workshop

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-1.7#795]
Doesn't detect crafting with ewy

**Comment by JasonMcRay** [comment]
reported to dev: https://github.com/EwyBoy/EwysWorkshop/issues/15

**Comment by codewarrior0** [comment]
Same with LogisticsPipes Request Table (NOT automated Crafting Table): RS485/LogisticsPipes/issues/1074
