### ISSUE TITLE
Thaunmonoicon issues.

### ISSUE THREAD

**Issue by svhss** [JasonMcRay/InfiTech-1.7#796]
#### Issue Description:
 Thaunmonoicon does not show research names or descriptions properly.

**Please state if you modified the modpack in any way.**
Nope!

#### Is the issue happening on server? Client? Both?
I play only single player, and so does the issue happens there.

#### What happens:
 Thaunmonoicon does not show research names or descriptions properly.
 http://i.imgur.com/czrrSMq.png

#### What you expected to happen:
A working Thaunmonoicon 

#### Steps to reproduce (if aplicable):

1.Click play.
2.Open  Thaunmonoicon
3.Check names.

____
#### Modpack Version (Do *not* use "latest"):
3.2.11 (From curse client)

#### Your most recent log file where the issue was present: 
http://pastebin.com/MqpQrNKR

**Comment by JasonMcRay** [comment]
Please update to latest and check if the issue persists.

**Comment by Xavion3** [comment]
Also, what language is your game set to? Just in case it matters, all our custom researches only have US english entries.

**Comment by svhss** [comment]
Updated to 3.2.15 and the issue is still there, playing on English (UK), also tried on US with the same results.

**Comment by JasonMcRay** [comment]
Can confirm this with different languages than EN_US
