### ISSUE TITLE
recipe bug: scanning electric piston (IV) and conveyor modules (IV)

### ISSUE THREAD

**Issue by wtfmynamesarepopular** [JasonMcRay/InfiTech-1.7#797]
#### Issue Description:
Also please state if you modified the modpack in any way.

deactivated annoying fir tree spawning in extrabiomes config.
installed optifine.
cheated a little bit by increasing biogas burn value (took me 2 weeks to get the materials to build a large power plant early game just to realize it was actually losing power... f*** you greg :p )

#### Is the issue happening on server? Client? Both?

tested in ssp.

#### What happens:

data sticks disappear into the void when trying to scan an electric piston(IV) (in an advanced scanner III).
the piston doesn't get used up, neither does the scanning process start.

edit: on a side note, the quest for building an assembly line expects players to build an assembly line that's 1 block too short to do anything.

edit 2: the same bug happens with conveyor modules.
motors, robot arms, pumps, sensors, emitters and field generators do work though.

#### What you expected to happen:

piston/conveyor modules gets scanned, some time later the scanned data comes out so i can craft LuV pistons in the assembling line.

#### Steps to reproduce (if aplicable):

1. build an IV piston, multiple data sticks and a scanner. i dont think the scanner's level matters.
2. put piston and stack of data sticks in scanner.
3. watch single data sticks disappear every few seconds.

____
#### Modpack Version (Do *not* use "latest"):

3.2.15

#### Your most recent log file where the issue was present: 

issue doesn't show up in log.

**Comment by JasonMcRay** [comment]
Fixed in .16 via GT Update -> 5.09.26
