### ISSUE TITLE
Missing Nitric Acid and Nitration Mixture "fluid" to "cell" recipes

### ISSUE THREAD

**Issue by antropod** [JasonMcRay/InfiTech-1.7#798]
Unable to craft Nitric Acid and Nitration Mixture cells neither with Fluid Canner nor with EnderIO Tank.
____
latest

**Comment by wtfmynamesarepopular** [comment]
latest? seriously? ~~
3.2.15
but yea, one can't fill cells with that stuff.

**Comment by Bryfer** [comment]
same with Epichlorohydrin (only tested with EnderIO Fluid Tank), SP 3.2.15

**Comment by JasonMcRay** [comment]
Intended. A lot of different fluids cannot be put into cells... Minecraft limitation on maximum number of items. For storage use Drums/Tanks.
