### ISSUE TITLE
Chunks not loading

### ISSUE THREAD

**Issue by alven4** [JasonMcRay/InfiTech-1.7#801]
#### Issue Description:
I created new world (with Optifine at lowest settings) and after a short time walking I hit array of not loaded chunks. I then relogged (closed world and opened again) and the chunks loaded fine but after a while I hit another array of not loaded chunks. I repeated this few times while changing setting of the Optifine and this issue persisted. Using F3 + A didn't help at all and neither waiting did, only relog and some quick swapping render distances from 2 to 11 and back repeatedly (then Minecraft froze for a minute) loaded the not loaded chunks.
I removed the Optifine and started Minecraft again and the not loaded chunks persisted. Only relogging loaded them back again, nothing else.

I am running Minecraft at lowest graphical settings, with recommended java arguments (I only changed -Xmx 4G to -Xmx 2G, -Xms 2G to -Xms 1G and parralel to 2). Only added mod besides Optifine have been NoNausea mod (modifies nausea effect only). I am using 64-bit java 1.8.0_51 (I cannot update it because the java update breaks my graphic driver) with 4 gb RAM installed and processor with 2 cores.

With Optifine, the Minecraft didn't lag and it was running at 40-50 FPS, without it, Minecraft started to stutter and FPS was much lower.

#### Is the issue happening on server? Client? Both?
Client and I didn't test at server (I don't have one).

#### What happens:
Some chunks are not loaded even after pressing F3 + A and they get loaded only after relog.

#### What you expected to happen:
I expect all chunks to be loaded when I am near them or at least get loaded after pressing F3 + A.

#### Steps to reproduce (if applicable):

1. Create new world.
2. Walk around.

That is all I did.
____
#### Modpack Version (Do *not* use "latest"):

3.2.15

#### Your most recent log file where the issue was present: 

https://gist.github.com/alven4/298b94d110c5a595312130c5757f3871

**Comment by JasonMcRay** [comment]
2Gigs allocated for InfiTech is really low. There is nothing noone can do but you and upgrade your PC.

**Comment by codewarrior0** [comment]
Very rarely, while moving long distances around the world, I'll find a strip of chunks that are not rendered. I found out that just changing my view distance setting will make them render immediately, instead of logging out and back in.

**Comment by alven4** [comment]
I found a solution with the Optifine installed. The render distance has to be at least 4 for the chunks to load properly.

**Comment by Timeslice42** [comment]
My render distance is set to 12 or 16 (depending) and I still see chunk errors from time to time. What alven4 was describing sounded far more frequent though.

**Comment by alven4** [comment]
Are you using Optifine with settings for best performance? 
I am and once I increased my render distance to 4 (I can't go much higher so I don't know what happens with render distance 12), unloaded chunks are extremely rare.

**Comment by Timeslice42** [comment]
I use multi-core settings, and I allocate 3 ticks (per second?) for loading chunks. I don't recall if I have world smoothing on or not.
