### ISSUE TITLE
Suggestion (Internal Tank switching)

### ISSUE THREAD

**Issue by Lithorn** [JasonMcRay/InfiTech-1.7#802]
If you examine the Fluid canner from IC2, It has the ability to switch its internal tanks, allowing you to empty its contents without loss. Currently no gregtech machine has this ability except I think the canners which can have their input drained IIRC. 

Things like the Chemical reactant machine, or the electrolizer, it would be nice if you could switch their tanks so that you can empty them without losing your liquids.

**Comment by codewarrior0** [comment]
Probably more appropriate to post this to GT issues, as I don't think there's much InfiTech can do about it.

In fact, a quick issue search shows: Blood-Asp/GT5-Unofficial#471
