### ISSUE TITLE
Large Steam Turbine, incomplete structure after update

### ISSUE THREAD

**Issue by Bryfer** [JasonMcRay/InfiTech-1.7#808]
#### Issue Description:
Large Steam Turbine stops wokring after update (3.2.16)

Also please state if you modified the modpack in any way:
Railcraft world anchor not needing fuel to work (already reverted back to normal, still dosnt work)

#### Is the issue happening on server? Client? Both?
Only tried on SP but in my world, and in creative.

#### What happens:
After installing the newest update (3.2.16) from update (3.2.15) using the FTB Launcher, my Large Steam Boiler stops working. It keeps saying Incomplete Structure

I have tried rebuilding it, placing the hatches at diffrent places. It looks like it dosnt find my maintenance hatch (I cant fix the problems with it)

If I revert back to 3.2.15 I can get it running again.

#### What Blocks I used:
1x Large Steam Turbine (Front, Centered)
1x Maintenance hatch (Topside, "Front" slot)
1x Input Hatch (MV) (Topside, "Back" slot)
1x Output Hatch (MV) (Rightside, "Front" slot)
_1x Muffler Hatch (MV) (Rightside, "Back" slot) -- Part removed since it wasnt used (Steam)_
1x HV Dynamo Hatch (HV) (Back, Centered)
28x(?) Turbine Casing

1x Small Turbine Blade, Cobalt

Works if I rebuild it in 3.2.15, cant get it running in 3.2.16

To get steam into it I use an Large Steel Fluid pipe which has an Shutter module connected on the bottom side and an Machine Controller to the Back 

The power gets feeded directly into an High Voltage battery buffer, which has an energy detector upgrade.

I use WR-CBE Logic for Wireless Redstone

#### Steps to reproduce (if aplicable):

1. Build it like i did with version 3.2.15 (check image)
2. Upgrade to 3.2.16
3. Get energy problems
...
![backright15](https://cloud.githubusercontent.com/assets/22825059/20037838/970f370e-a428-11e6-8653-962302d126ed.jpg)
![frontleft15](https://cloud.githubusercontent.com/assets/22825059/20037839/97106502-a428-11e6-882e-c68fc2031b17.jpg)

____
#### Modpack Version (Do *not* use "latest"):
3.2.16

#### Your most recent log file where the issue was present: 

needed? if so Ill post it aswell.

**Comment by JasonMcRay** [comment]
Unfortunately I am unable to replicate it. I have build it exactly the same as you have it. Works perfectly fine. Will you be able to share the world you have it built in, so I can take a look?

**Comment by Timeslice42** [comment]
@Bryfer FYI, if you want a fueless chunk loader I recommend setting the dimensional anchor to not needing fuel (in config/immibis.cfg) and using that instead.

**Comment by aBash85** [comment]
i know about this problems out of other GT packs.  build one cable between the batbuffer and turbines dynamohatch it will work ;) or some time u got hyperenergetic nitor in ur inv, it will spawn some "ghost light blocks" inside the turbine. Thaumcrafts arcane lamp will do that same.

**Comment by Timeslice42** [comment]
Oh yeah... internal ghost blocks can be a real hassle. You could open your world in MCEdit to check if there are any tile entities inside your turbine.

**Comment by JasonMcRay** [comment]
Any news on this? Still an issue?
