### ISSUE TITLE
Pressurized fluid conduit requires HV

### ISSUE THREAD

**Issue by ct-klein** [JasonMcRay/InfiTech-1.7#810]
#### Issue Description:
Also please state if you modified the modpack in any way.
When making a pressurized fluid conduit it requires vibrant alloy which is an HV process to create.
By comparison, the EnderIO fluid conduit only requires MV to create and is the better conduit.

#### What you expected to happen:
I would expect that they would be reversed, the better conduit having the higher requirements.

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.16

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by Nex4rius** [comment]
The fluid conduit is better than the pressurized fluid conduit? That's new.

**Comment by ct-klein** [comment]
not the 'fluid conduit', the enderio fluid conduit.

**Comment by codewarrior0** [comment]
Are you sure? Ender Fluid Conduit requires Enderium Nugget, which requires Enderium Base to be made in an HV chemical reactor. 

<sub>Smelting the Enderium also requires an EBF with Nichrome coils, which require an HV-powered EBF to make, but this isn't truly *HV tier*</sub>

**Comment by codewarrior0** [comment]
Actually, since GregTech *mumble*.25 added its own recipes for EnderIO alloys, it looks like a bunch of stuff got bumped up a tier. I remember being able to make Pulsating Iron and Vibrant Alloy at MV-tier, using an ordinary Alloy Smelter instead of an EBF.

Maybe Pressurized Fluid Conduit should be bumped down to MV somehow?

**Comment by Timeslice42** [comment]
Or better yet, just drop the new GT recipes for the old ones we used to have...

**Comment by JasonMcRay** [comment]
I will be returning the old recipes we had, but will tier them slightly.
Pulsating Iron -> Alloy Smelter (any)
Energetic Alloy -> Alloy Smelter (MV)
Vibrant Alloy -> Alloy Smelter (MV, slightly higher voltage than Energetic)

**Comment by JasonMcRay** [comment]
Closed via 23ecf2f6d31e86cd271b1b98df719f337e4a2da7
