### ISSUE TITLE
BUG Processing Array with all kind of Macerator

### ISSUE THREAD

**Issue by aBash85** [JasonMcRay/InfiTech-1.7#811]
#### Issue Description:
I tryed in SP and Multiplayer. If i setup a Processing Array with Macerators or Pulverizer, it will void the products. Output hatch keeps empty but the material get consumed.

#### Is the issue happening on server? Client? Both?
Both

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.14

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by Nex4rius** [comment]
If there is no place for the items to go they will be voided. A macerator needs an output BUS not a hatch.

**Comment by aBash85** [comment]
sorry i tryed both hatch and bus

**Comment by JasonMcRay** [comment]
Unable to recreate in 3.2.16, please update and if the issue is still present, please reopen.
