### ISSUE TITLE
Processing Array keeps voiding the products when macerating certain ores.

### ISSUE THREAD

**Issue by Dacer1** [JasonMcRay/InfiTech-1.7#816]
#### Issue Description:
The Processing Array voids the outcome of certain ores like Uranium 238 or Redstone.
Strangely it macerates Almandine Ore and Cobblestone normally.
This issue is happening on any kind of macerator.

#### Is the issue happening on server? Client? Both?
The issue is happening on both in Singleplayer as well as on the Server.

#### What happens:
-Trying to macerate certain Ores
-No products in the output busses

#### What you expected to happen:
I expected to have a Processing Array macerating my ore with an outcome.

#### Steps to reproduce (if aplicable):

1. Building a Processing Array with an Output Bus and an LV Input Bus and a HV Energy Hatch (probably      not necessary to mention), the Array is filled with any kind of macerator available (tested for LV,MV,HV  and EV variants)
2. Putting ores like Redstone/Yellow Limonite/Uranium-238 in the Processing Array.
3. Watch the Processing Array turning on and off after the macerating would be normally done.
4. Looking into the Output Bus where nothing was returned.
5. Looking into the Input Bus seeing 1 ore which you tried to macerate disappearing when dragging it into your inventory.

____
#### Modpack Version (Do *not* use "latest"):
The modpack version I was using was v3.2.15

#### Your most recent log file where the issue was present: 

I'm sorry that I don't really know what to post here.
I still hope the information provided is enough to solve this issue.

**Comment by JasonMcRay** [comment]
Dupe #811. Please update to 3.2.16
