### ISSUE TITLE
Crash with Modular Exoskeleton 

### ISSUE THREAD

**Issue by a3626a** [JasonMcRay/InfiTech-1.7#820]
#### Issue Description:
I'm using SEUS shader.

I was trying to use Modular Exoskeleton with some items (described below).
It eventually crashed

#### Is the issue happening on server? Client? Both?
When I get this crash on multiplayer server, I see 'Internal Server Error'  and on single player, it just crashed. Attached log was generated at single player

#### What happens:
CRASH!

#### What you expected to happen:
Just not wanna use them :)

#### Steps to reproduce (if aplicable):
I wear 4 modular exoskeleton with
Medium Lithium Battery
MV Electric Motor
Good Elecronics
Aluminium plate

____
#### Modpack Version (Do *not* use "latest"):
3.2.17

#### Your most recent log file where the issue was present: 
http://pastebin.com/yEr0QN6i

**Comment by JasonMcRay** [comment]
Does it crash without the Shaders?

**Comment by a3626a** [comment]
I didn't complete remove Shaders, but it still crashes if i disable the shaders by option.

**Comment by JasonMcRay** [comment]
fast repost to Blood: https://github.com/Blood-Asp/GT5-Unofficial/issues/769

**Comment by Timeslice42** [comment]
Did you disable the shaders, or just switch it back to default rendering? There's a difference, and the only way to really be sure is to not load the shader mod. That being said I find it very difficult to imagine a way in which shaders could cause this error.
