### ISSUE TITLE
Wither Chain Kill Crash

### ISSUE THREAD

**Issue by ToAsgaard** [JasonMcRay/InfiTech-1.7#823]
Issue Description:
After around 10-15 kills in a row of the wither while testing an automatic kill setup in creative, the game would crash.  Happened twice, however if I crashed and restarted, I could load the world fine and continue killing the wither.  Only two modifications to the pack are Decocraft and sphax textures.  I did try it without decocraft once as well, however the crash still occured.

Is the issue happening on server? Client? Both?
I had the server crash once and the client crash another according to the crash logs.

What happens:
A kill or two before the crash, the wither's health lags at 0 for around 5 secs while the fps drops and freezes and then he finally dies.  On the crash death, the fps steadily drops and locks up again and again, then finally freezes and I have to force shutdown.  Tried waiting once for 5 minutes to see if it would finally catch up, but no dice.

What you expected to happen:
The wither to die and much rejoicing to ensue.

Steps to reproduce (if aplicable):

1. Make a wither box with 2 thick walls of reinforced obsidian.
2.Stick a tesla coil onto the side of the box with some power attached, tried both gregtech to transformers and mfe power.
3.Spawn wither and let it die 10+ times.
4. After that, the fps will start to chug more and more after each death, and then finally crash.

Modpack Version (Do *not* use "latest"):

3.2.17

Your most recent log file where the issue was present: 
[crash-2016-11-21_07.57.25-client.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/604221/crash-2016-11-21_07.57.25-client.txt)

**Comment by JasonMcRay** [comment]
The deathknell ability is pretty devastating. Testing lower strength values...
