### ISSUE TITLE
multiplayer server login

### ISSUE THREAD

**Issue by f0rwards13** [JasonMcRay/InfiTech-1.7#824]
so I launched infitech and when I try and join any multiplayer server it just says logging in and will never join me in the server. any solutions to this problem?

**Comment by vksfn** [comment]
Yes me and my friend are having the same problem. and dont know what to do. we have restarted clients and everything.

**Comment by Timeslice42** [comment]
Are you sure you're not running a newer version of the pack than the server is?

**Comment by JasonMcRay** [comment]
No response from reporter. Closed
