### ISSUE TITLE
IC2 Coolant in Big Reactor?

### ISSUE THREAD

**Issue by codewarrior0** [JasonMcRay/InfiTech-1.7#825]
Currently, a Big Reactor can be used to drive steam turbines, but the 1:1 ratio in steam production means that it takes sixteen reservoirs to supply water to a reactor that produces enough steam to run a single Turbo Steam Turbine. With a minor patch to BigReactors ([probably somewhere in here](https://github.com/erogenousbeef/BigReactors/blob/master/src/main/java/erogenousbeef/bigreactors/common/multiblock/helpers/CoolantContainer.java)), the reactor could accept IC2 coolant and output IC2 hot coolant instead. This can then be used in the Large Heat Exchanger to produce enough Steam to drive a Large Steam Turbine. Any thoughts on this idea?

**Comment by JasonMcRay** [comment]
Yes. But I would much prefer just using their API to do this within InfinityCore mod, instead of modifying the base mod. But I am considering InfiTech 2 as frozen for 1.7.10. Only major bugfixes will be done and submitted PRs if they will make sense.

**Comment by Timeslice42** [comment]
@codewarrior0 What he's saying is he might accept it if you make a PR ;)

**Comment by codewarrior0** [comment]
Alas, the coolant registry in Big Reactors was never code complete, so there's no way to do this with just a patch to InfinityCore. I'd have to do a fork of BR and finish implementing the coolant registry, or else do a quick hack that makes it recognize IC2 coolants. If I ever get around to doing that I'll let you know.
