### ISSUE TITLE
Diesel Engine still energy output when off 

### ISSUE THREAD

**Issue by danirpg** [JasonMcRay/InfiTech-1.7#830]
#### Issue Description:
The diesel engine continues to emit power when it is turned off.

#### Is the issue happening on server? Client? Both?

Yup

#### What happens:

The diesel engine continues to emit power when it is turned off.

#### What you expected to happen:

It stops emitting energy when it is off.

#### Steps to reproduce (if aplicable):

1. Build an diesel engine(Multiblock)
2. Start it and use Portable Scanner to see the power output
3. Stop Diesel engine when emit power and check with scanner

____
#### Modpack Version (Do *not* use "latest"):

v3.2.17

#### Your most recent log file where the issue was present: 

No log but GIF to explain it: https://giphy.com/gifs/3o6Zt0VBs7Va2NZsYw

**Comment by JasonMcRay** [comment]
It does not produce any energy when its turned off. It remembers the last state it was in before stopped, that is what is displayed by the scanner. But the energy is not produced. This goes for other multiblock generators as well.

**Comment by danirpg** [comment]
http://giphy.com/gifs/3o6Zt2NwY59EnCrJWo

**Comment by JasonMcRay** [comment]
Hmm.  What are you using as fuel?

**Comment by danirpg** [comment]
Nitro Diesel

**Comment by JasonMcRay** [comment]
Well of course it will be filling up when you start the diesel engine, it will pile fair amount of energy in the Dynamo Hatch and when you connect it it will start dumping the stored energy into the batteries. If you will leave it like that for couple seconds it will empty the stored energy in the Dynamo Harch and not produce any more.

**Comment by danirpg** [comment]
http://giphy.com/gifs/3o6Zt3UodZqhTay8c8

**Comment by danirpg** [comment]
you see the gif? @JasonMcRay
