### ISSUE TITLE
Is Mining Laser recipe bugged?

### ISSUE THREAD

**Issue by OmikronGamma** [JasonMcRay/InfiTech-1.7#831]
1)I "insert" recipe directly from NEI -> Laser is "there", but i cant craft it, nothing happens when i click it.
http://imgur.com/DQiyx3L
2)I insert all parts manually, and laser icon dissapears on putting Charging Lapotron Crystal (both charged and discharged), no craft at all.
http://imgur.com/mn9oo2W
Basicly, as soon as i put Charging Lapotron Crystal into crafting grid, crafting is no longer available.

I tried both - my current playthrough and new test-creative world.
Client, 3.2.17.

PS, Sorry, i accidently deleted your bug-report template, and recreating this post wont restore it.

**Comment by JasonMcRay** [comment]
Yes, it is bugged out. It looks for the crystal without any Metadata, but that one is not obtainable: https://github.com/Blood-Asp/GT5-Unofficial/issues/775

**Comment by JasonMcRay** [comment]
For now I have made workaround fix for this.
Download and replace workarounds.zs script file in scripts folder:
https://raw.githubusercontent.com/JasonMcRay/InfiTech-1.7/master/scripts/workarounds.zs
