### ISSUE TITLE
Essentia feedback loop (Lux/Tenebrae) with Railcraft stone alchemy recipe

### ISSUE THREAD

**Issue by CelestialPhoenix** [JasonMcRay/InfiTech-1.7#832]
#### Issue Description:
Railcraft Quarried and Abyssal stone can be made with 2 Lux or 2 Tenebrae.
They can then be smelted into their respective block- worth 4 Lux/Tenebrae each.

Lux is fairly easy to get, but Tenebrae is rather tricky- and is used in a few high end recipes (such as stainless steel)

Pack version is 3.2.17

**Comment by FURi4N** [comment]
Tenebrae tricky? Farm shrooms ;) How much u need when u can auto farm it, or mana beens clean tenebrae, but u have to work for it, like that little loop. U should check with an auto chisel want can u do ;) lux, tenebrae, ordo, lucrum all can be made from stone with some  process and so but u need stabel fuel source, mettalum to use the gain. Actually to get that need a of lot progress in Gt too in this pack if u aren't in creative.

I really like the abyssal to build and i dont have to make quarrys for it.
