### ISSUE TITLE
Jabba BSpace upgrade

### ISSUE THREAD

**Issue by trlababalan** [JasonMcRay/InfiTech-1.7#833]
This is not a bug report, it's a feature request.

It's disabled currently and I'd really like to have it on the server. In my case, it would be convenient to have the same "my base block" barrel on two places in the base. Considering that we can use Magic Mirrors, I see no reason why BSpace upgrades shouldn't exist.

If they're too cheap, change the recipe to piston-magic mirror-piston (vertical). It would make sense, remain balanced, not break anything and there would be one less item in NEI that says "This item is DISABLED!"

#### Modpack Version:    3.2.17.

**Comment by JasonMcRay** [comment]
BSpace upgrade allows easy automation. If you want to have your "base block" available, use Ender Chest.

**Comment by trlababalan** [comment]
Yeah... A hopper or a hungry maw has to be hidden behind drawers, catching the drops of a mirror. Then a comparator, wirelessly linked, detects the "fullness" of those drawers. This way, you're still able to get all the items on both (or more) ends. Equalizing them is not an expensive problem, but this kind of replacement creates comparatively more lag and takes more space. 

I want the end-goal to be just clicking for a stack, or shift-clicking for a single item.
Ender Chest requires opening an inventory.

So... It's a definite no go?

**Comment by Timeslice42** [comment]
Can't you use the super crafting frame item frame to do that? Or does it not work on ender chests?

**Comment by Nex4rius** [comment]
The endgame solution would be a simple me system for that item (with a quantum bridge).
