### ISSUE TITLE
WTF on forestry worktable

### ISSUE THREAD

**Issue by syrun97** [JasonMcRay/InfiTech-1.7#838]
#### Issue Description:
Also please state if you modified the modpack in any way.

use faithful 32x resource pack

#### Is the issue happening on server? Client? Both?

client

#### What happens:

![2016-12-14_20 01 00](https://cloud.githubusercontent.com/assets/19798397/21179671/69e18d58-c238-11e6-8dac-aeb2c3c783b3.png)

#### What you expected to happen:

see the lock mark rather than annoying cheeseburger(or bacon cheeseburger).

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):
latest
3.2.18

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by Xavion3** [comment]
First off, a quick but important question. Does disabling your texture pack fix the problem?

**Comment by syrun97** [comment]
when i use default texturepack that fixed but i wanna use faithful texturepack. :'(
![2016-12-15_21 29 56](https://cloud.githubusercontent.com/assets/19798397/21224093/cc9beaee-c30d-11e6-9f36-b8e4d759cef7.png)

**Comment by Xavion3** [comment]
I'm sorry but I don't know the texture pack, what's the bug in the second image?

**Comment by Timeslice42** [comment]
Yeah, this is completely inside the Faithful texture pack itself, and has nothing to do with anything we could change in the modpack.
