### ISSUE TITLE
I am bender quest bug after update .18

### ISSUE THREAD

**Issue by Erixonich** [JasonMcRay/InfiTech-1.7#839]
#### Issue Description:
Also please state if you modified the modpack in any way.

#### Is the issue happening on server? Client? Both?
probably only me(Xonich) and person in party (Noralltach)  - we have common quests
I think if this happened due to update it can be solved by op command /hqm edit <nickname>, manually completing this quest.

#### What happens:
quest cant be completed with all parts completed

#### What you expected to happen:
quest can be completed

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.18

#### Your most recent log file where the issue was present: N/A
![2016-12-15_04 38 12](https://cloud.githubusercontent.com/assets/12836717/21208777/3b365fe4-c281-11e6-8429-c512695fb0e5.png)
![2016-12-15_04 38 20](https://cloud.githubusercontent.com/assets/12836717/21208776/3b34724c-c281-11e6-9fd6-f5bc9c62cae1.png)

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Yes. This can happen. Its because of I moved some quests around and HQM doesn't really like it. Using /hqm edit helps. there is nothing I can do on the modpack side
