### ISSUE TITLE
blast furnace inhancement

### ISSUE THREAD

**Issue by syrun97** [JasonMcRay/InfiTech-1.7#841]
when i tped into working EBF(making tungsten), i didn't take any damage from heat. but i tped into working bronze blast furnace, i take damage from lava. that's very unrealistic. what's happening on EBF? that smelt tungsten with magic?

(i'm bad at English please don't care about spellings)
![2016-12-20_21 17 07](https://cloud.githubusercontent.com/assets/19798397/21350539/2bac9e8e-c6fb-11e6-8af8-b7773ca53ca8.png)
EBF that smelt tungsten
![2016-12-20_21 20 58](https://cloud.githubusercontent.com/assets/19798397/21350542/2d1fa428-c6fb-11e6-8732-4184e0567cef.png)
steel making bronze BF

**Comment by JasonMcRay** [comment]
Not related to modpack. Not a modpack bug. I have nothing to do with mods themselves. If you want some enhancement to a mod, than ask mod devs.

**Comment by Timeslice42** [comment]
The EBF is a closed multiblock, there's no legitimate reason for a player to ever be in there while it's working. The BBF has an open top, a player could totally fall in there while it's working.

Functioning as designed, no changes necessary.
