### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by syrun97** [JasonMcRay/InfiTech-1.7#846]
#### Issue Description:
Also please state if you modified the modpack in any way.

used faithful texturepack but not in mods

#### Is the issue happening on server? Client? Both?

server

#### What happens:

game crashs

#### What you expected to happen:

not crash

#### Steps to reproduce (if aplicable):

1.I
2.Dont
3.Know
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.18
or latest

#### Your most recent log file where the issue was present: 

[crash-2016-12-25_20.13.01-server.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/672165/crash-2016-12-25_20.13.01-server.txt)
[crash-2016-12-25_20.09.24-server.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/672164/crash-2016-12-25_20.09.24-server.txt)

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
As a server owner you must find where the crash is originating from.

It is definitely some entity ticking, can be the chicken as you can see in the crash log. Either remove the entity or regen whole chunk with MCEdit.

**Comment by syrun97** [comment]
I removed chicken with MCEdit and it worked.
FIXED YAY

**Comment by JasonMcRay** [comment]
If it keeps happening it can be tied to the chunk/world corruption. Still I cannot do anything about these crashes, because its vanilla minecraft mechanic crashing.
