### ISSUE TITLE
pneumaticcraft refinery

### ISSUE THREAD

**Issue by Nex4rius** [JasonMcRay/InfiTech-1.7#848]
#### Issue Description:

The PneumaticCraft Refinery only works with the normal oil and not with the gregtech light oil, heavy oil and raw oil.

#### Is the issue happening on server? Client? Both?

both

#### What happens:

You cannot insert the other oil types into the refinery.

#### What you expected to happen:

You can insert the other oil types into the refinery.

____
#### Modpack Version (Do *not* use "latest"):

3.2.18

**Comment by JasonMcRay** [comment]
Intended. Having PcCraft refinery for GT oils would break balance, since it would work similiar to Distillation Tower and energy free, because you cannot balance heat and EU usage together

**Comment by Nex4rius** [comment]
Could you at least allow the gregtech LPG in the pneumaticcraft machines or is it intended that we cannot use anything from the gregtech oil processing to make pneumaticraft plastics?

**Comment by JasonMcRay** [comment]
No I cant allow anything regarding PcCraft, since I have no access to it. It would need to be done on the PcCraft side, but same as 99% of other mods, it is no longer being developed for 1.7

**Comment by Timeslice42** [comment]
@Nex4rius Time to learn how to use ASM, Darkness :)
