### ISSUE TITLE
Cannot login to server after crash on equiped modular nano leggings 

### ISSUE THREAD

**Issue by zeyad001** [JasonMcRay/InfiTech-1.7#853]
#### Issue Description:
Also please state if you modified the modpack in any way.

Added Extra Cells 2

#### Is the issue happening on server? Client? Both?

Server. 
Single Player game is fine
Other person on the server can login fine

#### What happens:

Timed out or internal server error on login

#### What you expected to happen:

Normal Login/ No Crashing

#### Steps to reproduce (if aplicable):

1. Build Gregtech modular nano armour set
2. Put 2 mv pistons and a good circuit onto the leggings
3. Attempt to jump to test that the jump boost is working
4. Crashes the game. Have to restart client side, Cannot rejoin the server
...
Note I have tested the modular armour on the single player world by spawning it in. It seems to be working fine.
____
#### Modpack Version (Do *not* use "latest"):

3.2.19.1

#### Your most recent log file where the issue was present: 

http://pastebin.com/xAYiEHrB
http://pastebin.com/BeuGRqxW
[pastebin/gist/pastee etc link here]

**Comment by zeyad001** [comment]
Similar Issue : Blood-Asp/GT5-Unofficial#851

**Comment by Timeslice42** [comment]
Retest with the latest version of the pack.

**Comment by zeyad001** [comment]
Still present. Have to use the nbt editor to remove the item from player.dat. We probably have to wait for the new gregtech release.

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10
GT Modular armor is very buggy. it might have been fixed in .29 of GT. You can update GT, but keep in mind some things might get broken in the recipes. You can jump on our discord if you will need assistance and we might provide you with a script file to fix some of the recipe issues.
