### ISSUE TITLE
Lack of proper transfer of Nuclear Reactor power to Gregtech-usable EU

### ISSUE THREAD

**Issue by uladak** [JasonMcRay/InfiTech-1.7#854]
#### Issue Description:
Currently, with a Nuclear Reactor, it will output IC2-grade EU. This means that it needs to be awkwardly transformed down with little-to-no explanation via the Quest Book.

#### Is the issue happening on server? Client? Both?
Both.

#### What happens:
When you try to connect a Gregtech cable to the nuclear reactor, it will not work. You have to jump a few hoops to awkwardly transfer energy. If you look inside the HV transformer as you try to transform, it looks as if it's panicking.

#### What you expected to happen:
Some sort of IC2 energy should be available to buffer between transforming the two. Having multiple transformers take in EU/t that can be uneven, awkward numbers like 240 seems to make the Transformers cause unnecessary strain on processing.

**Comment by codewarrior0** [comment]
GregTech doesn't support the full IC2 energynet API, and won't ever. Blood-Asp/GT5-Unofficial#847

Using the IC2 transformer and GT transformer together is the only recommended way to convert to GT EU.
