### ISSUE TITLE
Railcraft tank empties containers that can store more than 1B when there is no space for liquid

### ISSUE THREAD

**Issue by alven4** [JasonMcRay/InfiTech-1.7#855]
#### Issue Description:
Also please state if you modified the modpack in any way.
When partially filled fluid container (for example: jetpack, large steel fluid cell) is put into top slot of Railcraft tank containing the same fluid, the Railcraft tank drains fixed amount (in case of large steel fluid cell, it is 4000 mb/L) of the fluid from the cell/jetpack even when there is not enough space for the fluid.

I added ChocoCraft and Twilight forest to the pack.
#### Is the issue happening on server? Client? Both?
Both.

#### What happens:
Railcraft tank drains more fluid from fluid container that can store more than 1000 mb/L than there is free space in the tank so the extra fluid disappears.

#### What you expected to happen:
I expect the Railcraft tank to drain only that amount of fluid as there is free space in tank or no fluid at all (like it does with small 1B cells and buckets if there isn't at least 1B of free space in the tank). 

#### Steps to reproduce (if aplicable):

1. Build Railcraft tank.
2. Fill it with fluid so it is full or there is less than 1000 mb of free space.
3. Put fluid container containing more than 1000 mb of the same fluid in to top slot of the Railcraft tank GUI.

____
#### Modpack Version (Do *not* use "latest"):
3.2.19.1

#### Your most recent log file where the issue was present: 
https://gist.github.com/alven4/e9d57386be7861344809a79a6acb3923

**Comment by JasonMcRay** [comment]
Railcraft is no longer developed in 1.7.10, thus this will not be fixed.
