### ISSUE TITLE
Filled Crystal capsule draining Buildcraft tank instead of filling

### ISSUE THREAD

**Issue by alven4** [JasonMcRay/InfiTech-1.7#856]
#### Issue Description:
Also please state if you modified the modpack in any way.
When I right click with filled Crystal capsule on Buildcraft tank containing the same fluid, the 1000 mb/L of the fluid from the tank gets drained. The capsule isn't drain in this case.

When I shift right click on the tank with crystal capsule with the same fluid, the tank gets filled normally and the capsule gets drained.

I added ChocoCraft and Twilight forest.
#### Is the issue happening on server? Client? Both?
Both.

#### What happens:
Fluid from Buildcraft tank gets drained instead of getting added when I right click the Buildcraft tank with crystal capsule containing the same fluid

#### What you expected to happen:
I expect the tank to contain more fluid after I right click the tank with crystal capsule containing the same fluid.

#### Steps to reproduce (if aplicable):

1. Place down Buildcraft tank.
2. Fill it partially with any fluid.
3. Obtain Crystal capsule containing the same fluid as the tank.
4. Right click with the Crystal capsule on the Buildcraft tank.
...

____
#### Modpack Version (Do *not* use "latest"):
3.2.19.1

#### Your most recent log file where the issue was present: 
https://gist.github.com/alven4/e9d57386be7861344809a79a6acb3923

**Comment by JasonMcRay** [comment]
Cryswtal Capsules are broken pretty much since beggining of WG and never been fixed. Also WG development has stopped half a year ago and not going to be maintained for 1.7 anymore
