### ISSUE TITLE
Aqua Affinity Enchantment Book Infusion Error

### ISSUE THREAD

**Issue by bunnyman14** [JasonMcRay/InfiTech-1.7#857]
#### Issue Description:
Thaumcraft Infusion Crafting Error.
Placing Water Shard and Salius Mundus in pedestals, and Book in center, causes the crafting for Respiration 1 to begin in instead of Aqua Affinity 1.

#### Is the issue happening on server? Client? Both?
Preformed on client. Most servers do not do HQM, which is the biggest reason why I'm using the pack; to learn how to do Gregtech.

#### What happens:
Respiration 1 book is crafted

#### What you expected to happen:
Aqua Affinity 1 Book to be crafted

#### Steps to reproduce (if aplicable):

1. Place Water Shard and Sailus Mundus on outer pedestals
2. Place a book in the middle pedestal,
3. Place neccessary essentia around for Aqua Affinity
4. Right click Runic Matix
5. Watch as Respiration 1 book is being crafted instead of Aqua Affinity 1.

____
#### Modpack Version (Do *not* use "latest"):
3.2.20

#### Your most recent log file where the issue was present: 
Not in a log file, as it is not a crash.

#### Additional notes
After applying Respiration 1 to helmet, you can use NEI's Cheat Mode and pressing X to overwrite the enchantment with Aqua Affinity 1 as a workaround.

**Comment by bunnyman14** [comment]
Thanks for getting on this so soon! My two cents about this issue is that the game sees all shards for the Respiration 1 enchant as acceptable, even tough should be only an Air Shard. It sees a shard is there, then goes to the first recipe in the 'book,' not realizing that's not the right shard.

**Comment by JasonMcRay** [comment]
https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/workarounds.zs You can download this file and replace the current one, that should fix the issue

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10

For a fix do as I suggested above.
