### ISSUE TITLE
Gregtech sg craft: Stargate not selectable

### ISSUE THREAD

**Issue by HawkridgeV** [JasonMcRay/InfiTech-1.7#859]
#### Issue Description:
Whenever I try to click on any block of the stargate after I have built it, my inventory goes funny and nothing else happens. I cannot put camoflage blocks into the base or see the sg adress. 

#### Is the issue happening on server? Client? Both?
Server -> MyFTB
in Singleplay it works normally

#### What happens:
SG GUI does not pop up!

#### Steps to reproduce (if aplicable):

1. Build sg
2. right clock on it. 

#### Modpack Version (Do *not* use "latest"):
19.1 
#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Update the modpack to 3.2.20 and report back if the issue is still present
