### ISSUE TITLE
Industrial Information Panel Error

### ISSUE THREAD

**Issue by xenojin23x** [JasonMcRay/InfiTech-1.7#860]
#### Issue Description:
Also please state if you modified the modpack in any way.

#### Is the issue happening on server? Client? Both?
Client 

#### What happens:
When supplied with the Reactor Sensor Location Card, the display will only show information on EU output, melting point, reactor temp, and max heat. The panel shows that the reactor is off even though it is on and producing EU. It also does not display time remaining on the cycle. The cycle time is stuck at 0.00.00.

I've tried breaking the panel and replacing it again. I also tried removing the Reactor Sensor Location Card and the corresponding range upgrade (I only used one).

![online](https://cloud.githubusercontent.com/assets/25256294/22167743/5dd0bb2c-df36-11e6-8235-be0cf168ba39.png)

![offline](https://cloud.githubusercontent.com/assets/25256294/22167752/6763bb26-df36-11e6-9960-6a5a7acde385.png)

The pictures show the displays when the reactor is online and offline.
#### What you expected to happen:
I expect to see time remaining and that the reactor is online.

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):

3.2.20

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by Nex4rius** [comment]
Do you have thorium fuel rods in the reactor?
It is a known problem that the cycle time doesn't show for thorium rods.

https://github.com/JasonMcRay/InfiTech-1.7/issues/465
https://github.com/xbony2/Nuclear-Control/issues/137

**Comment by xenojin23x** [comment]
I have regular quad uranium rods.

**Comment by Timeslice42** [comment]
Didn't @Blood-Asp say that the interface for all of the fuel rods was changing? Did @xbony2 ever get updated on the current GT5u API?

**Comment by xbony2** [comment]
I don't think I updated it, no. Feel free to send a PR if desired.

**Comment by JasonMcRay** [comment]
Duplicate https://github.com/xbony2/Nuclear-Control/issues/137

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10
 Also NC is probably also no longer maintained.

**Comment by xbony2** [comment]
It is not maintained in the sense that I am probably not going to do anything myself for 1.7 other than maybe push the version.
