### ISSUE TITLE
Wireless Crafting Terminal Not Available

### ISSUE THREAD

**Issue by HawkridgeV** [JasonMcRay/InfiTech-1.7#861]
#### Issue Description:
The WCT has dissappeared after upgrading to 3.20.2
All AE2 receipes are not working anymore

#### Is the issue happening on server? Client? Both?
Server.
WCTs infinity booster is not even available on single player

#### Steps to reproduce (if aplicable):

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):
3.20.2

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Everything works fine. Infinity Booster is disabled. AE2 recipe changes should work perfectly fine if your server admin did not broke the scripts.

Provide a minetweaker.log file from the server and list of changes
