### ISSUE TITLE
Thaumcraft staves unable to use focus

### ISSUE THREAD

**Issue by Babbie** [JasonMcRay/InfiTech-1.7#862]
#### Issue Description:
Also please state if you modified the modpack in any way.

Default Infitech2: Thaumcraft staves (not wands, not sceptres) are completely unable to use wand foci, which is their only use.

#### Is the issue happening on server? Client? Both?

Both.

#### What happens:

Nothing.

#### What you expected to happen:

A dial of foci to appear, allowing me to select and put a focus on my staff.

#### Steps to reproduce (if aplicable):

1. Obtain any Thaumcraft staff.
2. Obtain any focus.
3. Press the "Change Wand Focus" key (Default: C) with the staff in hand.

For comparison, use a wand instead of a staff.

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):

3.2.20

#### Your most recent log file where the issue was present: 

https://gist.github.com/Babbie/04b91120a6b7325ce5fc60c6d7e74dc7

**Comment by JasonMcRay** [comment]
Just tested and everything works fine. I made myself Void Aspected Obsidian Staff and pressed the button assigned to change wand focus, dial appeared and I put in the focus without a problem.

Make sure you are not trying to put focus onto Staff Core, but actual staff (made from Core + Caps)

**Comment by Babbie** [comment]
I'm making the exact same staff, and it doesn't work. Here are some pictures:
This is the void aspected obsidian staff:
![Staff](http://i.imgur.com/BQRilh0.png)
This is a void aspected obsidian wand:
![Wand](http://i.imgur.com/YUuGWfB.png)
The wand works fine, but the staff still refuses.
![Wand works fine](http://i.imgur.com/EdMJVQQ.png)

**Comment by JasonMcRay** [comment]
Have you tried to change the keybind? It might be conflicting and not working properly. Change it to something that is not at all used (like semicolon for example)

**Comment by Babbie** [comment]
That didn't help, still works for wand but not for staff.

**Comment by Babbie** [comment]
I just realised what happened. I accidentally created staff-sceptre hybrids by using the wrong recipe. Sorry for wasting your time!
