### ISSUE TITLE
Often game crashes

### ISSUE THREAD

**Issue by Varioss** [JasonMcRay/InfiTech-1.7#866]
#### Issue Description:
Game crashing every few hours, 4 crashes in 4 hours today.
I have added OptiFine_1.7.10_HD_U_D6

#### Is the issue happening on server? Client? Both?

It's a single player world, although crash reports are either named "crash-...-server.txt" or "crash-...-client.txt"

#### What happens:

Game crashing in random moments.

#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):

3.2.20

#### Your most recent log file where the issue was present: 

2 different recent crashlogs

http://pastebin.com/C9G08L7k
http://pastebin.com/V5qX7QTS

**Comment by Timeslice42** [comment]
Are these exceptions always memory exceptions? Is the game getting laggy/choppy a bit before the crashes? Try allocating 6GB to minecraft instead of just 4.

**Comment by Varioss** [comment]
Not more laggy than always, 6gb sounds a bit to much since i have installed only 8. I can try it anyway.
What sort of hardware failure? If it matters sometimes i'm having visual artifacts ingame, huge piramid like shaped structures.

**Comment by bunnyman14** [comment]
Optifine is a VERY bad idea considering EnderIO HATES it. If you can uninstall it then try a day without Optifine, then we narrow down the source.

**Comment by Timeslice42** [comment]
Visual artifacts are definitely not a good sign. Do you play any other games that are either graphically intensive, or memory intensive?

**Comment by Varioss** [comment]
Rust/Skyrim/civ5/witcher3 - No problems with other games. Although i'm often getting memory related errors while turning off my computer. 

> The instruction at ... referenced memory at .... the memory could not be written.

That sort of errors, only when i'm turning off pc. 
I did ram tests from windows level, everything was ok. Maybe i should try from bios.


I will also try playing without optifine. It will be painfull :<

**Comment by Ugachaga** [comment]
I blame Player API.
1st crash exactly the same as [there](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996-player-api?comment=1766). I also had similar problems with Player API on another modpack.

**Comment by JasonMcRay** [comment]
RAM tests from windows are useless. Because it will not test every single bit. Best is to use boot tests, like memtest (http://www.memtest.org/#downiso).

As for the crashes you posted. First one is definitely memory related.
Second one is rendering of GregTech modular armor, which is known.

Also checking for driver updates might not be bad idea as well. I had a driver that was leaking memory, so after some time of not doing anything my memory usage went to 97%. Turned out it was network driver (Killer series). After updating that, my memory issues went away.

**Comment by Varioss** [comment]
Apparently Optifines is the mod to blame, since i removed it i had only one crashe due to gt armor. Graphical artifacts are gone too. Yet lack of ingame graphics settings, and distinct change in smoothness of the game (no change in fps though) forces me to install optifine again, and live with often crashes :<

Thanks alot for the help.

**Comment by alven4** [comment]
Try installing OptiFine_1.7.10_HD_U_C1. I get no crashes with it and the only issue with it is that Chisel blocks are invisible.

**Comment by JasonMcRay** [comment]
A) Try using this config file (put it into Infitech/minecraft folder)
[optionsof.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/750195/optionsof.txt)
I am using this config and got no crashes at all when using any Optifine version
B) For invisible Chisel blocks, do not use Multi-core chunk loading.
