### ISSUE TITLE
Quest doesn't mention Iron Tanks require valve on very bottom

### ISSUE THREAD

**Issue by thePalindrome** [JasonMcRay/InfiTech-1.7#867]
#### Issue Description:
The Quest to build an Iron Tank to hold steam fails to mention that the valve MUST be placed on the bottom, otherwise a pump of some kind is required (source: http://railcraft.info/wiki/device:iron_tank) This problem is compounded because in order to replace the bottom block with a valve, you will destroy all liquid in the tank.

#### Modified?
Modpack has not been modified.

#### Is the issue happening on server? Client? Both?
N/A

____
#### Modpack Version
3.2.00

#### Logs?
Log files are not applicable

**Comment by Timeslice42** [comment]
Note that it's only destroying the *center* bottom block that will kill the tank. Of course if you're building a 3x3xwhatever tank then that's the only block you have on the bottom...

That said, I thought the quest did mention that the tank will automatically output on the bottom. Maybe that got lost?

**Comment by thePalindrome** [comment]
It does state something like that, but due to the grammar of most of the book, it's assumed that "bottom" means "the bottom two layers"

**Comment by codewarrior0** [comment]
Maybe "underside" is a better word? In any case, it's kind of important because even using an LV pump or basic fluid conduit on any other side of the tank doesn't even draw enough steam to drive an LV Steam Turbine.

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10
