### ISSUE TITLE
Compresser thaumium block minor bug

### ISSUE THREAD

**Issue by Erixonich** [JasonMcRay/InfiTech-1.7#869]
#### Issue Description:
Also please state if you modified the modpack in any way.
thaumiumblock compresser recipe doesn't work properly.

#### Is the issue happening on server? Client? Both?
Both

#### What happens:
If u place more than 9 ingots of thaumium they wont be proceeded.
for instance place 11 ingots into compresser

#### What you expected to happen:
Compresser'll start working

#### Steps to reproduce (if aplicable):

1. Place 10,11,12, or more thaumium ingots into compresser
2.and nothing will happen
3.
...

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):
3..2.20

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
just in case. if you put exactly 9 ingots it works as intended?

**Comment by Erixonich** [comment]
Yep.

**Comment by JasonMcRay** [comment]
Fixed. You can download thaumcraft.zs and chisel.zs files and replace the old ones from github.
