### ISSUE TITLE
Naquadria Arrows are disabled in the default configs

### ISSUE THREAD

**Issue by Murdermancer** [JasonMcRay/InfiTech-1.7#870]
Naquadria arrows are required to craft the Robes of the Stratosphere, which is the end-game magical armor added by Thaumic Tinkerer. When the configs are adjusted, the recipe seems to be craftable as expected. 

This issue happens on both the server and client, in version 3.2.20.

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10

Feel free to reenable the Naquadria arrows in the Config file: `config/gregtech/MaterialComponents.cfg` - find naquadria part and set `toolHeadArrow_false=false` -> `toolHeadArrow_false=true`
