### ISSUE TITLE
desh nugget

### ISSUE THREAD

**Issue by Nex4rius** [JasonMcRay/InfiTech-1.7#872]
#### Issue Description:

desh nugget to ingot recipe missing

#### What happens:

desh nugget to ingot recipe missing

#### What you expected to happen:

not missing

#### Steps to reproduce (if aplicable):

1. 3x3 crafting
2. packager 3x3 crafting

____
#### Modpack Version:

3.2.20

**Comment by MarcNemesis** [comment]
Simply macerate the NUgget to Tiny Pile of dust. Afterward you can craft them into dust using the 3x3 recipe or packager.

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10

As MarcNemesis suggested, you can macerate nuggets and then craft them into dust as workaround.
