### ISSUE TITLE
Cables and WAILA bug

### ISSUE THREAD

**Issue by Agrax** [JasonMcRay/InfiTech-1.7#875]
Minor bug at 3.2.20: you are told by WAILA that you need a wrench to get back your cables (all sorts- checked), when you need wire cutter. I was really confused at first and it took me approximatelly one week irl to check out the wire cutter. I hope this is not intentional.

**Comment by Nex4rius** [comment]
It's a bug in the mod itself and Jason cannot fix those.
https://github.com/squeek502/WailaHarvestability/issues/52

**Comment by Agrax** [comment]
Thanks for the response. Should i ask for it on greg's post or rather ProfMobius then?

**Comment by Nex4rius** [comment]
ProfMobius is from WAILA but the effective tooltip is done from waila harvestability which is an addon but I've posted that there last year in november and nothing.
I think you should report it to gregtech directly.

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10
