### ISSUE TITLE
Thaumcraft Crafting Table -> NEI autofill -> Crash

### ISSUE THREAD

**Issue by cinch** [JasonMcRay/InfiTech-1.7#876]
pick a recipe, shift + left click on the "?", so that NEI autofills the crafting table -> crash

when you only hit the "?", you can see it doesn't fill the crafting table correctly (off by one bug?).

(as seen on: infitech 2 client, single player only)

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10

Same goes for Thaumcraft.
