### ISSUE TITLE
Macerator doesn't like furnaces. Gives only sand.

### ISSUE THREAD

**Issue by RussianSanity** [JasonMcRay/InfiTech-1.7#877]
#### Issue Description:
Also please state if you modified the modpack in any way.

The recipe for macerators to turn furnaces into stone dust actually turns it to sand. 
I didn't see anything in the recent changelog for the next version that recipes were fixed so I thought it best to report this issue here.
The only modification that has been made is pollution has been disabled.

#### Is the issue happening on server? Client? Both?

This problem is happening on a server and on singleplayer. 

#### What happens:

Furnaces go into the macerator, sand ends up coming out as the end product.

#### What you expected to happen:

The furnace to give stone dust via one of the recipes for stone dust displayed by NEI.

#### Steps to reproduce (if applicable):

1. Put furnace (vanilla) into macerator
2. Wait
3. Sand comes out instead of stone dust
...

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):

3.2.19.1

#### Your most recent log file where the issue was present: 

To show the problem:
https://gyazo.com/6bd0a8b9c71f9ea00b0395f97f939868

To show that stone dust actually works in the same machine:
https://i.gyazo.com/a542aa0f1721dbd1979d476a0857d43c.png

The NEI recipe for furnace + macerator = stone dust:
https://gyazo.com/b4a90e1853d85241e92ac312c09615a4

**Comment by Nex4rius** [comment]
But furnaces in a macerator are supposed to give you sand.

**Comment by RussianSanity** [comment]
That's not what NEI tells you as you can see in the third link I posted.

**Comment by JasonMcRay** [comment]
The real recipe for the furnace into sand comes from backwards compatibility with Pulverizer. And as @Nex4rius said, Furnaces are indeed intended to give you sand in macerator. The recipe for Furnace -> Stone Dust is probably coming from IC2, and I am not sure, If I can disable the recipe showing up, since it is not easy to remove macerator recipes.

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10
