### ISSUE TITLE
endium ore

### ISSUE THREAD

**Issue by Nex4rius** [JasonMcRay/InfiTech-1.7#879]
#### Issue Description:

I'm pretty sure that was already fixed but endium ore doesn't have macerator recipes.

#### Steps to reproduce (if aplicable):

1. take endium ore
2. put in macerator
3. wait
4. nothing

____
#### Modpack Version:

3.2.20 official iniftech2 server

**Comment by JasonMcRay** [comment]
InfiTech for 1.7.10 is no longer maintained, we are focusing now on 1.10
