### ISSUE TITLE
SlackOverflowError when try to make Fresh water in Worktable with sneak+click.

### ISSUE THREAD

**Issue by ontario** [JasonMcRay/InfiTech-1.7#880]
Infitech 3.2.20 not modified.

When I try to make Fresh water (4892) in Worktable (0632/2) with sneak+click.

Game crush with error:
java.lang.StackOverflowError: Updating screen events
The issue happening on client.

#### Steps to reproduce:

1. Single player
2. World seed: 712573132070845451
3. x:205 z:1 y:68
4. Sneak+click to make Fresh water in Worktable

____
http://c2n.me/3JFgQ3X

Logs:
#1 https://pastebin.com/ktMH8JZH
#2 https://pastebin.com/JeRDRA0F

**Comment by JasonMcRay** [comment]
1) Dupe: https://github.com/JasonMcRay/InfiTech-1.7/issues/537
2) Forestry is no longer maintained for 1.7
3) InfiTech is also no longer maintained, we are focusing now on 1.10
