### ISSUE TITLE
stop development

### ISSUE THREAD

**Issue by Nex4rius** [JasonMcRay/InfiTech-1.7#881]
You stopped development of 1.7 but could you at least still publish the latest version?
This change here https://github.com/JasonMcRay/InfiTech-1.7/blame/master/config/SGCraft.cfg#L62 was done 3 month ago and its still not available in the latest version (3.2.20) and I assume there are other changes aswell in the last months.

**Comment by JasonMcRay** [comment]
Last pack update (3.2.21) is prepared and will be up on the FTB Launcher soon (tm)
