### ISSUE TITLE
game crash at main menu

### ISSUE THREAD

**Issue by Dongonzales** [JasonMcRay/InfiTech-1.7#882]
#### Issue Description:
I am using version 3.2.21 without any changes.
The game crashes as soon as the main menu appears, and loading takes a very long time

should not be a ram issue, i have 18Gb assigned

#### Is the issue happening on server? Client? Both?
the game doesn't stay open long enough to choose

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):
v 3.2.21

#### Your most recent log file where the issue was present: 

https://pastebin.com/4unFXZgv

**Comment by JasonMcRay** [comment]
Looks like a keybindings problem. Reset your keybinds (by deleting options.cfg)

**Comment by Dongonzales** [comment]
hey that worked! thanks 👍
