### ISSUE TITLE
Crash upon right clicking with scooperator on a hive

### ISSUE THREAD

**Issue by DonArmadillo** [JasonMcRay/InfiTech-1.7#885]
#### Issue Description:
Crash upon right clicking with scooperator on a hive

#### Is the issue happening on server? Client? Both?
Client I am playing in single player (since the/your server whitelist is closed)

#### What happens:
You crash

#### What you expected to happen:
To get the hive block as stated and shown in a Minecrafters video

#### Steps to reproduce (if aplicable):

1. Right Click with a GenDustry Scoperator onto a Hive (Forest Hive in my case)

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):
3.2.21

**Comment by JasonMcRay** [comment]
1) No crash-log = no help = insta-close
2) Development of Infitech 2 has been stopped
